### ISSUE TITLE
Native manifest not in the right dir for ungoogled chromium on linux

### ISSUE THREAD

**Issue by jamespeapen** [glacambre/firenvim#1007]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 86.0.4240.111
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4
- What I tried to do: install and run firenvim
  - Installed with `Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }`
  - Used troubleshooting guide
 
- What happened:
  - with `2>>/tmp/firenvim_errors` for debugging: `E117: Unknown function: firenvim#run` 
  - `nvim --headless -c "call firenvim#install(0, 'export PATH=\"$PATH\"')" -c quit` did not fix the problem
  - manifest files are present for the browser
  - running `echo "abcde{}" | ~/.local/share/firenvim/firenvim` returns nothing but
  - it returns the version and firenvim runs in the browser when running it from /tmp and setting ` -u NORC --cmd 'set rtp+=/tmp/firenvim'`

**Comment by glacambre** [comment]
Hi, thanks for going through the troubleshooting guide, this was very useful :).

>with 2>>/tmp/firenvim_errors for debugging: E117: Unknown function: firenvim#run
>it returns the version and firenvim runs in the browser when running it from /tmp and setting -u NORC --cmd 'set rtp+=/tmp/firenvim'

This means that there is something wrong with your init.vim and that firenvim is not in your runtime path. I think I'll need you to upload your entire init.vim in order to figure out what is wrong.

**Comment by jamespeapen** [comment]
My init.vim and other config files can be found [here](https://github.com/jamespeapen/dotfiles/tree/master/config/nvim). 

I've also installed this on a linux machine with the same configs and there I get the error 'Neovim died without responding'. The manifests are present and piping into the `firenvim` script returns the version. Trying to redirect error output did not create an error log in /tmp or other locations I tried.

**Comment by glacambre** [comment]
The issue is right here:

https://github.com/jamespeapen/dotfiles/blob/e2c572d398eaa66383dbbc1f53c72dc573b6ac09/config/nvim/init.vim#L1-L5

You're not loading your plugins, and thus the firenvim plugin, when neovim is started by firenvim. So firenvim can't do all the setup that is needed to be able to talk with the browser. The solution is to make sure firenvim is always loaded :).

**Comment by jamespeapen** [comment]
Ah that was a setting I was using when firenvim was in /tmp. I removed that and with a minimal init.vim using just the firenvim plugin and no other settings, the echo command on the script now returns the version but the error output still says `Unknown function: firenvim#run()`. 

I added 
```sh
exec '/usr/local/Cellar/neovim/0.4.4_1/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()' --startuptime ~/startup 2>~/errors
```

This created the errors file but the startup file was empty. 
Errors:
```
Error detected while processing command line:
E117: Unknown function: firenvim#run
Press ENTER or type command to continue
```

When manually running the script, it shows that firenvim is loaded during startup.
```
> .local/share/firenvim/firenvim
> cat ~/startup

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.009  000.009: --- NVIM STARTING ---
000.872  000.863: locale set
001.321  000.448: inits 1
001.340  000.020: window checked
001.347  000.006: parsing arguments
001.592  000.245: expanding arguments
001.661  000.069: inits 2
002.118  000.457: init highlight
002.312  000.195: --cmd commands
004.487  001.693  001.693: sourcing ~/.local/share/nvim/site/autoload/plug.vim
010.285  004.992  004.992: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/filetype.vim
010.523  000.082  000.082: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/ftplugin.vim
010.744  000.077  000.077: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/indent.vim
011.547  000.325  000.325: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/syntax/syncolor.vim
011.642  000.593  000.268: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/syntax/synload.vim
011.669  000.800  000.207: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/syntax/syntax.vim
011.682  009.007  001.362: sourcing ~/.config/nvim/plugins.vim
011.689  009.118  000.111: sourcing ~/.config/nvim/init.vim
011.693  000.263: sourcing vimrc file(s)
012.452  000.103  000.103: sourcing ~/.config/nvim/plugged/firenvim/plugin/firenvim.vim
014.146  000.168  000.168: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/gzip.vim
014.251  000.017  000.017: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/health.vim
014.399  000.066  000.066: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/man.vim
015.604  000.202  000.202: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
015.677  001.196  000.994: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/matchit.vim
015.910  000.146  000.146: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/matchparen.vim
016.354  000.356  000.356: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/netrwPlugin.vim
016.688  000.014  000.014: sourcing ~/.local/share/nvim/rplugin.vim
016.696  000.242  000.228: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/rplugin.vim
016.880  000.096  000.096: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/shada.vim
016.997  000.027  000.027: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/spellfile.vim
017.217  000.134  000.134: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/tarPlugin.vim
017.395  000.083  000.083: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/tohtml.vim
017.508  000.025  000.025: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/tutor.vim
017.775  000.160  000.160: sourcing /usr/local/Cellar/neovim/0.4.4_1/share/nvim/runtime/plugin/zipPlugin.vim
017.783  003.271: loading plugins
017.931  000.148: loading packages
018.079  000.148: loading after plugins
018.091  000.012: inits 3
021.165  003.075: reading ShaDa
021.171  000.006: clearing screen
023.073  001.902: opening buffers
023.138  000.065: BufEnter autocommands
023.140  000.002: editing files in windows
023.706  000.405  000.405: sourcing ~/.config/nvim/plugged/firenvim/autoload/firenvim.vim
023.822  000.277: executing command arguments
023.930  000.108: VimEnter autocommands
023.932  000.002: before starting main loop
024.197  000.265: first screen update
024.199  000.002: --- NVIM STARTED ---
```

**Comment by glacambre** [comment]
I'm really not sure what could be going on. Could you upload your updated init.vim, the content of the [manifest file](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-firenvim-native-manifest-has-been-created) and the content of the firenvim script here?

**Comment by jamespeapen** [comment]
init.vim

```vim
source ~/.config/nvim/plugins.vim
```

plugins.vim
```vim
call plug#begin()
Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
call plug#end()
```

Library/ApplicationSupport/Chromium/NativeMessagingHosts/firenvim.json
```
{ "name": "firenvim", "description": "Turn Firefox into a Neovim client.", "path": "/Users/James.Eapen/.local/share/firenvim/firenvim", "type": "stdio", "allowed_origins": [ "chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/" ]}
```

~/.local/share/firenvim/firenvim - created using

```bash
nvim --headless -c "call firenvim#install(0, 'export PATH=\"$PATH\"')" -c quit
```

```bash
#!/bin/sh
mkdir -p /var/folders/hj/3c4c94dd6dz4_nj4_0h3q0l80000gp/T//firenvim
chmod 700 /var/folders/hj/3c4c94dd6dz4_nj4_0h3q0l80000gp/T//firenvim
cd /var/folders/hj/3c4c94dd6dz4_nj4_0h3q0l80000gp/T//firenvim
unset NVIM_LISTEN_ADDRESS
export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Users/James.Eapen/.cargo/bin:/Users/James.Eapen/Library/Python/3.9/bin:/Users/James.Eapen/.fzf/bin:/Users/James.Eapen/.cargo/bin:/Users/James.Eapen/Library/Python/3.9/bin:/opt/anaconda3/bin"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Users/James.Eapen/.cargo/bin:/Users/James.Eapen/Library/Python/3.9/bin:/Users/James.Eapen/.fzf/bin:/Users/James.Eapen/.cargo/bin:/Users/James.Eapen/Library/Python/3.9/bin:/opt/anaconda3/bin"
exec '/usr/local/Cellar/neovim/0.4.4_1/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()'  --startuptime ~/startup 2>~/errors
```

**Comment by glacambre** [comment]
You're not loading vim-plug in plugins.vim - this might be the source of your problem with the minimal init.vim.

Could you replace the calls to vim-plug with directly loading the plugin, like this: `set rtp+=/path/to/firenvim/checkout/on/your/computer` and check if anything changes? Please make sure to restart your browser - this shouldn't be necessary but I'm getting paranoid there :p

**Comment by jamespeapen** [comment]
So it turns out it may be a permissions issue. I tried it with just that `set rtp` line in the init.vim and it didn't work. It worked with that line in the firenvim script without needing the `-u NORC` so I tried sourcing the files manually but I got `E484: Can't open file ...`. My nvim configs in ~/.config were links to a dotfiles repository in ~/Documents and nvim can't read past $HOME, even after I changed permisssions. Once I copied the files to ~/.config/nvim, it works in the browser. 

Thanks for your help and the plugin!

**Comment by jamespeapen** [comment]
> I'll try the same fix on the linux system later and see if it works.

I use ungoogled chromium and the manifest was getting installed in `~/.config/chromium/NativeMessagingHosts` instead of that path in `~/.config/ungoogled-chromium`.

**Comment by glacambre** [comment]
>I use the same browser on the mac so I don't know why it doesn't behave consistently.

Because the native manifest API is a real mess and no two browser behaves the same, even when it comes to forks :sob: .

>I use ungoogled chromium and the manifest was getting installed in ~/.config/chromium/NativeMessagingHosts instead of that path in ~/.config/ungoogled-chromium

Thanks for letting me know, I'll update Firenvim to put the native messenger in the right place on linux :)
