### ISSUE TITLE
Scrolling in vertical split breaks display of the other window.

### ISSUE THREAD

**Issue by luetage** [glacambre/firenvim#1016]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 90.0.4430.58
- Browser Addon Version: 0.2.5
- Neovim Plugin Version: 0.2.5

- What I tried to do: Open a lengthy file in Firenvim and create a vertical split. Scroll down.
- What happened: Scrolling affects the second window and messes up the display.

![Screenshot from 2021-04-14 10-37-42](https://user-images.githubusercontent.com/13988217/114680687-b4e56400-9d0d-11eb-9531-75415793dcf5.png)

**Comment by glacambre** [comment]
Fixed on master in 657cd89f1a240a2ff2344ea7a9e513761ca143da - the fix will reach you once I publish a new release :).
