### ISSUE TITLE
Neovim Terminal shows double cursors when loaded in Firenvim.

### ISSUE THREAD

**Issue by luetage** [glacambre/firenvim#1017]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 90.0.4430.58
- Browser Addon Version: 0.2.5
- Neovim Plugin Version: 0.2.5
- What I tried to do: Open a terminal in a Firenvim frame.
- What happened: I see a double cursor both in insert and normal mode.

![Screenshot from 2021-04-14 09-53-32](https://user-images.githubusercontent.com/13988217/114681828-d004a380-9d0e-11eb-85a1-56f86a8204fd.png)

**Comment by glacambre** [comment]
Does leaving and entering terminal mode clear the cursor for you too?

**Comment by luetage** [comment]
At first yes, but switching between normal and insert mode and moving around brings the second one back.

**Comment by glacambre** [comment]
That's a neovim bug: https://github.com/neovim/neovim/issues/14386

**Comment by glacambre** [comment]
It turns out that this was a documentation bug rather than a code one, so I was able to fix the problem in Firenvim. The fix is available on master and will reach you when I publish a new version on the firefox/chrome add-on stores :).

**Comment by luetage** [comment]
Great news, thanks for looking into this.
