### ISSUE TITLE
Allow overriding ctrl-w using a webextension command

### ISSUE THREAD

**Issue by tbodt** [glacambre/firenvim#103]
https://developer.chrome.com/extensions/commands

If you create a command, then go to the extension keyboard shortcut settings and map ctrl-w to it, that will override the close tab shortcut. This may also work with firefox.

**Comment by glacambre** [comment]
Hi, thanks for pointing this out, I had completely forgotten about the commands API. This API doesn't let you override what happens when you press `<C-w>` on Firefox, which was the only browser I supported when I wrote the `Drawbacks` section of the readme.
I'll see what I can do for Chrome :).

**Comment by NilsIrl** [comment]
According to [the description of this addon](https://addons.mozilla.org/en-US/firefox/addon/disable-ctrl-q-and-cmd-q/), this might only be the case on Linux.

Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1325692

**Comment by glacambre** [comment]
I've implemented the ability to override `<C-n>`, `<C-t>` and `<C-w>` (which are the only 3 keyboard shortcuts that can't be overriden on Chrome AFAIK) in 8c73600, read [this](https://github.com/glacambre/firenvim#drawbacks) to discover how to use it :).
Note that this is currently only available if you build the browser extensions from source - otherwise you'll have to wait for me to publish a new release.

**Comment by Freed-Wu** [comment]
Thanks!

**Comment by Niekto350** [comment]
@glacambre

**Comment by glacambre** [comment]
Hi :).

>I've seen your guide
>here https://github.com/glacambre/firenvim#drawbacks but don't
>understand how to use it. The patch here
>https://github.com/glacambre/firefox-patches does not have any
>instructions.

This is a firefox patch, you need to apply it to Firefox's source code and then recompile Firefox. If you don't want to recompile Firefox, instructions to patch a compiled Firefox have been described here: 

https://github.com/glacambre/firefox-patches/issues/1

>
>Is it possible to pass c-w mapping to firenvim when the frame is
>focused? This would be preferred. Or at least intercept the browser
>default behavior to close the tab so I would not loose my work? Or
>maybe at least prompt for closing the tab like those annoying
>confirmation dialogs some websites uses before leaving the iste?

This is not possible without patching Firefox. This is something Mozilla does on purpose. If you want this to change, you'll need to convince them on bugzilla.mozilla.org, but know that a lot of people have tried to do that over the years and that none succeeded :/.

**Comment by Niekto350** [comment]
Thank you, I would prefer not to compile it from source. I'll check it up hopefully during weekend if I'll have some free time.

**Comment by Niekto350** [comment]
Works like a charm, thank you.

I was also wondering, would it be possible to overwrite the regex so it won't replace all reserved FireFox stuff but instead only that one mapping for `C-W`?

**Comment by glacambre** [comment]
Yes, you can narrow the replacement by using `key id="key_close" data-l10n-id="close-shortcut" command="cmd_close" modifiers="accel" reserved="true"` as the pattern and `key id="key_close" data-l10n-id="close-shortcut" command="cmd_close" modifiers="accel"` as the replacement :)

**Comment by Niekto350** [comment]
Great, thanks. I guess I'll have to reinstall Firefox first before trying it out as I didn't make a backup of the original file.

But shouldn't the regex be like this (the spaces replacing the reserved attribute)?
```
sudo perl -i -pne 's/id="key_close" data-l10n-id="close-shortcut" command="cmd_close" modifiers="accel" reserved="true"/id="key_close" data-l10n-id="close-shortcut" command="cmd_close" modifiers="accel"                /g' /usr/lib/firefox/browser/omni.ja
```

**Comment by glacambre** [comment]
>But shouldn't the regex be like this (the spaces replacing the reserved attribute)?

Yeah, probably :)
