### ISSUE TITLE
The height of nvim instance is shorter than original textbox and thus contents are not fully showed

### ISSUE THREAD

**Issue by GaryLiuTelus** [glacambre/firenvim#1048]
- OS Version: win x86-64
- Browser Version:  Firefox 88.0
- Browser Addon Version: 0.2.6
- Neovim Plugin Version: 0.2.6
- Neovim Version: 0.50
- What I tried to do: Using firenvim in Jupyter notebook or Zeppelin
- What happened: The nvim instance window is too short, and the contents are not fully showed
This is without nvim. The contents are fully showed
![image](https://user-images.githubusercontent.com/39339422/118869343-4454d880-b8b3-11eb-8369-24914e4a3b2e.png)
And this is with nvim instance, the contents are short after adding title and status line
![image](https://user-images.githubusercontent.com/39339422/118869517-79f9c180-b8b3-11eb-9697-793d55dc23c9.png)

**Comment by glacambre** [comment]
You can adjust the size of the Firenvim frame with the `lines` and `columns` settings, e.g. `:set lines=10`, see `:h lines` :).

**Comment by GaryLiuGTA** [comment]
yes, this works. 

Is it possible to automatically expand the height (but not more than screen height) as more contents typed in? 

Thanks!

**Comment by glacambre** [comment]
Here's the general idea, I'll let you customize it to your needs:
```
function! Buf_Height()
  let win_width = nvim_win_get_width(0) + 0.0
  let lines = nvim_buf_get_lines(0, 0, -1, v:false)
  let buf_height = 0
  for line in lines
    let buf_height = buf_height + 1 + floor(len(line) / win_width)
  endfor
  return buf_height
endfunction

function! Adapt_To_Height()
  let buf_height = Buf_Height()
  if buf_height > 1
    execute("set lines=" . float2nr(buf_height))
  endif
endfunction

au TextChangedI * call Adapt_To_Height()
```
