### ISSUE TITLE
Click `comment`, `Submit Review`, `Submit new Issue` on Github

### ISSUE THREAD

**Issue by ayushxx7** [glacambre/firenvim#1049]
How to click on buttons such as `Submit new Issue` & `Comment` using firenvim on Github.
I don't quite like the `:wq` & use mouse to click approach. 

Btw, I really liked the ggdG tip :)

**Comment by glacambre** [comment]
You can use `firenvim#eval_js` for that - see [this issue](https://github.com/glacambre/firenvim/issues/542#issuecomment-623203410) for more information.

Note that clicking buttons is out of the scope of Firenvim, so the day these snippets stop working you'll have to fix them on your own ;).
