### ISSUE TITLE
Firenvim not working after updating plugin

### ISSUE THREAD

**Issue by isaif** [glacambre/firenvim#1051]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 90.0.4430.93
- Browser Addon Version: 0.2.6
- Neovim Plugin Version: 0.2.6
- What I tried to do: I was getting error "Neovim plugin version (0.2.4) and browser addon version (0.2.6) do not match.", so I updated the plugin using vimplug. The firenvim extension was working correctly before this issue of mismatched version.
- What happened: The error no longer appears but the extension is not working either. All I am getting is the extension dialogue box as follows. 
![2021-05-28_17-50](https://user-images.githubusercontent.com/11773308/119983249-87aef580-bfdd-11eb-8968-6176d8cb7e9e.png)

I tried the troubleshooting and the following steps shows no issue:

1. **Make sure the neovim plugin is installed**
2. **Make sure the firenvim script has been created**
   `echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim` doesn't work but `echo 'abcde{}' | ~/.local/share/firenvim/firenvim` does as `$XDG_DATA_HOME` may not be defined in my linux distribution.

    The output is as follows:

        ```�{"version": "0.2.6", "settings": {"localSettings": {".*": {"priority": 0, "cmdline": "neovim", "selector": "textarea", "takeover": "never"}}, "globalSettings": {"alt": "all"}}}% ```
3. **Make sure the firenvim native manifest has been created**

4. "**Make sure the browser extension can communicate with neovim**" 
    This step doesn't show any message in console even when I click on `reload settings` button.

P.S: If this info is useful, I am using both vim and neo vim. I have enabled firenvim only in neovim.

**Comment by glacambre** [comment]
The `"takeover": "never"` setting you have prevents Firenvim from automatically starting, does removing it fix your issue?

**Comment by isaif** [comment]
Yes removing `"takeover": "never"` solves the issue.

**Comment by isaif** [comment]
According to docs:

> Setting 'takeover' to 'never', Firenvim will never automatically appear, thus forcing you to use a keyboard shortcut in order to make the Firenvim frame appear.

But now the firenvim appears automatically on focusing text areas since I have deleted `"takeover": "never"`.

Is there a way to solve this issue but not have firenvim appears automatically?

I would like to use shortcut to make firenvim appear.

**Comment by glacambre** [comment]
Oh, ok, I misunderstood your problem, sorry!

You can re-add `"takeover": "never"` to your config - the keyboard shortcut should indeed work even with that setting.

What is the firenvim keyboard shortcut set to in `chrome://extensions/shortcuts`?

**Comment by isaif** [comment]
The shortcut is CTRL+ e

**Comment by glacambre** [comment]
Could you save the following HTML file on your computer, open it in your browser, press `CTRL+e` and tell me what gets printed in the page?

```html
<html>
  <body>
    <textarea></textarea>
    <script>
      let txtarea = document.getElementsByTagName("textarea")[0];
      txtarea.addEventListener("keydown", (e) => {
        document.body.appendChild(document.createTextNode(e.key + "\n"));
      });
    </script>
  </body>
</html>
```

**Comment by isaif** [comment]
> Could you save the following HTML file on your computer, open it in your browser, press `CTRL+e` and tell me what gets printed in the page?
> 
> ```
> <html>
>   <body>
>     <textarea></textarea>
>     <script>
>       let txtarea = document.getElementsByTagName("textarea")[0];
>       txtarea.addEventListener("keydown", (e) => {
>         document.body.appendChild(document.createTextNode(e.key + "\n"));
>       });
>     </script>
>   </body>
> </html>
> ```

"Control" gets printed every time I try the shortcut.
I tried changing the shortcut to Ctrl + G, even then "Control" gets printed. Now If I try previous shortcut i.e. Ctrl + e then I can see "Control e" in the browser. So the shortcut I am assigning is only printing "Control" and any other keys are getting printed without any issue.

**Comment by glacambre** [comment]
Ok, I think that's good news, it means that the `Control+e` key is captured by chrome instead of being passed to the page.

If you go to `chrome://extensions/` and click on the `background page` link for Firenvim, do you see any errors in the console?

**Comment by isaif** [comment]
> Ok, I think that's good news, it means that the `Control+e` key is captured by chrome instead of being passed to the page.
> 
> If you go to `chrome://extensions/` and click on the `background page` link for Firenvim, do you see any errors in the console?

No errors are there in the console.

**Comment by isaif** [comment]
I tried the firefox addon now and its working fine, therefore you are right about the issue being related to chrome.

**Comment by glacambre** [comment]
Ok, let's try to figure out what's happening with custom logging. Please open firenvim's background page console, click on the "sources" tab, open `top > Firenvim > . > src > background.ts` in the leftmost column, find the function named "acceptCommand" (you can use `Ctrl+f` to search for it) and add a logpoint at the beggining and at the end of the function. You can add logpoints by right-clicking on the number column, selecting `Add logpoint` and entering a string like `line XXX has run`.

Once the logpoints have been added, try to trigger Firenvim by using the shortcut in a text area. The logpoints should get printed in the console - does that actually happen?

**Comment by isaif** [comment]
No logpoints getting printed in the console.

**Comment by isaif** [comment]
I removed the `"takeover":"never"` and tried the logging again.  But still no logpoints.

Second thing which I noticed is the addon is still not working in the test page (the html file which asked me to open in chrome) but it works on other page as usual.

**Comment by glacambre** [comment]
If the logpoints aren't printed, then there's nothing I can do: the `acceptCommand` is supposed to be called by your browser and if it isn't that's a browser bug :/.

**Comment by isaif** [comment]
I don't know if it is useful but on changing tabs I get this error:

`Uncaught (in promise) Error: Tabs cannot be queried right now (user may be dragging a tab).
    at browser-polyfill.js:792`

**Comment by glacambre** [comment]
@isaif Does using a "weirder" keyboard shortcut (e.g. `<C-A-z>`) work? I'm thinking that you might be encountering something similar to #1046.

**Comment by isaif** [comment]
Thank you for your time. After updating the chrome it is working now.

**Comment by glacambre** [comment]
Weird, but I won't look a gift horse in the mouth. Thanks for the update :)
