### ISSUE TITLE
nvim version >= 0.4.0 required. Aborting , using v0.4.4

### ISSUE THREAD

**Issue by greg0ire** [glacambre/firenvim#1065]
- OS Version: linux x86-64
- Browser Version:  Firefox 89.0
- Browser Addon Version: 0.2.7
- Neovim Plugin Version: 0.2.6
- What I tried to do: I tried using `:call firenvim#install(0)` after `:packadd firenvim`
- What happened: I got the message in the title, although I'm using `v0.4.4`

Note: I've been using https://github.com/kristijanhusak/vim-packager , and I cannot figure out how to make it work for firenvim.

**Comment by glacambre** [comment]
I don't think you are using v0.4.4, the version check is here:

https://github.com/glacambre/firenvim/blob/1f271184aec2620caab4dffbf1955c28e45d1409/autoload/firenvim.vim#L661-L664

As you can see, it's only checking for the presence of `v0.4.4`, and it's impossible for a neovim binary to return false here.

What does `nvim --version` print?

**Comment by greg0ire** [comment]
`nvim --version` is where I got that information from. However, and this is embarassing, after tonight's reboot, it works :sweat_smile: Sorry for the trouble I guess, let's close.

**Comment by glacambre** [comment]
No problem, you probably had a $PATH issue or something. Glad it's fixed :).
