### ISSUE TITLE
Is there any way of making firenvim show when I'm recording a macro?

### ISSUE THREAD

**Issue by rafaelmuynarsk** [glacambre/firenvim#1066]
When I use firenvim everything works fine just like the NeoVim that I have installed. However, when I'm recording a macro I can't see the status of `recording @a` that I usually see when I'm using NeoVim. Is there any configuration I have to change to make it possible? Creating macros works perfectly fine too, my issue is just about the status that doesn't show when I use firenvim...

**Comment by glacambre** [comment]
>Is there any configuration I have to change to make it possible?

Yes an no :). Right now, you can make neovim render the command line with `let g:firenvim_config = { 'localSettings': { '.*': { 'cmdline': 'neovim' } } }`. However, this will eat one line of screen estate.

Showing macro status while keeping the external command line isn't possible for now. Fixing that would require making Firenvim react to the `msg_showcmd` messages neovim sends. Except I'm under the impression that it isn't 100% exact, for example entering insert mode while recording a macro clears the "recording macro" status. There's probably a bug here that I'll need to report upstream before changing anything in Firenvim :).

**Comment by rafaelmuynarsk** [comment]
Cool, in my case I don't mind sacrificing the last line on the screen in order to have this status. :)

One new problem now is that I use the following configuration on my init.vim file in order to start NeoVim only after I use a defined shortcut on the Browser:

```
let s:fc = {}
let g:firenvim_config = { 'localSettings': s:fc }
let s:fc['.*'] = { 'selector': 'textarea, div[role="textbox"]', 'priority': 0, 'takeover': 'never' }
```

It works fine but after adding the line `let g:firenvim_config = { 'localSettings': { '.*': { 'cmdline': 'neovim' } } }` NeoVim is starting all the times the I click on a text window (like the default behavior does). I think there's a small detail that I'm missing here and the last configuration is overriding the first one. Can I let the status of recording macros as you showed and keep my configuration of starting NeoVim only when I use a shortcut?

**Comment by glacambre** [comment]
>I think there's a small detail that I'm missing here and the last configuration is overriding the first one

Yes, if your config looks like this:
```vim
let s:fc = {}
let g:firenvim_config = { 'localSettings': s:fc }
let s:fc['.*'] = { 'selector': 'textarea, div[role="textbox"]', 'priority': 0, 'takeover': 'never' }
let g:firenvim_config = { 'localSettings': { '.*': { 'cmdline': 'neovim' } } }
```
You're overriding `g:firenvim_config` - so only the last line is taken into account. Try this instead:
```vim
let s:fc = {}
let g:firenvim_config = { 'localSettings': s:fc }
let s:fc['.*'] = { 'cmdline': 'neovim', 'selector': 'textarea, div[role="textbox"]', 'priority': 0, 'takeover': 'never' }
```
