### ISSUE TITLE
Browser locks up (briefly) when using `set lines`

### ISSUE THREAD

**Issue by larsks** [glacambre/firenvim#1068]
First: This is such a fantastic extension; thank you for your work!

I've noticed that changing the size of the firenvim widget (using e.g. `set lines=30`) will often lock up the browser for several (5-10?) seconds. I've seen this happen on both github and on stackexchange sites. While things are paused, it's not possible to interact with the browser at all -- no switching tabs, clicking buttons, or anything else.

Any idea what could be going on?

- OS Version: linux x86-64
- Browser Version: Brave Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
- Browser Addon Version: 0.2.7
- Neovim Plugin Version: 0.2.7

**Comment by glacambre** [comment]
Thanks for the kind words :).

This sounds very similar to https://github.com/glacambre/firenvim/issues/890 . Webextensions shouldn't be able to make the browser hang - so this is very probably an issue with how Chrome interacts with your hardware. You could try to alleviate the problem by disabling hardware acceleration.

The true way to understand what's going on would be to compile brave in debug mode (be ready to wait for a day if you don't have one of these nifty 32-core CPUs...), reproduce the bug and attach GDB to the browser while it's hanging. From there you would be able to see the call stack and see what Brave is stuck on.

**Comment by larsks** [comment]
> You could try to alleviate the problem by disabling hardware acceleration.

A cursory test suggests that disabling hardware acceleration does indeed alleviate the problem.

**Comment by dclong** [comment]
In my case, `:set lines=30` takes about 30 seconds to run when I write comments in an issue in GitHub. And it takes even more time (about 1 minute) when working with a cell of a JupyterLab notebook even if the cell contains only 1 line of code.

**Comment by glacambre** [comment]
@dclong Does disabling hardware acceleration help?

**Comment by dclong** [comment]
I also confirm that disabling hardware acceleration helps.

**Comment by larsks** [comment]
@glacambre I was just noticing that with a recent version of Brave (1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit) ), this no longer seems to be an issue. Yay for the passage of time! 😄

**Comment by glacambre** [comment]
@larsks Great to hear, thanks a lot for letting me know the issue is fixed :)
