### ISSUE TITLE
Jupyter notebook cell type

### ISSUE THREAD

**Issue by medwatt** [glacambre/firenvim#1080]
In a jupyter notebook, a cell can be a markdown cell or a code cell. I would like to set the correct filetype depending on the type of cell I'm in. For example, if I'm inside a markdown cell, I'd like to set filetype to markdown, and if I'm inside a code cell, I'd like to set the filetype to python. The issue is the name of the text file that gets created by firenvim ends with the `.txt` extension for both types of cells. How can I differentiate between the two so I can create an autocommand that sets the file type appropriately?

**Comment by glacambre** [comment]
It looks like jupyter uses "ipython" and "ipythonfm" as format for its cells instead of "python" and "markdown", this is why firenvim was unable to guess the right file extension. I've fixed that in https://github.com/glacambre/firenvim/pull/1082 , the fix will reach you when I publish a new release :)

**Comment by medwatt** [comment]
Thanks for looking into it? What about the support of other programming languages other than python for code cells ? As you know, you can probably use any popular language in iPython notebooks by installing the appropriate kernel.

**Comment by glacambre** [comment]
>What about the support of other programming languages other than python for code cells ?

Jupyter seems to be using CodeMirror names (e.g. Julia cells have the name `julia`) for all other programming languages listed [here](https://jupyter.org/try), so they are already correctly handled by the existing mechanism. It looks like python is the only language that had a non-standard name :).
