### ISSUE TITLE
Change current text areas reference file

### ISSUE THREAD

**Issue by vito-c** [glacambre/firenvim#1081]
I would like the ability to change the associated text areas file. The reason I would like to be able to do this is because a lot of websites have a drop down for the source type and I have to `set ft` to get it to work. Then if I come back to the site it still loads the file based on the path's filetype. I would like to try and add this feature myself. Is it something you think would be beneficial to the plugin?

**Comment by glacambre** [comment]
>I would like the ability to change the associated text areas file.

I am not sure I understand what you mean - do you want to change the path of the file firenvim uses? If yes, this is indeed a feature I would be okay with having :)

**Comment by vito-c** [comment]
Yeah essentially when you select a text area it creates a file in `/private/var/folders/.../foo.txt` I would like to be able to change that file to something else.

**Comment by vito-c** [comment]
Another question I had for you is have you had any luck getting nvim to load on sites with more exotic text inputs like:
- google docs
- gist
- replit

**Comment by glacambre** [comment]
Okay, changing the directory in which the file is created can be done by exporting an environment variable named XDG_RUNTIME_DIR and set to the directory you want to use before running `firenvim#install()`.

Changing the name of the file itself is currently impossible. I think the best way to implement this feature would be to create a new site-local setting accepting a format string that would specify the name the file should have.

The format string could be something like `${h:0:10}_${p:-5:-1}_${s:-10:-1}_${l}.${e}`, where `h` would stand for the hostname, `p` for the path of the file, `s` for the selector of the textarea in use, `l` for the language and `e` for the extension being used. `h`, `p` and `s` would be sanitized, we could imagine offerring `H`, `P` and `S` for their unsanitized version. The colon-separated numbers would allow slicing the strings as desired.

Implementing this setting would require [adding it to the code that loads settings](https://github.com/glacambre/firenvim/blob/b7d4133fc4d0344f6370fb54d8ab3937e1ab2ada/src/background.ts#L199). Once that is done, you can use [getConfForUrl](https://github.com/glacambre/firenvim/blob/b7d4133fc4d0344f6370fb54d8ab3937e1ab2ada/src/utils/configuration.ts#L75) in [toFileName](https://github.com/glacambre/firenvim/blob/b7d4133fc4d0344f6370fb54d8ab3937e1ab2ada/src/utils/utils.ts#L124) to get the format string, expand it and return it.

>Another question I had for you is have you had any luck getting nvim to load on sites with more exotic text inputs like:

I don't know about Google Docs and Replit as I don't want to have to create accounts at the moment but Gist uses security settings that prevent Firenvim from working, so there's nothing I can do unfortunately. I wouldn't be surprised if the other two sites had the same issue.

**Comment by glacambre** [comment]
@vito-c I merged #1138, which makes the filename configurable. I described how to configure the filename [here](https://github.com/glacambre/firenvim#configuring-the-filename). This feature will reach you once I publish a new release :)

**Comment by vito-c** [comment]
Thank you! Sorry I wasn’t able to spend more time on it
