### ISSUE TITLE
Disable by default

### ISSUE THREAD

**Issue by Saecki** [glacambre/firenvim#1088]
I would like an option to disable firenvim in the current tab by default, and opt in to enabling it.

**Comment by alerque** [comment]
The option exists already. Set `takeover` to `never` for `*` sites if that's what you want.

**Comment by Saecki** [comment]
Thanks! Sorry, didn't read that properly.

**Comment by frogtile** [comment]
with `takeover: 'never'` how do enable firenvim when i need.

**Comment by justinmk** [comment]
@frogtile https://github.com/glacambre/firenvim#manually-triggering-firenvim
