### ISSUE TITLE
Configure font-size in CSS

### ISSUE THREAD

**Issue by washtubs** [glacambre/firenvim#110]
The font-size is a little bit too small. Not sure what it's dependent on, but I'd like to be able to configure it if possible. Maybe even fully customizable CSS for the `#host` element?

**Comment by glacambre** [comment]
Currently firenvim uses the browser's default font size. I have a branch on my computer that lets users set their preferred fonts with `guifont` (it's a branch that will fix #102 too) but I'm experiencing a small issue with automatically resizing the frame when the font size changes. It should be ready soon though.

**Comment by BlueDrink9** [comment]
Adoring this extension, but the font for me is absolutely tiny. Would love to see this fixed soon.

**Comment by glacambre** [comment]
@justinmk is there a standard way to define font sizes? From reading `:h E244` I'm unsure whether having a colon-separated list is specific to windows/osx's GVIM or if every GUI should support that.

**Comment by justinmk** [comment]
> is there a standard way to define font sizes? From reading `:h E244` I'm unsure whether having a colon-separated list is specific to windows/osx's GVIM or if every GUI should support that.

@glacambre Vim never expected GUI extensions, so this is untrodden territory :)

I would suggest conforming to the colon convention unless there's some reason not to. Unfortunately the `option_set` UI event doesn't parse the 'guifont' setting, so each UI has to parse the value...

**Comment by glacambre** [comment]
You can now set font sizes with `:set guifont=monospace:h10`. Read `:h E244` and 135c77c in order to know more and feel free to ask questions if things don't go as you expect them to :)

**Comment by glacambre** [comment]
I released a new version for both chrome and firefox. Upgrade to firenvim 0.1.11 and use `:h guifont` to be able to change your font and its size.

**Comment by Asheq** [comment]
This works if I set guifont inside an existing firenvim text area, but it does not work if I put the line in my vimrc; firenvim will still start up with a tiny font. Any idea what is going on?

**Version info:**
- NVIM v0.4.2
- Firenvim 0.1.11

PS: This extension is amazing. I'm looking forward to using it everywhere! Keep up the great work.

**Comment by glacambre** [comment]
@Asheq What does `set guifont` print right after starting neovim? Does this issue still happen if you empty your `init.vim` except for the `guifont` line?

**Comment by Asheq** [comment]
It prints `  guifont=Iosevka:h12`

I changed my init.vim to contain nothing but the following:
```
set guifont=Iosevka:h12
call plug#begin('~/.vim/plugged')
set guifont=Iosevka:h12
Plug 'glacambre/firenvim'
set guifont=Iosevka:h12
call plug#end() " Automatically executes 'filetype plugin indent on' and 'syntax enable'.
set guifont=Iosevka:h12
```

As you can see, I tried setting guifont in various locations, and none of them work. Only when I type it in manually in the command-line after the firenvim instance starts does it work:

![Untitled](https://user-images.githubusercontent.com/4657140/68258799-bb39c180-ffec-11e9-8ee3-811ca7c4fd00.gif)

**Comment by alerque** [comment]
@Asheq You need to actually use the code that is in the README for setting the configuration on startup. You need to set the values in function that gets fired on the `UIEnter` event and checks for Firenvim.

```vim
function! OnUIEnter(event)
	let l:ui = nvim_get_chan_info(a:event.chan)
	if has_key(l:ui, 'client') && has_key(l:ui.client, 'name')
		if l:ui.client.name ==# 'Firenvim'
			set guifont=Iosevka:h12
		endif
	endif
endfunction
autocmd QueInit UIEnter * call OnUIEnter(deepcopy(v:event))
```

That should work (at the end of your `init.vim` somewhere after plugins are loaded.

**Comment by Asheq** [comment]
Thanks @alerque. That works for me. Based on the fact that @glacambre created #214, it appears that he agrees that guifont should not have to be set in an autocommand, at least in the long-term. For now, I'm happy with this solution!

**Comment by y2w8** [comment]
@glacambre icons not fully displayed there are like cutted when i search about they say its terminal configurations
and this my autocmd
```lua
vim.api.nvim_create_autocmd({ "UIEnter" }, {
  callback = function(event)
    local client = vim.api.nvim_get_chan_info(vim.v.event.chan).client
    if client ~= nil and client.name == "Firenvim" then
      vim.o.laststatus = 3
      vim.o.guifont = "JetBrainsMono Nerd Font:h12"
      vim.o.linespace = -2
      require("base46").load_all_highlights()
    end
  end,
})
```
<img width="865" height="259" alt="Image" src="https://github.com/user-attachments/assets/f4db7941-7bff-478e-8d24-13d8f63831fb" />
