### ISSUE TITLE
Make file names always unique

### ISSUE THREAD

**Issue by hhhapz** [glacambre/firenvim#1101]
At the moment, whenever the same website is opened multiple times and one is
editing the same selector, the file paths collide and cause issues with each
other. This could be fixed by just appending the current UNIX timestamp to each
file (as long as someone does not open the same text area multiple times within
a second, of course). I wonder if this is functionality that we can get? This
is relatively useful for me when I work with https://play.golang.org/, as it
allows me to edit multiple snippets simultaneously :)

**Comment by glacambre** [comment]
I like the idea of textareas always using the same file name, but I must admit that it has lots of drawbacks and not many advantages. Adding a timestamp to the filename is an excellent idea which would also allow re-enabling swap files ( https://github.com/glacambre/firenvim/issues/679 ).

I think adding this timestamp could be combined with the change described [here](https://github.com/glacambre/firenvim/issues/1081#issuecomment-874966900) to allow people to make the filename configurable, this way users would be able to go back to always using the same filenames for the same textareas if they wanted it.

From reading your other issue it seems that you're not afraid of tweaking and compiling Firenvim from sources. Do you want to implement this feature yourself or would you prefer to let me do it? :)

**Comment by hhhapz** [comment]
Sure, I'll do it 😄

**Comment by glacambre** [comment]
Great, thank you for taking care of that! There's a small guide about contributing [here](https://github.com/glacambre/firenvim/blob/master/CONTRIBUTING.md), I described the process of making filenames configurable in [#1081](https://github.com/glacambre/firenvim/issues/1081#issuecomment-874966900) and there's a (mostly dead) matrix chatroom [here](https://app.element.io/#/room/#firenvim:matrix.org). Don't hesitate to open a PR early and to ask questions if you have them, I'll be happy to answer them when I'm available :).

**Comment by glacambre** [comment]
@hhhapz I merged #1138, which adds a timestamp to the filenames used by firenvim by default. You can learn more about the feature [here](https://github.com/glacambre/firenvim#configuring-the-filename). The feature will reach you once I publish a new release :).
