### ISSUE TITLE
Prevent Firenvim from being trigger when entering a textarea?

### ISSUE THREAD

**Issue by molleweide** [glacambre/firenvim#1104]
Hi,

How can I prevent firenvim from being triggered when entering a textarea?

I know how to configure browser so that I can use keybinding to trigger firenvim
but firenvim still is being triggerd the first time I click/enter a textarea.

Again, I also have to thank you glacambre for this awesome plugin. After having
understood how to set the guifont size properly it works perfectly!

**Comment by glacambre** [comment]
Preventing Firenvim from taking over when entering a textarea is described [here](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements). Let me know if it is unclear :)

**Comment by molleweide** [comment]
Cool thank you very much!! It seems to be quite straight forward.

**Comment by molleweide** [comment]
Allri
