### ISSUE TITLE
Not displaying Unicode Characters

### ISSUE THREAD

**Issue by meatballs** [glacambre/firenvim#1107]
Similar to #932 

- OS Version: Ubuntu 20.04
- Browser Version: Firefox 91.0 (Also tried on Chrome)
- Browser Addon Version: 0.2.7
- Neovim Plugin Version: 22e7618

### What I tried to do
I have `set guifont=SauceCodePro_Nerd_Font:h10` in my neovim config.

It's definitely working because I can change the font size successfully.

### What happened
Similar to #932, none of the glyphs are displaying properly.

**Comment by meatballs** [comment]
Aha! I hadn't spotted that issue. Backslashes and spaces fixed it for me.

Thank you.

**Comment by glacambre** [comment]
Glad it's now working for you. Feel free to ask any other question you may have :).

**Comment by WhyNotHugo** [comment]
My font is getting picked up properly, but unicode characters are not.

I'm using operator mono, with this fontconfig override (which firefox, alacritty, and others pick up fine):

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>OperatorMono</family>
    <prefer><family>Symbols Nerd Font</family></prefer>
  </alias>
</fontconfig>
```

```lua
  use({
    "glacambre/firenvim",
    run = function()
      vim.fn["firenvim#install"](0)
    end,
    config = [[vim.cmd("set guifont=Operator\ Mono\ Regular:h11")]],
  })
```

I tried using both `Operator\ Mono\ Regular` and `Operator_Mono_Regular`. Both
seem to make the font get picked up fine, but unicode characters just render
their square-box-with-numbers.

Any idea?

**Comment by glacambre** [comment]
>Both seem to make the font get picked up fine

Are you sure that the right font gets used, though? Firefox might be silently defaulting to something else that looks reasonable.

**Comment by WhyNotHugo** [comment]
When using font `set guifont=Lol_Regular:h11` (e.g.: obviously wrong):

![image](https://user-images.githubusercontent.com/730811/130497678-1d598a44-4470-43af-9321-79661d2baf58.png)

With `set guifont=Operator\ Mono:h11`:

![image](https://user-images.githubusercontent.com/730811/130497813-f5640fac-2d18-45de-b67d-21f7432ee34c.png)

With `set guifont=Operator\ Mono\ Regular:h11`:

![image](https://user-images.githubusercontent.com/730811/130497890-713f7a42-737c-4391-9416-16a41374a933.png)

With `set guifont=Operator\ Mono\ Book:h11`:

![image](https://user-images.githubusercontent.com/730811/130498075-0cae4548-8155-4cb0-a12d-471215497546.png)

Note that `Book` and `Regular` are aliases for the same font, but yield very different results:

```console
$ fc-list | grep OperatorMo
/usr/share/fonts/OTF/OperatorMono-BoldItalic.otf: Operator Mono,Operator Mono Bold:style=Bold Italic,Italic
/usr/share/fonts/OTF/OperatorMono-Book.otf: Operator Mono,Operator Mono Book:style=Book,Regular
/usr/share/fonts/OTF/OperatorMono-BookItalic.otf: Operator Mono,Operator Mono Book:style=Book Italic,Italic
/usr/share/fonts/OTF/OperatorMono-Light.otf: Operator Mono,Operator Mono Light:style=Light,Regular
/usr/share/fonts/OTF/OperatorMono-XLight.otf: Operator Mono,Operator Mono XLight:style=Extra Light,Regular
/usr/share/fonts/OTF/OperatorMono-LightItalic.otf: Operator Mono,Operator Mono Light:style=Light Italic,Italic
/usr/share/fonts/OTF/OperatorMono-XLightItalic.otf: Operator Mono,Operator Mono XLight:style=Extra Light Italic,Italic
/usr/share/fonts/OTF/OperatorMono-MediumItalic.otf: Operator Mono,Operator Mono Medium:style=Medium Italic,Italic
/usr/share/fonts/OTF/OperatorMono-Medium.otf: Operator Mono,Operator Mono Medium:style=Medium,Regular
/usr/share/fonts/OTF/OperatorMono-Bold.otf: Operator Mono,Operator Mono Bold:style=Bold,Regular
```

It seems that `Operator Mono` _does_ use the fallback, but `Operator Mono Book` does not.

**Comment by WhyNotHugo** [comment]
Note that, however, using Firefox `Operator Mono` _does_ apply Nerd fonts (both the icons here are Nerd Fonts):

![2021-08-23T20:31:51,289724340+02:00](https://user-images.githubusercontent.com/730811/130499052-89b3f3f5-e7b4-4bb5-b04d-3b49a490fc01.png)

The text in the screenshot is:

```
 init.vim 
html 
```

**Comment by glacambre** [comment]
I wonder if setting a default font string [here](https://github.com/glacambre/firenvim/blob/97f4794ffea6c559b71341597a293fe65863c3da/src/renderer.ts#L632-L645) might be causing issues.
The following patch might help:
```diff
diff --git a/src/renderer.ts b/src/renderer.ts
index 218684c..d745321 100644
--- a/src/renderer.ts
+++ b/src/renderer.ts
@@ -629,20 +629,8 @@ const handlers : { [key:string] : (...args: any[])=>void } = {
         const state = globalState;
         switch (option) {
             case "guifont": {
-                let newFontString;
-                if (value === "") {
-                    newFontString = defaultFontString;
-                } else {
-                    const guifont = parseGuifont(value, {
-                        "font-family": defaultFontFamily,
-                        "font-size": defaultFontSize,
-                    });
-                    newFontString =  makeFontString(guifont["font-size"], guifont["font-family"]);
-                }
-                if (newFontString === fontString) {
-                    break;
-                }
-                setFontString(state, newFontString);
+                functions.echo([[value]], true, {});
+                setFontString(state, value);
                 const [charWidth, charHeight] = getGlyphInfo(state);
                 functions.ui_try_resize_grid(getGridId(),
                                              Math.floor(state.canvas.width / charWidth),
```

I've built a firenvim version with this patch so that you don't have to. Could you disable (or possibly even remove) Firenvim from your browser, download [the new version](https://github.com/glacambre/firenvim/files/7036380/firefox.zip), unzip it, go to `about:debugging` in the URL bar, select `this firefox`, then click on `Load Temporary Addon` and select the unzipped `manifest.json` file?

This should load the version of firenvim that passes `guifont` straight to the canvas, without doing any processing. This means that you will need to set the font using a valid CSS `font:` string,  e.g. `:set guifont=11pt\ Operator\ Mono` to set the canvas' font to `11pt Operator Mono`.

Then, try to play around and set different values in the hope you find one that does what you need. If that doesn't work, I'm afraid there's nothing I can do :/

**Comment by glacambre** [comment]
Closing this issue because it has been awaiting feedback from its author for more than a month. If you're still experiencing the problem you reported, please reply to my previous comment and I'll reopen.
