### ISSUE TITLE
Can't clone source for extensions

### ISSUE THREAD

**Issue by washtubs** [glacambre/firenvim#111]
Getting permission denied.

    > git clone git@git.sr.ht:~glacambre/firenvim

    Cloning into 'firenvim'...
    git@git.sr.ht: Permission denied (publickey,keyboard-interactive).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by glacambre** [comment]
Woops, sorry about that, I should have tried these steps on a completely clean computer. Thanks for opening this issue :)
