### ISSUE TITLE
Automate reload setting

### ISSUE THREAD

**Issue by albert-ying** [glacambre/firenvim#1112]
Hi, I'm wondering if it is possible to get firenvim reload settings whenever the init.vim file changed? Or if there is a bash command that I can use to reload settings programmatically? The reason I ask is that I have a dynamic theme program running (`pywal`), and I want to have firenvim synchronized with everything else.

Thanks in advance!

**Comment by glacambre** [comment]
>possible to get firenvim reload settings whenever the init.vim file changed?

Nope.

>a bash command that I can use to reload settings programmatically?

You can use [nvr](https://github.com/mhinz/neovim-remote) to connect to neovim instances and execute commands:
```
for nvim in /tmp/nvim* ; do
  nvr --servername "$nvim/0" -c ":source stdpath("config") . '/init.vim'"
done
```

**Comment by albert-ying** [comment]
Cool! I got it work with `nvr`.

Actually, I'm not very clear how to specify which nvim instance does firenvim use. Currently, I did it by adding `alias nvim="nvr"` to my .bashrc file. I'm wondering if there is a better way to do this.

**Comment by glacambre** [comment]
You can use `nvr` to connect to each of your neovim instances and then use `call nvim_list_chans()` to get a list of all channels currently open in neovim. You can then run `nvim_get_chan_info()` on each of these channels.

`nvim_get_chan_info()` will return an object that looks like this for a channel belonging to Firenvim:
```
{
  'id': 3,
  'client': {
    'version': {
      'major': '0',
      'patch': '6',
      'minor': '2'
    },
    'name': 'Firenvim',
    'methods': {},
    'type': 'ui',
    'attributes': {}
  },
  'mode': 'rpc',
  'stream': 'socket'
}
```
So if you find a channel whose `client.name` is equal to `Firenvim`, you'll know that a Firenvim instance is connected to neovim.
