### ISSUE TITLE
Check for existing local file when launching NeoVim instance

### ISSUE THREAD

**Issue by AndreasNasman** [glacambre/firenvim#1122]
Hi! 👋

First off, thanks for this excellent program and plugin! It has helped be increase my browser productivity significantly! 🙂

One thing I find myself doing repeatedly is editing chunks of code on e.g. Wiki pages. Quite often I want to make a single larger commit than multiple smaller ones and thus have a significant number of edits.

My question regarding this: Is it possible to have Firenvim check for an existing matching file (with content), and let the user choose how to proceed when launching a NeoVim instance in a browser element? I have enabled [auto save](https://github.com/glacambre/firenvim/#automatically-syncing-changes-to-the-page) in Firenvim so my most recent edits are always synced to the file system. If e.g. the browser crashes, it would be helpful if Firenvim could check for existing edits when relaunching the NeoVim instance. Currently, existing file content is forcefully overwritten with the most recent browser version.

Kind regards,
– Andreas

**Comment by glacambre** [comment]
>If e.g. the browser crashes, it would be helpful if Firenvim could check for existing edits when relaunching the NeoVim instance.

That's exactly what neovim's swap file mechanism is meant to do, which is currently disabled (see https://github.com/glacambre/firenvim/issues/679 for more information). I think the problems described in #679 are gone now so I can probably re-enable it and see how things go :)

**Comment by AndreasNasman** [comment]
Ah, swap files, of course! I noticed files are written locally (on my Mac) to `/var/folders/.../firenvim`, so the swap files could probably be put there then as well? 🙂

**Comment by glacambre** [comment]
>so the swap files could probably be put there then as well?

I think Firenvim shouldn't be making this decision. Instead, users should implement this, possibly using something like
```vim
if exists('g:started_by_firenvim')
  set directory=/path/to/firenvim/directory
end
```

I've re-enabled swap files with #679, so I'll close this issue. The change will reach you once I publish a new release :)

**Comment by AndreasNasman** [comment]
Alrighty, thanks! 👍
