### ISSUE TITLE
Doesn't update the textarea on quit

### ISSUE THREAD

**Issue by indeedhat** [glacambre/firenvim#115]
If there is already text in the textarea then it gets loaded into the vim buffer but changes dont get set on quitting the client

i get the following error in the console
```
NeovimFrame.ts:120 Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at NeovimFrame.ts:120
    at Array.find (<anonymous>)
    at NeovimFrame.ts:120
```
OS: Fedora 30
Browser: Chrome 1569574344
Nvim: 0.4.2

**Comment by glacambre** [comment]
Hi, thanks for the detailed information. Can you reliably reproduce this bug or does it only happen from time to time? Does the textarea contain a lot of text or special characters before you focus it?

**Comment by indeedhat** [comment]
thanks for the quick response,

it happens every time, i am yet to get it to update on a single textare, i have tried a few different sites and one custom html page with nothing but a textarea in a form with the same results each time.

most of the testing was just with the string "this is a test" but i also tried pasting in a few paragraphs of lorem ipsum into a github release box with the same results

Further info:
one thing i forgot to mention is that when i do :q it doesn't instantly quit i have to hit enter as if i needed to dismiss a message but i dont see any error or message in the status line

if i am watching the console the error comes back as i pasted above, if i am not then it comes back as:
```
nvimui.js:6350 Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at nvimui.js:6350
    at Array.find (<anonymous>)
    at nvimui.js:6350
```
i assume this is just down to the map files

**Comment by indeedhat** [comment]
i just checked and the files in .local/share/firenvim do get updated on save

**Comment by glacambre** [comment]
I think this happens because one of the plugins you're using doesn't specify a name for one of its channels. This is fine and shouldn't prevent firenvim from working, so there indeed is a bug in firenvim.

I'll (hopefully) fix it tomorrow and upload a new version on the chrome web store then. Thanks a lot for providing a backtrace, this was very useful.

**Comment by indeedhat** [comment]
thank you,
 vim in textareas is something i have been wanting for some time, i really appreciate your time on this.
let me know if you need any more information about my system, init.vim etc

**Comment by indeedhat** [comment]
i have just rebuilt the plugin from master and can confirm that this issue is fixed, thanks!

**Comment by glacambre** [comment]
Thank you for taking the time to build and test it, I'll try to release a new version on the chrome web store soon :).
