### ISSUE TITLE
Maybe firenvim should always autosave

### ISSUE THREAD

**Issue by Julian** [glacambre/firenvim#117]
Hi.

I haven't spent much time thinking about how to implement this, but it seems to
me like there might be an argument to make that firenvim should always autosave
/ always write the buffer to the input box.

The argument is it's really low effort to delete the resulting text from the
textbox if you need to, but high risk if you throw away a really long comment.

I.e. the workflow I kind of expected was something like as soon as I left
focus from the input box, autoquit vim, autopopulate the input box, then if I
refocus, re-open.

Having an explicit save/quit via :q / :w / :x seems just a bit unnatural there
to me.

But yeah curious to hear what you think!

(I guess on the implementation side, even not having read yet how this works,
you just have JS always send :x or whatever at the end itself)

**Comment by glacambre** [comment]
This probably wouldn't be too hard to implement, however I'm not sure how to do that efficiently. The obvious approach would be to have neovim send firenvim the content of the buffer on every TextChanged autocommand, setting the textarea's content to that and then triggering 6 events to inform the page that the textarea's content changed.
I'm affraid this could be rather slow for large documents or if the page does a lot of processing when the textarea's content changes. I'll think about it :).

**Comment by Julian** [comment]
Yeah I considered that implementation too, but assumed that'd be too slow yeah... but maybe at least if you buffer that (and don't do the send any more often than like 5 seconds) then that'd still be fast enough and also for practical purposes still prevent losing all someone's typing.

Does VimFocus or whatever that one is called that fires when the window loses focus get fired "correctly"? If so could always pick a super high timeout for the above, and then rely on the focus change events to do a final send?

**Comment by BlueDrink9** [comment]
I agree with the principle here, and realised it should have been doing this according to my setup anyway.

I have a snippet in my vimrc that autowrites when (amongst other things) leaving insert mode.

However, in Fnvim, it doesn't write. Calling the function manually does, and an `echom` in the write place tells me the function is called on `insertleave`, but the buffer isn't written.

You may prefer to have me make this as another issue.

```
" Autosave
function! s:Autosave()
    " Don't autosave if there is no buffer name.
    if bufname('%') != '' && &ro != 1 && &modifiable == 1
        " Automatically save before commands like :next and :make
        set autowrite
        " If no changes, don't touch modified timestamp.
        silent! update
    endif
endfunction
" Save on focus loss, leaving insert, leaving buffer.
au myVimrc FocusLost,InsertLeave,BufLeave * call s:Autosave()
```

**Comment by BlueDrink9** [comment]
I suspect it has something to do with triggering firenvim's `autocmd`s from within my autocmd

**Comment by glacambre** [comment]
@BlueDrink9 Firenvim uses the `BufWrite` event in order to sync the content of the buffer back to the page. In order to be able to trigger these from an autocommand, you need to use `++nested`: `au myVimrc FocusLost,InsertLeave,BufLeave * ++nested call s:Autosave()`. Let me know if this works.

**Comment by BlueDrink9** [comment]
Brilliant, ty. That works nicely

**Comment by glacambre** [comment]
```
au TextChanged * ++nested write
au TextChangedI * ++nested write
```
Is fast enough for me. If it isn't for you, you can combine TextChanged with timer_start (see `:h timer`) in order to delay writes like this:
```
let g:dont_write = v:false
function! My_Write() abort
	let g:dont_write = v:false
	write
endfunction

function! Delay_My_Write() abort
	if g:dont_write
		return
	end
	let g:dont_write = v:true
	call timer_start(10000, 'My_Write')
endfunction

au TextChanged * ++nested call Delay_My_Write()
au TextChangedI * ++nested call Delay_My_Write()
```

Since all of this can be done by users (and only when in Firenvim thanks to https://github.com/glacambre/firenvim#configuring-neovims-behavior ), I'm going to close this issue without bringing any changes to firenvim itself. I think I want firenvim to be a dumb client that can and should be configured by users rather than something "smart" that handles more things than needed.

Feel free to disagree and to let me know what your opinion on this matter is ; I can't promise that I'll change my mind but I will certainly read what you say and try to evaluate your points fairly :).

**Comment by Julian** [comment]
Cool! Sounds quite reasonable to me, will give it a shot.

*Maybe* too if there's a way to use autocmds to tell (fire)nvim to exit if the buffer doesn't change after 5-10 seconds, then one can combine that with this to partially fix #49.

**Comment by Julian** [comment]
For anyone else who finds this, I actually just started even simpler :), with just:

https://github.com/Julian/dotfiles/commit/ea0ebb61d50465aa310ae4fa22ca0bd0672ca654#diff-fda005e1b8a5d8852e58d831e12ab94cR16-R17

**Comment by BlueDrink9** [comment]
If you are using it for more than just firenvim, note that your solution will throw irritating warnings whenever you edit readonly or nameless buffers

**Comment by Julian** [comment]
I am not it's in my [firenvim-specific config file](https://github.com/Julian/dotfiles/blob/master/.config/nvim/firen.vim) but appreciate the warning!

**Comment by NilsIrl** [comment]
> autocmd FocusLost * ++nested write

@Julian

This doesn't work for me for some reason.

**Comment by rafaelmuynarsk** [comment]
I think it's also a good idea to add `set ul=-1` at the end of the configuration file on neovim when the autosave is activated... Without that, if by any chance I press `u` by accident and close the window, it'll erase all the text that I have there and it'll save it, which is not good...
