### ISSUE TITLE
Repeated keys during a keydown don't get sent

### ISSUE THREAD

**Issue by Julian** [glacambre/firenvim#118]
If I have a long multiline doc and hold down e.g. `j` in the embedded nvim, only the first j reaches the editor seemingly, and the cursor stays on the second line down rather than scrolling line-by-line.

Not sure if there's anything I can provide for diagnosis or if this can be reproduced by others.

**Comment by glacambre** [comment]
I can't reproduce this, keeping `j` pressed works for me. What OS+Browser+Neovim version are you using?

**Comment by Julian** [comment]
Hm, interesting.

Here, Firefox Quantum (69.0.1) on macOS Mojave (10.14.6) and nvim 0.4.2 from
Homebrew.

Separately, I have an issue where the embedded nvim doesn't show a cursor (of
any kind), so possibly the two issues are related and nvim is confused about
what terminal it's running in or something?

Let me know if there are other things I can poke at or provide obviously, and thanks again for the extension, well done.

**Comment by glacambre** [comment]
Could you save the following html file somewhere on your computer, open it in your browser and see if keeping `j` pressed works in all of the textareas?
```html
<!doctype html>
<html lang="en">
        <head>
                <meta charset="utf-8">
                <meta name="viewport" content="">
                <title></title>
        </head>
        <body>
                <textarea id="textarea0"></textarea>
                <textarea id="textarea1"></textarea>
                <textarea id="textarea2"></textarea>
                <textarea id="textarea3"></textarea>
                <script>
                        document.getElementById("textarea1").addEventListener("input", e => {
                                e.target.innerText += "a";
                                evt.preventDefault();
                                e.target.stopImmediatePropagation();
                        });
                        document.getElementById("textarea2").addEventListener("input", e => {
                                e.target.innerText += "a";
                                evt.preventDefault();
                        });
                        document.getElementById("textarea3").addEventListener("input", e => {
                                e.target.innerText += "a";
                                e.target.stopImmediatePropagation();
                        });
                </script>
        </body>
</html>
```

I don't think your cursor issue is related. I believe I remember experiencing something similar before but I have no idea how/why it disappeared.

**Comment by Julian** [comment]
It doesn't, in any of them...

Which was enough to remind me what the issue was.

It's the Apple accent key nonsense (which doesn't trigger on `j`, but if you
have it enabled at least prevents j from sending key repeats).

If I'd have tried 'e' I'd have known why immediately.

For anyone finding this, https://ioshacker.com/how-to/disable-macos-accent-keys-and-enable-key-repeat is how you'd fix it.

Though there must be some per-App-ness to it because key repeat has always
worked in terminal nvim, so maybe there's a way to disable it here too by
default even on macOS machines that otherwise have it enabled...

But yeah will close for now, thanks for the hint!

**Comment by glacambre** [comment]
Sounds like a nice feature to train yourself to use `3j` instead of `jjj` :smile:

**Comment by cohml** [comment]
Wow, I would have absolutely never figured this out on my own. Thanks @Julian!

For posterity, I'll mention that I've added the following lines to my `.zshrc`:

```zsh
if [[ "${KERNEL}" == "darwin" ]]; then
  if [[ $(defaults read -g ApplePressAndHoldEnabled 2>/dev/null) != 0 ]]; then
    defaults write -g ApplePressAndHoldEnabled -bool false
  fi
fi
```

This hook ensures that `defaults write ...` is only run if on MacOS and if the option has not yet been disabled.

My dotfiles are under version control. So as long as I symlink the `.zshrc` in that repo to `~/.zshrc` when setting up a new machine, I should never have to think about this again.
