### ISSUE TITLE
How to exclude single line text input boxes

### ISSUE THREAD

**Issue by tommyalatalo** [glacambre/firenvim#1186]
The readme shows this example for excluding firenvim from taking over specific elements.

```
let fc['.*'] = { 'selector': 'textarea:not([class=xxx])' }
```

But how do I set this up for firenvim to take over only multiline text areas, and never single line input boxes such as the title field when creating a new github issue?

**Comment by glacambre** [comment]
Firenvim doesn't take over input fields like Github's issue title field by default, so if your issue is precisely about Github's issue title field, there must be something wrong with your configuration.

**Comment by glacambre** [comment]
Closing this issue because it has been awaiting feedback from its author for more than a month. If you still are experiencing problems, please answer the question and I'll reopen :).

**Comment by xeruf** [comment]
You should look into employing bots for auto-closing unanswered issues ;)
