### ISSUE TITLE
Offer a way to manually trigger Firenvim in an element

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#119]
Someone on reddit said they wanted that and it sounds really reasonable.

**Comment by svermeulen** [comment]
Is there documentation on how to use this feature?

**Comment by svermeulen** [comment]
Nevermind, I see now it's listed in chrome commands and the default is CTRL+E (though maybe some extra documentation mentioning that this exists would be nice)

Is there a way to change firenvim to not activate by default and instead always rely on the manual trigger?

**Comment by svermeulen** [comment]
Nevermind, figured it out.  Can disable by default easily by just setting selector to an empty string
