### ISSUE TITLE
Closing a tab with an open firenvim orphans the process

### ISSUE THREAD

**Issue by Julian** [glacambre/firenvim#120]
- OS Version: macOS Mojave 10.14.6
- Browser Version: Firefox Quantum 69.0.1
- What I tried to do: Open firenvim in a tab, then close the tab without
  quitting nvim
- What happened: a process is orphaned (noticeable via ``ps aux | rg
  firenvim``)
- What I expected: the process should die when the tab dies, throwing away the
  contents

**Comment by glacambre** [comment]
I believe this is the same issue as #49 since I have code that asks neovim to shutdown when the connection with firefox is closed.

**Comment by Julian** [comment]
A ha! Seems likely, yeah. Closing this one, thanks.
