### ISSUE TITLE
Allow adding a prologue to the firenvim startup script

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#122]
- OS Version: OSX Mojave 10.14.3
- Browser Version: Google Chrome `77.0.3865.90` (x64)
- What I tried to do: Edit a file on github
- What happened: Regular editor
- What I expected: Text frame becomes nvim

* Install with vim-plug
* `echo 'abcde{}' | .local/shared/firenvim/firenvim` returns a json with my settings
* `$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts/firenvim.json` exists and has the right path for `firenvim`'s script
* Opened the extension's background/console, saw nothing
* Opened github.com and console, cleared console and started editing a file with console open. Nothing prints to console.
* Click firenvim icon and `reload settings`. Nothing prints.
* Opened incognito window with only lastpass and firenvim active as extensions. Opened github, logged in, tried commenting. Again, no nvim.

init.nvim config [here](https://github.com/BlueDrink9/env/blob/4988676c95a694a1f07b8789846304dfc74864e0/editors/vim/main_plugins.vim#L50)

**Comment by BlueDrink9** [comment]
Should probably mention also that I'm using the release version as of this date

**Comment by BlueDrink9** [comment]
Minimal init.vim seems to have made a difference.
```
call plug#begin()
Plug 'glacambre/firenvim', {'do': ':call firenvim#install(0)'}
call plug#end()
```
Still issues, but it loads now.

But it didn't work when I had this:

```
let g:firenvim_config = {
            \ 'localSettings': {
            \ '.*': {
            \ 'selector': '',
            \ 'priority': 1,
            \ },
            \ 'github\.com': {
            \ 'selector': 'textarea',
            \ 'priority': 1,
            \ },
            \ },
            \ }
```

**Comment by BlueDrink9** [comment]
Messages in console:

* Unhandled `Redraw.ts:147` redraw event: hl_group_set (and then a bunch of arrays).
* Unhandled `Redraw.ts:101` cursor shape: undefined

Colourscheme and font are awful, but that's incidental. I think the problem is my vimrc, so I'll bisect the problem and report back.

**Comment by BlueDrink9** [comment]
Aha, found it.

I have a guard `if has('node')` before installing the plugin. In firenvim, this is 0, whereas even in a no-rc nvim it is 1.

Also, any 'executable('x') statements seem to return 0, even where they should return 1.

**Comment by glacambre** [comment]
I think this is 100% OSX's fault, emptying $PATH when you run chrome :(. Could you run `echo $PATH` in your shell and `:!echo $PATH` in firenvim and see if there's a difference? If there is, a simple fix would be to manually export the right $PATH in the firenvim shell script in `$HOME/.local/share/firenvim/`.

**Comment by BlueDrink9** [comment]
Wouldn't surprise me if it was OSX's fault. And indeed, I don't get my usual PATH in chrome. Given node is a brew install, I should have picked up on that. I will export the PATH - or rather, I'll soure my normal path script.

Would you consider an option, therefore, in `init.vim` to take a string to be put into the firenvim script when installing?

That would make things much easier to keep in centralised files, in version control. Would also let apply a few options that would normally be applied by shell alias.

It would also allow a huge degree of flexibility for people that want to use this, for example by setting their own env vars etc.

**Comment by glacambre** [comment]
>Would you consider an option, therefore, in `init.vim` to take a string to be put into the firenvim script when installing?

This sounds like a pretty good idea :)

**Comment by BlueDrink9** [comment]
Thanks! Shall I rename the issue? Or close?

**Comment by justinmk** [comment]
Maybe it's worth it for firenvim to get a baseline PATH using something like:

    sh -il -c 'echo $PATH'

**Comment by BlueDrink9** [comment]
Are you sure that wouldn't just pass the same PATH? If OSX only passes along a base system path to GUI apps like Chrome, would `sh -il` called from the same context have the same PATH?

**Comment by justinmk** [comment]
can you try it?  in firenvim, something like:

    :echo system('sh -il -c "echo $PATH"')

**Comment by BlueDrink9** [comment]
Delightfully, it doesn't work but it does crash vim/firenvim.

I also discovered my system register (`+`) doesn't hold my clipboard in firenvim

**Comment by justinmk** [comment]
"doesn't work" means something else, or that it crashes?

**Comment by BlueDrink9** [comment]
Sorry, that was vague. It hangs then crashes.

On the other hand, using just `sh` instead of `bash` works brilliantly and prints the same !PATH! I see in terminal nvim! In conclusion, your idea is excellent.
