### ISSUE TITLE
Not working for vivaldi-snapshot

### ISSUE THREAD

**Issue by adelin-b** [glacambre/firenvim#1220]
The extension don't work for vivaldi-snapshot but works for firefox and chrome

When rrunning the install hook :
```
No config detected for chromium. Skipping.
No config detected for opera. Skipping.
No config detected for brave. Skipping.
No config detected for vivaldi. Skipping.
No config detected for chrome-canary. Skipping.
Installed native manifest for chrome.
Installed native manifest for firefox.
Press ENTER or type command to continue
```

Maybe vivald-snapshot should be handled here

**Comment by glacambre** [comment]
Where does `vivaldi-snapshot` stores its config? How did you install it?

**Comment by glacambre** [comment]
Closing this issue because it has been awaiting feedback from its author for more than a month. If you still are experiencing problems, please answer the question and I'll reopen :).
