### ISSUE TITLE
Can't save on Github 

### ISSUE THREAD

**Issue by marcelarie** [glacambre/firenvim#1221]
![firenvim](https://user-images.githubusercontent.com/62728887/137590099-b012971b-5b24-4752-b963-d523fd9e81b4.gif)
- OS Version: linux x86-64
- Browser Version:  Firefox 93.0
- Browser Addon Version: 0.2.10
- Neovim Plugin Version: 0.2.10
- Neovim -v `NVIM v0.6.0-dev+464-g1ced6cf08` with `init.lua`
- Tridactyl

### What I tried to do
`:w` to save.

### What happened
The text area and preview in github are empty.

**Comment by glacambre** [comment]
What happens if you remove all of your config, except for the bits that load the firenvim plugin?

**Comment by marcelarie** [comment]
> What happens if you remove all of your config, except for the bits that load the firenvim plugin?

That works like a charm, I will create a custom config then. Thanks!

**Comment by marcelarie** [comment]
You are right. The problem is with this plugin. [trim.nvim](https://github.com/cappyzawa/trim.nvim)

**Comment by marcelarie** [comment]
I added this to my config to fix it.
```lua 
if not vim.g.started_by_firenvim then
	require("plugins.trim-lua") -- ./lua/plugins/trim-lua/init.lua
end
```
