### ISSUE TITLE
Set 'gui_running' or some other variable indicating we are in firenvim

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#123]
As stated in the title. For setting fonts, and no doubt a handful of other options, it's good to know we are in firenvim, or at least in a gui nvim. Oni sets g:gui_oni, would be good to have firenvim do something similar.

Similar to #121

**Comment by justinmk** [comment]
There's no need. See `:help UIEnter` in Nvim 0.4.x

**Comment by BlueDrink9** [comment]
Have done. The best I can do there is something like

`au UIEnder if v:event.chan.client.name == "Firenvim" | let g:gui_firenvim=1`

This is pretty unwieldly for everyone to have to do.

Am I missing something @justinmk? Thanks for the reply.

**Comment by justinmk** [comment]
Why is it unwieldy? Presumably you're planning to write a lot of code that uses that variable, so this 1 line of code is the tip of the iceberg.

**Comment by BlueDrink9** [comment]
Not if all I want to do (as an exmaple) is change the colourscheme, or disable a statusline, which I imagine is a common usecase.

What's more, it seems consistent to not make every user replicate this code.

**Comment by BlueDrink9** [comment]
Have you gotten the `UIEnter` method working? Because when I add it, the channel dictionary isn't fully populated yet.

```
function! FirenvimSetup(channel)
    echom channel
    let l:ui = nvim_get_chan_info(a:channel)
    echom l:ui.client.name
    if has_key(l:ui, 'client') &&
                \ has_key(l:ui.client, "name") &&
                \ l:ui.client.name == "Firenvim"
        let l:isFnv = 1
    endif
endfunction

autocmd UIEnter * call FirenvimSetup(deepcopy(v:event.chan))
```

When first entering firenvim, the channel is echoed correctly (3), but the name is not a valid key.
When subsequently manually calling FirenvimSetup(3), "Firenvim" is echoed in return.

**Comment by justinmk** [comment]
> the channel dictionary isn't fully populated yet.

firenvim would need to call nvim_set_client_info before attaching.

**Comment by BlueDrink9** [comment]
Could you elaborate a little more? Does that mean there is still an issue here? Or am I making a mistake in how I set up to get the channel client name?

**Comment by justinmk** [comment]
Requires a change in firenvim.

**Comment by BlueDrink9** [comment]
Ok, yup.

Then I reiterate, the easiest option is probably just for firenvim to set a variable when it loads.

**Comment by justinmk** [comment]
I'm sure that will happen, but I would also like to have a more common pattern that applies to all UIs .

**Comment by BlueDrink9** [comment]
Yes, that's definitely more desirable. I understand your motiviation now

**Comment by glacambre** [comment]
Justinmk is absolutely right, I was attaching the UI before setting my client info. This is now fixed in the master branch. I'll upload a new version to the chrome web store once I'm done automating the upload process :).

**Comment by BlueDrink9** [comment]
Awesome. Would you consider setting some variable as well? That's a design decision you may not like to make, I guess.

If not, it would be good to have a cannonical vimscript snippet in the README to tell us how to set it ourselves (i.e., a fixed-up version of my above snippet).

**Comment by glacambre** [comment]
I'd like to avoid setting a global variable. I find using UIEnter/Leave events much cleaner. Note that you can set the variable yourself by editing the script in `$HOME/.local/share/firenvim/firenvim` and adding something like `--cmd 'let g:started_by_firenvim = v:true'` to the command that starts neovim. This is unsupported though and will break everytime you run `firenvim#install()` (but you never have to run it again once firenvim is installed).

**Comment by justinmk** [comment]
@BlueDrink9 btw there is already a `g:firenvim_loaded` variable that one can check.

**Comment by BlueDrink9** [comment]
There is, but it's set for _all_ nvim instances, not just browser ones.

(Also, just read an article and realised you are/were Neovim's BD. I want to especially thank you then for helping me out with these small issues.)
