### ISSUE TITLE
Gmail doesn't honor a changed default font setting (in Gmail) after firenvim

### ISSUE THREAD

**Issue by bookbinder** [glacambre/firenvim#1234]
- OS Version:
- Browser Version:
- Browser Addon Version:
- Neovim Plugin Version:

### What I tried to do

I changed the default font in Gmail to "fixed width". My font in nvim is "JetBrainsMono NF". I wanted firenvim, after I exited with a :wq, to place the text in the textbox already in the new default font style of "fixed width".

### What happened

Gmail ignores the new default font and retains the previous default font of "Sans Serif". This also happens if I disable firenvim altogether and reopen Chrome. However, when I go into Incognito Mode, then Gmail honors the new default font of fixed width. So perhaps this isn't a firenvim issue? But it only started after I installed the firenvim extension. Before that it worked fine. I can't figure it out. Thank you.

**Comment by glacambre** [comment]
Hi, thanks for the report. How did you disable Firenvim? Was it from `chrome://extensions/`?

**Comment by bookbinder** [comment]
Yes

**Comment by glacambre** [comment]
Then Firenvim can't possibly be to blame, this must be an issue with your browser. You could try the solution here: https://www.techpowerup.com/forums/threads/disabling-web-fonts-in-mozilla-firefox-and-google-chrome.184198/ .

**Comment by bookbinder** [comment]
Ok, thank you.
