### ISSUE TITLE
Neovim Died Without Answering

### ISSUE THREAD

**Issue by jam1015** [glacambre/firenvim#1239]
- OS Version: mac x86-64
- Browser Version:  Firefox 94.0
- Browser Addon Version: 0.2.10
- Neovim Plugin Version: 0.2.10

### What I tried to do
Here is how I have it configured
```
		call minpac#add('glacambre/firenvim', { 'type': 'opt', 'do': 'packadd firenvim | call firenvim#install(0)'})
			let g:firenvim_config = {
    \ 'globalSettings': {
        \ 'alt': 'all',
    \  },
    \ 'localSettings': {
        \ '.*': {
            \ 'cmdline': 'neovim',
            \ 'content': 'text',
            \ 'priority': 1,
            \ 'takeover': 'never',
        \ },
    \ }
\ }
		if exists('g:started_by_firenvim')
			packadd firenvim
			set guifont=Consolas:h10:w10
		endif

```

I furthermore have `<C-q>` to toggle firenvim in a tab, and `<C-e>` to activiate it in a text area.  

I hadn't used it in a while so I went to a text area and hit <C-e> and it turned on just fine.  Then I entered `:q` to quit.  

### What happened

Now I get the error message `Neovim died without responding` in both Firefox and Chrome in the icon in the top right.  It won't activate in any text area.   Not sure what to do because I didn't change anything that I'm aware of and it stopped working.

**Comment by glacambre** [comment]
My guess is you installed neovim with brew and upgraded it recently. Could this be correct?

In any case, there two ways to fix it. Either go through the [troubleshooting guide](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-firenvim-script-has-been-created) or run `firenvim#install(0)` again :).

**Comment by glacambre** [comment]
Closing this issue because it has been awaiting feedback from its author for more than a month.
