### ISSUE TITLE
Rendering breaks on inputs containing the U00AD SOFT HYPHEN character

### ISSUE THREAD

**Issue by silmeth** [glacambre/firenvim#1243]
- OS Version: linux x86-64
- Browser Version:  Firefox 94.0
- Browser Addon Version: 0.2.10
- Neovim Plugin Version: 0.2.10

### What I tried to do

Open firenvim on Wikisource on an input pre-filled automatically by OCR from the transcribed image, the input contains the U00AD (`SOFT HYPHEN`) unicode character.

### What happened
 
The cursor is not rendered and the text in the firenvim frame is only visible up to the soft hyphen character, the rest of the are being completely black.

given the text area (the soft hyphen character being directly after the `SOFT HYPHEN` text):
![soft-hyphen-textarea](https://user-images.githubusercontent.com/5329644/142494610-84f056ba-bf98-443a-b633-ac2886913d55.png)
the input value being:
> test test test test test test test
> test SOFT HYPHEN­ test test test test
> test test test test test test test

when I open firenvim I see this (and although I can see on which line the cursor is from relative line numbers, I don’t see the cursor itself either):
![firenvim-soft-hyphen](https://user-images.githubusercontent.com/5329644/142494592-e22a3bf4-4729-41b0-a407-15f5be846831.png)

but the visual selection in the visible area still kinda works:
![firenvim-visual-selection](https://user-images.githubusercontent.com/5329644/142494886-d75fc6c3-1528-438e-952f-48bf7c502474.png)

**Comment by glacambre** [comment]
Well, today I learned a bit more about the joys of unicode :).

Thanks a lot for the report, I fixed this bug in #1244, it will be available once I publish a new release :).
