### ISSUE TITLE
Covers tags generated by vimium(and other content on the webpage)

### ISSUE THREAD

**Issue by glyh** [glacambre/firenvim#1246]
- OS Version: `Linux arch 5.15.2-arch1-1 #1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000 x86_64 GNU/Linux`
- Browser Version: Brave 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
- Browser Addon Version: 0.2.10 
- Neovim Plugin Version: 0.2.10

### What I tried to do

Lose focus from firenvim, and focus it again via vimium; I do it by pressing "f" to command vimium to generate tags

### What happened

Tags are covered by firenvim, so I can't see it. 

![image](https://user-images.githubusercontent.com/12870742/142612124-4907f5ae-2a7d-4c7f-8c84-88efeffd42c8.png)

**Comment by glyh** [comment]
There are also some other times this neovim layer convers some floating windows, It would be better if this neovim layer can just lie in the right position just like the textbox.

**Comment by glacambre** [comment]
>Tags are covered by firenvim, so I can't see it.

I already lowered the z-Index of the firenvim frame [once](https://github.com/glacambre/firenvim/commit/6f152a9b37460ccb29ebabf7afc4abaab78d2415) for Vimium. I won't do this again, if the hints can't cover the Firenvim iframe this is Vimium's issue. Note that other "vim in the browser" extensions such as Tridactyl are able to display hints over the Firenvim frame.

>There are also some other times this neovim layer convers some floating windows, It would be better if this neovim layer can just lie in the right position just like the textbox.

This is covered by https://github.com/glacambre/firenvim/issues/427 .

I'll close this issue but feel free to ask any other question you may have :).
