### ISSUE TITLE
Not working for gist.github.com due to CSP

### ISSUE THREAD

**Issue by glyh** [glacambre/firenvim#1249]
- OS Version: `Linux arch 5.15.2-arch1-1 #1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000 x86_64 GNU/Linux`
- Browser Version:  Mozilla Firefox 95.0b9
- Browser Addon Version: 0.2.10
- Neovim Plugin Version: 0.2.10

### What I tried to do

Using [Github GIST](https://gist.github.com/)

### What happened

Not working.

**Comment by glacambre** [comment]
This is fixed on master - the fix will reach you when I publish a new version :)
