### ISSUE TITLE
error in browser.storage.local.get() handler

### ISSUE THREAD

**Issue by justinmk** [glacambre/firenvim#125]
- firenvim version:  0.1.9 (from Chrome web store)
- OS Version: Windows 10 64bit
- Browser Version: Chrome 76
- What I tried to do: Trying to get firenvim "working", i.e. have it enable on a text area/box

- What happened: 

When I click on a text area (e.g. at http://txti.es/ ), firenvim doesn't activate.  I see this in the Chrome devtools console:

```
content.ts:220 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at content.ts:220
```

navigating to the source, it highlights `.entries(localSettings)`, suggesting that `Object.entries(localSettings)` is undefined:

```
browser.storage.local.get("localSettings").then(async ({ localSettings }: { [key: string]: { [key: string]: any }}) => {
    function or1(val: number) {
        if (val === undefined) {
            return 1;
        }
        return val;
    }
    const [, conf] = Array.from(Object.entries(localSettings))
        .sort((e1, e2) => (or1(e2[1].priority) - or1(e1[1].priority)))
        .find(([pat, sel]) => (new RegExp(pat)).test(document.location.href));
    if (conf.selector) {
        setupListeners(conf.selector);
    }
});
```

### Additional info

I tried following the [troubleshooting steps](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-browser-extension-can-communicate-with-neovim). When I click "background page", the console shows:

```
_generated_background_page.html:1 Unchecked runtime.lastError: Specified native messaging host not found.
```

**Comment by glacambre** [comment]
Thanks for providing the background page's log, it's useful. I assume you ran `call firenvim#install(0)` and it printed `Installed manifest for Chrome.` and `Created registry key for Chrome.`.

Could you check if you have a file named `firenvim.json` in your `$XDG_DATA_HOME\firenvim` or `fnamemodify(stdpath("data"), ":h") . '\firenvim'` directories?

If you do, do you also have a registry key named `HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\firenvim`, the value of which is an absolute path to the `firenvim.json` file?

Could you open `firenvim.json` and check if the `path` attribute is an absolute path to a batch file named `firenvim.bat`?

Could you upload the content of that batch file here?

**Comment by justinmk** [comment]
>  I assume you ran `call firenvim#install(0)` and it printed `Installed manifest for Chrome.` and `Created registry key for Chrome.`.

Yes, but I ran `firenvim#install()` without `0`. Re-ran with `0` . In all cases, it prints:

```
No config detected for firefox. Skipping.
Installed native manifest for chrome.
Creating registry key for chrome. This may take a while.
Created registry key for chrome.
No config detected for chromium. Skipping.
```

> Could you check if you have a file named `firenvim.json` in your `$XDG_DATA_HOME\firenvim` or `fnamemodify(stdpath("data"), ":h") . '\firenvim'` directories?

Directory contents of `C:\Users\foo\AppData\Local\firenvim`:

```
C:\Users\foo\AppData\Local\firenvim\chrome.ps1
C:\Users\foo\AppData\Local\firenvim\firenvim-chrome.json
C:\Users\foo\AppData\Local\firenvim\firenvim.bat
```

contents of `filenvim-chrome.json`:

```
{ "name": "firenvim", "description": "Turn Firefox into a Neovim client.", "path": "C:\\Users\\foo\\AppData\\Local\\firenvim\\firenvim.bat", "type": "stdio", "allowed_origins": [ "chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/" ]}
```

> If you do, do you also have a registry key named `HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\firenvim`, the value of which is an absolute path to the `firenvim.json` file?

Navigating to `HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts` in regedit, I don't see a `firenvim` entry. Only `com.microsoft.browsercore`.

I wonder if UAC prevented `firenvim#install()` from editing the registery? I didn't get prompted.

> Could you open `firenvim.json` and check if the `path` attribute is an absolute path to a batch file named `firenvim.bat`?

Do you mean `firenvim-chrome.json`? (Contents are listed above.)

> Could you upload the content of that batch file here?

Contents of `C:\\Users\\foo\\AppData\\Local\\firenvim\\firenvim.bat` :

```
@echo off
cd "C:\Users\foo\AppData\Local\firenvim"
"C:\Users\foo\Downloads\nvim-win64\Neovim\bin\nvim.exe" --headless -c "call firenvim#run()"
```

**Comment by justinmk** [comment]
If I remove the `-ErrorAction SilentlyContinue` args from `firenvim/chrome.ps1, this is the result:

```
:!powershell C:/Users/foo/AppData/Local/firenvim/chrome.ps1

C:/Users/foo/AppData/Local/firenvim/chrome.ps1 : File C:\Users\foo\AppData\Local\firenvim\chrome.ps1 cannot be 
loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ C:/Users/foo/AppData/Local/firenvim/chrome.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

I'm poking around to see if there's a way to fix this without "Run as administrator".
