### ISSUE TITLE
"Neovim died without answering."

### ISSUE THREAD

**Issue by nobodyatandnothing** [glacambre/firenvim#1264]
- OS Version: Clear Linux 35390
- Browser Version: Chromium 96.0.4664.45 (flatpak)
- Browser Addon Version: 0.2.11
- Neovim Plugin Version: manual installation neovim 0.6.0

### What I tried to do
install firenvim 
i tried everything in the troubleshooting guide 

### What happened
does not work
![Screenshot from 2021-12-07 17-10-49](https://user-images.githubusercontent.com/91722596/145113964-58b5e57f-9339-47ee-9ede-1ba3c98f7886.png)

**Comment by glacambre** [comment]
The problem comes from using flatpak. Chromium most probably is not allowed to start neovim. Unfortunately, there is nothing I can do about this. If you want to use Firenvim, you will have to find a way to install Chromium without using flatpak.

**Comment by nobodyatandnothing** [comment]
thank you

**Comment by glacambre** [comment]
You're welcome. Don't hesitate to ask for more help if you need it :).
