### ISSUE TITLE
Add configuration instructions to browser add-on preferences page

### ISSUE THREAD

**Issue by albertas** [glacambre/firenvim#1266]
It would be great if there was a firenvim addon option not to start firenvim on textarea focus, but only after pressing `<C-e>`. I found out that most of the times I don't want to use firenvim for small changes, but its handy when writing longer text.

**Comment by glacambre** [comment]
You can do this by using firenvim's [takeover](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements) setting :).

I'm curious, have you searched for this? If yes, what keywords did you use (so that I may add them to the readme)?

**Comment by albertas** [comment]
I have simply installed the addon for Firefox and went to addon preferences and there was no preferences.

Thanks, now I see that there is and example in README.md how to achieve this. Didn't think that browser addon can be configured via nvim config.

**Comment by glacambre** [comment]
Ah, yes, at first Firenvim was configurable through the browser, but in the end I thought that allowing to configure it through yout init.vim/lua would make more sense.

Thank you for trying out Firenvim, and don't hesitate to ask more questions if you have them! :)

**Comment by glacambre** [comment]
Actually I think it'd be a good idea if the browser add-on preferences page told the user that Firenvim is configured through init.vim/init.lua. Let's repurpose this issue for this :)

**Comment by glacambre** [comment]
Done, the next release will have a link to the README on the addon preferences page :)
