### ISSUE TITLE
Is it possible to customize the background based on the website we are on?

### ISSUE THREAD

**Issue by pvinis** [glacambre/firenvim#127]
I would like to know if it's possible to have something in my config that will only customize firenvim. Furthermore, if I can have something like 'on github, background should be always light', and as a default the brackground should be dark.

Is that possible? Does it make sense? Thanks.

**Comment by glacambre** [comment]
Yes, it's possible. Buffers are named after the following scheme: `domainname_page_selector.txt` so you can use an autocommand like `au BufEnter github.com_*.txt set background=light` to your init.vim to have neovim set the background to white every time you edit a github textarea.

**Comment by pvinis** [comment]
awesome! I'll do that.

ps: one other thing. where are these buffers stored? can I recover them?

**Comment by glacambre** [comment]
They're in `$HOME/.local/share/firenvim` on linux and OSX, but I plan to move them to another directory (#112). They're automatically deleted when you close the firenvim instance that created them.
