### ISSUE TITLE
Reddit's title issue

### ISSUE THREAD

**Issue by zim0369** [glacambre/firenvim#1271]
- OS Version: `Linux arch 5.15.7-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 08 Dec 2021 14:33:18 +0000 x86_64 GNU/Linux`
- Brave Version: `Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)`
- Browser Addon Version: 0.2.11
- Neovim Plugin Version: 0.2.11

### What I tried to do
Attempted to write into the title section of reddit.

### What happened
https://i.imgur.com/hvBOryt.png

**Comment by glacambre** [comment]
I can't reproduce this issue, so it's most likely coming from your config/plugins. Try commenting out everything line of your init.vim/init.lua until you find the one responsible :).

**Comment by zim0369** [comment]
> I can't reproduce this issue, so it's most likely coming from your config/plugins. Try commenting out everything line of your init.vim/init.lua until you find the one responsible :).

My config is a little too big. Can you try to tell me what plugin must be
causing it? Like a random guess?
```
require('settings')
require('autocmds')
require('plugins/packer')
require('plugins/nvim-colorizer')
require('plugins/nvim-lspconfig')
require('plugins/telescope-fzf-native')
require('plugins/comfortable-motion')
require('plugins/nvim-treesitter')
require('plugins/nvim-autopairs')
require('plugins/headlines-nvim')
require('plugins/renamer-nvim')
require('plugins/nvim-neorg')
require('plugins/nvim-tree')
require('plugins/telescope')
require('plugins/venn-nvim')
require('plugins/hop-nvim')
require('plugins/nvim-cmp')
require('plugins/null-ls')
require('plugins/feline')
require('compiler')
require('mappings')

-- Needs to be loaded in the end
require('plugins/tabout-nvim')
```

**Comment by glacambre** [comment]
>My config is a little too big. Can you try to tell me what plugin must be causing it? Like a random guess?

No, I can't. You're the one who built your config, you're the only one able to debug it :).

**Comment by mcepl** [comment]
> > I can't reproduce this issue, so it's most likely coming from your config/plugins. Try commenting out everything line of your init.vim/init.lua until you find the one responsible :).
> 
> My config is a little too big. Can you try to tell me what plugin must be causing it? Like a random guess?
> 
> ```
> require('settings')
> require('autocmds')
> require('plugins/packer')
> require('plugins/nvim-colorizer')
> require('plugins/nvim-lspconfig')
> require('plugins/telescope-fzf-native')
> require('plugins/comfortable-motion')
> require('plugins/nvim-treesitter')
> require('plugins/nvim-autopairs')
> require('plugins/headlines-nvim')
> require('plugins/renamer-nvim')
> require('plugins/nvim-neorg')
> require('plugins/nvim-tree')
> require('plugins/telescope')
> require('plugins/venn-nvim')
> require('plugins/hop-nvim')
> require('plugins/nvim-cmp')
> require('plugins/null-ls')
> require('plugins/feline')
> require('compiler')
> require('mappings')
> 
> -- Needs to be loaded in the end
> require('plugins/tabout-nvim')
> ```

Just copy your current config somewhere else and create the minimal one for this bug.

**Comment by zim0369** [comment]
Okay.

**Comment by zim0369** [comment]
The issue is related to nvim-cmp.

**Comment by molleweide** [comment]
A tip that i learnt is to comment out half of the plugins and do a binary search for the plugin that generates the problem.
