### ISSUE TITLE
How to change style to default instead of my neovim custom style?

### ISSUE THREAD

**Issue by AGou-ops** [glacambre/firenvim#1273]
- OS Version: mac arm64
- Browser Version: Google Inc. Chrome 96.0.4664.110
- Browser Addon Version: 0.2.11
- Neovim Plugin Version: 0.2.11

I don't want this:
![image](https://user-images.githubusercontent.com/57939102/147215980-ac4dfe49-7d64-4cde-a423-52b87dd0c88e.png)

I want this default neovim style instead:
![image](https://user-images.githubusercontent.com/57939102/147216062-4a14b79c-195d-4838-971c-25b61ffd73c0.png)

**Comment by glacambre** [comment]
This is not neovim's default style, this is my custom colorscheme. If you want to have a white background, add something like this to the end of your init.vim:
```vim
if exists('g:started_by_firenvim')
  set bg=light
  colorscheme delek
end
```

I'll close this issue but feel free to ask any other question you may have :).

**Comment by AGou-ops** [comment]
> This is not neovim's default style, this is my custom colorscheme. If you want to have a white background, add something like this to the end of your init.vim:
> 
> ```viml
> if exists('g:started_by_firenvim')
>   set bg=light
>   colorscheme delek
> end
> ```
> 
> I'll close this issue but feel free to ask any other question you may have :).

I see. Thank you very much! Very interesting plugin!
