### ISSUE TITLE
Disable firenvim by default

### ISSUE THREAD

**Issue by ferdinandyb** [glacambre/firenvim#1285]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 96.0.4664.110
- Browser Addon Version: 0.2.11
- Neovim Plugin Version: 0.2.11

### What I tried to do

Firenvim sounds like fun, but currently I think in the majority of cases I would NOT be using it, so I would rather go by having a shortcut to manually active per textarea when I need it. 

For this effect, I set up the config as such:

```
let g:firenvim_config = { 
    " \ 'globalSettings': {
    "     \ 'alt': 'all',
    " \  },
    \ 'localSettings': {
        \ '.*': {
            \ 'takeover': 'never',
        \ },
    \ }
\ }
```

### What happened

This kind-of works, but every time I click on text area firenvim flashes up (and it looks like if I go to a different page than come back I might have the whole area replaced by white space which goes away after some clicking around). I'm assuming something is actually launched which later decides based on the vim config that it is not need. 

What would be great to have is for a setting where firenvim doesn't do anything at all other than listen for ctrl+e and if it gets it, _then_ invoke nvim.

**Comment by glacambre** [comment]
This is caused by the three commented lines in your g:firenvim_config object - they confuse neovim and as a result your config isn't applied. Remove them and Firenvim should start behaving as expected :).

**Comment by ferdinandyb** [comment]
So as per your suggestion I modified the config. It still flashes when I click into the textbox, and if I click outside the box I get this:

![image](https://user-images.githubusercontent.com/6343487/148022546-1e511450-d026-444f-9ae0-58a1bdcc195a.png)

note that I have already entered the above text, when I clicked outside (and the background of the textbox should be black with my github settings).

Since the config is not long I'm going to put the entire `nvim` config here.

init.vim:
```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
if exists('g:started_by_firenvim')
    source ~/.vim/configs/firenvim.vim
else
    source ~/.vim/vimrc
endif
```

and the sourced firenvim.vim:
```
set laststatus=0

let g:firenvim_config = {
    \ 'localSettings': {
        \ '.*': {
            \ 'takeover': 'never',
        \ },
    \ }
\ }
```
I haven't actually figured out yet how to make the white overlay disappear, it feels like if I click enough times into the box it goes away after a while. 

I'm not sure if this is relevant, but this is my nvim version:
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-PzR5es/neovim-0.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-PzR5es/neovim-0.5.1/build/config -I/build/neovim-PzR5es/neovim-0.5.1/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-PzR5es/neovim-0.5.1/build/src/nvim/auto -I/build/neovim-PzR5es/neovim-0.5.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
```

Thanks for taking the time!

**Comment by glacambre** [comment]
This is a very barebones init.vim - are you sure you are loading the firenvim plugin in neovim?

**Comment by ferdinandyb** [comment]
OK, so this is super embarrassing, but I actually managed to delete the entire plugin. I also didn't notice until now, that the extension icon changes when it cannot connect to nvim ... Really sorry to have taken your time with this ...

**Comment by glacambre** [comment]
No problem, glad to see the problem is solved :)
