### ISSUE TITLE
Allow users to define separate nvim config (and binary) to use for firenvim

### ISSUE THREAD

**Issue by errantepiphany** [glacambre/firenvim#1286]
I think it would be great if people could, via configuration of the **browser extension settings**, specify a different nvim config file to use rather than the default. So instead of launching nvim with no arguments (which would mean nvim sourcing `~/.config/nvim/init.vim` by default), let the user configure it to start with `nvim -u ~/.config/firenvim/init.vim` (or `nvim -u ~/my/custom/path/my-config.lua`, or whatever).

For people with medium-to-complex nvim init configs, it's way cleaner (and much easier to maintain) to separate their firenvim-specific config from their normal nvim config by using completely different files. Otherwise what you end up with is having to litter a bunch of  `if exists('g:started_by_firenvim')` all throughout your config.

The above gets especially messy if one likes to modularize their nvim config into options, mappings, plugins, etc. - all sourced from init.vim (or init.lua). Right now you have to go digging to find everywhere you do the g:started_by_firenvim if/else logic, and hope it all plays nice together in the order it's all loaded.

Extra credit would be to let the user specify the **entire** nvim command that gets executed, that way they can even invoke a different nvim binary then the one that is default in their PATH. (Just in case they're testing different nvim versions.) So, something like `~/.local/bin/nvim.appimage -u ~/.config/nvim/pre-release.vim`.

Thanks so much for your consideration. I did find this other issue, but it's a little different in purpose, I think:
https://github.com/glacambre/firenvim/issues/1209

**Comment by glacambre** [comment]
>I think it would be great if people could, via configuration of the browser extension settings, specify a different nvim config file to use rather than the default.

Browser extensions have no way of controlling what programs gets launched or what arguments are given to the programs that are run (it's all statically defined in a manifest created when you run `firenvim#install`), so it would be impossible to run neovim with a different `-U` flag depending on user settings.

>The above gets especially messy if one likes to modularize their nvim config into options, mappings, plugins, etc. - all sourced from init.vim (or init.lua).

I do this myself and I don't really see the problem :). You can do something like
```vim
source /path/to/common.vim
if exists('g:started_by_firenvim')
  source /path/to/firenvim_config.vim
else
  source /path/to/programming_config.vim
end
```

>Extra credit would be to let the user specify the entire nvim command that gets executed, that way they can even invoke a different nvim binary then the one that is default in their PATH.

Impossible to do with a browser setting, for the reasons stated above. However there are two ways you can change the neovim used by firenvim: either run `call firenvim#install(0)` again from the new neovim you want to try, or add a prolog to the `firenvim#install` call once, like this: .

```vim
let prolog =<<EOF
if [ SOME CONDITION ]; then
  exec '/path/to/neovim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()'
else
  exec '/other/path/to/other/neovim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()'
fi
EOF

call firenvim#install(0, join(prolog, "\n"))
```

**Comment by glacambre** [comment]
Closing this issue but feel free to ask any other question you may have :)

**Comment by errantepiphany** [comment]
Hi @glacambre , thanks for the detailed reply. The problem with using the `if exists('g:started_by_firenvim')` conditional to load different config files is that I still need to load the firenvim vim plugin first before that global variable is set, right? The thing is, the biggest point of having two separate config files is that I don't want to load any of my other plugins if firenvim is active. So that means I'd have to load firenvim, do the check, then potentially load my other plugins. I guess that's possible, but I use a plugin manager so I don't know if it's possible to load plugins twice (with a different list). I guess what I could do is load firenvim with vim's built-in directory-structure-based package support for plugins, and then save using vim-plug for everything else. Either way, I've got some things I can try, so thanks again.

**Comment by errantepiphany** [comment]
Gah, nvmd. Vim loads packages (plugins) _after_ it processes the user's vimrc file. So that would be too late to exclude loading plugins with vim-plug. :/

**Comment by glacambre** [comment]
>The problem with using the if exists('g:started_by_firenvim') conditional to load different config files is that I still need to load the firenvim vim plugin first before that global variable is set, right?

Nope, this variable will exist before any plugin/config is loaded :).

**Comment by errantepiphany** [comment]
Okay, that makes it a lot easier, thank you! Works great. :)
