### ISSUE TITLE
firenvim#eval_js not working

### ISSUE THREAD

**Issue by olablt** [glacambre/firenvim#1287]
- OS Version: Fedora
- Browser Version: Firefox 95.0.2
- Browser Addon Version: 0.2.11
- Neovim Plugin Version: 0.2.2

### What I tried to do

In vim config I have a command:

```
nnoremap <C-s> <Cmd>call  firenvim#eval_js('console.log("Hello World!")')<CR>
```

### What happened

When I press C-s in console I get:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

### My question

How to overcome?

**Comment by glacambre** [comment]
This is caused by the website's security settings, unfortunately there is nothing you can do to work around this. I think I might be able to work around this issue in Firefox by using a hidden API instead of what I'm currently doing, so I'll keep this issue open.

Thanks for the report :)
