### ISSUE TITLE
Add multiple localSettings concerning all sites

### ISSUE THREAD

**Issue by xeruf** [glacambre/firenvim#1291]
- OS Version: linux x86-64
- Browser Version:  Firefox 96.0
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### What I tried to do

Add multiple localSettings concerning all sites.

### What happened
	
```lua
    \ '.*': {
      \ 'cmdline': 'firenvim',
      \ 'priority': 0,
      \ 'selector': 'textarea:not([readonly]):not([class="handsontableInput"]):not([wrap="off"]):not([rows="1"]):not([title="Replace"]):not([title="Search"]):not([name="message"]),
        \ div[role="textbox"]:not([aria-label="Search"])',
      \ 'takeover': 'always',
    \ },
    \ '.*': {
      \ 'priority': 1,
      \ 'selector': 'textarea.inputbox',
      \ 'takeover': 'once',
    \ },
```
plugin complains about duplicate key. So how else should I implement this?

**Comment by glacambre** [comment]
It's not the plugin that complains, it's Neovim :). You should try another pattern that will match in the same way, e.g. `.+` or `..*`.

**Comment by glacambre** [comment]
I'll close this issue, but don't hesitate to ask more questions if you have some :)
