### ISSUE TITLE
Blacklist and whitelist not working as expected

### ISSUE THREAD

**Issue by yuujay** [glacambre/firenvim#1293]
I am trying to make `firenvim` by default to not takeover any site instead takeover on only a few sites. But for some reason, I can't seem to have this working.
 
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 97.0.4692.99
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### What I tried to do

I looked at the README configuration as well as couple of closed issues, but unable to get it to work. I am using nvim `v0.6.1` on mac and have the following `lua` configuration

```lua
vim.g.firenvim_config = {
      globalSettings = {
         alt = 'all',
      },
     localSettings = {
         ['.*'] = {
             cmdline  = 'neovim',
             content  = 'text',
             priority = 0,
             selector = 'textarea',
             takeover = 'never',
         },
         ['stackoverflow.com'] = { takeover= 'always' },
         ['github.com'] = { takeover= 'always' },
     }
 }
```

### What happened

I seem to have firenvim take over on all domains irrespective of the filters that I put in. 

Can someone help me look at the config and let me know what I have configured wrong?

**Comment by glacambre** [comment]
@yuujay I can't reproduce your problem. I copy-pasted your snippet in my init.vim and this resulted in firenvim not taking over `txti.es`'s textarea anymore, while still automatically taking over github's.

Is your config available somewhere?

**Comment by yuujay** [comment]
Thanks for the response @glacambre  

I have my configurations commented in my dotfiles [here](https://github.com/yuujay/dotfiles/blob/ce9618a68941554db1a173123592f83f1d318217/nvim/lua/plugins/plugin-config.lua#L32) . Let me know if you need any information troubleshooting this issue.

**Comment by yuujay** [comment]
My bad with the commit that I sent. I did try with `['.*'] = {` it didn't work. Hence, I was fiddling with `stackOverflow.com` just to see if it blacklists that. But the configuration wasn't disabling firenvim on StackOverflow. Is there any difference between how vimscripts and lua configurations?

**Comment by glacambre** [comment]
>Is there any difference between how vimscripts and lua configurations?

I don't think so, although I can't claim to be an expert on the topic. It would really surprise me, given that I copy-pasted the snippet of your first post in my config and it worked. Have you tried to put it at the end of your init.lua?

**Comment by yuujay** [comment]
I am not sure what else to look for. 

This is the output for `echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim` 

```
N{"version": "0.2.12", "settings": {"localSettings": {".*": {"priority": 0, "cmdline": "neovim", "content": "text", "selector": "textarea", "takeover": "never"}, "github.mathworks.com": {"takeover": "always"}, "confluence.mathworks.com": {"takeover": "always"}, "github.com": {"takeover": "always"}}, "globalSettings": {"alt": "all"}}}
```

Also my installation of the plugin is with this in `{'glacambre/firenvim', run='firenvim#install(1)'},` from my init.lua [here](https://github.com/yuujay/dotfiles/blob/ce9618a68941554db1a173123592f83f1d318217/nvim/lua/install-plugins.lua#L60) 

I did run `nvim --headless "+call firenvim#install(0) | q" ` from command line. Notice the **number** 0 and 1 from both my init and the command that I ran. Would that have messed any configuration?

If you don't see anything that stands out, feel free to close the issue. Thanks for all the help.

**Comment by glacambre** [comment]
>Notice the number 0 and 1 from both my init and the command that I ran. Would that have messed any configuration?

No, that shouldn't cause any issues :).

>If you don't see anything that stands out, feel free to close the issue.

I don't close issues until the bug is fixed :). I guess we will need to jump in the debugger to figure out what's happening.

In order to do that, go to `chrome://extensions`, enable developer mode (top right toggle), click on the "details" button of the firenvim extension, click on `background page` in the `inspect views` section. This should open a debugger window.

Click on the `Sources` tab, and open `background.ts` in the file tree in the left column (Firenvim > . > src > background.ts). Search (`Ctrl+f`) for `applySettings(resp.settings).finally(() => {` and once you found it, right click on the number column, select `Add logpoint`, type `resp` and unfocus the input box.

Once you've done that, go to the `Console` tab, click the Firenvim icon next to the urlbar and then click the `Reload settings` button. This should result in a json object containing your settings being printed in the console, can you copy that object and paste it here?

**Comment by yuujay** [comment]
Thanks for the detailed debugging steps. I tried the steps that you had, I get few errors on the console when I try reloading the plugin from my browser extension icon. Let me know if you need more information. 

![image](https://user-images.githubusercontent.com/3604600/152700094-24f9233d-31e7-4324-a153-a194fd7c5603.png)

**Comment by glacambre** [comment]
Thank you for providing this info. It's very puzzling, with these errors I would expect Firenvim to not work at all, not to take over every domain. The logpoint doesn't seem to be triggered at all.

You should find a script named `firenvim` in `$HOME/.local/share/firenvim`, could you edit its last line like this:

```diff
-exec '/usr/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()'
+exec '/usr/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()' 2>>/tmp/firenvim_errors | tee /tmp/stdout
```

Then, try to activate/deactivate firenvim a couple of times. After that, please upload the content of `/tmp/stdout` and `/tmp/stderr` here. Hopefully it'll make the problem obvious.
