### ISSUE TITLE
Can't select c-w (ctrl+w) or a-w (alt+w) for deleting shortcut on osx

### ISSUE THREAD

**Issue by Liverm0r** [glacambre/firenvim#1296]
![image](https://user-images.githubusercontent.com/14236531/151665408-13e34eb2-ec16-4f14-835e-6611d7f1a003.png)

- OS Version: osx monterey 12.1
- Browser Version: chrome Version 97.0.4692.99 (Official Build) (x86_64)
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: master 1f91597

### What I tried to do
Trying to select ctrl+w for typical ctrl+w vim action in chrome://extensions/shortcuts

### What happened
Red line shows an error that I should use ctr, alt or cmd. 
But I am using it! 
I can select cmd+w or ctrl+v, but cant use ctrl+w.

**Comment by glacambre** [comment]
This sounds like a bug in your browser, as this works fine on google chrome 99.0 on linux. Please report it on Google's bug tracker.

**Comment by Liverm0r** [comment]
Oh, my, the problem was in the fact that I override c-w in karabiner to work like alt+delete and forget about it.

**Comment by glacambre** [comment]
Great to hear, thank you for reporting the solution to your problem :).
