### ISSUE TITLE
Ability to disable transparency or make it less translucent

### ISSUE THREAD

**Issue by Liverm0r** [glacambre/firenvim#1305]
I have a usecase when I work with two chrome windows opened and visible with virenvim opened in both. I want them both to be visible. 

As found [here](1), it was deliberately made so to tell the user that window has no focus. But is there a way to decrease transparency in some way or completely disable it?

[1]: https://github.com/glacambre/firenvim/issues/756

**Comment by glacambre** [comment]
No, there is no way to disable transparency for now.

Closing this issue as duplicate of https://github.com/glacambre/firenvim/issues/1100 :).
