### ISSUE TITLE
TROUBLESHOOTING.md: Undefined variable: reject

### ISSUE THREAD

**Issue by thesofakillers** [glacambre/firenvim#1316]
- OS Version: MacOS Catalina 10.15.7 
- Browser Version: Chrome Version 98.0.4758.102 (Official Build) (x86_64)
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### Issue Description

I am troubleshooting another (very niche) issue (everything else works perfectly).
Before opening the (niche) issue here, I want make sure I went through the troubleshooting guide.
When I get to [Make sure the firenvim script has been created
](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-firenvim-script-has-been-created) I run as instructed

```console
echo 'abcde{}' | ~/.local/share/firenvim/firenvim
```

And get the following output

```stderr
{"version": "0.2.12", "settings": {"localSettings": {".*": {"priority": 0, "cmdline": "neovim", "takeover": "never", "selector": "textarea", "content": "text"}}, "globalSettings": {"alt": "all"}}}Error detected while processing function OnStdin[3]..<SNR>74_NvimExitCallback[7]..<SNR>73_OnExit:
line    7:
E121: Undefined variable: reject
```

Not sure if this is what's causing my other (very niche) issue, but thought I would flag this sort of output. Everything else seems to be running fine

**Comment by glacambre** [comment]
Hi, thanks for the report. That's quite an interesting error. Could you run something like `grep -r OnExit` in the directory where your plugins are stored (usually `~/.config/nvim`)?

**Comment by thesofakillers** [comment]
Thanks for the fast response!

I get

```
grep: warning: recursive search of stdin
```

And the command hangs without further output, I imagine due to the recursion. Not sure how long I should wait.

I should note that my plugins are usually stored in `~/.vim/plugged/` and that my `init.vim` file used by neovim in `~/.config/nvim/` is simply sourcing my vim config, i.e.

```viml
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vim/vimrc
```

I've tried running `grep -r OnExit` both in `~/.vim/plugged/` and in `~/.config/nvim/` but the result is the same

**Comment by glacambre** [comment]
Sorry, I meant *on* the directory rather than *in*. `grep -r OnExit ~/.vim/plugged` and `grep -r ~/.config/nvim` should give us more results (or at least, end in a reasonable time :)).

**Comment by thesofakillers** [comment]
Ahh my bad. Here is what I get for `grep -r OnExit ~/.vim/plugged`

```stdout
/Users/thesofakillers/.vim/plugged/vim-polyglot/autoload/go/config.vim:function! go#config#TermCloseOnExit() abort
/Users/thesofakillers/.vim/plugged/vim-polyglot/autoload/go/config.vim:function! go#config#SetTermCloseOnExit(value) abort
/Users/thesofakillers/.vim/plugged/vim-polyglot/syntax/zimbu.vim:syn match zimbuAttribute "@notOnExit\>"
/Users/thesofakillers/.vim/plugged/vim-polyglot/syntax/autoit.vim:syn match autoitOption "\([\"\']\)OnExitFunc\1"
/Users/thesofakillers/.vim/plugged/coc.nvim/autoload/coc/terminal.vim:  function! s:OnExit(status) closure
/Users/thesofakillers/.vim/plugged/coc.nvim/autoload/coc/terminal.vim:          \ 'on_exit': {job, status -> s:OnExit(status)},
/Users/thesofakillers/.vim/plugged/coc.nvim/autoload/coc/terminal.vim:          \ 'exit_cb': {job, status -> s:OnExit(status)},
/Users/thesofakillers/.vim/plugged/coc.nvim/autoload/coc/util.vim:  function! s:OnExit(status) closure
/Users/thesofakillers/.vim/plugged/coc.nvim/autoload/coc/util.vim:          \ 'on_exit': {job, status -> s:OnExit(status)},
/Users/thesofakillers/.vim/plugged/coc.nvim/autoload/coc/util.vim:          \ 'exit_cb': {job, status -> s:OnExit(status)},
Binary file /Users/thesofakillers/.vim/plugged/fzf/bin/fzf matches
/Users/thesofakillers/.vim/plugged/fzf/src/terminal.go:                 renderer = tui.NewLightRenderer(opts.Theme, opts.Black, opts.Mouse, opts.Tabstop, opts.ClearOnExit,
/Users/thesofakillers/.vim/plugged/fzf/src/terminal.go:         renderer = tui.NewLightRenderer(opts.Theme, opts.Black, opts.Mouse, opts.Tabstop, opts.ClearOnExit, false, maxHeightFunc)
/Users/thesofakillers/.vim/plugged/fzf/src/terminal.go:         cleanExit:   opts.ClearOnExit,
/Users/thesofakillers/.vim/plugged/fzf/src/options.go:  ClearOnExit bool
/Users/thesofakillers/.vim/plugged/fzf/src/options.go:          ClearOnExit: true,
/Users/thesofakillers/.vim/plugged/fzf/src/options.go:                  opts.ClearOnExit = true
/Users/thesofakillers/.vim/plugged/fzf/src/options.go:                  opts.ClearOnExit = false
/Users/thesofakillers/.vim/plugged/fzf/src/tui/light.go:        clearOnExit   bool
/Users/thesofakillers/.vim/plugged/fzf/src/tui/light.go:func NewLightRenderer(theme *ColorTheme, forceBlack bool, mouse bool, tabstop int, clearOnExit bool, fullscreen bool, maxHeightFunc func(int) int) Renderer {
/Users/thesofakillers/.vim/plugged/fzf/src/tui/light.go:                clearOnExit:   clearOnExit,
/Users/thesofakillers/.vim/plugged/fzf/src/tui/light.go:                if r.clearOnExit {
/Users/thesofakillers/.vim/plugged/fzf/src/tui/light.go:                if x > 0 && r.clearOnExit {
/Users/thesofakillers/.vim/plugged/fzf/src/tui/light.go:        if !r.clearOnExit && !r.fullscreen {
/Users/thesofakillers/.vim/plugged/fzf/src/tui/light.go:        if r.clearOnExit {
```

and here' s what i get for `grep -r OnExit ~/.config/nvim`

```stdout
/Users/thesofakillers/.config/nvim/pack/github/start/copilot.vim/autoload/copilot/agent.vim:function! s:OnExit(agent, code) abort
/Users/thesofakillers/.config/nvim/pack/github/start/copilot.vim/autoload/copilot/agent.vim:        \ function('s:OnExit', [instance]))
```

No mention of firenvim, although not sure if that's a good thing or a bad thing at this point. For reference, you can see my dotfiles [here](https://github.com/thesofakillers/dotfiles). Although I don't expect you to dedicate your time to perusing my dotfiles.

**Comment by glacambre** [comment]
Great, that's progress :). Does the error message still happen when you remove CoC from your config and also `rm -rf ~/.vim/plugged/coc.nvim`?

**Comment by thesofakillers** [comment]
Ok, i removed all coc-related things stuff from `~/.vim/plugged/coc.nvim`, from `~/.config/` and from my `vimrc`. 

Running

```console
echo 'abcde{}' | ~/.local/share/firenvim/firenvim
```

Once again gives 

```stderr
u{"version": "0.2.12", "settings": {"localSettings": {".*": {"takeover": "never"}}, "globalSettings": {"alt": "all"}}}Error detected while processing function OnStdin[3]..<SNR>68_NvimExitCallback[7]..<SNR>67_OnExit:
line    7:
E121: Undefined variable: reject
```

**Comment by glacambre** [comment]
Okay, thanks. I think we should then try to remove copilot - which seems like the only other possible culprit. Could you try removing anything about it from your init.vim and then doing a `rm -rf /Users/thesofakillers/.config/nvim/pack/github/start/copilot.vim` and then seeing if the error message is still there?

**Comment by thesofakillers** [comment]
That seemed to have fixed it!

Running

```console
echo 'abcde{}' | ~/.local/share/firenvim/firenvim
```

Now gives

```stdout
u{"version": "0.2.12", "settings": {"localSettings": {".*": {"takeover": "never"}}, "globalSettings": {"alt": "all"}}}
```

Note that re-enabling CoC does not cause the issue to resurface, so copilot was probably the culprit.

I imagine that that output is expected, right? If so, feel free to close this issue and I'll continue troubleshooting my original niche issue

**Comment by glacambre** [comment]
>I imagine that that output is expected, right?

Right, everything looks as expected now :).

>I'll continue troubleshooting my original niche issue

Okay. I'll close this issue but feel free to open another issue about your other problem :)
