### ISSUE TITLE
Autoformatting of LaTeX files via coc-texlab latexindent fails

### ISSUE THREAD

**Issue by thesofakillers** [glacambre/firenvim#1317]
- OS Version: MacOS Catalina 10.15.7
- Browser Version: Chrome Version 98.0.4758.102 (Official Build) (x86_64)
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### Issue Description

I use [CoC](https://github.com/neoclide/coc.nvim) a lot, particularly for its [LSP](https://en.wikipedia.org/wiki/Language_Server_Protocol) offerings. For LaTeX, I make use of [coc-texlab](https://github.com/fannheyward/coc-texlab), which, among other things, allows me to autoformat latex files through the use of [latexindent](https://github.com/cmhughes/latexindent.pl).

I was working on [Overleaf.com](https://overleaf.com), using firenvim, and tried calling the autoformatting like I normally would, but nothing happened.

From here I tried a few things:

- call autoformatting in a more manual way, i.e. `:call CocAction("format")`
  - it did not work
- tried running the formatting on a normal nvim instance on my terminal on a copy of the latex file i was editing on overleaf
  - it worked as expected
- checked that the correct filetype was being picked up by firenvim
  - it was, as confirmed by correct syntax highlighting
  - for safety, i also used `:set filetype=latex`
- tried editing a tex file on a different website, my CV here on GitHub
  - autoformatting also failed to do anything here
- tried editing another kind of file on GitHub
  - tried markdown, javascript, python
  - formatting always worked flawlessly, but here I am not using `coc-texlab` but
    rather `coc-jedi` or `coc-prettier`
- went through the `TROUBLESHOOTING.md` guide on this repository, to no avail.

So my conclusion is that for some reason, perhaps due to the internal machinations of latexindent, coc-texlab, firenvim, or some combination of these three, autoformatting with latexindent does not work in a firenvim instance, despite working in a normal nvim instance.

I understand this is a very niche issue and you may not have the bandwidth to solve it. If you have any ideas what's up, I'm all ears. If not, I thought I'd signal it here, in case someone else comes across this bug. Fortunately it's quite small and overall I'm very happy with firenvim.

PS: wrote this issue with firenvim ;).

**Comment by glacambre** [comment]
I think the problem probably is that latexindent is not in your $PATH. What happens when running `:!which latexindent` from firenvim and from the terminal?

**Comment by thesofakillers** [comment]
Forgot to mention that I also tried that. Running that command gives the same both from firenvim and from the terminal, i.e. I get `/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin/latexindent`, which seems correct.

**Comment by glacambre** [comment]
Does running `:%!latexindent` in firenvim work?

**Comment by thesofakillers** [comment]
Interesting. In my nvim terminal this prints `x lines filtered` when there is some autoformatting to do, or nothing. In firenvim, I get the following

```stderr
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LC_ALL = (unset),
	LANG = "en_IT.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Can't locate YAML/Tiny.pm in @INC (you may need to install the YAML::Tiny module) (@INC contains: /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 20.
BEGIN failed--compilation aborted at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 20.
Compilation failed in require at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/TrailingComments.pm line 21.
BEGIN failed--compilation aborted at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/TrailingComments.pm line 21.
Compilation failed in require at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/Replacement.pm line 20.
BEGIN failed--compilation aborted at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/Replacement.pm line 20.
Compilation failed in require at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 27.
BEGIN failed--compilation aborted at /usr/local/texlive/2021basic/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 27.
Compilation failed in require at /Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin/latexindent line 27.
BEGIN failed--compilation aborted at /Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin/latexindent line 27.
```

This is weird because I definitely have `YAML/Tiny.pm` installed.

**Comment by thesofakillers** [comment]
Fixed via [this comment](https://github.com/Glavin001/atom-beautify/issues/1792#issuecomment-357460658)

thanks for the help!
