### ISSUE TITLE
Most keys not working in vivaldi

### ISSUE THREAD

**Issue by Aetf** [glacambre/firenvim#1318]
- OS Version: linux x86-64
- Browser Version: Vivaldi 5.1.2567.49
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### What I tried to do

* Use a new vivaldi profile `vivaldi-stable --profile-directory=NewEmpty`
* Install firenvim from chrome store
* Install firenvim in nvim
* Make sure native message host manifest is in place
* Login to GitHub and goto https://github.com/glacambre/firenvim/issues/new
* Click on the textarea and see firenvim showing up
* Type `i` to go to insert mode
* Try type a few things

### What happened
Backspace/esc/ctrl-z not working. I didn't try others, but it seems only alphanumeric keys work.

In the webpage console, I see the following output every time I press a key that doesn't work:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'insert')
    at HTMLTextAreaElement.<anonymous> (KeyHandler.ts:56:31)
(anonymous) @ KeyHandler.ts:56
```

There's also these during initial page loading
```
page.ts:283 Unhandled page request: {args: Array(1), funcName: Array(1)}args: [0]0: 0length: 1[[Prototype]]: Array(0)funcName: ['setLastFocusedContentScript']0: "setLastFocusedContentScript"length: 1[[Prototype]]: Array(0)[[Prototype]]: Object
(anonymous) @ page.ts:283
onMessage @ browser-polyfill.js:1
```

**Comment by glacambre** [comment]
Huh, weird, Firenvim is known to work in vivaldi (see e.g. https://github.com/glacambre/firenvim/issues/1012 ).

The error message you provided means that ignoreKeys is undefined here:

https://github.com/glacambre/firenvim/blob/a9ac769d3c87c9b4c4671e7c295cb3916b5400eb/src/KeyHandler.ts#L56

The settings are passed to KeyHandler from BrowserKeyhandler:

https://github.com/glacambre/firenvim/blob/a9ac769d3c87c9b4c4671e7c295cb3916b5400eb/src/frame.ts#L16

Which itself got its settings from getGlobalConf:

https://github.com/glacambre/firenvim/blob/a9ac769d3c87c9b4c4671e7c295cb3916b5400eb/src/frame.ts#L72

And getGlobalConf just returns the "globalSettings" object of the settings:

https://github.com/glacambre/firenvim/blob/a9ac769d3c87c9b4c4671e7c295cb3916b5400eb/src/utils/configuration.ts#L150

Which we do define here:

https://github.com/glacambre/firenvim/blob/a9ac769d3c87c9b4c4671e7c295cb3916b5400eb/src/utils/configuration.ts#L87

So I think this can mean two things: either you have a broken `g:firenvim_config` object in your init.vim or Vivaldi's browser extension storage is broken. Do you have a `firenvim_config` object in your init.vim?

**Comment by Aetf** [comment]
You are right that the `g:firenvim_config` object is broken. Removing it from my init.vim solves the problem.

I don't understand why it is broken, though. I had the following in lua

```lua
  vim.g.firenvim_config = {
    globalSettings = {
    },
    localSettings = {
      ['.*'] = {
        takeover = 'always',
      },
    },
  }
```

**Comment by glacambre** [comment]
Writing `globalSettings = {}` in lua makes neovim translate globalSettings as an array, not an empty object. But `globalSettings` has to be an object. I'll add some defensive code in Firenvim to handle this case, thanks for the report :)
