### ISSUE TITLE
Tracking down hotkey conflicts?

### ISSUE THREAD

**Issue by larsks** [glacambre/firenvim#1320]
- OS Version: Fedora 35
- Browser Version: Vivaldi 5.1.2567.49
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 

### What I tried to do

I'm running Firenvim in two profiles in the same Chrome-based browser (Vivaldi right now, but I also saw this with Brave). In both profiles, I have the "Turn the currently focused element into a neovim iframe." keyboard shortcut set to "CTRL-I" ("Global").

In one profile, it works just fine.

In the other profile, it does nothing.

And to make it *extra* frustrating, if I decide instead to use `SHIFT-CTRL-I` as the activator, the behavior *switches*: the profile that worked with `CTRL-I` doesn't work with `SHIFT-CTRL-I`, and vice-versa. I just want the plugin to work the same in both profiles :).

I assume there's a conflicting hotkey configured somewhere, but where? I tried disabling all other extensions in the non-working profile, and I still can't get `CTRL-I` to work as the Firenvim activator in one profile.

Do you have any suggestions for figuring out what's going on here?

**Comment by glacambre** [comment]
>Do you have any suggestions for figuring out what's going on here?

Nope :). I know that chrome-based browsers have the concept of "global keyboard shortcuts", that apply even when the browser isn't focused. Perhaps the two profiles are stepping on eachother's toes? Does this also happen when a single browser instance is running?

**Comment by larsks** [comment]
> Perhaps the two profiles are stepping on eachother's toes?

Oh geez, that's totally it.

Part of the problem seems to be that I can only get the Firenvim hotkey to work when I mark the hotkey "Global". The problem seems to be *particular* to Firenvim -- other extensions with non-global hotkeys activate just fine. For example, the default hotkey for "ProxySwitch Omega" is `ALT-SHIFT-O`; if I type that while this text box is active, it pops up the extension's menu. If I disable that hotkey and assign it to Firenvim instead...nothing happens.

**Comment by larsks** [comment]
> Part of the problem seems to be that I can only get the Firenvim hotkey to work when I mark the hotkey "Global".

...which apparently only happens when using Vivaldi, so I'm just going to close this issue and swap browsers. Sorry for the noise!

**Comment by glacambre** [comment]
>Part of the problem seems to be that I can only get the Firenvim hotkey to work when I mark the hotkey "Global", which apparently only happens when using Vivaldi

Huh, weird. Do you know of any open-source extension that doesn't have issues with non-global hotkeys? I'd like to compare my code with something known to work to see if I'm doing anything wrong.

>Sorry for the noise!

No problem :)

**Comment by glacambre** [comment]
Thanks, I had looked for it but somehow couldn't find anything in Github search. Must have used the wrong keywords :)
