### ISSUE TITLE
ThePrimeagen showcase video was deleted.

### ISSUE THREAD

**Issue by pragmaticmero** [glacambre/firenvim#1321]
- OS Version: It doesn't matter
- Browser Version: Mozilla Firefox 97.0.1
- Browser Addon Version: Not installed yet
- Neovim Plugin Version: I plan to use native, that's another issue.

### What I tried to do

I clicked in the Primeagen showcase video for FireNvim

### What happened

The youtube appears to be deleted.

### Conclusion

Remove the missing link.

**Comment by glacambre** [comment]
Thanks for telling me :)
