### ISSUE TITLE
Console error for content.ts:220 

### ISSUE THREAD

**Issue by benwoodward** [glacambre/firenvim#133]
```javascript
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at content.ts:220
(anonymous) @ content.ts:220
[Violation] Forced reflow while executing JavaScript took 34ms
```

Using Chrome on Mac, Neovim 0.4.2

No errors showing in background page console.

**Comment by glacambre** [comment]
Does this also happen when you try to use firenvim [without loading your init.vim](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-its-not-your-initvim)?

**Comment by alexriedl** [comment]
This same thing happens to me in chrome on ubuntu 18.04. I have tried without loading my init.vim and the issue still happens. 

I also got firenvim's error output and got this:
```
Error detected while processing function OnStdin[29]..WriteStdout:
line    5:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: attempt to index global 'bit' (a nil value)
```

**Comment by benwoodward** [comment]
I followed the linked-instructions, and changed my `firenvim` script to the following: 

```bash

#!/bin/sh
cd /Users/ben/.local/share/firenvim

# exec '/usr/local/Cellar/neovim/0.4.2/bin/nvim' --headless -c 'call firenvim#run()'
# exec env IN_FIRENVIM=1 '/usr/local/bin/nvim' --headless -c 'call firenvim#run()'
exec '/usr/local/bin/nvim' -u NORC --cmd 'set rtp+=/tmp/firenvim' --headless -c 'call firenvim#run()'
```

I then restarted Chrome, and it's now working for me.

![image](https://user-images.githubusercontent.com/1472981/66246546-2d05bd80-e758-11e9-98dc-6d2d47cabd97.png)

**Comment by glacambre** [comment]
@benwoodward Cool! This means that you're probably experiencing an issue with your `$PATH`. Could you update the neovim plugin and run `call firenvim#install()` again? I recently pushed a small change that should help users get a default `$PATH`.

If this doesn't help, could you perform a dichotomic search on your config by commenting parts of it? Knowing what plugin/setting is causing this issue would help a lot.
