### ISSUE TITLE
Work nvim (qt) on windows 10 or nvim in wls2? 

### ISSUE THREAD

**Issue by meicale** [glacambre/firenvim#1332]
- OS Version: Windows 10
- Browser Version: chrome
- Browser Addon Version: newest
- Neovim Plugin Version: newest

### What I tried to do
Use this plugin in my windows 10 laptop which has neovim  6.0 and chrome  installed. 

### What happened
It just has no response when I click the textaera or using "ctrl+e" key.

**Comment by glacambre** [comment]
Please go through the [troubleshooting guide](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md) and let me know what the result is.
