### ISSUE TITLE
Turn off auto-activation

### ISSUE THREAD

**Issue by JinraeKim** [glacambre/firenvim#1337]
Thank you for this great plugin.

In my case, I use Notion.
Since `firenvim` is activated when opening every Notion page,
it is a bit annoying.

As one can activate `firenvim` via `<C-e>`,
can I turn off auto-activation for this?

Here is the screenshot:
![image](https://user-images.githubusercontent.com/43136096/160053201-c8cb2902-dbfb-47fe-8303-134e75238845.png)

**Comment by alerque** [comment]
There is documentation for how to add site specific default settings (such as auto activation or not) to the `g:firenvim_config` array under `localSettings` with URL matchers.

**Comment by JinraeKim** [comment]
> There is documentation for how to add site specific default settings (such as auto activation or not) to the `g:firenvim_config` array under `localSettings` with URL matchers.

Very nice.
But I tried this, and it caused an error:

- In my `vim.init`
```
" firenvim
let fc = g:firenvim_config['localSettings']
let fc['.*'] = { 'takeover': 'never' }
```

- After sourcing it via `:so %`, the error message is
```
line  165:
E121: Undefined variable: g:firenvim_config
E15: Invalid expression: g:firenvim_config['localSettings']
line  166:
E121: Undefined variable: fc

```

**Comment by glacambre** [comment]
Please read [this section](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object) of the readme :)

**Comment by JinraeKim** [comment]
> Please read [this section](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object) of the readme :)

Ok, I'll read it again carefully. Thanks :)
