### ISSUE TITLE
Maybe an easier way to use firenvim for portable browser users

### ISSUE THREAD

**Issue by dingZvel** [glacambre/firenvim#1347]
After installing firenvim plugin in my neovim, I ran the `:call firenvim#install()` command and found it could only detect my Edge and Brave, but not Google Chrome, in which I expected to use firenvim.
Then I realized I was using a portable chrome and checked [this code](https://github.com/glacambre/firenvim/blob/f8cd5a516d7527d0bc97dd6030e09b838055489d/autoload/firenvim.vim#L168-L304) and [TROUBLESHOOTING.md](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md), finding that firenvim checks if the `APPDATA\Local\Google\Chrome` exists to decide whether you have Chrome installed or not (on Windows).
Thus I came up with an easy way to make it work and that is to make a symlink of that path pointing to your portable chrome.
In my case, the command is (make sure you are in ***cmd***, **not Powershell**):
``` cmd
MKLINK /J "C:\Users\dingZvel\AppData\Local\Google\Chrome" "D:\Program Files (x86)\TOOLS\Chrome_99.0.4844.74_64bit_Portable\Chrome"
```
For Linux users, you may use `ln -s ...` to do the same thing. However, I haven't try it for myself yet, so it cannot be guaranteed to work successfully.
I don't know whether there are flows in this method or not, but it just works for me;) So If there are reasons for not to doing so, please let me know. Or if it's almost perfect, I think it would be great to be added to [TROUBLESHOOTING.md](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md) as a simpler method.

**Comment by glacambre** [comment]
Hi, thanks a lot for going through the troubleshooting guide and sharing the solution you found. I've added a mention of symbolic links in TROUBLESHOOTING.md, so I've closed this issue. Thanks again! :)
