### ISSUE TITLE
Connection Problem across all website

### ISSUE THREAD

**Issue by Maverun** [glacambre/firenvim#1360]
- OS Version: Arch Linux X86_64 (5.17.6-arch1-1)
- Browser Version: 100.0
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: up to date ( so... 458ccfe ?)

### What I tried to do
Enter the input

### What happened
 Black screen...
after a few second, it times out

according to debugger
![image](https://user-images.githubusercontent.com/17103748/168412197-4b02f35e-e208-40b7-89c5-892996963fdf.png)
not just one website, but all I went,
even with https://txti.es/

**Comment by glacambre** [comment]
Thanks for opening this issue. Could you open ~/.local/share/firenvim/firenvim, and append `2>>/tmp/stderr | tee -a /tmp/stdout` at the end of the `exec` line? Then, try to use firenvim a couple of times. This will create two files names `stderr` and `stdout` in /tmp whose content I'd like to see :)

**Comment by Maverun** [comment]
I hate to say this...
I did as your instruction
but it somehow didn't generate those two files, 
I even did restart firefox to double-check and still, it didn't generate files.
this is what I sorta did according to `history`
```bash

 6270  cd .local/share/firenvim/
 6271  ls
 6272  e firenvim
 6273* cd /tmp
 6274* ls
 6275* cat stdout
 6276* cat stderr
 6277  e
 6278* cat stdout
 6279  cat stderr
 6280  e firenvim
 6281* cat stdout
 6282  e firenvim
 ```
 
 What could this mean? Look like it didn't touch that firenvim files in the first place? is it really a connection issue?

**Comment by glacambre** [comment]
The firefox console says that it can't connect to `ws://127.0.0.1:42037/...`. This URL correctly contains the port number, which is generated from neovim, so we know neovim was able to start. But adding `>/tmp/stderr | tee -a /tmp/stdout` to the script should create the files unconditionally. So that must mean that the script that firefox is running isn't the script we edited?

Could you give me the content of `~/.mozilla/native-messaging-hosts/firenvim.json`? This file should contain a json object containing a `"path"` attribute. Could you also give me the content of the file pointed to by `"path"`?

**Comment by Maverun** [comment]
interesting enough, path is indeed same as your first message
`{ "name": "firenvim", "description": "Turn your browser into a Neovim GUI.", "path": "/home/maverun/.local/share/firenvim/firenvim", "type": "stdio", "allowed_extensions": ["firenvim@lacamb.re"]}
`

**Comment by glacambre** [comment]
Could you show me the content of /home/maverun/.local/share/firenvim/firenvim then? :)

**Comment by Maverun** [comment]
ask and you shall get it

```sh
#!/bin/sh
mkdir -p /run/user/1000/firenvim
chmod 700 /run/user/1000/firenvim
cd /run/user/1000/firenvim
export PATH="$PATH:/home/maverun/.local/bin:/home/maverun/.local/bin:/home/maverun/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin"
unset NVIM_LISTEN_ADDRESS
if [ -n "$VIM" ] && [ ! -d "$VIM" ]; then
  unset VIM
fi
if [ -n "$VIMRUNTIME" ] && [ ! -d "$VIMRUNTIME" ]; then
  unset VIMRUNTIME
fi
if [ ! -n "$XDG_DATA_DIRS" ]; then
  XDG_DATA_DIRS='/home/maverun/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop'
  export XDG_DATA_DIRS
fi
if [ ! -n "$XDG_RUNTIME_DIR" ]; then
  XDG_RUNTIME_DIR='/run/user/1000'
  export XDG_RUNTIME_DIR
fi

exec '/usr/bin/nvim' --headless --cmd "let g:firenvim_i=[]|let g:firenvim_o=[]|let g:Firenvim_oi={i,d,e->add(g:firenvim_i,d)}|let g:Firenvim_oo={t->add(g:firenvim_o,t)}|let g:firenvim_c=stdioopen({'on_stdin':{i,d,e->g:Firenvim_oi(i,d,e)},'on_print':{t->g:Firenvim_oo(t)}})" --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()'
2>>/tmp/stderr | tee -a /tmp/stdout
```

**Comment by glacambre** [comment]
Oh, the problem is that `2>>/tmp/stderr | tee -a /tmp/stdout` should be on the "exec" line. Put it there, try to use firenvim a couple of times and we should get our stdout and stderr files :)

**Comment by Maverun** [comment]
Appear so, i could not read instruction... (in my defences I did it at 5am in the morning hahah...)
`cat stderr` return nothing but
on other hand `cat stdout` return this one line (I run firenvim 3 time)
`4{"messages": [], "version": "0.2.12", "port": 41461}4{"messages": [], "version": "0.2.12", "port": 35395}4{"messages": [], "version": "0.2.12", "port": 44159}%`

**Comment by glacambre** [comment]
So no error messages anywhere in sight, huh... Does running `:lua bit.band(1,1)` in a normal neovim instance work?

**Comment by Maverun** [comment]
Not sure what it is supposed to do,
nothing happen? was there supposed to be output to cmdline or what?

**Comment by glacambre** [comment]
It would have printed an error if it didn't work, so we can safely assume it works :) 

Please apply this patch to your local installation of the plugin and try to use firenvim a couple of times:
```diff
diff --git a/lua/firenvim-websocket.lua b/lua/firenvim-websocket.lua
index 4c441ec..9308610 100644
--- a/lua/firenvim-websocket.lua
+++ b/lua/firenvim-websocket.lua
@@ -1,3 +1,6 @@
+local file = io.open("/tmp/log", "a")
+file:write("loaded")
+
 if bit == nil then
         bit = require("bit")
 end
@@ -14,6 +17,7 @@ local opcodes = {
 
 -- The client's handshake is described here: https://tools.ietf.org/html/rfc6455#section-4.2.1
 local function parse_headers()
+        file:write(vim.inspect("parse_headers-start"))
         local headerend = nil
         local headerstring = ""
         -- Accumulate header lines until we have them all
@@ -34,15 +38,23 @@ local function parse_headers()
         for key, value in string.gmatch(keyvalues, "([^:]+) *: *([^\r\n]+)\r?\n") do
                 headerobj[key] = value
         end
+        file:write(vim.inspect("parse_headers-end"))
+        file:write(vim.inspect(request))
+        file:write(vim.inspect(headerobj))
+        file:write(vim.inspect(rest))
         return request, headerobj, rest
 end
 
 local function compute_key(key)
+        file:write(vim.inspect("compute_key"))
+        file:write(vim.inspect(key))
         return utils.base64(utils.sha1(key .. "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"))
 end
 
 -- The server's opening handshake is described here: https://tools.ietf.org/html/rfc6455#section-4.2.2
 local function accept_connection(headers)
+        file:write(vim.inspect("accept-connection"))
+        file:write(vim.inspect(headers))
         return "HTTP/1.1 101 Switching Protocols\n" ..
         "Connection: Upgrade\r\n" ..
         "Sec-WebSocket-Accept: " .. compute_key(headers["Sec-WebSocket-Key"]) .. "\r\n" ..
@@ -52,6 +64,7 @@ end
 
 -- Frames are described here: https://tools.ietf.org/html/rfc6455#section-5.2
 local function decode_frame()
+        file:write(vim.inspect("decode_frame-start"))
         local frame = ""
         local result = {}
         while true do
@@ -91,7 +104,7 @@ local function decode_frame()
                                 frame = frame .. coroutine.yield(nil)
                         end
                         result.payload_length = utils.to_64_bits_number(string.sub(frame, current_byte))
-                        print("Warning: payload length on 64 bits. Estimated:" .. result.payload_length)
+                        file:write(vim.inspect("Warning: payload length on 64 bits. Estimated:" .. result.payload_length))
                         current_byte = current_byte + 8
                 end
 
@@ -115,12 +128,15 @@ local function decode_frame()
                 current_byte = payload_end + 1
                 frame = string.sub(frame, current_byte) .. coroutine.yield(result)
         end
+        file:write(vim.inspect("decode_frame-end"))
 end
 
 -- The format is the same as the client's (
 -- https://tools.ietf.org/html/rfc6455#section-5.2 ), except we don't need to
 -- mask the data.
 local function encode_frame(data)
+        file:write(vim.inspect("encode_frame-start"))
+        file:write(vim.inspect(data))
         -- 130: 10000010
         -- Fin: 1
         -- RSV{1,2,3}: 0
@@ -134,6 +150,10 @@ local function encode_frame(data)
         else
                 len = string.char(127) .. utils.to_64_bits_str(string.len(data))
         end
+        file:write(vim.inspect("encode_frame-end"))
+        file:write(vim.inspect(header))
+        file:write(vim.inspect(len))
+        file:write(vim.inspect(data))
         return  header .. len .. data
 end
 
@@ -142,10 +162,12 @@ local function pong_frame(decoded_frame)
         -- Fin: 1
         -- RSV{1,2,3}: 0
         -- Opcode: 0xA (pong)
+        file:write(vim.inspect("pong_frame"))
         return string.char(138) .. decoded_frame.payload_length .. decoded_frame.payload_data
 end
 
 local function close_frame()
+        file:write(vim.inspect("close_frame"))
         local frame = encode_frame("")
         return string.char(136) .. string.sub(frame, 2)
 end
```

You don't need to do any recompilation steps. This will create a file named `/tmp/log` whose content I'd like to see :)

**Comment by Maverun** [comment]
i...I dont understand what is going on...
`cat /tmp/log` return only
`loadedloadedloaded%`

just in case I make a mistake or so.. ( I am not sure how would you patch it, I assume manually editing it?)
https://gist.github.com/Maverun/a2311e6b2ba6e5ea22f4daae596bfb21
(I also include entirely file just in case at bottom)

Did I do something wrong or it is...actual issue?

**Comment by glacambre** [comment]
It looks like you correctly patched the plugin :).
So this means that the lua part of the plugin does get loaded, but that the browser never connects to neovim over TCP, so we can rule out problems that could occur during the websocket handshake.
At this point, I'm thinking that this might be a browser issue. Could you open Firefox's network monitor (Ctrl+Shift+E) and try to launch firenvim? This should log a failed websocket request. Right click on it, select "Save All As HAR" and upload it here please :)

**Comment by Maverun** [comment]
I create 2 har in two different website just in case they give different result
https://gist.github.com/Maverun/135a12516061582c7783d40c7f9d2608

**Comment by glacambre** [comment]
Thanks, this is useful. I think this might be caused by your other browser add-ons, if you have any. Could you try to use firenvim in a new firefox profile? You can do this by running `firefox -P` in your shell.

**Comment by Maverun** [comment]
Interestingly enough, I try it on new profile firefox, with no addon but firenvim and the issue is still there
I assume it is either a firefox thingy you link article the other day or a local issue that prevents it?

**Comment by glacambre** [comment]
Are you using a flatpak or snap version of Firefox by any chance?

**Comment by Maverun** [comment]
Not sure what differences, I just use Pacman, does that answer to it?

**Comment by glacambre** [comment]
>Not sure what differences,

Snap and Flatpak sandbox firefox, and this prevents Firenvim from working.

>I just use Pacman, does that answer to it?

I'm not sure, I know that the firefox you get from `apt get install firefox` on ubuntu is a snap and not a regular package, so I'm not 100% certain that what you're running is a native package.

**Comment by Maverun** [comment]
I just remember I have chrome, through pain open it up, and install firenvim only,...
The issue is also the same there, so I believe this is not a browser problem but a local issue?

**Comment by Maverun** [comment]
Wait, it doesn't connect out, just black screen? it been almost min and it still black (usually 10 second and it would DC)
so for chrome, it would be a black screen...

so that means it is only firefox that is issued with websocket?

**Comment by glacambre** [comment]
Did you re-run `firenvim#install()` after installing chrome? If not you're experiencing different issues.

**Comment by Maverun** [comment]
Yes, I `nvim --headless "+call firenvim#install(0) | q"` and result is just black screen, so it is only firefox that is dealing with connection timeout...

to summary:
- nothing show up in the log from that patch other than "loaded"
- it stderr blank but something in stdout
- `firefox -p` and only install firenvim, issue is still there
- did HAR network DC requests

as for chrome, it's just a black screen and that is prob on GPU side I assume (just a different issue as you state it)

**Comment by glacambre** [comment]
This is caused by https://github.com/glacambre/firenvim/issues/1357 . Unfortunately there is no fix for now - you'll have to downgrade neovim to a ~2 weeks old version if you want Firenvim to start working again.

**Comment by Maverun** [comment]
So that how it is,
I assume it will patch in the future?

Thanks for dealing issues with me
Sorta fun debugging haha...

**Comment by glacambre** [comment]
Hey Mave, I figured out a fix! Just update the neovim plugin, and Firenvim should start working again. Thanks a lot for your help :)

**Comment by Maverun** [comment]
You are amazing!
It work as it should (well I got error but that just my config about autocmd hahaha, that a good sign!)
Good work mate.
