### ISSUE TITLE
Firenvim not working Firefox/OSX

### ISSUE THREAD

**Issue by drewnutt** [glacambre/firenvim#1374]
- OS Version: mac x86-64
- Browser Version:  Firefox 101.0
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### What I tried to do
I am unable to use firenvim in Firefox on OSX. Whenever I click a text box it turns into a black box that does not let me alter anything. 

I went through the troubleshooting guide and everything seemed normal up till [Make sure the browser extension can communicate with neovim](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-browser-extension-can-communicate-with-neovim)

I was previously able to use firenvim just fine, but then I updated/added other plugins to my vimrc and it broke.

### What happened
When I click a text box this is what appears in the console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 
```

**Comment by JavierParra** [comment]
Getting the same error in Brave:

Brave Version: 1.39.122 Chromium: 102.0.5005.115 (Official Build) (x86_64)
Firenvim extension: 0.2.12
Firenvim Plugin: #v0.2.12

**Comment by glacambre** [comment]
@JavierParra please open a new issue.

@drewnutt Can you try removing `~/.local/share/firenvim` and then running `:call firenvim#install()` again?

**Comment by drewnutt** [comment]
I removed that directory and ran that command in neovim command mode, but nothing has changed with the functionality of firenvim.

**Comment by glacambre** [comment]
Okay, I was hoping this was https://github.com/glacambre/firenvim/issues/1360 but it isn't :/.

Can you try the [last step of the troubleshooting guide](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#print-debugging-your-initvim)?

**Comment by silmeth** [comment]
I seem to have the same (or at least similar) problem, trying to open `firenvim` window prints this in the Firefox js console:

<details>
<summary>browser console log</summary>

```
14:01:46.755 Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „inline” („script-src”). moz-extension
14:01:46.776 Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „inline” („script-src”). moz-extension
14:01:46.776 Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „inline” („script-src”). moz-extension
14:01:47.116 Uncaught TypeError: decoded is not iterable
    onMessage Stdout.ts:46
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
2 Stdout.ts:46:48
14:01:47.121 Uncaught (in promise) TypeError: damages is undefined
    pushDamage renderer.ts:242
    grid_line renderer.ts:469
    onRedraw renderer.ts:1062
    neovim Neovim.ts:63
    emit EventEmitter.ts:20
    emit EventEmitter.ts:18
    onMessage Stdout.ts:50
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
renderer.ts:242:8
14:01:47.543 Unhandled message kind undefined 9 Stdout.ts:54:24
14:01:47.546 Uncaught TypeError: decoded is not iterable
    onMessage Stdout.ts:46
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
Stdout.ts:46:48
14:01:47.547 Uncaught (in promise) TypeError: damages is undefined
    pushDamage renderer.ts:242
    grid_line renderer.ts:469
    onRedraw renderer.ts:1062
    neovim Neovim.ts:63
    emit EventEmitter.ts:20
    emit EventEmitter.ts:18
    onMessage Stdout.ts:50
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
2 renderer.ts:242:8
14:05:08.657 Uncaught TypeError: decoded is not iterable
    onMessage Stdout.ts:46
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
Stdout.ts:46:48
14:05:08.662 Uncaught (in promise) TypeError: damages is undefined
    pushDamage renderer.ts:242
    grid_line renderer.ts:469
    onRedraw renderer.ts:1062
    neovim Neovim.ts:63
    emit EventEmitter.ts:20
    emit EventEmitter.ts:18
    onMessage Stdout.ts:50
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
renderer.ts:242:8
```
</details>

did the last troubleshooting step and that’s what I get:

`/tmp/stdout`:
```
�{"messages": [], "version": "0.2.12", "settings": {"localSettings": {".*": {"priority": 0, "cmdline": "firenvim", "takeover": "never"}}, "globalSettings": {"alt": "all"}}, "port": 38013}
```

and `/tmp/stderr` is empty

The vim command line works in the firenvim window, I can do `:q` to close it, but I see just a black box instead of the buffer contents, and cannot edit anything.

**Comment by tsturzl** [comment]
I'm experiencing the same issue on Ubuntu 20.04 with Firefox.

**Comment by glacambre** [comment]
@tsturzl Please open a new issue.

**Comment by glacambre** [comment]
Closing this issue as it was the same as #1382, which is now fixed.
