### ISSUE TITLE
Each input will carry the part that has been input before when using Chinese input

### ISSUE THREAD

**Issue by LioTree** [glacambre/firenvim#1375]
- OS Version: windows11
- Browser Version: chrome 102.0.5005.115
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### What I tried to do
Enter Chinese using the Microsoft Chinese Input.

### What happened
Each input will carry the part that has been input before.

Here is an example,When I type "你好" for the first time, everything works fine.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/12847578/175341161-22c2d621-5726-445f-a637-3481433095d1.png">

But when I then enter a "H", there will be another "你好" appear.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/12847578/175342360-bf0db42b-b1e7-4470-9c27-bbddb1dd329e.png">

**Comment by LioTree** [comment]
Indeed,on Firefox there is no such problem.Thanks for the response.

**Comment by LioTree** [comment]
Hi,it seems like the old problem disappears,but new problem appears.The Chinese input I typed doesn't appear until I type some English.
















At 2022-10-10 22:24:24, "Ghjuvan Lacambre" ***@***.***> wrote:

Could you try this version and let me know if it fixes your problem? In order to try it:

Remove firenvim from Chrome in chrome://extensions
Unzip the archive
Enable developer mode (top right toggle in chrome://extensions)
Click on the load unpacked button
Select the directory where you unzipped the archive

**Comment by glacambre** [comment]
@LioTree I think I figured out a fix. Could you try [this version](https://github.com/glacambre/firenvim/files/9930562/chrome.zip) and let me know if it works?
