### ISSUE TITLE
Trouble using firenvim in chrome on ubuntu 18.04

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#138]
This same thing happens to me in chrome on ubuntu 18.04. I have tried without loading my init.vim and the issue still happens. 

I also got firenvim's error output and got this:
```
Error detected while processing function OnStdin[29]..WriteStdout:
line    5:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: attempt to index global 'bit' (a nil value)
```

_Originally posted by @alexriedl in https://github.com/glacambre/firenvim/issues/133#issuecomment-538559551_

**Comment by glacambre** [comment]
@alexriedl Could you post the content of your firenvim script (the one in `~/.local/share/firenvim/firenvim`) and what neovim version you're using?

**Comment by alexriedl** [comment]
```
#!/bin/sh
cd /home/alex/.local/share/firenvim
export PATH="$PATH:/home/alex/.nvm/versions/node/v10.16.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/alex/.dotnet/tools:/home/alex/.dotnet/tools"

exec '/usr/bin/nvim' --headless -c 'call firenvim#run()'
```

```
$ nvim --version
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
```

I installed neovim via apt by suggestion of the docs [here](https://github.com/neovim/neovim/wiki/Installing-Neovim#install-from-package). I noticed the stable version in the ubuntu repo is 3.8 and the unstable is 5.0 so I cannot get exactly 4.0 easily - not sure if that is contributing to the issue.

**Comment by alexriedl** [comment]
I noticed my issue is very similar to #140, so I tried out the suggestion posted there.
Running `:lua print(bit.band(1,1))` throws and error.

**Comment by glacambre** [comment]
Does `sudo apt install luarocks && luarocks install luabitop` fix anything?

@jamessan I saw you listed on the ubuntu ppa page for neovim, do you have any insights about this issue? Is there something wrong with the ppa?

**Comment by justinmk** [comment]
@alexriedl @kuator  can you try the appimage instead: https://github.com/neovim/neovim/releases

**Comment by alexriedl** [comment]
The appimage works for me!

**Comment by glacambre** [comment]
@fwalch @jszakmeister You're also listed on ubuntu's neovim ppa page, do you know anything about this?

**Comment by jamessan** [comment]
The stable PPA will be updated once I get the Debian version updated.  There are multiple dependencies that need to be updated, so it's taking some time to get done.

**Comment by glacambre** [comment]
So `:lua print(bit.band(1,1))` working on an nvim 0.3.8 appimage but not on ubuntu's 0.3.8 is normal and will be fixed with the next update?

**Comment by jamessan** [comment]
Ubuntu's 0.3.8 will work just fine if you have lua-bitop installed or are using a version built against luajit.  I thought the issue was that, according to this repo's README.md, it requires nvim 0.4 or later.

**Comment by glacambre** [comment]
Yes, it's one issue, but alexriedl also tried nvim 0.5.0 from ubuntu's PPAs and it didn't work ( see https://github.com/glacambre/firenvim/issues/138#issuecomment-538808968 ). Would it be possible to make lua-bitop (and any other module/library available when using luajit) a dependency of neovim, so that plugin developpers can be sure they will always be available everywhere?

Also, do you want help with packaging neovim for debian/ubuntu? I know it's probably not very fun but that's something I've always been curious about, so I'd be happy to help :).

**Comment by alerque** [comment]
Given that Neovim releases on most platforms are compiled with LuaJIT I think it's a reasonable expectation that if a platform decides to compile against something else they make sure the dependencies for it are up to par with that, yes. This means plain Lua 5.1 needs a couple libraries to go with it, yes.

**Comment by jamessan** [comment]
1. What architecture is the system this is being tested on?

2. I don't think there's a clear statement from the Neovim side about what the expected Lua API is.  I know we target 5.1 because that's the baseline compatibility between Lua and LuaJIT, but is that _also_ supposed to include any additional modules LuaJIT provides or is LuaJIT just an implementation detail to get better performance?  If it's the former, that it implies Neovim packagers should depend on lua-bitop (anything else?) when _not_ building against LuaJIT.  If it's the latter, projects should call those modules out as dependencies if they're using them.

As someone not very familiar with the Lua ecosystem, it still seems like a good idea to specify whether or not your project is depending on modules that aren't available in pure Lua, independent of whether Neovim packagers declare those dependencies for Neovim itself.

**Comment by glacambre** [comment]
>What architecture is the system this is being tested on?

This is reproducible on x86_64.

>I don't think there's a clear statement from the Neovim side about what the expected Lua API is

I've opened #11301 to talk about this.

>it still seems like a good idea to specify whether or not your project is depending on modules that aren't available in pure Lua

You're right, I'll do that :)

**Comment by jamessan** [comment]
>> What architecture is the system this is being tested on?
>
> This is reproducible on x86_64.

Ok, so that one is built against LuaJIT.

I just downloaded the deb from https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable/+build/17356438, extracted it with `dpkg-deb -x neovim*deb ubuntu`, and then ran `./ubuntu/bin/nvim`.  This ran your example lua command just fine.

**Comment by glacambre** [comment]
> This ran your example lua command just fine.

Could this be because you have the lua bitop package installed somewhere on your computer?

```
>uname -a
Linux x250 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

>/usr/bin/nvim --version
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-CVUtpn/neovim-0.5.0+ubuntu1+git201910232033-53b0258-00e710e=.
-fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g
 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimpl
icit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_
MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-CVUtpn/neovim-0.5.0+ubuntu1+git201910232033-53b0258-00e710e/build
/config -I/build/neovim-CVUtpn/neovim-0.5.0+ubuntu1+git201910232033-53b0258-00e710e/src -I/build/neovim-CVUtpn/neovim-0.5.0+ubu
ntu1+git201910232033-53b0258-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-CVUtpn/neovim-0.5.0+ubuntu1+git2019102320
33-53b0258-00e710e/build/src/nvim/auto -I/build/neovim-CVUtpn/neovim-0.5.0+ubuntu1+git201910232033-53b0258-00e710e/build/includ
e
Compiled by buildd@lcy01-amd64-029

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

>/usr/bin/nvim --headless -c 'lua bit.band(1,1)' -c q
Error detected while processing command line:
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: attempt to index global 'bit' (a nil value)%
```

**Comment by jamessan** [comment]
The one you're testing is built against Lua, not LuaJIT.

```
>/usr/bin/nvim --version
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
```

vs.

```
./ubuntu/usr/bin/nvim  --version
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by glacambre** [comment]
Yep, you're right, I just downloaded neovim 0.3.8 and `lua bit.band(1,1)` indeed works - sorry for my bogus claim.

**Comment by jamessan** [comment]
I guess that just proves the point. :) I'm already changing Debian's packaging to Depend on lua-bitop when not building against LuaJIT.
