### ISSUE TITLE
Firenvim not working with neovim nightly

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#1382]
I seem to have the same (or at least similar) problem, trying to open `firenvim` window prints this in the Firefox js console:

<details>
<summary>browser console log</summary>

```
14:01:46.755 Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „inline” („script-src”). moz-extension
14:01:46.776 Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „inline” („script-src”). moz-extension
14:01:46.776 Content Security Policy: Ustawienia strony zablokowały wczytanie zasobu „inline” („script-src”). moz-extension
14:01:47.116 Uncaught TypeError: decoded is not iterable
    onMessage Stdout.ts:46
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
2 Stdout.ts:46:48
14:01:47.121 Uncaught (in promise) TypeError: damages is undefined
    pushDamage renderer.ts:242
    grid_line renderer.ts:469
    onRedraw renderer.ts:1062
    neovim Neovim.ts:63
    emit EventEmitter.ts:20
    emit EventEmitter.ts:18
    onMessage Stdout.ts:50
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
renderer.ts:242:8
14:01:47.543 Unhandled message kind undefined 9 Stdout.ts:54:24
14:01:47.546 Uncaught TypeError: decoded is not iterable
    onMessage Stdout.ts:46
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
Stdout.ts:46:48
14:01:47.547 Uncaught (in promise) TypeError: damages is undefined
    pushDamage renderer.ts:242
    grid_line renderer.ts:469
    onRedraw renderer.ts:1062
    neovim Neovim.ts:63
    emit EventEmitter.ts:20
    emit EventEmitter.ts:18
    onMessage Stdout.ts:50
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
2 renderer.ts:242:8
14:05:08.657 Uncaught TypeError: decoded is not iterable
    onMessage Stdout.ts:46
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
Stdout.ts:46:48
14:05:08.662 Uncaught (in promise) TypeError: damages is undefined
    pushDamage renderer.ts:242
    grid_line renderer.ts:469
    onRedraw renderer.ts:1062
    neovim Neovim.ts:63
    emit EventEmitter.ts:20
    emit EventEmitter.ts:18
    onMessage Stdout.ts:50
    Stdout Stdout.ts:17
    neovim Neovim.ts:32
    setupInput input.ts:17
    isReady frame.ts:70
renderer.ts:242:8
```
</details>

did the last troubleshooting step and that’s what I get:

`/tmp/stdout`:
```
�{"messages": [], "version": "0.2.12", "settings": {"localSettings": {".*": {"priority": 0, "cmdline": "firenvim", "takeover": "never"}}, "globalSettings": {"alt": "all"}}, "port": 38013}
```

and `/tmp/stderr` is empty

The vim command line works in the firenvim window, I can do `:q` to close it, but I see just a black box instead of the buffer contents, and cannot edit anything.

_Originally posted by @silmeth in https://github.com/glacambre/firenvim/issues/1374#issuecomment-1174991038_

**Comment by glacambre** [comment]
@silmeth Thanks a lot for this information, this is very useful. Could you tell me what OS, browser and neovim version you are using?

**Comment by silmeth** [comment]
* Kubuntu 21.10
* Firefox 101.0.1 from system repos
* neovim nightly, from package version `0.7.0~ubuntu1+git202207032117-acb7a9028-dd05b3569-e19377839~ubuntu21.10.1` from `ppa:neovim-ppa/unstable` repo, `nvim --version` prints
  ```
  NVIM v0.8.0-dev
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  ```
* Firenvim add-on 0.2.12, plugin from current master branch (commit `e90f87872b313df15a06119ddbb84cdf1599657c`).

**Comment by glacambre** [comment]
Great, thanks. Could you open the network tab of the browser console, start firenvim, select the newly-created websocket connection, go to the "response" tab and then take screenshots of all the logs (it looks like firefox is unable to save websocket logs using its regular mechanisms...)?

**Comment by glacambre** [comment]
Actually don't bother with this - I can reproduce by upgrading neovim to its latest release. Investigating.

**Comment by justinmk** [comment]
> but I see just a black box instead of the buffer contents, and cannot edit anything.

If it's just a display issue, I was wondering if these commits are related (which were also cherry-picked to 0.7.2):

https://github.com/neovim/neovim/commit/98e2da7d50b8f22edb20cdb744788ef0085d0cb6
https://github.com/neovim/neovim/commit/1ad6423f02bad6d7941ca38f2d5f7b757811e022

**Comment by glacambre** [comment]
It's https://github.com/neovim/neovim/commit/5d6987210578f5f1c3151988b99a9411f9603374 , which bfredl warned might be disruptive. Firenvim already does the right thing around flushes, I think the issue is more subtle than the gotcha described in the commit message. My guess is this involves changes around how the messagepack messages are written to the websocket, with Firenvim failing on the parse of an incomplete message.

So the workaround for now is to use any release before june 19. I'll keep digging when I have time.

**Comment by glacambre** [comment]
@Gelio submitted a fix (thanks a lot!), I'll try to publish a new release on the chrome and firefox add-on stores soon.

**Comment by silmeth** [comment]
Can confirm that the new Firefox version works again with nightly nvim.

**Comment by glacambre** [comment]
Firenvim v0.2.13 is now available on both the Firefox and the Chrome add-on stores.
