### ISSUE TITLE
Installation is failed in Firefox on Windows.

### ISSUE THREAD

**Issue by koijigen** [glacambre/firenvim#1383]
- OS Version: Windows10
- Browser Version: FIrefox 103.0b5
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.2.12

### What I tried to do

I installed firenvim by following steps at [README.md](https://github.com/glacambre/firenvim#installing) with vim-plug.
And that did not worked.
The browser console printed bellow message, when I push `Reload settings` on the extension's popup menu.
```
 ExtensionError: Native application tried to send a message of 2191494690 bytes, which exceeds the limit of 1048576 bytes.
```

And I went through the troubleshooting guide at [make-sure-the-firenvim-script-has-been-created](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-firenvim-script-has-been-created).

### What happened

When I running `echo 'abcde{}' | %APPDATA%\firenvim\firenvim` on cmd.exe after executing `:call firenvim#install(0)` on neovim, this did not print json object.
The printed is following: `The system cannot find the path specified.`

Is there any good idea to install firenvim in correct?
I want to use this awesome extension:yum:
thanks.

**Comment by koijigen** [comment]
P.S.

When I running `echo 'abcde{}' | %LOCALAPPDATA%/firenvim/firenvim` on cmd.exe.
I obtained a bellow message: 

```
�{"messages": [], "version": "0.2.12", "settings": {"localSettings": {".*": {"priority": 0, "selector": "textarea, div[role=\"textbox\"]"}}}}
```

hope this helpful :pray:

**Comment by glacambre** [comment]
>hope this helpful pray

It is :). Can you tell me what's the value of your `HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\firenvim` registry key?

**Comment by koijigen** [comment]
Yes, here is the value of key :eyes:
```
C:\Users\oto\AppData\Local\firenvim\firenvim-firefox.json
```

**Comment by koijigen** [comment]
Worked fine at all! :seedling:

Maybe, the trouble is because of my windows registry value of `Autorun` at `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor` :thinking:
There was my startup command for cmd.exe, and I tried removing them.
Furthermore, I restart firenvim on browser, it worked.

Thank you for your help @glacambre :blush:
As I expected, firenvim is great.

**Comment by koijigen** [comment]
> Maybe, the trouble is because of my windows registry value of Autorun at HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor 🤔

Because, when I tried to set a value to the key again, the firenvim stop working again 🔬 
For example, when the setting a value `echo "hello, firenvim."` and select "reload settings" from the popup menu of extension, a error message in browser console is bellow :
```
ExtensionError: Native application tried to send a message of 1818585122 bytes, which exceeds the limit of 1048576 bytes.
```

**Comment by koijigen** [comment]
Call me whenever you want more information about this.
I will cooperate if there is something I can cooperate with 🤝

**Comment by glacambre** [comment]
Good job for figuring out what the problem was! The message "Native application tried to send a message of 1818585122 bytes, which exceeds the limit of 1048576 bytes." usually means that unexpected text was printed when attempting to run firenvim.bat.

According to https://devblogs.microsoft.com/oldnewthing/20071121-00/?p=24433 , having "autorun" be set to something causes arbitrary commands to be executed before the script starts. If these arbitrary commands print things, this will indeed prevent the browser from starting Firenvim.

**Comment by koijigen** [comment]
I tried using other native messaging extensions to isolate the problem.
https://github.com/mdn/webextensions-examples/tree/master/native-messaging

After installing extension and checking its behavior is correct,  set a value to key "Autorun".
And run the extension feature, ...It did not work!

Thus, I assume this issue is not unique to firenvim.
It is related to Firefox extension specification.

That means It is difficult to use "Autorun" key in the future. It can't be helped 🥲

**Comment by koijigen** [comment]
> According to https://devblogs.microsoft.com/oldnewthing/20071121-00/?p=24433 , having "autorun" be set to something causes arbitrary commands to be executed before the script starts.

That's right, it is the thing I did 😉 

> If these arbitrary commands print things, this will indeed prevent the browser from starting Firenvim.

I see :+1:
