### ISSUE TITLE
README: convert vimscript to lua

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#1391]
As requested in https://github.com/glacambre/firenvim/issues/991#issuecomment-1192125656 .

**Comment by alerque** [comment]
https://github.com/nanotee/nvim-lua-guide has quite a few useful examples of how various options and configurations can be ported to Lua. Might be a good reference for somebody looking to help get the README rewritten.

**Comment by richchurcher** [comment]
It can be done fairly easily using the `vim.g.firenvim_config` syntax. I've added a PR with an example.
