### ISSUE TITLE
[Feat]: option in browser extension to exclude site(s) by domain root

### ISSUE THREAD

**Issue by huyz** [glacambre/firenvim#1392]
It would be nice if we could configure the browser extension to not auto-launch on certain domains or subdomains.

I'm particularly thinking about Slack where I'd like to start typing and increasing the textarea height by typing either text or shift+ENTER several times before hitting cmd+E to trigger firenvim. That way things won't be too cramped.

**Comment by alerque** [comment]
The configuration options to do this already exist, see the help documentation for specifics of how to setup per-domain behavior. You can match domain roots or subdomains with pattern matching expressions quite easily.
