### ISSUE TITLE
Firenvim is not working on Linux Mint 19

### ISSUE THREAD

**Issue by kuator** [glacambre/firenvim#140]
After trying commands in troubleshooting guide, firenvim is still not working.
```
~/.local/share/firenvim   38s
❯ $ echo 'abcde{}' | /home/evakuator/.local/share/firenvim/firenvim
Error detected while processing function OnStdin[29]..WriteStdout:
line    5:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: attempt to index global 'bit' (a nil value)
Press ENTER or type command to continue

```
The firenvim script:
```
~/.local/share/firenvim   55s
❯ $ cat firenvim                                         
#!/bin/sh
cd /home/evakuator/.local/share/firenvim

exec '/usr/bin/nvim' --headless -c 'call firenvim#run()'
```
The neovim version:
```
~/.local/share/firenvim   
❯ $ nvim --version                                                                
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
```

**Comment by justinmk** [comment]
Looks like you are missing a Lua package. How exactly did you install nvim ?

**Comment by kuator** [comment]
I installed through ppa of neovim

**Comment by justinmk** [comment]
Well, for some reason the `bit` Lua package is missing. Not really a firenvim issue. If you run `nvim` by itself, this should print `1`:

    :lua print(bit.band(1,1)) 

If that throws an error, then you need to report this bug to the PPA maintainer for Linux mint or whoever maintains the package that you installed. Or you could try installing the `luabitop` package via LuaRocks.

**Comment by kuator** [comment]
So, I installed appimage, and it prints that it has lua installed.
Now, in firefox console it says
`Firefox can’t establish a connection to the server at ws://127.0.0.1:35027/3826609526.`

**Comment by glacambre** [comment]
@kuator Did you re-run `call firenvim#install()` after you installed the neovim appimage?

**Comment by kuator** [comment]
Yes, I ran `nvim --headless -c "call firenvim#install(0)" -c "quit"`

**Comment by kuator** [comment]
I just installed chrome, and added firenvim in it. And it works.

**Comment by glacambre** [comment]
Huh. That's weird. Could you re-install the firenvim plugin in firefox? Maybe try with a fresh profile (`firefox -P freshprofile`)?

**Comment by kuator** [comment]
@glacambre it works
