### ISSUE TITLE
Whitelist, Blacklist option

### ISSUE THREAD

**Issue by Archie-2021** [glacambre/firenvim#1401]
I don't think there would be a situation in near future where all websites support this method of input, so a whitelist and blacklist for website not supporting this is necessary. For example i have to disable this plugin and reload every time I am on a fresh boot and using discord on my browser. 

Thank you

**Comment by rddunphy** [comment]
You can disable it for certain domains using the config object (in `init.vim`):

```vim
let g:firenvim_config = { 
		\	'localSettings': {
		\		'.*': {
		\			'priority': 0,
		\			'takeover': 'always'
		\		},
		\		'https://twitter.com': {
		\			'priority': 1,
		\			'takeover': 'never'
		\		},
		\		'https://docs.google.com': {
		\			'priority': 1,
		\			'takeover': 'never'
		\		},
		\		'https://www.messenger.com': {
		\			'priority': 1,
		\			'takeover': 'never'
		\		}
		\	}
		\ }
```
