### ISSUE TITLE
Mention "whitelist" and "blacklist" in README

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#1402]
https://github.com/glacambre/firenvim/issues/1401 shows that users might use these words when describing preventing Firenvim from taking over some pages/elements. We need to use them in the [takeover section](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements) in order to make said section easier to find.

**Comment by glacambre** [comment]
Can't find a way to reword the paragraph without making it harder to parse. Will revisit if/when new issues are opened.

**Comment by 00sapo** [comment]
I think this issue is actually useful. I was looking for these information but couldn't it

**Comment by glacambre** [comment]
@00sapo Thanks a lot for the feedback :)
