### ISSUE TITLE
Is there support for editable HTML elements?

### ISSUE THREAD

**Issue by bgshacklett** [glacambre/firenvim#1411]
- OS Version:
macOS 12.5
- Browser Version:
Firefox 103.0.2
- Browser Addon Version:
Latest
- Neovim Plugin Version:
0.2.13

### What I tried to do
Edit text in an editable `<body>` HTML field in [Rally](https://www.broadcom.com/products/software/value-stream-management/rally).

```HTML
<iframe src="[...]" style="[...]" class="[...]" title="Description" [...]>
    <html dir="ltr" lang="en">
        <head>[...]</head>
        <body class="[...]" spellcheck="true" contenteditable="true">
            <!-- Editor here -->
            <p><br></p>
        </body>
    </html>
</iframe>
```

### What happened
firenvim was not invoked.

### What I Expected
firenvim to show an embedded neovim window

**Comment by glacambre** [comment]
Yes, Firenvim is supposed to work with contenteditable elements (but it won't automatically trigger itself - you have to use the keyboard shortcut, `<C-e>` by default, to launch it). It seems to work with [this codepen](https://codepen.io/caraya/pen/ZyQMWd) for example (although the formatting is lost, but that is expected, you need to change [your settings](https://github.com/glacambre/firenvim#editing-html-directly) to be able to keep it).

I don't have access to Rally so I won't be able to fix your problem though.

**Comment by bgshacklett** [comment]
<C-e> works! Unfortunately, the styling in the application makes it pretty unusable, but that seems like it's a bit outside of the scope of the project. :-D
