### ISSUE TITLE
install issue: firenvim script freezes and doesn't print json object

### ISSUE THREAD

**Issue by edementyev** [glacambre/firenvim#1424]
- OS Version:  Linux manjaro x86_64
- Browser Version: 103.0.2
- Browser Addon Version: 0.2.13
- Neovim Plugin Version: latest as of now (commit [56a49d7](https://github.com/glacambre/firenvim/commit/56a49d79904921a8b4405786e12b4e12fbbf171b))

### What I tried to do
Installed firenvim plugin and firefox add-on. Followed troubleshooting guide, tried deleting firenvim dir and reinstalling nvim extension couple of times

### What happened
Firefox add-on says that neovim is not responding, headless neovim instance freezes when calling firenvim script
`echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim`

**Comment by glacambre** [comment]
Hi, thanks for the report.
Could you edit `$XDG_DATA_HOME/firenvim/firenvim` and
1) Remove `--cmd "let g:firenvim_i=[]|let g:firenvim_o=[]|let g:Firenvim_oi={i,d,e->add(g:firenvim_i,d)}|let g:Firenvim_oo={t->add(g:firenvim_o,t)}|let g:firenvim_c=stdioopen({\"on_stdin\":{i,d,e->g:Firenvim_oi(i,d,e)},\"on_print\":{t->g:Firenvim_oo(t)}})"` from the command that runs neovim.
2) Add `2>/tmp/stderr | tee /tmp/stdout` at the end of the command that runs neovim.

And then, attempt to use neovim a couple of times in your browser? This should create two files named `/tmp/stdout` and `/tmp/stderr`, please upload their content here.

**Comment by edementyev** [comment]
Thanks for quick response!
Modified the script, when I reload configuration in add-on both `/tmp/stdout` and `/tmp/stderr` are empty, launching with shortcut doesn't seem to do anything

**Comment by glacambre** [comment]
Are these files created if you run the firenvim script from the command line?

**Comment by edementyev** [comment]
Yes, if I run script `/tmp/stdout` is still empty and `/tmp/stderr` has `:startinsert :stopinsert` line

**Comment by glacambre** [comment]
Okay, the problem very likely comes from your configuration then. I would recommend removing parts of your config until running the script results in an empty `/tmp/stderr` file - Firenvim will probably start working after that :).

**Comment by edementyev** [comment]
Yes, the problem is within my config, loading neovim within script with `-u NONE` does work. Thanks for help! 
Is there a way to see output of `:messages` window in headless? I think it gets stuck on some error message when loading one of the plugins

**Comment by glacambre** [comment]
The content of `messages` should be displayed on the command line (or redirected to /tmp/stdout) if you remove `--cmd "let g:firenvim_i=[]|let g:firenvim_o=[]|let g:Firenvim_oi={i,d,e->add(g:firenvim_i,d)}|let g:Firenvim_oo={t->add(g:firenvim_o,t)}|let g:firenvim_c=stdioopen({\"on_stdin\":{i,d,e->g:Firenvim_oi(i,d,e)},\"on_print\":{t->g:Firenvim_oo(t)}})"` from the command used to run neovim :)

I'll close this issue because there's nothing to do in Firenvim, but feel free to ask any other question you may have :)
