### ISSUE TITLE
Installation didn't create file in the Vivaldi manifest directory.

### ISSUE THREAD

**Issue by anterpin** [glacambre/firenvim#1433]
- OS Version: Linux manjaro 5.10.141-1-MANJARO #1 SMP PREEMPT Mon Sep 5 10:15:26 UTC 2022 x86_64 GNU/Linux
- Browser Version: Vivaldi 5.5.2805.38 (Stable channel) stable (64-bit) 
- Browser Addon Version: Firenvim 0.2.13
- Neovim Plugin Version: 0.2.13

### What I tried to do
firenvim#install(0) didn't install the firenvim.json in ~/.config/vivaldi/NativeMessagingHosts directory.

**Comment by glacambre** [comment]
What is the value of `$XDG_CONFIG_HOME` in your shell?

**Comment by glacambre** [comment]
>I don't have this environment variable set.

Okay, that's probably the reason why Vivaldi isn't being detected. I'll update Firenvim to work around such problems.

>I copied firename.json from the google-chrome folder to the Vivaldi folder, and it started to work

That's surprising to hear, I've had reports that Vivaldi used Chrome's native messaging host directory in the past. Something probably changed. Thanks for the report.
