### ISSUE TITLE
OnUIEnter as documented does not have event

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#146]
A cannot get the function documented in the README for detecting Firenvim to work in my actual config. It throws the following error indicating that the event object is not being passed or doesn't have the properties that function expects it to.

![image](https://user-images.githubusercontent.com/173595/66657823-11fbe780-ec49-11e9-9dfb-843e6d307f6a.png)

Neovim 0.4.2 and Firefox 69.0.2 on Arch Linux.

https://github.com/glacambre/firenvim/blob/master/README.md#L98-L106

**Comment by glacambre** [comment]
That's because I made a mistake - it's `a:event.chan` instead of `a:event.channel`. Sorry, will fix this soon :)
