### ISSUE TITLE
How to verify if the headless nvim is setup correct?

### ISSUE THREAD

**Issue by SuperSandro2000** [glacambre/firenvim#1460]
- OS Version: Windows 11 (Microsoft Windows [Version 10.0.22000.1098])
- Browser Version: Chrome 106.0.5249.119 
- Browser Addon Version: 0.2.13
- Neovim Plugin Version: git rev eeaddd0b503f841fa24f60cebd14fa93d2b33f77

### What I tried to do

Run ``"/etc/profiles/per-user/sandro/bin/nvim" --headless --cmd "let g:firenvim_i=[]|let g:firenvim_o=[]|let g:Firenvim_oi={i,d,e->add(g:firenvim_i,d)}|let g:Firenvim_oo={t->add(g:firenvim_o,t)}|let g:firenvim_c=stdioopen({'on_stdin':{i,d,e->g:Firenvim_oi(i,d,e)},'on_print':{t->g:Firenvim_oo(t)}})" --cmd "let g:started_by_firenvim = v:true" -c "call firenvim#run()"`` inside WSL to debug why the extension fails with ``Neovim died without answering.``

### What happened

I didn't receive an output.

How do I know if the command works?

**Comment by SuperSandro2000** [comment]
This is probably related to #1458

In ``/mnt/wslg/runtime-dir/`` I have some nvim sockets but they could also be related to coc.

**Comment by glacambre** [comment]
Not getting any output is expected - the command you're running expects some input on stdin. Try `echo 'abcde{}' | "/etc/profiles/per-user/sandro/bin/nvim" ...` instead.

**Comment by glacambre** [comment]
#1466 should have improved things a lot in term of wsl setup debuggability. I'll close this issue and await your answer in #1458 :)

**Comment by SuperSandro2000** [comment]
Thanks for your help! I will test this in the next day or two and report back.
