### ISSUE TITLE
plugin won't install: 'lua require("bit")' fails

### ISSUE THREAD

**Issue by hwine** [glacambre/firenvim#1476]
- OS Version: Ubuntu 20.04 (focal)
- Browser Version: n/a
- Browser Addon Version: n/a
- Neovim Plugin Version: latest (git ref 17a189f0f1e2d4197e00cd56dbeaed8c268bac8c)

<details><summary>Neovim version: v0.9.0-dev with Lua 5.1</summary>

```
NVIM v0.9.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-CqPw1c/neovim-0.9.0~ubuntu1+git202212270019-fe5665be3-333b5866f=. -fstac
k-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET
_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-prom
otion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-commo
n -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_
LEVEL=3 -I/build/neovim-CqPw1c/neovim-0.9.0~ubuntu1+git202212270019-fe5665be3-333b5866f/build/cmake.config -I/build/neovim-CqPw1c/neovim-
0.9.0~ubuntu1+git202212270019-fe5665be3-333b5866f/src -I/build/neovim-CqPw1c/neovim-0.9.0~ubuntu1+git202212270019-fe5665be3-333b5866f/.de
ps/usr/include -I/usr/include -I/build/neovim-CqPw1c/neovim-0.9.0~ubuntu1+git202212270019-fe5665be3-333b5866f/build/src/nvim/auto -I/buil
d/neovim-CqPw1c/neovim-0.9.0~ubuntu1+git202212270019-fe5665be3-333b5866f/build/include
Compiled by buildd@bos01-arm64-010
```
</details>

### What I tried to do

Per install instructions: `call firenvim#install(0)`

### What happened

Received error message:
```
Error detected while processing function firenvim#install[10]..function firenvim#install:
line    8:
Error: Lua package "bit" unavailable. Install it or switch to LuaJIT.
```

Neovim's checkhealth does not report any issues.

I've not had any luck resolving this. I've tried installing both `lua-nvim` and `lua-nvim-dev`, and neither helps. (I even tried installing `lua` and `luajit`, even though I didn't expect that to help.)

**Comment by glacambre** [comment]
Try to install the `bit` package by running `luarocks install bit` :).

Off-topic: Are you trying to use Firenvim on ARM?

**Comment by alerque** [comment]
Most distros compile NeoVIM using LuaJIT which has a built in bitwise library. Yours for some reason is compiled against plain Lua 5.1, not LuaJIT — hence the need to supply a 3rd party substitute library.

**Comment by justinmk** [comment]
in the future this will hopefully be resolved: https://github.com/neovim/neovim/pull/21222

**Comment by hwine** [comment]
**Fixed**: `sudo apt install -y lua-bitop` did the trick.

Looks like I switched to an [unstable PPA of Neovim](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) about a month ago. Unlike the [focal Neovim](https://packages.ubuntu.com/focal/neovim), the PPA did not have `lua-bitop` as a dependency (it apparently isn't needed on amd64, but I'm arm64).

**Comment by hwine** [comment]
> Off-topic: Are you trying to use Firenvim on ARM?

Yes -- I use a Microsoft Surface X (arm64) running Windows 11 and WSL. I run graphics apps (Zoom, etc) under windows, and do all my editing in neovim. I'm very happy with it in general.

Windows and linux are both good nowadays at executing amd64 binaries - I rarely notice a difference. And the bridge between the 2 OS is getting thinner -- Neovim (linux) is my embedded editor for VSCode (win11).
