### ISSUE TITLE
Command modifier gets sent as meta modifier on osx

### ISSUE THREAD

**Issue by svermeulen** [glacambre/firenvim#148]
- OS Version: Macos mojave 10.14.6
- Browser Version: Chrome77.0.3865.90
- What I tried to do: `<c-v><d-e>` (where `d-e` is the mac command key + the e key)
- What happened: Inside the embedded neovim it prints `<m-e>`
- What I expected: I expected `<d-e>` which is what is printed in other GUIs such as nvim-qt.

**Comment by glacambre** [comment]
Yep, looks like command is named meta [in javascript](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey). Should be easy to fix. Does OSX have a meta key?

**Comment by justinmk** [comment]
> Does OSX have a meta key?

It has ALT, yes. That should be M- prefix whereas cmd should be D- prefix.

**Comment by svermeulen** [comment]
Yeah, I think the meta key on OSX usually refers to the option/alt key and not command key

That link you included states that "On Macintosh keyboards, this is the Command Key".  And if you execute `:h <D-` in vim it states that it is for `command-key or "super" key`.  Also, nvim-qt maps the OSX command key to `<D-`.

So I think it should be changed to `<D-`.

**Comment by glacambre** [comment]
I think I'm probably doing something wrong on Windows too regarding meta & other modifiers. I couldn't a help page that describes what prefixes neovim expects for each modifier+os combo. Is that documented somewhere?

**Comment by justinmk** [comment]
> Is that documented somewhere?

    :h keycode
