### ISSUE TITLE
firenvim with lunarvim and chrome

### ISSUE THREAD

**Issue by ea42gh** [glacambre/firenvim#1486]
- OS Version:                         windows 11
- Browser Version:                 chrome Version 108.0.5359.125 
- Neovim Plugin Version:       firenvim 0.2.14

### What I tried to do:
using
    lunarvim  (NVIM v0.9.0-dev)  via wsl
    chrome browser from windows
I made sure the browser is correctly entered in the windows registry
and adjusted the exec statement in the firenvim shell script to execute lvim rather than nvim directly.

----------------------------------------------------------------------------------
No config detected for chromium. Skipping.
No config detected for ungoogled-chromium. Skipping.
No config detected for librewolf. Skipping.
No config detected for opera. Skipping.
Installed native manifest for brave.
Creating registry key for brave. This may take a while. Script: /mnt/c/Users/lab/AppData/Local/firenvim/brave.ps1
Created registry key for brave.
No config detected for vivaldi. Skipping.
Aborting installation for chrome-dev. No chrome dev on win32.
Installed native manifest for firefox.
Creating registry key for firefox. This may take a while. Script: /mnt/c/Users/lab/AppData/Local/firenvim/firefox.ps1
Created registry key for firefox.
No config detected for chrome-canary. Skipping.
Installed native manifest for chrome.
Creating registry key for chrome. This may take a while. Script: /mnt/c/Users/lab/AppData/Local/firenvim/chrome.ps1
Created registry key for chrome.
Installed native manifest for edge.
Creating registry key for edge. This may take a while. Script: /mnt/c/Users/lab/AppData/Local/firenvim/edge.ps1
Created registry key for edge.

### What happened

The firenvim plugin shows "FireNvim has access to this site"  (A jupyter lab notebook),
but I cannot get the editor window

**Comment by glacambre** [comment]
>and adjusted the exec statement in the firenvim shell script to execute lvim rather than nvim directly.

I do not support this, sorry. You'll have to ask for help from the lunarvim maintainers.
