### ISSUE TITLE
Your plugin manager did not load the Firenvim plugin for neovim

### ISSUE THREAD

**Issue by niekas** [glacambre/firenvim#1488]
- OS Version: Ubuntu 20.04
- Browser Version: Firefox 108
- Browser Addon Version: Latest 2022 November release.
- Neovim Plugin Version: Latest 2022 November release.

### What I tried to do
Tried to install Firenvim using Packr and nvim=v0.8.2, it was installed, but it does not work. Tried to troubleshoot and got an error. The $XDG_DATA_HOME is set to `/`, but `/home/niekas/.local/share/firenvim/firenvim` file exists.

### What happened
```
echo 'abcde{}' | /home/niekas/.local/share/firenvim/firenvim
f{"messages": ["Your plugin manager did not load the Firenvim plugin for neovim."], "version": "0.0.0"}Firenvim not in runtime path. &rtp=/home/niekas/.config/nvim,/etc/xdg/xdg-ubuntu/nvim,/etc/xdg/nvim,/home/niekas/.local/share/nvim/site,/home/niekas/.local/share/nvim/site/pack/*/start/*,/usr/share/ubuntu/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/var/lib/snapd/desktop/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/runtime/pack/dist/opt/matchit,/lib/nvim,/var/lib/snapd/desktop/nvim/site/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/usr/share/ubuntu/nvim/site/after,/home/niekas/.local/share/nvim/site/after,/etc/xdg/nvim/after,/etc/xdg/xdg-ubuntu/nvim/after,/home/niekas/.config/nvim/after
```

**Comment by glacambre** [comment]
>The $XDG_DATA_HOME is set to /

What does this mean? Is this something you've configured on your machine?

**Comment by niekas** [comment]
> > The $XDG_DATA_HOME is set to /
> 
> What does this mean? Is this something you've configured on your machine or something you think firenvim computes wrong?

I did nothing custom. I have found this value in the [Firenvim Troubleshooting guide](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-firenvim-script-has-been-created) and simply outputed its value.

**Comment by glacambre** [comment]
What happens if you:
- Run `git clone https://github.com/glacambre/firenvim /tmp/firenvim`
- Then replace the content of your `init.vim` with `set rtp+=/tmp/firenvim`?

Do you get the same error message when running `echo 'abcde{}' | /home/niekas/.local/share/firenvim/firenvim`?

**Comment by albertas** [comment]
Yup, I get the same error message after executing your steps:
```
echo 'abcde{}' | /home/niekas/.local/share/firenvim/firenvim
f{"messages": ["Your plugin manager did not load the Firenvim plugin for neovim."], "version": "0.0.0"}Firenvim not in runtime path. &rtp=/home/niekas/.config/nvim,/etc/xdg/xdg-ubuntu/nvim,/etc/xdg/nvim,/home/niekas/.local/share/nvim/site,/home/niekas/.local/share/nvim/site/pack/*/start/*,/usr/share/ubuntu/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/var/lib/snapd/desktop/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/runtime/pack/dist/opt/matchit,/lib/nvim,/var/lib/snapd/desktop/nvim/site/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/usr/share/ubuntu/nvim/site/after,/home/niekas/.local/share/nvim/site/after,/etc/xdg/nvim/after,/etc/xdg/xdg-ubuntu/nvim/after,/home/niekas/.config/nvim/after
```

**Comment by albertas** [comment]
I am using LunarVim, the Firenvim plugin was installed using this command:

```
lvim.plugins = {
    { "glacambre/firenvim",
        run = function() vim.fn['firenvim#install'](0) end
    }
}
```

**Comment by glacambre** [comment]
Sorry, but lunarvim is not supported. I recommend you ask the lunarvim maintainers for help.

**Comment by niekas** [comment]
But the LunarVim is just a Lua layer on top of Neovim :thinking:

**Comment by glacambre** [comment]
No, it's not, otherwise your installation would work out of the box (and so would https://github.com/glacambre/firenvim/issues/1486 ) :).
