### ISSUE TITLE
F1-F12 Keys do not get sent to nvim

### ISSUE THREAD

**Issue by svermeulen** [glacambre/firenvim#149]
- OS Version: Macos mojave 10.14.6
- Browser Version: Chrome77.0.3865.90
- What I tried to do: Enter insert mode then hit `<f1>` (or any function key)
- What happened: No text is added
- What I expected: In other nvims, including terminal nvim, `<f1>` gets added

**Comment by glacambre** [comment]
Thanks for reporting this :)
