### ISSUE TITLE
Console Warning: InstallTrigger is deprecated and will be removed in the future.

### ISSUE THREAD

**Issue by cassepipe** [glacambre/firenvim#1493]
The console on any website reports:
```InstallTrigger is deprecated and will be removed in the future.```

It seems that it comes from the utils.ts file at line 8				
https://github.com/glacambre/firenvim/blob/b59c95ef855aea7359373b66b1e27e439870137e/src/utils/utils.ts#L8
Thought I'd let you know since I did not find it the github issues.

**Comment by glacambre** [comment]
Thanks. I'm aware of this problem but unsure of how to work around it. I need to find another chrome-only feature that Mozilla will never implement and that Chrome will never deprecate 🫠.
