### ISSUE TITLE
<MiddleMouse> pastes even when remapped to <Nop>

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#1506]
_Originally posted by @ysl2 in https://github.com/glacambre/firenvim/issues/1505#issuecomment-1443791769_

Fix probably is just to handle mouse events on the keyboard handler the same way they're handled in the rest of the iframe.

**Comment by ysl2** [comment]
No, not paste behavior. I think I might mixed up the `middlemouse click` and `middlemouse scroll`.

I want to map middlemouse scroll to nop. beacuse when I use middlemouse to scroll page, the firenvim also scrolls. That's not I want. I just only want to scroll page, instead of the firenvim.

**Comment by glacambre** [comment]
It turns out that `:map <MiddleMouse> <nop>` pasting is actually normal: `:map` only maps in normal, operator and verbose mode, not in insert mode.
