### ISSUE TITLE
Failing to load in browser

### ISSUE THREAD

**Issue by benlieb** [glacambre/firenvim#1516]
My initial error was "Neovim died without answering." But after re-installing, now it just  stalls on "loading configs".

My troubleshooting failed on step 2:

╰─○ echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim                            
zsh: no such file or directory: /firenvim/firenvim

- OS Version: MacOS 12.5
- Browser Version: Version 110.0.5481.177 (Official Build) (arm64)
- Browser Addon Version: Firenvim 0.2.14
- Neovim Plugin Version: What is a the neovim plugin? You mean actual neovim version? NVIM v0.8.2

### What I tried to do
Reinstall Plugin
Troubleshooting steps

### What happened

Failed as above

**Comment by glacambre** [comment]
>But after re-installing, now it just stalls on "loading configs".

This is not something Firenvim prints by default, so this error must come from one of your other plugins. Try disabling all of your plugins except for Firenvim.

>My troubleshooting failed on step 2:

Could you replace `$XDG_DATA_HOME/firenvim/firenvim` with `$HOME/.local/share/firenvim` and try again?
