### ISSUE TITLE
Noice giving warnings on startup

### ISSUE THREAD

**Issue by shauryagoel** [glacambre/firenvim#1534]
- OS Version: Arch Linux
- Browser Version: google-chrome 113.0.5672.63-1
- Browser Addon Version: 0.2.14
- Neovim Plugin Version: plugin from commit- ee4ef314bd990b2b05b7fbd95b857159e444a2fe

### What I tried to do
As soon as firenvim starts on a text box

### What happened
I get the following warning which takes a lot of screen space and takes few seconds to go away.

![image](https://user-images.githubusercontent.com/6321314/236614032-1f347ad4-a55a-494e-a79b-9e2eb0dd0e8d.png)
Any way I can disable this warning at startup while using firenvim. Preferably some configuration inside the firenvim plugin config.

**Comment by glacambre** [comment]
Try following the instructions [here](https://github.com/glacambre/firenvim#choosing-a-command-line) :)

**Comment by shauryagoel** [comment]
I am adding the following config and I am still getting the same warning.

```
  config = function()
    vim.g.firenvim_config = {
      localSettings = {
        [".*"] = {
          -- takeover = "never",
          cmdline = "firenvim",
        },
      },
    }
  end,
```

**Comment by glacambre** [comment]
Yes, as described in the documentation you should use `cmdline = "none"`.

**Comment by shauryagoel** [comment]
`cmdline = "none"` is also not working

**Comment by glacambre** [comment]
Mh, I can see why in the code, thanks for telling me. Out of curiosity, could you also try `cmdline = "neovim"` and let me know what the result it?

**Comment by shauryagoel** [comment]
Setting to `cmdline = "neovim"` has solved the issue for me. I am not getting those noice warnings now. Thank you for the help.

**Comment by glacambre** [comment]
Great, thanks for letting me know. This is rather confusing when considering https://github.com/glacambre/firenvim/issues/1442 , where it was found that noice re-enabled the external command line, but if it works as is I'll take the win :)

**Comment by joshuadanpeterson** [comment]
I was also getting this same error and one for `ext_messages`. Setting both cmdline and messages to "neovim" fixed the issue.
