### ISSUE TITLE
Disabling a few plugins?

### ISSUE THREAD

**Issue by niksingh710** [glacambre/firenvim#1536]
- OS Version: Arch Linux
- Browser Version: Firefox 113.0
- Browser Addon Version: 0.2.14
- Neovim Plugin : v0.9.0

### What happened
There are a few plugins that shows big text message and i would not like to have them in the browser 
e.g noice.nvim (uses nui  as a dependency)

and there are a few texts those pop up and annoy if any solution is there tell me as i was unable to figure out...

### Different config?
is there anyway i can point firenvim to use config from somewhere else?

![image](https://github.com/glacambre/firenvim/assets/60490474/363abe4a-5c4c-447c-b804-bcbc5cdce306)

**Comment by alerque** [comment]
Yes, you can enable or disable whatever you want in the Firenvim instances. This is already covered in the documentation though:

https://github.com/glacambre/firenvim#building-a-firenvim-specific-config

**Comment by glacambre** [comment]
>unable to figure out how to disable this from lspsaga

I would recommend reading lspsaga's documentation to figure out how it gets enabled, and then not enable it when Firenvim is loaded (e.g. by checking the `started_by_firenvim` global variable).

>will it be possible to have a discussion tab where asking questions will be possible?

Done, although I doubt there will be much activity there.

>is it possible that firenvim captures all keymaps until it is quitted? or unfocused using the mouse?

Yes, Firenvim captures as many keyboard shortcuts as it can (there are a few it cannot capture though - see https://github.com/glacambre/firenvim#drawbacks for more information about this).
If you find unfocusing Firenvim annoying, know that you can create a keyboard shortcut to do that (see the `<Esc><Esc>` keyboard shortcut [here](https://github.com/glacambre/firenvim#interacting-with-the-page) for an example).
