### ISSUE TITLE
Use CMD key as CTRL key in Neovim

### ISSUE THREAD

**Issue by martin-braun** [glacambre/firenvim#1545]
On MacOS, I use karabiner to map my outer-most fn key to cmd, so I can use bindings like I am on Windows. On Terminal windows I then swap fn with ctrl to have the ctrl key on the outer most position.

I need the same setup for embedded Neovim in the browser. I use the Arc Browser. I thought about adding the fn-ctrl swap rule to Arc, but then I have to copy and paste everything using the physical ctrl key, which is less ideal.

It would be nice if I could remap keys only for the Neovim iframe. Mapping the cmd-key in macOS within Neovim doesn't work either.

**Comment by justinmk** [comment]
> if I could remap keys only for the Neovim iframe

    if exists('g:started_by_firenvim')

> Mapping the cmd-key in macOS within Neovim doesn't work either.

I just tried mapping `cmd-a` in firenvim on this page, it works:

    nnoremap <d-a> ifoo<esc>

**Comment by justinmk** [comment]
It sounds like you want to remap cmd to ctrl for all mappings. That would mean another layer of remappings:

1. your OS / window manager
2. chrome
3. firenvim
4. nvim

**Comment by martin-braun** [comment]
@justinmk thanks, it was a problem on my end, indeed it works. Good job.

> It sounds like you want to remap cmd to ctrl for all mappings.  

Yes, but no. Too many conflicts at this point. Just the basic stuff to use Neovim conveniently. Thanks again!
