### ISSUE TITLE
Deprecation notice on Chrome

### ISSUE THREAD

**Issue by craigmac** [glacambre/firenvim#1548]
Just FYI, I noticed this in the Error log:

```
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

This is after installing 0.2.14 from downloaded chrome.zip package.

**Comment by glacambre** [comment]
Thanks! ManifestV2 removal has been [indefinitely postponed](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E) by Google for now, so I prefer to wait until its removal is announced again before migrating Firenvim to ManifestV3.

Unfortunately, the ManifestV3 model will require a change in Firenvim's architecture, so I want everything to be as stable as possible before doing anything :)

**Comment by glacambre** [comment]
Closing in favor of https://github.com/glacambre/firenvim/issues/1193 .
