### ISSUE TITLE
Movement keys not repeating when held down

### ISSUE THREAD

**Issue by benlieb** [glacambre/firenvim#1550]
The movement keys h,j,k,l are not repeating whent I hold them down, however <space> does.

Is there a config option I need to set for this behavior?

Thanks!

**Comment by benlieb** [comment]
Actually this might be a global mac setting....

**Comment by glacambre** [comment]
>Is there a config option I need to set for this behavior?

No, this should work out of the box. What browser are you using?

**Comment by benlieb** [comment]
Sorry, Chrome Browser Mac

**Comment by danielb2** [comment]
it's a mac thing. try `defaults write -g ApplePressAndHoldEnabled -bool false` in your terminal of choice

**Comment by glacambre** [comment]
@benlieb Please let us know if @danielb2's command solves your problem :)

**Comment by benlieb** [comment]
Yes this actually did solve the problem! Thanks @danielb2! 

I had to restart my browser though.

**Comment by benlieb** [comment]
Considering done
