### ISSUE TITLE
How to setup isolated Firenvim-specific config?

### ISSUE THREAD

**Issue by eisukeesaki** [glacambre/firenvim#1555]
## runtime environment

Kernel Version: Linux 6.4.9-arch1-1
Neovim Version: NVIM v0.9.1
Browser Version: 116.0.2 (64-bit)
Browser Addon Version: 0.2.15
Neovim Plugin Version: 0.2.15

## What I want to achieve

[Set the `takeover` setting to `never`](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements)) using a Firenvim-specific config (in `~/.config/firenvim/init.lua`) isolated from `~/.config/nvim`.

## What I have tried

- set `export NVIM_APPNAME="nvim"` in `~/.bashrc`
- installed `glacambre/firenvim` Neovim plugin using Packer
- installed browser add-on
- confirm `:echo g:started_by_firenvim` = `true`
- in `~/.config/nvim/init.lua`, do:
```lua
if vim.g.started_by_firenvim == true then
  vim.g.firenvim_config.localSettings['.*'] = { takeover = 'never' }
end
```
- remove the above code and do the following in the same file:
```lua
vim.api.nvim_create_autocmd({'UIEnter'}, {
    callback = function(event)
        local client = vim.api.nvim_get_chan_info(vim.v.event.chan).client
        if client ~= nil and client.name == "Firenvim" then
          vim.g.firenvim_config.localSettings['.*'] = { takeover = 'never' }
        end
    end
})
```

## Summary

The Neovim frame is still automatically shown in the browser despite the attempt to alter that behavior.

What am I doing wrong?

**Comment by glacambre** [comment]
Hi, thanks for opening this issue. Let's do things one step at a time first. We'll begin with stopping Firenvim from running in your default config. If you open the browserAction (the Firenvim icon next to your URLbar), you'll probably see error messages about vim.g.firenvim_config not existing. If you try to replace your firenvim config in ~/.config/nvim/init.lua with
```lua
if vim.g.started_by_firenvim == true then
	vim.g.firenvim_config = {
		localSettings = {
			[".*"] = {
				takeover = "never"
			}
		}
	}
end
```
The error message should disappear and firenvim should stop appearing by default. Can you confirm that this works?

**Comment by eisukeesaki** [comment]
I did as you said, and the desired behavior was achieved. Are there any downsides to overwriting the entire `vim.g.firenvim_config`? I tried to see what is inside it before it is overwritten, but the result of `print()` was not printed when I manually activated the Neovim frame in the browser.

```lua
if vim.g.started_by_firenvim == true then
        print(vim.g.firenvim_config)
	vim.g.firenvim_config = {
		localSettings = {
			[".*"] = {
				takeover = "never"
			}
		}
	}
end

```

**Comment by eisukeesaki** [comment]
Appologies if I confused you. I just meant to let you know that: after following what you said, Firenvim no longer shows up automatically.

**Comment by glacambre** [comment]
>Are there any downsides to overwriting the entire vim.g.firenvim_config?

There are no downsides, `vim.g.firenvim_config` isn't defined by default :)

>I just meant to let you know that: after following what you said, Firenvim no longer shows up automatically.

Great! Now, if you are still interested in having a Firenvim-only config, here's how to do it:

- Edit ~/.config/firenvim/init.lua to add any plugins you need (e.g. packer.nvim, your colorscheme...), including Firenvim
- In a shell, run `export NVIM_APPNAME=firenvim`
- Then, run `nvim` and in nvim run `:call firenvim#install()`

That should be it! The neovim you run in your browser should be using your config defined in ~/.config/firenvim/init.lua .
