### ISSUE TITLE
Add support for portable version of Thorium which is based on chromium. Thx

### ISSUE THREAD

**Issue by meicale** [glacambre/firenvim#1572]
troubleshooting guide: https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md

I used chrome test this plugin and my wsl  lazyvim config, it works as expected. I hope to use it in the portable version of the browser. I find check the  link above and I have not found the exact solution to do that. Please add some information there such as "which file is copied and pasted where" etc. 
Thank you in advance for anyone reply and if you are interested in this too, just leave your comments.

**Comment by glacambre** [comment]
If you are on linux, you need to copy Chromium's [native manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests) file to Thorium's native [manifest directory](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#manifest_location). If you are on windows, you need to create a registry key pointing to that file.

It seems Thorium doesn't document the location of its manifest file directory nor the name of the registry key that needs to be created, so I can't help you there, you'll have to take a look at its source code to figure these out.
