### ISSUE TITLE
Unexpected directory created on Windows host after installation on Windows host side

### ISSUE THREAD

**Issue by xudyang1** [glacambre/firenvim#1578]
- OS Version: Windwos 10 22H2
- Browser Version: 120.0.6099.225
- Browser Addon Version: 0.2.15
- Neovim Plugin Version: 0.2.15

### What I tried to do
Run `:lua vim.fn["firenvim#install"](0)` on Windows host system

### What happened
A directory `mnt/c/Users/myUserName/appdata/local/firenvim/` with file `filenvim.bat` created under `C:` drive, so the full path is `C:\\mnt\\c\\Users\\....\\firenvim`

**Comment by glacambre** [comment]
Solved by @xudyang1 in https://github.com/glacambre/firenvim/pull/1579
