### ISSUE TITLE
Add explanation on how to use it with snap / flatpak

### ISSUE THREAD

**Issue by tyalie** [glacambre/firenvim#1591]
Just wanna shime in and state that the position "firenvim doesn't work with flatpak or snap" was true in the past, but due to effort by great people does not hold true anymore.

The problem you describe is basically the same as [keepassxc-browser][keepass-browser] had in the past. As I use it actively with snap on Ubuntu 22.04, I was sure that I could achive the same with firenvim, by just following their [troubleshooting guide][keepass-browser-troubleshoot].

### How to get firenvim running with snap/flatpak

1. install firenvim as described in the documentation
2. give the firenvim browser extension permission to use the native messaging host using
    - `flatpak permission-set webextensions firenvim snap.firefox yes`
3. restart firefox
4. enjoy

[keepass-browser]: https://github.com/keepassxreboot/keepassxc-browser
[keepass-browser-troubleshoot]: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#5-ubuntu-snap

**Comment by glacambre** [comment]
Thanks a lot for sharing your solution! :)

**Comment by SuggonM** [comment]
Not sure if this solves it for flatpak. On Zen flatpak, I still get `Neovim died without answering` despite the checklist in TROUBLESHOOTING.md all appearing green. Even tried adding permission to `app.zen_browser.zen` to no avail.
```sh
flatpak permission-set webextensions firenvim app.zen_browser.zen yes
```
