### ISSUE TITLE
Review/update recovery instructions in wiki

### ISSUE THREAD

**Issue by hwine** [glacambre/firenvim#1598]
I just had my browser crash in the middle of crafting a long email in firenvim. Gmail, of course, only knew about the few lines before I started up firenvim, so I'd lost a lot.

I figured nvim would be my friend, and have saved almost-to-the-moment-of-crash state, but I wasn't sure where. I poked around and found it, and created [this wiki page](https://github.com/glacambre/firenvim/wiki/Recovering-edit-buffer-contents-when-browser-crashes) to document it and my procedure.

It needs review, for at least the following points:
- overall correctness (was there a simpler way)
- location of temp files on systems other than Windows 11

I figured an issue was the best way to draw attention to the new wiki page and the need for review. I hope someone can benefit from it.

**Comment by glacambre** [comment]
Hi, thank you for taking the time to write this wiki page! I was afraid you might have lost a lot of data (in my experience Firenvim isn't very good at recovering from crashes/unwanted shutdowns), but I'm relieved to see that it wasn't the case :). As far as I can tell, your instructions are perfect, I've added the location of the Firenvim directory on Linux/Mac, so I think we can this issue.

Thanks again!
