### ISSUE TITLE
"TypeError: nvim.call_atomic is not a function" on Nvim HEAD

### ISSUE THREAD

**Issue by justinmk** [glacambre/firenvim#1603]
- OS Version: macos 14.4
- Browser Version: chrome 124.0.6367.62
- Browser Addon Version: 0.2.15
- Neovim Plugin Version: 0.2.15

### What I tried to do

use nvim 0.10 HEAD which has deprecated `nvim_call_atomic()`

https://github.com/neovim/neovim/pull/28433

### What happened

If I try to use latest Nvim HEAD which has marked `nvim_call_atomic()` as deprecated, firenvim fails and this error is reported in devtools console:

```
index.js:6714 TypeError: nvim.call_atomic is not a function
```

If I remove `FUNC_API_DEPRECATED_SINCE(12)` from [nvim source](https://github.com/neovim/neovim/blob/47dbda97d2f40729733b1c0d1d13d914065af23c/src/nvim/api/deprecated.c#L727) and rebuild nvim, then firenvim works.

**Comment by justinmk** [comment]
It looks like this is the only use of nvim_call_atomic in firenvim: https://github.com/glacambre/firenvim/blob/e99aa603f5311a850be1d02759b0ec62ce3990a3/src/frame.ts#L118-L128

That could be replaced with `nvim_exec_lua`.

**Comment by justinmk** [comment]
Just to be clear, `nvim_call_atomic()` was not removed in Nvim HEAD, it was only marked as deprecated. So I'm wondering if firenvim might be filtering-out deprecated API functions, when it generates bindings ?

**Comment by glacambre** [comment]
@justinmk Thanks a lot for the early report/warning. The problem indeed was that depecrated functions were ignored by Firenvim (ironically, this saved Firenvim from breaking when https://github.com/neovim/neovim/commit/f31db30975479cb6b57247f124a65f4362f80bfe was merged, there was another bug in Firenvim's API that got triggered by this).

I'll attempt to fix a couple of other issues today and and then publish a new release to the chrome/firefox add-on stores this evening.
