### ISSUE TITLE
Neovim plugin version (0.2.15) and browser addon version (0.2.16) do not match.

### ISSUE THREAD

**Issue by benlieb** [glacambre/firenvim#1609]
Using Chrome. I removed and reinstalled firenvim, upgraded nvim via brew, and updated plugins in nvim. No change. Help?

**Comment by glacambre** [comment]
Have you tried running your plugin manager's update command from a firenvim instance?

**Comment by OsKaR31415** [comment]
@glacambre 
I have the same problem (on macos, using firefox). Updating all plugins (I'm using Vim-Plug) doesn't solve the problem.

**Comment by benlieb** [comment]
I basically have stopped trying. I've loved this extension, but it breaks all the time.

**Comment by glacambre** [comment]
>And since I can't start firenvim (the error is apparently blocking it)

Huh, that's super odd. I guess this warning must be masking a true error, this is quite unfortunate. What happens if you run `echo 'abcde{}' | ${XDG_DATA_HOME:-${HOME}/.local/share}/firenvim/firenvim` ?

**Comment by OsKaR31415** [comment]
>  What happens if you run `echo 'abcde{}' | ${XDG_DATA_HOME:-${HOME}/.local/share}/firenvim/firenvim` ?
For me, `echo 'abcde{}' | .local/share/firenvim/firenvim` executes fine and gives no output.

**Comment by glacambre** [comment]
>For me, echo 'abcde{}' | .local/share/firenvim/firenvim executes fine and gives no output.

It should be giving you some output, something that looks like `o{"messages": [], "version": "0.2.15", "settings": {"localSettings": {}}}`. Could you upload the contents of this script here?

**Comment by benlieb** [comment]
`echo 'abcde{}' | ${XDG_DATA_HOME:-${HOME}/.local/share}/firenvim/firenvim 
c{"messages": [], "version": "0.2.15", "settings": {"localSettings": {".*": {"takeover": "never"}}}}%  `

**Comment by OsKaR31415** [comment]
> Could you upload the contents of .local/share/firenvim/firenvim here?
```bash
#!/bin/sh
mkdir -p /var/folders/67/j6c23f3d5r18jd58813p8rbw0000gn/T//firenvim
chmod 700 /var/folders/67/j6c23f3d5r18jd58813p8rbw0000gn/T//firenvim
cd /var/folders/67/j6c23f3d5r18jd58813p8rbw0000gn/T//firenvim
export PATH="$PATH:/opt/homebrew/bin:/opt/homebrew/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/oscarplaisant/Library/Python/3.9/bin:/Applications/quarto/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/oscarplaisant/.zsh_scripts/:/Users/oscarplaisant/.cargo/bin:/Users/oscarplaisant/.local/bin:/Users/oscarplaisant/.zsh_scripts/:/Users/oscarplaisant/.cargo/bin:/Users/oscarplaisant/.local/bin"
unset NVIM_LISTEN_ADDRESS
if [ -n "$VIM" ] && [ ! -d "$VIM" ]; then
  unset VIM
fi
if [ -n "$VIMRUNTIME" ] && [ ! -d "$VIMRUNTIME" ]; then
  unset VIMRUNTIME
fi

exec '/opt/homebrew/Cellar/neovim/0.9.5/bin/nvim' --headless --cmd "let g:firenvim_config={'globalSettings':{},'localSettings':{'.*':{}}}|let g:firenvim_i=[]|let g:firenvim_o=[]|let g:Firenvim_oi={i,d,e->add(g:firenvim_i,d)}|let g:Firenvim_oo={t->[chansend(2,t)]+add(g:firenvim_o,t)}|let g:firenvim_c=stdioopen({'on_stdin':{i,d,e->g:Firenvim_oi(i,d,e)},'on_print':{t->g:Firenvim_oo(t)}})" --cmd 'let g:started_by_firenvim = v:true' -c 'try|call firenvim#run()|catch /Unknown function/|call chansend(g:firenvim_c,["f\n\n\n"..json_encode({"messages":["Your plugin manager did not load the Firenvim plugin for neovim."],"version":"0.0.0"})])|call chansend(2,["Firenvim not in runtime path. &rtp="..&rtp])|qall!|catch|call chansend(g:firenvim_c,["l\n\n\n"..json_encode({"messages": ["Something went wrong when running firenvim. See troubleshooting guide."],"version":"0.0.0"})])|call chansend(2,[v:exception])|qall!|endtry'
```

**Comment by glacambre** [comment]
@benlieb I fixed a problem on master a few minutes ago, could you upgrade your firenvim plugin for neovim, run `firenvim#install()` again and then let me know if your problem is fixed?
