### ISSUE TITLE
Is there a way to have Google Apps Script autocomplete?

### ISSUE THREAD

**Issue by joshuadanpeterson** [glacambre/firenvim#1610]
I'm using Firenvim in the Google Apps Script editor, and while my autocomplete gives me JavaScript syntax, it's sorely lacking with Google Apps Script. Is there a way to set up Firenvim so that way it autocompletes with Apps Script syntax? I've been racking my brain and can't seem to find a good solution. I was thinking clasp, but that seems to be project specific.

**Comment by glacambre** [comment]
I think the simplest option might be to use a typescript language server and to make it load the type definitions for google-apps-script ( https://www.npmjs.com/package/@types/google-apps-script ). How exactly to do this will depend on what LSP plugin/server you use though, so I can't really provide instructions

**Comment by alerque** [comment]
In case this is news: This is no different really from getting completions working in NeoVIM itself. It might be easier to play around with getting completions working in NeoVIM first, then the only thing you have to work out with Firenvim is getting the filetype set correctly so the right other plugins take over.

**Comment by joshuadanpeterson** [comment]
Gotcha, thanks @glacambre @alerque - I'll try it out and report back.
