### ISSUE TITLE
"Neovim died without answering" in Chrome

### ISSUE THREAD

**Issue by craigmac** [glacambre/firenvim#1616]
I've search the issues here with this phrase, but couldn't find anything that solved this for me. I tried Firefox as well, and I get a slightly different error from the plugin, saying "Unexpect output, run nvim --headless..", which I tried and then reloaded the plugin, nothing seems to happen or be output on stdout.

## Setup

- OS Version: `macOS Sonoma 14.5`
- Browser Version: `Chrome Version 125.0.6422.142 (Official Build) (arm64)`
- Browser Addon Version: `0.2.16`
- Neovim Plugin Version: `0.2.9`
- Neovim version: `v0.10.1-dev-10+g4e9864147`

### What I tried to do

```
nvim
:call firenvim#install(0)
No config detected for chromium. Skipping.
No config detected for ungoogled-chromium. Skipping.
No config detected for opera. Skipping.
No config detected for brave. Skipping.
No config detected for vivaldi. Skipping.
No config detected for chrome-dev. Skipping.
Installed native manifest for firefox.
No config detected for chrome-canary. Skipping.
Installed native manifest for chrome.
No config detected for edge. Skipping.
```

I ran through [Troubleshooting](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md) but couldn't get it to work. Here are my notes:

- Not using flatpak/snap
- `:call firenvim#install(0)` seems to have worked correctly (check output above)
- ran `echo 'abcde{}' | ${XDG_DATA_HOME:-${HOME}/.local/share}/firenvim/firenvim` which gave me:

```text
Error detected while processing function OnStdin[30]..WriteStdout:
line    6:
E714: List required0{"version": "0.2.9"}
```

That one doesn't seem right, compared to other answers I found on here.

- contents of firenvim.json manifest for Chrome:

```json
{ "name": "firenvim", "description": "Turn your browser into a Neovim GUI.", "path": "/Users/craigmaceachern/.local/share/firenvim/firenvim", "type": "stdio", "allowed_origins": [ "chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/" ]}
```
- contents of `~/.local/share/firenvim/firenvim`:

```sh
#!/bin/sh
mkdir -p /var/folders/gq/5xbmrbld1gxd4dcqlc0x3xwr0000gp/T//firenvim
chmod 700 /var/folders/gq/5xbmrbld1gxd4dcqlc0x3xwr0000gp/T//firenvim
cd /var/folders/gq/5xbmrbld1gxd4dcqlc0x3xwr0000gp/T//firenvim
export PATH="$PATH:/Users/craigmaceachern/.local/share/nvim/rocks/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/craigmaceachern/.cargo/bin:/opt/homebrew/opt/mysql-client@5.7/bin:/Users/craigmaceachern/.composer/vendor/bin:/Users/craigmaceachern/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
unset NVIM_LISTEN_ADDRESS
if [ -n "$VIM" ] && [ ! -d "$VIM" ]; then
  unset VIM
fi
if [ -n "$VIMRUNTIME" ] && [ ! -d "$VIMRUNTIME" ]; then
  unset VIMRUNTIME
fi

exec '/usr/local/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()'
```

Hmm, I'm using rocks.nvim which uses luarocks, so could that be affecting this? It's first in the $PATH.

- checking whether extension can communicate with neovim, in Chrome, here's the console output:

```text
_generated_background_page.html:1 Uncaught (in promise) Neovim died without answering.
Promise.then (async)
updateSettings @ background.ts:159
updateSettings @ background.ts:315
(anonymous) @ background.ts:326
onMessage @ browser-polyfill.js:1

_generated_background_page.html:1 Unchecked runtime.lastError: Error when communicating with the native messaging host.
```

- nvim config files are in `~/.config/nvim`
- nvim $PATH has `/Users/craigmaceachern/.local/share/nvim/rocks/bin` prepended, otherwise it's the same as shell $PATH

### What happened

No work :( Error message says "Neovim died without answering" in Chrome.

**Comment by glacambre** [comment]
Hi, thanks for opening this issue and for going through the troubleshooting guide on your own, very appreciated :). First, could you try to upgrade your neovim plugin version to the most recent version (0.2.16)?
