### ISSUE TITLE
Odd problem.

### ISSUE THREAD

**Issue by LeaWron** [glacambre/firenvim#1618]
Add-on basically works, but my style in browser isn't same as in terminal.

- OS Version: Windows 10 Enterprise 22H2
- Browser Version: Chrome 125.0.6422.142
- Browser Addon Version: 0.2.16
- Neovim Plugin Version: 0.2.16

### What I tried to do
TroubleShooting Guide.
- firenvim script was created, but run it will be blocked. Here's the content.
```
@echo off
mkdir "C:\Users\Onlw\AppData\Local\Temp\firenvim" 2>nul
cd "C:\Users\Onlw\AppData\Local\Temp\firenvim"

 "C:\Program Files\Neovim\bin\nvim.exe" --headless --cmd "let g:firenvim_config={'globalSettings':{},'localSettings':{'.*':{}}}|let g:firenvim_i=[]|let g:firenvim_o=[]|let g:Firenvim_oi={i,d,e->add(g:firenvim_i,d)}|let g:Firenvim_oo={t->[chansend(2,t)]+add(g:firenvim_o,t)}|let g:firenvim_c=stdioopen({'on_stdin':{i,d,e->g:Firenvim_oi(i,d,e)},'on_print':{t->g:Firenvim_oo(t)}})" --cmd "let g:started_by_firenvim = v:true" -c "call firenvim#run()"
```

- console output:
```
page.ts:282 Unhandled page request: {args: {…}, funcName: Array(1)}args: args: [0]funcName: ['setLastFocusedContentScript']0: "setLastFocusedContentScript"length: 1[[Prototype]]: Array(0)[[Prototype]]: ObjectfuncName: Array(1)0: "messagePage"length: 1[[Prototype]]: Array(0)[[Prototype]]: Object
@ page.ts:282
onMessage @ browser-polyfill.js:1

page.ts:282 Unhandled page request: {args: Array(1), funcName: Array(1)}args: [0]0: 0length: 1[[Prototype]]: Array(0)funcName: Array(1)0: "setLastFocusedContentScript"length: 1[[Prototype]]: Array(0)[[Prototype]]: Object
@ page.ts:282
onMessage @ browser-polyfill.js:1

```
### What happened
It should be like:
![normal nvim](https://github.com/glacambre/firenvim/assets/152857271/75a13517-38d8-47e0-9569-631c0d48fa0d)

But it is:
![web ](https://github.com/glacambre/firenvim/assets/152857271/c373be40-4cc2-42b7-9b24-9ce3783651de)

I tried in firefox but it doesn't matter.

**Comment by glacambre** [comment]
Do `:echo $MYVIMRC` show the same result in neovim in your terminal and in firenvim?

**Comment by LeaWron** [comment]
> Do `:echo $MYVIMRC` show the same result in neovim in your terminal and in firenvim?

Yes, "C:\Users\Onlw\AppData\Local\nvim\init.lua"

**Comment by glacambre** [comment]
Does `:colorscheme` also give the same result?

**Comment by LeaWron** [comment]
> Does `:colorscheme` also give the same result?

yes

**Comment by glacambre** [comment]
Cool. What about `:echo &bg` and `:echo &termguicolors`?

**Comment by LeaWron** [comment]
> Cool. What about `:echo &bg` and `:echo &termguicolors`?

same. "light" and "1"

**Comment by glacambre** [comment]
Okay, thanks. That's surprising, I would have expected any of these options to be different so far... Could you give me the result of `:verbose hi Normal`, both from Neovim and from Firenvim?

**Comment by LeaWron** [comment]
> Okay, thanks. That's surprising, I would have expected any of these options to be different so far... Could you give me the result of `:verbose hi Normal`, both from Neovim and from Firenvim?

I find that they are same in command line.

**Comment by LeaWron** [comment]
> Okay, thanks. That's surprising, I would have expected any of these options to be different so far... Could you give me the result of `:verbose hi Normal`, both from Neovim and from Firenvim?

I find them same in command line:
nvim:
![image](https://github.com/glacambre/firenvim/assets/152857271/ebc66ea4-3633-4ee2-ac81-63e0cba5f0ba)

firenvim:
![image](https://github.com/glacambre/firenvim/assets/152857271/63697a46-51e8-4b40-9e6e-abb1563ffdf9)

**Comment by glacambre** [comment]
These are the same colors - were you complaining about having different fonts instead of different colorschemes?

**Comment by LeaWron** [comment]
> These are the same colors - were you complaining about having different fonts instead of different colorschemes?

Sry, I didn't make it clear. It's fonts' color confused me most.

**Comment by glacambre** [comment]
To change the font used by Firenvim, you need to use [`:set guifont`](https://neovim.io/doc/user/options.html#'guifont').
