### ISSUE TITLE
Expand textarea as more lines are typed

### ISSUE THREAD

**Issue by girishji** [glacambre/firenvim#1619]
When I type inside the code box of a notebook, such as on colab.research.google.com, the height of the text area dynamically adjusts, expanding as more lines are entered. This is quite convenient, as the box starts small (just one line) and grows to accommodate additional lines.

However, when I start using Firenvim within the box, it maintains a fixed height regardless of the number of new lines added. This requires manual resizing by dragging the box with the mouse. It would be great if Firenvim could automatically adjust the height of the HTML element as more text is entered, similar to the default behavior of the notebook.

I'm not sure if this is technically feasible, but I wanted to suggest it as a potential improvement.

**Comment by glacambre** [comment]
Hi, does this do what you want?
```lua
local max_height = 20
local id = vim.api.nvim_create_augroup("ExpandLinesOnTextChanged", { clear = true })
vim.api.nvim_create_autocmd({"TextChanged", "TextChangedI"}, {
    group = id,
    callback = function(ev)
      local height = vim.api.nvim_win_text_height(0, {}).all
      vim.cmd.echomsg(vim.inspect(height))
      if height > vim.o.lines and height < max_height then
        vim.o.lines = height
      end
    end
  })
```

**Comment by glacambre** [comment]
Huh, that's actually super nice to use, I wonder if this should be the default...

**Comment by girishji** [comment]
Thanks for quick response!

It almost works. I incremented line count to account for the ruler, and had to adjust the viewport (it was scrolling off first line). This is tested only on google colab.

```
            if height >= vim.o.lines and height < max_height then
                vim.o.lines = height + 1
                if height == 2 then
                    vim.cmd("norm! zb")
                end
            end            
```

The width needs to match the width of text box (it is too wide). You can look into this.

Thanks!

**Comment by girishji** [comment]
<img width="1385" alt="Screenshot 2024-06-08 at 2 11 14 PM" src="https://github.com/glacambre/firenvim/assets/16529248/8d95fc51-e006-4fbd-8777-e6c7215b8c5a">

Too wide.

**Comment by glacambre** [comment]
I don't think I'll be able to do anything about that, I'd recommend reducing the size of the frame with `:set width=60` if it's a problem :)

**Comment by girishji** [comment]
No problem, it is good enough. There is no Vim option `width` though. `textwidth` has no effect on window itself.

**Comment by glacambre** [comment]
Ah, yeah, sorry, that's `:set columns=60` :)

**Comment by girishji** [comment]
Yep, that works!

**Comment by girishji** [comment]
Leaving this info for anyone interested:

Setting `columns` from `BufRead` does not work. Something else resets it back later. You can defer the execution using `vim.defer_fn()` with say 1 millisec delay just to let Vim's typehead do other things. Or, use `WinScrolled` event to `set columns=120`. It is also a good idea to only do this to websites where neovim window is too wide.
