### ISSUE TITLE
Build failed during Lazy update

### ISSUE THREAD

**Issue by joshuadanpeterson** [glacambre/firenvim#1629]
- OS Version: macOs Sonoma 14.5
- Browser Version: Chrome Version 126.0.6478.183 (Official Build) (x86_64)
- Browser Addon Version: 0.2.16
- Neovim Plugin Version: 

### What I tried to do
I tried updating the plugin in Lazy 

### What happened
I got a build failed error message with this:

`Vim:E117: Unknown function: firenvim#install`

**Comment by glacambre** [comment]
Please provide steps to reproduce this issue from scratch, with a minimal `init.lua`.

**Comment by gnomegl** [comment]
I just installed this with Lazy as well for the first time and am experiencing the same issue.

The steps are just to test using Lazy.nvim to load the plugin. It fails during the build task with the following error:
```
Vim:E117: Unknown function: firenvim#install
```

I was able to get it working by going to `~/.local/share/nvim/lazy/firenvim` and running 
```bash
npm i && npm run build && npm run install_manifests
``` 
Now Lazy.nvim seems to be able to see that it's loaded.

Also note that when I run
```bash
echo 'abcde{}' | ${XDG_DATA_HOME:-${HOME}/.local/share}/firenvim/firenvim
```
I get this:
```
Tracking session in Session.vim{"messages": ["Tracking session in Session.vim"], "version": "0.2.16", "settings": {"localSettings": {".*": {}}, "globalSettings": {}}}Deleting session in Session.vim
```
I am using a plugin to manage my vim sessions. I don't know if that's what could be causing the install issue or not, I just thought it was worth mentioning.

**Comment by joshuadanpeterson** [comment]
Thank you @gnomegl and @glacambre! The fix you made for the installation instructions resolved the issue for me.
