### ISSUE TITLE
[Bug] Resizing textarea causes white flashes on websites with dark color-scheme

### ISSUE THREAD

**Issue by robinplace** [glacambre/firenvim#1637]
Bacause of the imperfect nature of resize observers and such, Firenvim ends up relying on iframe transparency to prevent various visual glitches. It turns out that there's a subtle sharp corner in the iframe spec that causes this to break down under certain conditions related to the `<meta name="color-scheme"/>` tag. This [blog post](https://fvsch.com/transparent-iframes) lays out the situation better than I can.

The real world impact is that on websites that use the color-scheme as part of their dark mode implementation, e.g. github, resizing textareas causes a white flash.

This could be solved either by setting a `color-scheme` `meta` tag inside the Firenvim iframe that matches that of the page or by adjusting the canvas resize process to be frame perfect. I'd be happy to implement either, though I'd like to ask a few questions of someone who knows the codebase better than I do before taking a pass.

Great extension btw!

**Comment by glacambre** [comment]
Hi, thanks for the bug report and linking to that article, it was a pretty interesting read :)

The best solution would probably indeed be to implement canvas resize to be frame perfect, but given the complexity of the resizing machinery in Firenvim, it's also the hardest approach.

I think the solution with the best result/effort ratio likely is to set the background color of the iframe's html document to the background color sent by Neovim. This will ensure that there is no user-visible boundaries, even when the user changes their colorscheme through Neovim or when their Neovim's colorscheme does not match the page's.

**Comment by glacambre** [comment]
Fixed on master, will be available once I publish a new release to the add-on stores (which is unlikely to happen soon, I think I can't upload new versions to the chrome store until Firenvim is ported to manifest v3...)
