### ISSUE TITLE
Unable to run in Firefox developer edition

### ISSUE THREAD

**Issue by husseljoo** [glacambre/firenvim#1646]
- OS Version: Arch Linux
- Browser Version: Mozilla Firefox 132.0b9
- Browser Addon Version: 0.2.16
- Neovim Plugin Version: 0.2.16

I followed the instruction and it did not work at all in firefox developer edition.
Tried disabling all other extenstions and rebinding the `Turn the currently focused element into a neovim iframe.` shortcut but no luck.
Tried the same on a regular firefox browser(Mozilla Firefox 131.0.3) in the same machine and it worked flawelessly.

Any idea how to solve this?

**Comment by glacambre** [comment]
That's rather surprising. Do you run both Firefox and Firefox Developer Edition from the same shell/terminal?

**Comment by husseljoo** [comment]
Yes I do

**Comment by glacambre** [comment]
Do you see anything about apparmor failures in `sudo dmesg`/`sudo journalctl -xe` after attempting to run Firenvim from Firefox dev edition (either by using the keyboard shortcut or just clicking on normal text areas such as Github's)

**Comment by husseljoo** [comment]
Tried both commands and apparmor related failures do not appear.
This is the only occurence of `apparmor`.

```bash
 sudo dmesg | grep -i 'apparmor'
[    4.377742] systemd[1]: systemd 256.7-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT +LIBARCHIVE)
```

**Comment by glacambre** [comment]
Could you try copying ~/.mozilla/native-messaging-hosts/firenvim.json to /usr/lib/mozilla/native-messaging-hosts/firenvim.json or /usr/lib64/mozilla/native-messaging-hosts/firenvim.json and attempting to use firenvim again?

If that doesn't work we'll have to go through the debugging tools.

**Comment by husseljoo** [comment]
Just did that and still no luck.
Btw I had to create this directory `/usr/lib64/mozilla/native-messaging-hosts/`

**Comment by glacambre** [comment]
Okay, could you go to `about:debugging`, select "This Firefox" in the column on the left, click "Inspect" on the Firenvim card? This should open the extension debugger, then you would need to go the "console" tab, and attempt to use Firenvim. Hopefully some error messages will be printed.

**Comment by husseljoo** [comment]
Hey @glacambre , it just worked now after I rebooted.
I think the `/usr/lib64/mozilla/native-messaging-hosts/` copying solved it?
Anyways, thank you for you prompt responses and for this awesome extension/plugin!
