### ISSUE TITLE
The NativeMessagingHosts/firenvim.json file is not installed for Microsoft Edge

### ISSUE THREAD

**Issue by ymattw** [glacambre/firenvim#1651]
- OS Version: macOS 15.1.1
- Browser Version: Microsoft Edge 131.0
- Browser Addon Version: 0.2.16
- Neovim Plugin Version: master (I suppose, commit 64f9389)

### What I tried to do

Followed the installation guide, installed both the extension and nvim plugin with lazy.vim:

```
  {
    "glacambre/firenvim",
    build = ":call firenvim#install(0)",
  },
```

Then opened a github issue, clicked the edit box, pressed cmd-e.

### What happened

nvim did not take over the interface.

Followed the troubleshooting guide and found out the reason is that the `firenvim.json` file is not created under

```
~/Library/Application\ Support/Microsoft\ Edge/NativeMessagingHosts/
```

I also have Chrome installed, so that file is present in
```
~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/
```

I copied it over and everything then works.

I took a glance of the `firenvim#internal_install` function, but the logic does not seem to be what I thought: it does iterate all known browsers and install the file for all of them. I have no ability to debug further so stopped looking. Maybe experts will tell easily.

Thanks for the awesome tool!

**Comment by glacambre** [comment]
Hi, thanks a lot for reporting this problem, and for beginning to look into it by yourself, knowing that the path of the your Edge config was `~/Library/Application\ Support/Microsoft\ Edge/` was necessary to fix Firenvim :)

I'm slightly surprised to see you have a different path than the one Firenvim was already using - apparently that path was the one in use [back in 2020](https://github.com/glacambre/firenvim/issues/560#issuecomment-687908028).

Finally I'm quite curious: what are your reasons for using Edge on OSX? That's probably the OS/Browser combination I would have expected the least :)

**Comment by ymattw** [comment]
Hi @glacambre, thanks for the quick response. Had to send you a one liner to really fix it :).

The new path is maybe a breaking change since some version of Edge.

Reasons I am using Edge are the nice features that Chrome and Safari do not offer: Read Aloud This Page, Ask Copilot and translate selected text.
