### ISSUE TITLE
Add a way to disable or replace the vim command line

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#167]
Using Firenvim with some text areas is obnoxious because they only give you room for a 2 or 3 line interface. I've setup my rc file so that `OnUIEnter()` in a Firevim instance sets these these:

```vim
set showtabline=0
set laststatus=0
```

That helps, but the command line is still very much in the way. I asked in the [Neovim Gitter](https://gitter.im/neovim/neovim?at=5db026ed7477946badb582ce) and it seems like there is no way to handle this from the other side, disabling the cmd line is something that happens when attaching a UI. For example here:

https://github.com/glacambre/firenvim/blob/master/src/NeovimFrame.ts#L101-104

```patch
--- a/src/NeovimFrame.ts
+++ b/src/NeovimFrame.ts
@@ -99,6 +99,7 @@ window.addEventListener("load", async () => {
     );
 
     nvim.ui_attach(cols, rows, {
+       ext_cmdline: true,
         ext_linegrid: true,
         rgb: true,
     });
```

I haven't actually compiled to test that, but the request here is to either

* Have a plugin setting that would toggle this value from the Firefox plugin side of things so that a source recompile isn't necessary and/or,
* Have some way to set this from the usual global or per-site options in `init.vim`.

~~A bonus would be to actually have some web UI overlay for using the command line when it was disabled, but the initial use case would just be to hide it visually.~~ (Opened #168 to track that larger feature request separately.)

**Comment by infokiller** [comment]
I also tried to hide the command line but didn't succeed.
I set different options in vimrc depending on the iframe size, so it would be great if I'll be able to set this from neovim as well.

In case some finds it useful, here's a relevant snippet from my vimrc:

```vim 
" Settings that are always applied for a minimal UI.
set showtabline=1
set shortmess+=F
set colorcolumn=0
set textwidth=200
set noruler
let g:ale_enabled = 0
" Settings that are used by default for a minimal UI, but get overridden if
" the window size is sufficient (see below).
set cmdheight=1
set laststatus=0
set showmode
set nocursorline
set nonumber

function! s:OnFirenvimIframeLoad() abort
  if &lines >= 10
    set laststatus=2
    set cmdheight=2
    set noshowmode
    set cursorline
    if &columns >= 10
      set number
    endif
  endif
  " Get rid of the annoying message at the bottom about the new file being
  " written, and then start insert mode.
  call feedkeys("\<C-L>", 'n')
endfunction
```

**Comment by matheusfillipe** [comment]
I just found out that I have this problem only on the github page even on my default profile. On an empty profile I don't have the issue, firevim works normally!
