### ISSUE TITLE
Can't install the plugin on 0.5.0-dev version.

### ISSUE THREAD

**Issue by damani42** [glacambre/firenvim#175]
- OS Version: Fedora 30
- Browser Version: 69.0
- What I tried to do: Install the plugin on neovim with vim-plug
- What happened: Post-update hook for firenvim ... Vim(if):E728: Using a Dictionary as a Number
- What I expected: To install it

I use the nightly repository for fedora to install neovim.

**Comment by alerque** [comment]
What Neovim version exactly do you have at the moment?

**Comment by damani42** [comment]
Actually I have the same error with neovim 0.4.2.

**Comment by damani42** [comment]
More information about neovim:

```sh
NVIM v0.4.2
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/hobbestigrou/neovim-0.4.2/build/config -I/home/hobbestigrou/neovim-0.4.2/src -I/home/hobbestigrou/neovim-0.4.2/.deps/usr/include -I/usr/include -I/home/hobbestigrou/neovim-0.4.2/build/src/nvim/auto -I/home/hobbestigrou/neovim-0.4.2/build/include
Compiled by root@dhcp-208-101.arn.redhat.com

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by kdheepak** [comment]
I have the same issue on my Mac.

```
$ nvim --version
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by kdheepak** [comment]
I believe the problem is because of these lines:

https://github.com/glacambre/firenvim/blob/master/autoload/firenvim.vim#L240-L245

If I remove them I no longer get the error. I'm not sure what the fix should be though, I'm very new to lua and my skills right now are limited to deleting lines :)

**Comment by kdheepak** [comment]
Works like a charm once I do that! :)


![Screen Shot 2019-10-25 at 9 45 17 AM](https://user-images.githubusercontent.com/1813121/67585271-6bb1e680-f70c-11e9-83ef-7cd61cb677fa.png)

**Comment by damani42** [comment]
So you remove these lines before install it the plugin?

**Comment by kdheepak** [comment]
I ended up creating a fork and deleted the lines there.

https://github.com/kdheepak/firenvim/commit/6cef0d3bfeeb0683e49f54e80d928dc36ae87b16

But you can probably edit the file directly though:

```
vim ~/.local/share/nvim/plugged/firenvim/autoload/firenvim.vim
```

and type `:call firenvim#install(0)` and hit enter after restarting neovim.

**Comment by glacambre** [comment]
I can't reproduce this issue on nvim0.4.2 + vim-plug eee50c5. Could you try the following steps and let me know if the bug still happens?
```
mkdir /tmp/plugged
curl -fLo /tmp/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim -u NORC
:source /tmp/plug.vim
:call plug#begin('/tmp/plugged')
:Plug 'glacambre/firenvim', { 'do': function('firenvim#install') }
:call plug#end()
:PlugInstall
```

**Comment by kdheepak** [comment]
Yeah I should have tried NORC, I didn't consider that it might be another plugin causing this. I'll test when I'm back at my computer.

**Comment by damani42** [comment]
Sorry for me that works now. After I have remove and install again neovim.

**Comment by JustinHoyt** [comment]
I also get the same error on MacOS Catalina, firefox 70.0.1, and Neovim 0.4.2

**Comment by glacambre** [comment]
@JustinHoyt Have you tried the steps I described in https://github.com/glacambre/firenvim/issues/175#issuecomment-546589110 ?

**Comment by masaeedu** [comment]
Hi @glacambre. I still end up getting the same error with the steps you provided:

![image](https://user-images.githubusercontent.com/3674056/69183164-79c30f00-0ae0-11ea-977d-71662eb66d1e.png)


FWIW my neovim is installed using the Nix package manager.

**Comment by glacambre** [comment]
@masaeedu Thanks for trying these steps out. Could you try to replace `{ 'do': function('firenvim#install') }` with `{ 'do': { _ -> firenvim#install(0) } }` and see if it changes anything? I'm thinking this bug might be caused by vim-plug inconsistently passing an object to `firenvim#install`.

**Comment by masaeedu** [comment]
Yup, that seems to have done it!

**Comment by glacambre** [comment]
Thanks for reporting back :)
