### ISSUE TITLE
Does not work in https://outlook.office365.com/mail

### ISSUE THREAD

**Issue by kdheepak** [glacambre/firenvim#176]
- OS Version: MacOS 10.12.6
- Browser Version: Firefox 70.0
- What I tried to do: Run firenvim in mail.outlook.com
- What happened: It did not trigger firenvim
- What I expected: I was expecting the extension to trigger neovim in any place I can enter text

It turns out mail.outlook.com uses `div` html tags instead of `textarea` html tags for user input. I'm assuming this is why it does not work.

![Screen Shot 2019-10-25 at 9 54 30 AM](https://user-images.githubusercontent.com/1813121/67586358-ad439100-f70e-11e9-9007-26410c0b1630.png)

This might be a big ask to getting this to work. I wanted to check if there was a quick fix or easy hack that you can add that allows users to set the element name or id or match some selector to choose which tags trigger nvim?

Awesome plugin btw!

**Comment by alerque** [comment]
That input field is a `contentEditable` not a text area, which is rather a different kettle of fish. If they don't have a plain text input mode this will be a somewhat difficult feature. See also #137 which is essentially the same issue.

**Comment by kdheepak** [comment]
Thanks for the quick reply! I'll look into it!

**Comment by alexriedl** [comment]
The solution used for #137 works the same for outlook, and has the same limitations.

**Comment by glacambre** [comment]
Outlook should now work automatically if you're building from source. There's still a small annoying bug with the page retaining focus after the neovim frame is created so I opened #178 to keep track of it.

**Comment by kdheepak** [comment]
Awesome!
