### ISSUE TITLE
Weird scrolling up to the one-line height effect

### ISSUE THREAD

**Issue by mcepl** [glacambre/firenvim#18]
Using firenvim from 9c810f0 with Firefox 67 from openSUSE/Tumbleweed package is rather flawless on Github, somehow manageable on Reddit (it doesn't activate every time), but complete disaster on Bugzilla.

When I click on "Reply" link, I get this:

![screencast](https://user-images.githubusercontent.com/198999/59147743-991d2280-89ff-11e9-8d31-da8162333ad7.gif)

What looks like nvim frame scrolls up over the actuall ``<textarea>`` just to the one line height, which is really hard to use.

**Comment by glacambre** [comment]
Hi. I don't have access to opensuse's bugzilla and couldn't reproduce this bug on GCC/Mozilla's bugzillas so I made an attempt at being a little less dumb about resizing the iframe but I can't test whether this actually fixed this bug or not. Could you try building Firenvim again and telling me if the problem persists?

**Comment by mcepl** [comment]
No change whatsoever (and yes, I made sure ``/home/matej/.local/share/firenvim/firenvim`` is new, and I have restarted Firefox).

**Comment by glacambre** [comment]
I think I fixed this in c67cd67. I'll reopen this until I publish a new version on addons.mozilla.org. I'll publish a new version when neovim 0.4.0 is released as new firenvim versions rely on new neovim apis.

**Comment by mcepl** [comment]
Something’s weird about upgrade from the previous version (I had to remove ``target/`` directory, ``~/.mozilla/native-messaging-hosts/*``, and ``~/.local/share/firenvim/`` manually) but with the build of the latest neovim from HEAD, I get it finally working. Thank you.

**Comment by mcepl** [comment]
Two more issues:

 1. When I open new comment on this page, I get always error "``Odkládací soubor "/tmp/github.com_glacambre-firenvim-issues-18_new-comment-field.txt.sw" již existuje!``" (that’s "Swapfile <name> already exists.") Firenvim should either clean up after itself (preferably), or use some random string in the filename of the swap file.

 2. I haven’t found explicitly in ``README.md``, that this repository should be installed as a neovim plugin. Kind of obvious, but it should be mentioned.

 3. Vibration is back. https://mcepl.fedorapeople.org/tmp/screencast_21-07-19_20_03_52.webm

**Comment by mcepl** [comment]
And yes, problem with bugzilla seems to be resolved. Thank you.

**Comment by glacambre** [comment]
Thanks for testing this. I must warn you, I found a bug (likely caused by a race condition) that sometimes prevents firenvim from writing the content of buffers back to the browser's text area. You can know in advance if this is happening by running `:au BufWrite` and checking if there's a firenvim autocommand. I'm having a hard time fixing it.
The swap file problem might be caused by the same bug.

**Comment by mcepl** [comment]
I am perfectly aware this is very unfinished developing project. Don’t worry about that. I don’t plan to write my novel via the web form any time soon.

**Comment by mcepl** [comment]
Complete report of the ``npm audit fix``:

```
firenvim (master)$ npm audit fix
npm WARN deprecated require-uncached@2.0.0: Renamed to `import-fresh`.
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated 
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated js-select@0.6.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> core-js@2.6.9 postinstall /home/matej/archiv/knihovna/repos/firenvim/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN Firenvim@0.1.5 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ web-ext@3.1.1
added 232 packages from 134 contributors, removed 38 packages, updated 71 packages and moved 13 packages in 148.7s
fixed 128 of 128 vulnerabilities in 10377 scanned packages
```

**Comment by glacambre** [comment]
I published a new version which changes the way resizing is handled, could you update to V0.1.14 and let me know if the firenvim frame still shakes?

**Comment by mcepl** [comment]
Confirmed. I haven’t seen this one in ages.
