### ISSUE TITLE
Is it working with gmail? 

### ISSUE THREAD

**Issue by blasco** [glacambre/firenvim#184]
It works perfectly fine here in github but it doesn't seem to be working in gmail.
Do I need to do anything extra in order to make it work with gmail?

**Comment by alerque** [comment]
Please see issue #137.

**Comment by glacambre** [comment]
Gmail will work by default in the next release. In the meantime, you can add https://github.com/glacambre/firenvim/issues/137#issuecomment-544641406 to your config in order to make it work.

I'll close this issue but if you have more questions, feel free to reopen it :)
