### ISSUE TITLE
Allow suspending of firenvim client (eg ctrl+z)

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#195]
Often I find myself needing to access the text box underlying firenvim, for example to access text formatting or completion in the underlying editor, or because firenvim/nvim is bugging out.

It would be brilliant to be able to ctrl+z a session in a text box, to be resumed the next time that box was activated. This would save having to wait the startup time for nvim, and mean any custom settings for that session didn't have to be re-entered.

**Comment by glacambre** [comment]
This is an excellent idea.

I'm also interested in your reasons for closing the neovim frame: is there anything firenvim could do to make this unnecessary? For example, firenvim could grab the content of the page and send it to whatever completion engine you use, would that help? What text formatting information is available in the underlying text editor but not in the neovim frame?

**Comment by alerque** [comment]
I don't know about @BlueDrink9 but the most common use case for me is using the web page's built int completion for things like usernames, e.g. here on Github completing @glacambre requires dropping back to the Github editor.

**Comment by justinmk** [comment]
> be able to ctrl+z a session in a text box, to be resumed the next time that box was activated.

Perhaps ctrl-z could resume the Nvim session also. So it works like a toggle.

**Comment by BlueDrink9** [comment]
Yes, alerque's example applies. Other use cases are completion from other cells in jupyter notebooks, and formatting in email client boxes (eg bold, hyperlink) where markdown isn't permitted), and highlighting, for example jupyter or something like grammerly/hemmingway's online editor etc

**Comment by BlueDrink9** [comment]
Being able to grab the underlying completion would be awesome though. I'd like to note that it'd have to be added to an existing completion source unless using a completion engine, since the omnifunc might already be added by something else

**Comment by infokiller** [comment]
> Yes, alerque's example applies. Other use cases are completion from other cells in jupyter notebooks, and formatting in email client boxes (eg bold, hyperlink) where markdown isn't permitted), and highlighting, for example jupyter or something like grammerly/hemmingway's online editor etc

Using `Ctrl-z` for this can be problematic because it will conflict with undo.

**Comment by BlueDrink9** [comment]
`Ctrl+z` only maps to undo if you source the windows mapping plugin (to the best of my knowledge). The canonical way to undo is with `u`. `ctrl+z` is the canonical way to suspend vim.

**Comment by glacambre** [comment]
This doesn't matter much - if this feature is implemented, the keybinding to which it is bound must be configurable.

**Comment by infokiller** [comment]
@BlueDrink9 I was referring to making it a toggle switch like was suggested, which means it will be typed like regular text in the browser.
BTW, `Ctrl+z` in terminal vim works because the terminal usually sends SIGTSTP to the foreground process.

**Comment by justinmk** [comment]
> BTW, `Ctrl+z` in terminal vim works because the terminal usually sends SIGTSTP to the foreground process.

Not true, though often assumed. Vim handles ctrl-z directly, it doesn't run in "cooked mode".

**Comment by infokiller** [comment]
Can you please elaborate? What do you mean by "cooked mode"?

**Comment by justinmk** [comment]
https://www.google.com/search?q=tty+cooked+mode

**Comment by infokiller** [comment]
Thanks! so how does `Ctrl-Z` actually ends up suspending the process, if the terminal is not involved in this?

**Comment by justinmk** [comment]
The process suspends itself.... that is, if you haven't remapped ctrl-z :)

**Comment by BlueDrink9** [comment]
@glacambre I see you've added a command to focus the input, which for now I've mapped to <c-z>. If you added a command to hide/unhide the firenvim frame, I think this could be closed.

**Comment by glacambre** [comment]
Implemented in #296. `:call firenvim#hide_frame()` will make the frame disappear. You can make the neovim frame reappear either by unfocusing and refocusing the textarea or by [manually triggering firenvim](https://github.com/glacambre/firenvim#manually-triggering-firenvim) while the element is focused.

I just realized that I forgot to properly document this feature, so I'll do that soon.

I'll publish a new release on monday :)
