### ISSUE TITLE
Fail gracefully if neovim doesn't start up without errors

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#196]
If there is a bug in my nvimrc somewhere that causes an error message (resulting in some sort of "push enter to continue" message, I assume), firenvim puts a blank box over the textbox. This not only prevents me from using *firenvim*, but from editing text in that box full stop - unless I reload the page, losing any filled textboxes.

Would it be possible to check for any error messages on startup that would halt firenvim, and release the box?

**Comment by glacambre** [comment]
Can reproduce - it's true that it's pretty annoying. I'm not sure I will be able to retrieve error messages for windows but I should be able to do something for linux and osx.
