### ISSUE TITLE
Permit setting firenvim to use `--remote` instead of starting a new neovim instance

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#197]
Could a way of [using nvr](https://github.com/mhinz/neovim-remote) be set up, so that each new firenvim instance connects to an existing neovim process rather than having to start up a new instance?

Neovim isn't always instant to start, especially if configured for more ide-like editing. I'm very pleased that I can use vim to edit jupyter notebooks properly now - but starting a new editor instance every time I click a box is painful. Connecting to a server would salve this.

**Comment by glacambre** [comment]
Yes, it should be possible to implement something like `--remote`, this would just require you to do something like `call firenvim#start_server({...})` if you want to start the neovim server yourself instead of having firenvim start it.

I'm disappointed to hear that startup is slow for you though and this is something I will fix regardless of whether and when `--remote` is implemented.

**Comment by glacambre** [comment]
Work has started in the [impl_single_server branch](https://github.com/glacambre/firenvim/tree/impl_single_server) and is blocked by https://github.com/neovim/neovim/issues/11646.

**Comment by glacambre** [comment]
Now blocked by https://github.com/neovim/neovim/issues/3338.

**Comment by NilsIrl** [comment]
https://github.com/neovim/neovim/pull/11331 was merged. Closing https://github.com/neovim/neovim/issue/3338

**Comment by glacambre** [comment]
Now implemented on master, either build from source or wait for a new release. See [this section of the readme](https://github.com/glacambre/firenvim#using-a-single-neovim-instance) to learn how to use it :).

**Comment by NilsIrl** [comment]
Does it require neovim built from https://github.com/neovim/neovim/pull/11821 at least?

**Comment by glacambre** [comment]
Yep, that's what I mean by "this requires a Neovim compiled at commit a2efc9c or more recent." :)

**Comment by NilsIrl** [comment]
> Yep, that's what I mean by "this requires a Neovim compiled at commit a2efc9c or more recent." :)

idk why, the way I read it I wasn't sure if this was referring to firenvim or nvim.

Anyway, as long as you're not using the persistent server, you're fine right?

**Comment by glacambre** [comment]
>Anyway, as long as you're not using the persistent server, you're fine right?

Yep, should be (except for #428 - which I intend to fix ASAP).
