### ISSUE TITLE
Can't type Japanese

### ISSUE THREAD

**Issue by Inazuma110** [glacambre/firenvim#200]
- OS Version: Ubuntu 18.04
- Browser Version: Firefox 70.0
- What I tried to do: I tried to type "あいうえお" (This is Japanese) 
- What happened: 
Please show this gif. This is my Nvim in firefox.
I type "aiueo" on keyboard. I want to display "あいうえお". But display "あ".
Maybe, Firenvim display only first charactor.

![Peek 2019-11-04 01-54](https://user-images.githubusercontent.com/31335755/68088857-6724c500-fea6-11e9-9ad0-0421f63ab199.gif)

I'm not good at English. Sorry for my poor English:bow:

**Comment by glacambre** [comment]
Thank you for reporting this issue. I believe I fixed it in #200, I'll publish a new release on the mozilla and chrome webstores soon.

Your english is fine by the way :)

**Comment by Inazuma110** [comment]
Thank you!! I look forward to new release!!

**Comment by glacambre** [comment]
Hi, I pushed a new release a few days ago, could you update Firenvim and let me know if everything works as expected?

**Comment by Inazuma110** [comment]
I updated. And I was able to type Japanese!!
However, it appears a little late.
![jap](https://user-images.githubusercontent.com/31335755/68832752-207c6980-06f5-11ea-9381-ba7b24754f70.gif)

However, I'm already satisfied :)
