### ISSUE TITLE
Iframe automatically created on disabled websites after manually creating it once

### ISSUE THREAD

**Issue by pierpo** [glacambre/firenvim#203]
Hi! Thanks for the amazing extension, this is a brilliant idea.

My concern: I do not want Neovim to run in all text areas.

My question: would it be possible to not trigger Firenvim automatically but only when I press a shortcut? That's wasavi's behaviour and it makes it super flexible.

Example: I focus my Github issue text area. For now, the text area is the default one. Then I press `CTRL-\` and it opens up Neovim.

Thanks 😉

**Comment by glacambre** [comment]
This can already be done by configuring firenvim to not trigger on any websites (see https://github.com/glacambre/firenvim#configuring-the-browser-addon-behavior) and then using `<C-e>` to selectively open a firenvim frame. You can replace `<C-e>` with `<C-\>` in `about://addons` or `chrome://extensions`.

I'm closing this issue but feel free to reopen/let me know if you need more clarifications :)

**Comment by pierpo** [comment]
Thank you for your very quick answer :blush:
I hadn't understood that disabling it would make it still usable with `<C-e>`. Makes sense!
Maybe it could be better documented or explicit, I guess I won't be the last one encountering this issue :wink: 

One step remains unclear though... I don't understand where you customize the shortcut in the `chrome://extensions` menu?

Couldn't find it in Firefox either.

![firenvim-settings](https://user-images.githubusercontent.com/6313316/68167626-65223b00-ff66-11e9-8627-748a39559c25.png)

Thank you!

**Comment by pierpo** [comment]
![firenvim-shortcut-setting](https://user-images.githubusercontent.com/6313316/68168046-db736d00-ff67-11e9-8ac0-1fdec6b62eac.png)

Got it! I didn't even know this page existed :smile: 

Maybe the doc could be more explicit about it...? :thinking: 

Thanks!

**Comment by pierpo** [comment]
**One problem remains:** if I activate the extension with `<C-e>` on the current text area and save+quit the buffer with `:wq`, then coming back will automatically trigger firenvim again!

Is that normal?

**Comment by glacambre** [comment]
Regarding the docs, could you submit a PR to better explain the parts you failed to understand? I'm having a hard time finding the right words.

**Comment by pierpo** [comment]
> Regarding the docs, could you submit a PR to better explain the parts you did not understand? I'm having a hard time finding the right words.

Sure :)

Any idea about the new problem I'm mentioning?

**Comment by glacambre** [comment]
Could you test #206 and see if the frame still reappears after you running `:wq`?

**Comment by alerque** [comment]
The relevant PR is #207 not 206.

**Comment by pierpo** [comment]
I tried it out, but that didn't fix it for me. Does it work for you?

**Comment by glacambre** [comment]
Works for me but it breaks other features so I'll need to keep working on it. Thanks for trying it out. I might ask your help again once I believe I'm done :)

**Comment by pierpo** [comment]
Thank you for the quickness of your reaction 😊 

I'll try it out more thoroughly when I have more time. Maybe I didn't build it properly, who knows.

Thanks for your help!

**Comment by pierpo** [comment]
Just tried it out. It works perfectly now, thanks :blush:
