### ISSUE TITLE
v0.1.12 does not exist on chrome web store

### ISSUE THREAD

**Issue by cappyzawa** [glacambre/firenvim#204]
[Release v0\.1\.12 glacambre/firenvim](https://github.com/glacambre/firenvim/releases/tag/v0.1.12) does not exist on [Firenvim \- Chrome Web Store](https://chrome.google.com/webstore/detail/firenvim/egpjdkipkomnmjhjmdamaniclmdlobbo).

Could you upload v0.1.12 to there, please:pray:

**Comment by glacambre** [comment]
I did upload it - about 24 hours ago. It's under review and will be available once Google decides that it's fine.

**Comment by cappyzawa** [comment]
@glacambre I see. Thanks! 
I'm looking forward it will be available.

**Comment by cappyzawa** [comment]
update
v0.1.12 is available on [Firenvim \- Chrome Web Store](https://chrome.google.com/webstore/detail/firenvim/egpjdkipkomnmjhjmdamaniclmdlobbo) 👍

**Comment by glacambre** [comment]
Thanks for letting me know ! :)
