### ISSUE TITLE
Option to pass "-u" argument when creating nvim instance

### ISSUE THREAD

**Issue by 3rdey3** [glacambre/firenvim#205]
I have a simpler vimrc file that I use when I need nvim for some light editing. For that purpose I start nvim by `nvim -u litevimrc`.

I would like firenvim to use this litevimrc file. Is this feature already available? If not, can this feature be added?

**Comment by alerque** [comment]
This would be an interesting option to have for sure. I'm not sure I would use it though, and I'm actually curious why you would.

One of the reasons I love Firenvim is that I spend so much time in my editor than having exactly the same configuration available wherever I am editing is a great thing. My `init.vim` file already loads plugins selectively based on filetype and sets options depending on it's environment (inside `tmux`? inside Firenvim? nvim-gtk? local or ssh?) and using the `UIEnter` event I further customize it a little for Firenvim.

I'm sure many people would get some mileage out of being able to specify different inits altogether ... but given that you can already selectively load plugins and do other things in the init based on environment, why would you prefer having a completely separate init?

**Comment by 3rdey3** [comment]
Well, the simple answer to you question would be that I am not much of an expert in configuring my `init.vim` file like that (I still consider myself a novice and most of my configuration is copy pasted from internet). So making a separate vimrc file seemed a easier path for me. Also some of the pluggins (i.e. airline, ctrlp) are overkill when I am using nvim to edit a single buffer/file.

**Comment by justinmk** [comment]
> using the `UIEnter` event I further customize it a little for Firenvim.

Yes, users should decide "heavy" or "light" configurations by handling `UIEnter` or otherwise detecting the type of connected UI. There's no need for firenvim to add a separate capability for sending `-u`.

**Comment by 3rdey3** [comment]
I ended up editing `firenvim.bat` file and adding the `-u` option manually. This will do for now.

However, can anyone share there `vimrc/ini.vim` file which uses `UIEnter` to handle "heavy" or "light" issue?

**Comment by justinmk** [comment]
sorry, I retract.  `UIEnter` fires after `VimEnter` (after init.vim is done), so that doesn't help this use-case. For this use-case it may make sense to set a `g:foo` variable when invoking `nvim` from firenvim:

    nvim -c "let g:firenvim=1" --embed ...
