### ISSUE TITLE
load settings from a .firenvimrc

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#21]

**Comment by mcepl** [comment]
Not ``~/.firenvimrc`` please. Either ``~/.config/firenvim/something`` or ``~/.config/nvim/firenvim/init.vim`` or even better with ``if has("firenvim")`` add all configuration to the main ``$VIMRC``.

**Comment by glacambre** [comment]
Yeah, I dislike files cluttering my $HOME too. I'll make sure to respect $XDG environment variables :).

I'm not sure about having everything in a $VIMRC as firenvim might end up with a lot of settings. I'll think about it :)

**Comment by mcepl** [comment]
Well, you can split ``$VIMRC`` and use ``source filename``, if you need to organize your vimrc into multiple files.

**Comment by glacambre** [comment]
I decided to go with your suggestion and now you need to create a `g:firenvim_config` object in your init.vim if you want to configure how firenvim behaves. I described how to configure firenvim [here](https://github.com/glacambre/firenvim).
The settings you might have created in `about:addons` will be lost on upgrade (because I don't feel like editing people's init.vim) so be sure to back them up before upgrading :).
