### ISSUE TITLE
Timeout seems too short.

### ISSUE THREAD

**Issue by satoryu** [glacambre/firenvim#213]
- OS Version: MacOS X 10.14.6
- Browser Version: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
- What I tried to do: 
  - Completed all install instructions. 
- What happened: firenvim says "Neovim is not responding'"

In order to use firenvim, firenvim says "Neovim is not responding" when clicking "realod neovim" button. 
Launching neovim with my configuration takes about 5 sec. 
But `background.ts` says the error when launching nvim over 1 sec. 
By adding `--noplugin` option to nvim command in `~/.local/share/firenvim/firenvim`, firenvim came to work.

**Comment by alerque** [comment]
This should probably be configurable, but...

You might want to consider the possibility that your vim configuration is actually broken. It shouldn't take 5 seconds. I suspect you have some plugin that is misbehaving or somehow miss-configured.

My own configuration loads 98 plugins, has 968 lines of rc code which also sources other scripts for specific functions. I'm using an 8 year old budget computer, and the startup time for me is somewhere considerably south of one second. If I had to guess I'd put it in the 300-600 ms range.

Again I'm not saying Firenvim can't adjust this, but I would take a serious look at what plugin manager you are using, whether it is properly loading things on demand, and whether or not you have some actively misbehaving code in your startup somewhere.

**Comment by satoryu** [comment]
Thank you for your prompt reply! 
The plugin manager I'm using is [dein](https://github.com/Shougo/dein.vim). 
It's time for me to review my vim configuration :)

**Comment by alerque** [comment]
See also issue #205 which is related, but applies more to the actual editor experience than just the load time issue.

**Comment by glacambre** [comment]
My init.vim is about as big as @alerque's and I use dein, neovim starts in about ~200ms for me, so I'd agree that there's something wrong with your init.vim. You can diagnose your startup times with `nvim --startuptime /tmp/startupfile -c 'q' && cat /tmp/startupfile`.

However, I would also agree that the timeout is probably too short. An HDD, high load and cold filesystem caches could probably bring neovim's startup time to more than 1000 milliseconds. I'll bump it to 10000. Thanks for reporting this issue :)

**Comment by glacambre** [comment]
Closed in 6beec96.

**Comment by satoryu** [comment]
@glacambre Thanks!
