### ISSUE TITLE
Turn the native messenger into a neovim plugin

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#22]
This should be fairly easy to do:
- Have a :FirenvimInstall command that creates a {power,}shell script in ~/.local/share/firenvim and puts the native manifest in ~/.mozilla/native-messaging-hosts
- On launch, have the neovim plugin open a tcp port (https://github.com/neovim/neovim/issues/10084) and generate a security token, then send token+port number to firefox with stdioopen() 
- Have the webextension open a websocket, send the token to the neovim plugin and then use regular msgpack-rpc messages until end of connection

This is probably going to make starting a new firenvim frame rather slow - we might want to instantiate one neovim process in the background in order to speed things up.

**Comment by glacambre** [comment]
This seems to work on windows and linux. Just need to wait for nvim 4.0 to become stable before releasing an updated version on amo.
https://github.com/neovim/neovim/milestone/21

**Comment by mcepl** [comment]
Something’s weird about upgrade from the previous version (I had to remove ``target/`` directory, ``~/.mozilla/native-messaging-hosts/*``, and ``~/.local/share/firenvim/`` manually) but with the build of the latest neovim from HEAD, I get it finally working. Thank you.
