### ISSUE TITLE
airline bugging out/dissapearing when scrolling

### ISSUE THREAD

**Issue by JonatanSiden** [glacambre/firenvim#226]
Hi,

I've noticed that the airline is bugging out/dissapearing when scrolling until you are inserting something again - then the airline appears again.

Do you know a fix for this issue in firenvim?

I love this plugin!

https://giphy.com/gifs/TfXVKjQmMzPUoVBt8m

**Comment by glacambre** [comment]
This looks like a firenvim rendering issue, not sure what's going on here. Might take me a while to fix.

**Comment by JonatanSiden** [comment]
> This looks like a firenvim rendering issue, not sure what's going on here. Might take me a while to fix.

Yes it looks like it, would be awsome to get fixed. Understandable that it might take time to fix, no worries. Thanks!
