### ISSUE TITLE
Firenvim not loading on latest Firefox nightly

### ISSUE THREAD

**Issue by ahal** [glacambre/firenvim#233]
- OS Version: Linux (Fedora 31)
- Browser Version: Firefox Nightly 72.0a1 (2019-11-15)
- Firenvim extension: 0.1.13
- What I tried to do: Click a textarea
- What happened: Firenvim fails to load (white box flashes quickly, then textarea loses focus). Upon double clicking, can edit text area normally (no firenvim).

Content console contains:
```
Firefox can’t establish a connection to the server at ws://127.0.0.1:37195/585407150. Neovim.ts:17:19
Port disconnected for element #content-input. Neovim.ts:23:16
```

Browser console contains:
```
Promise resolved after context unloaded        nvimui.js:6148
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] 3 network-response-listener.js:84
Promise resolved after context unloaded    nvimui.js:6148
```

I had actually just installed Firenvim today, and it was working great. Then updated to today's nightly and it stopped working. I also work at Mozilla so if this is an issue on Firefox's end, I can help raise it.

**Comment by glacambre** [comment]
Thanks for reporting this. The problem is that the `Origin` key of the websocket header isn't present so the neovim process cannot verify that the websocket has been made from the firenvim webextension and not another extension/website.
I consider this a firefox bug and opened https://bugzilla.mozilla.org/show_bug.cgi?id=1596889. Let's hope it'll get fixed faster than the other bugs I reported :).

**Comment by ahal** [comment]
Unfortunately it looks like it may have been intentionally removed to help prevent fingerprinting. We'll see what Tom says, but this might end up needing an alternative workaround.

**Comment by glacambre** [comment]
Discussion now happening in https://bugzilla.mozilla.org/show_bug.cgi?id=1592721 .

**Comment by ahal** [comment]
Just noting the change that caused this failure was backed out, so Firenvim is temporarily working on Nightly again (until it re-lands).
