### ISSUE TITLE
iframe size gets out of sync with original textarea

### ISSUE THREAD

**Issue by infokiller** [glacambre/firenvim#237]
- OS Version: `Linux desk18 5.3.11`
- Browser Version: `Chromium	78.0.3904.97 (Official Build) Arch Linux (64-bit)`
- What I tried to do:
    - Install latest firenvim from master (#7fa7139)
    - Start editing a textarea, for example [the left one here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea)
    - Resize the window so that the original textarea changes size
- What happened:
    - The original textarea size was changed, but the neovim iframe did not

I use an empty init.vim that only adds the plugin path to `rtp`.

Screenshot:
![image](https://user-images.githubusercontent.com/10516814/69001016-8c6ef580-08e0-11ea-9fb2-20e34fe319e5.png)

**Comment by glacambre** [comment]
Quite amusingly I pushed a commit (1c7217e) that should fix this a few hours before you opened this issue :smile: . I can't reproduce this bug now, can you test 1c7217e and let me know if this is fixed for you too?

**Comment by infokiller** [comment]
I can still reproduce this. Not sure if it's related, but I also see this error in the extension error log:
![image](https://user-images.githubusercontent.com/10516814/69007332-25375c80-0945-11ea-8c72-fc00357d6b6f.png)

**Comment by infokiller** [comment]
OK this actually works now, I accidentally used an older version.
BTW, I still see some errors:

![image](https://user-images.githubusercontent.com/10516814/69007553-cf17e880-0947-11ea-8a98-fc249d3e1857.png)


Is this expected?
