### ISSUE TITLE
Keybinding to turn on or off firenvim completely

### ISSUE THREAD

**Issue by JonatanSiden** [glacambre/firenvim#243]
Hi,

As said before - I love this extension, it's simply amazing!

Although I love this extension/plugin - I'd like to completely shut it off using a keybinding, or rather ACTIVE it using a keybinding - that way I'm not forced to use firenvim when writing emails on my gmail. I know that the "disable in this tab" is meant to solve this issue - but I'd rather not have firenvim activated by default since it affects my work in other platforms alot and creates big problems for me - it would be really frustrating for me to deactivate firenvim for each site I'm on - I want the other way around... active firenvim for each site I want instead.

Thanks! Keep up the good work buddy, it's amazing.

Best,

J

**Comment by glacambre** [comment]
Aren't you trying to do the same thing as https://github.com/glacambre/firenvim/issues/203 ?

**Comment by JonatanSiden** [comment]
even if adding 

let g:firenvim_config = {
    \ 'localSettings': {
        \ '.*': {
            \ 'selector': '',
            \ 'priority': 0,
        \ },
        \ 'github\.com': {
            \ 'selector': 'textarea',
            \ 'priority': 1,
        \ },
    \ }
\ }

firevim is triggered for me on other sites than github (like gmail).

**Comment by glacambre** [comment]
Even after using the `reload settings` button and then reloading the page?

**Comment by JonatanSiden** [comment]
Yes, even after reloading settings, clearing cache, restarting browser

**Comment by glacambre** [comment]
Oh, I'm sorry, I completely forgot that I had added two special cases to handle outlook and gmail: https://github.com/glacambre/firenvim/blob/master/src/background.ts#L142-L153

So you'd also need to add
```
'mail.google.com': {
    \ 'selector': '',
    \ 'priority': 2,
\},
'outlook.live.com': {
    \ 'selector': '',
    \ 'priority': 2,
\}
`

To your config. I'll merge the outlook/gmail-specific stuff into `.*` when I have time.

**Comment by JonatanSiden** [comment]
Thank you so much! This works perfectly fine.

Gotta love how enthusiastic you are with this plugin. Keep up the great work! Just hoping for the swedish/european characters that require alt to write to work now, then my life is complete :) cheers man!

**Comment by glacambre** [comment]
I merged the outlook & gmail configs back into the general one, so I think I can close this issue (your keybinding issues are tracked in #225). Please let me know if there's anything I missed - I'll reopen it :)
