### ISSUE TITLE
Neovim shifts in textarea

### ISSUE THREAD

**Issue by Inazuma110** [glacambre/firenvim#249]
- OS Version: Ubuntu18.04
- Browser Version: 70.0.1
- Browser Addon Version: 0.1.14
- Neovim Plugin Version: `d0e236c`
- What I tried to do: Using neovim in textarea successfully.
- What happened:
 please look at this gif.
![shift](https://user-images.githubusercontent.com/31335755/69316099-6b5d2a80-0c7b-11ea-9d8b-af6a8ede7750.gif)

Neovim dose not display in textarea successfully.(This gif shooting range is correct.)
This image show you I tried to type 'aaaa.....aaa' and `:message`.

Previously displayed correctly. This bug may have ocurred when updating firenvim.

**Comment by glacambre** [comment]
Thank you for reporting this issue. I can't reproduce it, could you try running firenvim [without your init.vim](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-its-not-your-initvim) and see if it changes anything?

**Comment by Inazuma110** [comment]
I tried `echo 'abcde{}' | !~/.local/share/firenvim/firenvim` like [this](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-firenvim-script-has-been-created).
This result was like this image and stop Neovim.(Press \<C-c>, restart moving Neovim)
![image](https://user-images.githubusercontent.com/31335755/69329394-5ccf3d00-0c94-11ea-9b88-dcc809ef7b91.png)
Is this result as expected?

Next, I tried [this](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-its-not-your-initvim).
```diff
- exec '/home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.2_1/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()'
+ exec '/home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.2_1/bin/nvim' -u NORC  --cmd 'let g:started_by_firenvim = v:true; set rtp+=/tmp/firenvim' --headless -c 'call firenvim#run()'
```

After edit firenvim, Neovim can't start in firefox.

**Comment by glacambre** [comment]
>Is this result as expected?

I think so, this command in meant to be ran in a shell rather than in firenvim. The troubleshooting guide isn't clear enough about this, sorry. I'll fix it.

>After edit firenvim, Neovim can't start in firefox.

Could you try `exec '/home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.2_1/bin/nvim' -u NORC  --cmd 'let g:started_by_firenvim = v:true' --cmd 'set rtp+=/tmp/firenvim' --headless -c 'call firenvim#run()'` instead of using a semicolon?

The example diff seems to be outdated, I'll fix that too :)

**Comment by Inazuma110** [comment]
I tried to edit as you said. And firenvim started successfully.
Recently, I add many plugins(calendar.vim, game_engine.vim, mario.vim etc...)

I'll review my init.vim. 
Thank you :)

**Comment by glacambre** [comment]
If you find out what plugin caused this to happen, please let me know, I still consider this a firenvim bug :)

**Comment by Inazuma110** [comment]
OK, I'll report you.
Should I report in this issue's comment?

**Comment by glacambre** [comment]
Yes please.

**Comment by szbergeron** [comment]
I seem to be having the same issue here, plugin list:
```Plug 'majutsushi/tagbar'
Plug 'neoclide/coc.nvim'
Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'kristijanhusak/vim-hybrid-material'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'jordwalke/vim-reasonml'
Plug 'liuchengxu/vim-clap'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'```

Anything in there look questionable/like something that I should look into removing first?

**Comment by glacambre** [comment]
I can't reproduce your problem even by copying your config and using the latest neovim nightly. However I see a lot of duplicated lines in your config (importing `romainl/flattened` twice, importing multiple themes, multiple `:filetype plugin on` (which you probably don't need as `plug#end()` does that for you), multiple `:set tabstop` calls…) so perhaps you could try to clean it up and see if things improve. I don't think it will though.

Does using `set columns=40` change anything to your problem?

**Comment by Inazuma110** [comment]
`set guifont=Hack\ Nerd\ Font\ Regular` is cause of this bug.
Probablly, plugins are not cause.

I'm sorry to troble you. And thank you for assisting me. :)

**Comment by glacambre** [comment]
Thanks @Inazuma110! I was able to reproduce this issue and fixed it. I'll publish a new release either tomorrow or the day after :)

**Comment by Escapingbug** [comment]
I have encountered this bug once again. The problem resides in the ".nvim_cell" css, where its width has been set to "1ch", which is not enough for a single character, so it has been shifted somehow.

**Comment by glacambre** [comment]
@escapingbug Thanks for investigating and reporting. I'm going to rewrite the renderer to stop using HTML soon. This bug will hopefully disappear in the rewrite :).
