### ISSUE TITLE
Keybinding for toggling firenvim in the current tab

### ISSUE THREAD

**Issue by infokiller** [glacambre/firenvim#265]
It would be great to have the ability to toggle firenvim in a tab from a keybinding, which can currently be done by clicking on the extension icon with the mouse.

In Chromium, you can launch a website with the `--app` argument, which opens a new window without the address bar and menus. This is useful for creating a dedicated window for a web application (like gmail), which is much more efficient in terms of screen real estate than a regular window. 
Extensions still run in app mode, however, since the menus are gone, there is no way to access an extension icon.
Maybe a context menu should also be considered?

Thanks!

**Comment by glacambre** [comment]
Having a keybinding to enable/disable firenvim in a tab is a good idea but I'm curious about your use case, if you frequently need to disable firenvim in gmail, why don't use just disable it in your config?

**Comment by infokiller** [comment]
So when I first write an email I usually want to use firenvim to edit it, but then later I may want to use features in the gmail editor like formatting (bold etc.), autocomplete, and others.
In these cases, firenvim can get in my way, because every time I change focus from the editor to another UI element and then bring the focus back, firenvim starts.

**Comment by alerque** [comment]
I run into this quite a bit too. For me the ideal scenario would probably be that Firenvim starts up automatically at first, but then if I explicitly close it it would not re-activate on that textarea until told specifically to do so.

**Comment by glacambre** [comment]
I see. The best workaround for now is to disable firenvim by default and then use `<C-e>` to selectively enable it. The keybinding to disable firenvim will be pretty straightforward to implemnt but an "automatically start firenvim and don't automatically bring it back after I close it" feature might take a bit longer design and implement.

**Comment by glacambre** [comment]
A browser shortcut to disable firenvim has been implemented in 2d6bc2baa4d5f6aa26fc397d47dec48a01d120b9 and a localSetting named `takeover` that you need to set to `once` in order to prevent firenvim from reappearing on a textarea after you `:q`'d has been implemented in fdaa07daf2dd40d029b67507a1353be4ce7f8526 . I'll document these features soon and publish a new release on sunday or monday.
