### ISSUE TITLE
`add()`/`remove()` functions to make tweaking config easier

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#267]
It might be worth having `add()`/`remove()` functions so that a default array can be maintained in the plugin and config files can just tweak to users' preferences. Having users set the entire array in their rc files for something that potentially has a lot of values is starting to get messy. Per-site configs could also be shared easier if each one was self contained.

Just brainstorming here, but maybe an adder that that accepted a site, selector, and optional priority arguments, and a remover that just took the site...

```vim
" Only catch some textareas on example.com
call firenvim#add_site_config('example.com, '.class textarea')

" Disables on riot.im (no selector)
call firenvim#add_site_config('riot.im')
```

_Originally posted by @alerque in https://github.com/glacambre/firenvim/issues/264#issuecomment-558550442_

**Comment by alerque** [comment]
Optional 4th argument might be a filetype, and when set an additional autocmd would be set for BufEnter. Right now my config has one config array for setting up selectors and a list of autocmd's for the same domains setting up filetypes. This gets to be pretty redundant.

To make these functions actually easy to use there should be some way of skipping over arguments you want to leave as default but get to the later arguments.

**Comment by glacambre** [comment]
I am closing this issue because most of the discussion is happening in #269 :)
