### ISSUE TITLE
Add new Firenvim filetype & include domain-aware syntax highlighting

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#268]
I've been using setting the `markdown` filetype for _most_ sites that I use Firenvim on including ones that are not actually markdown. Whatsapp web and Slack for example have bastardized Markdown-ish syntax that isn't actually Markdown.

As I use Firenvim on more and more sites I'm starting to run into more cases where some unique filetype handling and syntax rules would be useful.

Off the top of my head my suggestion is to default all Firenvim files to a new filetype `firenvim` by default unless otherwise requested by the user (see #267 for a related improvement), and bundle a syntax file for that filetype that uses the buffer name to add per-site syntax highlighting. I would implement that by first parsing out the domain, then checking if a setup function for that domain exists and calling it if it does.

Besides being able to handle some common cases out of the box, this would provide the framework for users to override Firenvim's defaults and extend the behavior of vim on a given domain just a bit easier than it is now.

**Comment by alerque** [comment]
This should probably be more than just domain aware, there should probably be a 1→1 link between the domain + selector that matched and the rules that fire. If for some reason I have more than one selector setup for a domain that's probably because I want different behavior for each. Perhaps setting this up as an optional callback function passed to the `add()` function would work.

**Comment by justinmk** [comment]
Isn't the buffer name a hint already? And the domain can be found there too.

**Comment by alerque** [comment]
@justinmk Yes it is, technically this is already all doable using `BufEnter` and my own callbacks. I'm only suggesting a way to bundle this setup with Firenvim that is much more convenient to use for end users and has defaults for a few common domains.

**Comment by justinmk** [comment]
filetype=firenvim might make sense, although it defeats Vim's mediocre content-detection, and also would be awkward if users then override it (to get syntax highlighting or whatever) after checking for it. A buffer (`b:`) variable might be better.

> the antics to get `UIEnter` to match only Firenvim

JFI: that will be improved soon, the UI name will be included in `v:event`.

**Comment by BlueDrink9** [comment]
I'd like to comment here that I think there's a real benefit to having a bundled set of filetypes for known website buffer names. Even if it's just on the wiki, but it'd be amazing to automatically have the correct ft set on whatever website I visit, even if it's a brand new website.

**Comment by glacambre** [comment]
@BlueDrink9 Done :)

**Comment by BlueDrink9** [comment]
I can't seem to edit it, do you mind checking the settings? https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by glacambre** [comment]
Woops, sorry, done :)

**Comment by glacambre** [comment]
Closed by #483.
