### ISSUE TITLE
package.json fix?

### ISSUE THREAD

**Issue by mcepl** [glacambre/firenvim#27]
When running ``npm audit fix`` I get this change:
```diff
diff --git a/package.json b/package.json
index 763936d..3b68478 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
     "tslint": "^5.13.1",
     "tslint-sonarts": "^1.9.0",
     "typescript": "^3.3.3333",
-    "web-ext": "^3.0.0",
+    "web-ext": "^3.1.1",
     "webpack": "^4.29.6",
     "webpack-cli": "^3.2.3"
   },
```

**Comment by glacambre** [comment]
I thought I had setup dependabot to get automatic updates to my package.json. I must have done something wrong. Thanks for letting me know.

**Comment by glacambre** [comment]
I think I managed to get dependabot back up. I also set up a bot named snyk which specializes in security issues in javascript dependencies. Hopefully this is the last time my dependencies get outdated, thanks for reporting this :).
