### ISSUE TITLE
Turn off console messages

### ISSUE THREAD

**Issue by mjarkk** [glacambre/firenvim#272]
- OS Version: Arch Linux x86-64 (5.3.13-arch1-1)
- Browser Version: Chrome 78.0.3904.108  
- Browser Addon Version: 0.1.15
- Neovim Plugin Version: 0.4.3 
- What I tried to do: Developing something
- What happened: Loads of debug messages in the console

Is it possible to turn of the console debug messages or can this be changed so there are no message by default?  
When i'm working on a web applicaiton and click on a textarea there are loads of (what seem to me) debug messages in the dev console that make it somewhat for me to work on a website.

**Comment by glacambre** [comment]
Not possible yet but a very reasonable request - I'll implement that today or tomorrow :).

**Comment by glacambre** [comment]
Implemented in 816af3f6028d27ccdf62215a7449f703ae257af7 - I'll publish a new release on Sunday/Monday.

**Comment by mjarkk** [comment]
Thanks!!
