### ISSUE TITLE
Open firenvim automatically only if textarea is empty

### ISSUE THREAD

**Issue by matthsims** [glacambre/firenvim#278]
I am mostly wondering if it is possible to activate firenvim, per domain, only if the textarea is empty. For example, on gmail and outlook, I do not want firenvim to open, clobbering my rich text edits after writing the initial e-mail. But I do want it to open automatically for github issues.

If this is not currently possible, I would love to see it as a new feature.

**Comment by glacambre** [comment]
What you're asking for isn't currently possible but could be implemented. However, the use case you're describing (enabling firenvim on github but not on gmail) looks like a good match for [url matching](https://github.com/glacambre/firenvim#configuring-what-sites-firenvim-should-automatically-appear-on), which lets you decide what websites firenvim should be activated on.

**Comment by matthsims** [comment]
Yes, I already use the url matching which is very useful. My question is more specifically directed towards the case of 'I need to switch tabs to get some text, and paste it into the text box, after I have already done some formatting', which you mention isn't currently possible.

I do think it would be quite nice, and would be an alternative to alerque's concern in #265.

**Comment by glacambre** [comment]
I think I'll just add the ability to set the `takeover` setting to `empty`. I'll try to implement that this week :).

**Comment by matthsims** [comment]
That will be awesome! Much like this plugin/extension!

**Comment by glacambre** [comment]
Implemented in b24bd514f3f59b693918fce7759e49adf8425cbc - I'll publish a new release on sunday/monday.
