### ISSUE TITLE
Crayon support

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#283]
https://github.com/aramk/crayon-syntax-highlighter
Used here: https://www.consentfactory.com/install-wireshark-3-0-2-on-ubuntu-desktop-18-04-redux/

**Comment by doronbehar** [comment]
Just out of curiosity, what exactly is the idea? What's the problem / what's the benefit of this over Neovim's syntax highlighting?

**Comment by glacambre** [comment]
Currently if you have javascript disabled and click on a crayon element, firenvim will open a neovim frame but it'll be empty - firenvim is unable to get the element's content.
There are two workarounds:
- Enable javascript
- Disable firenvim on sites that use crayon

I dislike both options so I'll have to add special support for crayon :)

**Comment by alerque** [comment]
@doronbehar I was confused by the issue report too — I was expecting it to be the other way around. The issue is Firenvim working on input fields that are already managed by Crayon, not Crayon working inside Firenvim ;-)
