### ISSUE TITLE
Allow custom startup command or prologue in startup script

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#287]
Since #122 was a path issue, I'm making one of the requests explicit here. From there:

> Would you consider an option, therefore, in init.vim to take a string to be put into the firenvim script when installing?

> That would make things much easier to keep in centralised files, in version control. Would also let apply a few options that would normally be applied by shell alias.

> It would also allow a huge degree of flexibility for people that want to use this, for example by setting their own env vars etc.

My RC uses a couple of variables to decide on plugins and special chars to use. I want to tell firenvim to only load my lite set of plugins, for example. It would be great if I could set these in the firenvim startup script, either as shell variables, or by customising the firenvim startup with `--cmd 'let g:liteMode=1'`

**Comment by glacambre** [comment]
What would a startup command/prologue bring over adding something like this to your init.vim?
```vim
if exists('g:started_by_firenvim')
        let g:liteMode=1
endif
```

**Comment by BlueDrink9** [comment]
Largely, clutter. I would have to put that at the top of my `init`, away from the config for firenvim. It is an option, but not an elegant one.

Meanwhile, users with specific path or alias issues could also benefit from being able to run shell commands before firenvim starts up, for example specifying a different version of nvim in their path

**Comment by glacambre** [comment]
You can add a prologue to the firenvim script by [giving a second argument to firenvim#install](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-firenvims-path-is-the-same-as-neovims). It isn't advertised in the README because I don't want people to use their own prologue.

I really think you should use `g:started_by_firenvim` instead :).
