### ISSUE TITLE
Feature request: Takeover='never'

### ISSUE THREAD

**Issue by maxfl** [glacambre/firenvim#299]
I've used firenvim for a small time and it's really an amazing extension. The problem is that in >90% cases I really do not need neovim to be embedded in a text field and only need it from time to time.

Given this, I would like to disable it by default but to have an option (keybinding) to use it explicitly for a given text field. There is a keybinding, but after some searching I did not find the way to have such a behavior.

So I propose to add an option `Takeover='never'`, that disables the embedding by default. In the same time it should keep firenvim working and waiting for a key press.

**Comment by glacambre** [comment]
This can already be achieved by emptying the `selector` attribute settings, as shown [here](https://github.com/glacambre/firenvim#configuring-what-sites-firenvim-should-automatically-appear-on). How would you change the docs in order to make this clearer/easier to understand?

**Comment by maxfl** [comment]
thanks, I will try it.

The problem with the current way is that disabling firenvim by default is something very essential and simple and you expect this to be explicitly stated somewhere in the documentation, but not derived by the thoughtful reader. Also current default behavior is very intrusive and may push away some of the new users.

This feature matches the description 'Configuring Firenvim to not always take over elements' very well. So I expect it should be explicitly noted or referenced in this section. If it is not the option 'takeover=never' then it should be noted that in case one does not want firenvim to take over, then the selector field should  be set to empty string.

Currently empty selector is noted in 'Configuring what sites Firenvim should automatically appear on' very indirectly. I actually did not read that section carefully because 
a) I wanted to disable firenvim an all sites, not on specific ones.
b) I wanted to disable firenvim for all fields, not for specific ones.
c) being lazy average user I do not want to dig into very specific thing like 'selector' and think too much how to compose it in order to get the desired behavior.

From the point of view of the user experience, having 'takeover=never' or even Chrome extension configuration dialog would be very helpful.

**Comment by alerque** [comment]
Are you sure about that @glacambre? I just tried this setup myself and an empty selector means <kbd>Ctrl</kbd>+<kbd>e</kbd> does not work at all. Also incidentally setting `'takeover': 'once'` for me has the effect that I get Firenvim once via manual trigger, but the second time it won't start even on the manual trigger. Either I'm doing something wrong or there is a gremlin in the machinery.

A takeover=never option actually makes a lot of sense to me. Configure the selector as usual for what to match, but then separately configure whether to grab automatically or manually.

**Comment by glacambre** [comment]
>Are you sure about that @glacambre? I just tried this setup myself and an empty selector means Ctrl+e does not work at all.

Yep, it works fine for me (tested on `https://txti.es`). `<C-e>` not working (independently from any settings) happened once or twice for me, but each time the issue magically disappeared when I started investigating it. Can you reproduce your issue on a clean firefox profile (`firefox -P`)?

**Comment by glacambre** [comment]
I've implemented `takeover: never` in #302 and tried to improve the Readme to make things clearer. Could you take a look at https://github.com/glacambre/firenvim/tree/impl_takeover_never and let me know if you see anything that should be improved in the readme?

**Comment by maxfl** [comment]
I've checked the readme, and it's ok.

Also I've tried to use the `impl_takeover_never` branch. Since I'm using `dein` I had to checkout the branch manually and call `dein#recache_runtimepath()` to make sure the new version is used.

My configuration is the following:
```vim
call dein#add('glacambre/firenvim', {
            \ 'hook_post_update': { _ -> firenvim#install(0) },
            \ 'hook_add' : "
            \ let g:firenvim_config = {
            \     'localSettings': {
            \         '.*': {
            \             'priority': 1,
            \             'takeover': 'never',
            \         },
            \     }
            \ }
            \ "
            \ })
```

With this configuration it acts as if the option `takeover = 'once'` was set. It takes over the first time and then ignores. If I add `selector = ''`, then it does not take over as expected.

I will try again later, maybe with clean configuration file.

**Comment by alerque** [comment]
@maxfl I think you need more than the vim plugin side of things updated, I think you need the Firefox plugin updated from that branch as well.

**Comment by maxfl** [comment]
@alerque, got it thanks. Ok, I will need some time to dig into this (:

**Comment by glacambre** [comment]
This has been merged and released, it's already available if you're on firefox and will be in the next 2-3 days if you're on Chrom*.

Thanks for proofreading the readme! :)

**Comment by maxfl** [comment]
Thank you for working on this!
