### ISSUE TITLE
takeover: never doesn't work for one website

### ISSUE THREAD

**Issue by GoldsteinE** [glacambre/firenvim#308]
- OS Version: linux x86-64
- Browser Version:  Firefox 71.0
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: Opened website (unfortunately, I can't show it, because it's in internal network)
- What happened: auto-focused textarea was replaced by nvim instance.
My `init.vim` (actually, `~/.vimrc` sourced from `init.vim`) has this lines in it:
```vim
if has('nvim')
	let g:firenvim_config = { 'localSettings': {} }
	let fc = g:firenvim_config['localSettings']
	let fc['.*'] = { 'takeover': 'never' }
endif
```

**Comment by glacambre** [comment]
Hi @GoldsteinE . I figured out what was wrong and fixed the problem. I'll publish a new release in a few days :)
