### ISSUE TITLE
Cursor is invisible

### ISSUE THREAD

**Issue by GoldsteinE** [glacambre/firenvim#309]
- OS Version: linux x86-64
- Browser Version:  Firefox 71.0
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: Opened firenvim instance with ^E
- What happened: Cursor is invisible in it, making it really hard to use.

**Comment by GoldsteinE** [comment]
It seems that `set guicursor=` set cursor to block (default) in terminal NeoVim, but makes in invisible in firenvim.

**Comment by GoldsteinE** [comment]
`set guicursor=a:block-blinkon0` resolved the problem, but since [NeoVim FAQ](https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal) suggests using `set guicursor=` to disable cursor styling, I suppose it should make cursor block in `firenvim` (or, at least, leave vertical bar as cursor).

**Comment by glacambre** [comment]
Thanks for reporting this issue! I won't have time to fix it this week, I'll try to take a look at it next week :)

**Comment by glacambre** [comment]
Fixed in #333, thanks for reporting!

I'll publish a new release either tomorrow or next week :).

**Comment by johnallen3d** [comment]
Do you think you'll publish a new release soon @glacambre? I was noticing some missing cursor problems and came across this issue.

Thanks for the amazing project!

**Comment by glacambre** [comment]
I published a new release, it's already available for Firefox and will be in a few days for Chrome :)
