### ISSUE TITLE
the variable g:started_by_firenvim does not exist when firenvim is started?

### ISSUE THREAD

**Issue by jdhao** [glacambre/firenvim#315]
- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 79.0.3945.88
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: It seems that the variable `g:started_by_firenvim` does not exist.
- What happened: when firenvim is started inside the textarea, `echo g:started_by_firenvim` does not exist.

![image](https://user-images.githubusercontent.com/16662357/71638300-1ad3e680-2c97-11ea-87df-88d6a85c5ec7.png)

**Comment by alerque** [comment]
Yes it does, here I will `:echo g:started_by_firenvim`:

![image](https://user-images.githubusercontent.com/173595/71638422-ad14c400-2c70-11ea-9924-c9542ab4ace7.png)

Do you perhaps have some persistent nvim session it's connecting to that was started up another way?

**Comment by jdhao** [comment]
Note that I am using a Windows machine, I checked the firenvim code and found that `g:started_by_firenvim` is only set when the platform is not Windows, as indicated by code [here](https://github.com/glacambre/firenvim/blob/master/autoload/firenvim.vim#L215).

Is there anything that I am missing here?

**Comment by alerque** [comment]
That looks like an oversight and a relatively easy fix!

**Comment by glacambre** [comment]
I fixed this issue and implemented a test to make sure this feature keeps working. Please update the neovim plugin and run `firenvim#install()` again and let me know if everything works as expected.

Thank you for reporting this bug :).

**Comment by jdhao** [comment]
Thanks, I have updated to the latest version of firenvim, and it is working great!
