### ISSUE TITLE
Is there some way to configure to be disabled by default?

### ISSUE THREAD

**Issue by lourenci** [glacambre/firenvim#321]
First all, thank you for the extension. It's the best one out there.

Is there some way to change the default behavior of being enabled by default?

I want to activate it just in some cases. In the most, I want the normal textarea.

**Comment by glacambre** [comment]
Yes, you can set the [takeover setting to `never`](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements) and then either set it back to `always` on [some sites](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object) or [manually triggre Firenvim](https://github.com/glacambre/firenvim#manually-triggering-firenvim).

Did you read the Readme? If yes, how would you make this information more obvious/easier to find?

**Comment by alerque** [comment]
You can change the selectors used on a global or per site basis. Here are some examples:


```vim
" Setup a shortcut variable to the per site settings array
let s:fc = {}
let g:firenvim_config = { 'localSettings': s:fc }

" Configure all sites
let s:fc['.*'] = { 'selector': 'textarea, div[role="textbox"]', 'priority': 0, 'takeover': 'never' }
```

This will enable Firenvim on all sites (`.*`) for both textareas and textbox divs, but it won't actually activate on _anything_ unless you hit <kbd>Ctrl</kbd><kbd>E</kbd>.

Here is one (using the same shortcut variables as before) that is deactivated on all sites (empty selector) but enabled on Github (with a higher priority than the deactivation):

```vim
let s:fc['.*'] = { 'selector': '', 'priority': 0 }
let s:fc['github.com'] = { 'selector': 'textarea', 'priority': 1 }
```

The possibilities are pretty endless, and you'll want to think through exactly what you do or don't want to have happen when. It's a pretty personal thing, but the tooling is there to adapt to most permutations you can imagine.

**Comment by glacambre** [comment]
Hi @lourenci, I'm closing this issue because I believe your question has been answered - if something is not clear or you need more information, feel free to ask/reopen this issue :).

**Comment by danielb2** [comment]
is there a way to do this with regular init.vim now ?
```
let g:firenvim_config.localSettings['.*'] = { 'takeover': 'always' }
```
doesn't seem to work now
