### ISSUE TITLE
`Neovim is not responding` in Firefox71 on Ubuntu with Nvim0.5.0

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#327]
I just installed firenvim and I see `Neovim is not responding` when I click on the extension's icon. Any workarounds or troubleshooting tips?

(Firefox 71.0, NVIM v0.5.0-dev, Ubuntu 16.04)

_Originally posted by @oren in https://github.com/glacambre/firenvim/issues/206#issuecomment-570757383_

**Comment by glacambre** [comment]
What we know:
- Firefox is installed through apt
- Firenvim is installed with vim-plug

@oren Could you run `printf 'abcde{}' | $HOME/.local/share/firenvim/firenvim` in a shell and tell me what the result it?

**Comment by oren** [comment]
Error detected while processing function OnStdin[28]..WriteStdout:
line    5:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: attempt to index global 'bit' (a nil value)
Press ENTER or type command to continue

**Comment by glacambre** [comment]
Ah, you're using lua, not luajit, so you don't have the `bit` package. This is explained in the [readme](https://github.com/glacambre/firenvim#pre-built), you need to install it yourself. `luarocks install luabitop` should do the trick :).

**Comment by oren** [comment]
I am still having the same issue but maybe the installation of luabitop was not successful?

sudo luarocks install luabitop

```
Installing https://rocks.moonscript.org/luabitop-1.0.2-3.rockspec...
Using https://rocks.moonscript.org/luabitop-1.0.2-3.rockspec... switching to 'build' mode
Cloning into 'luabitop'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 32 (delta 2), reused 22 (delta 2), pack-reused 0
Receiving objects: 100% (32/32), 37.18 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
Note: checking out 'ad0412ab7f94bd3d5b4ff3ddc1037e0e9531d54a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

gcc -O2 -fPIC -I/usr/include/lua5.1 -c bit.c -o bit.o
gcc -shared -o bit.so -L/usr/local/lib bit.o
Updating manifest for /usr/local/lib/luarocks/rocks
luabitop 1.0.2-3 is now built and installed in /usr/local (license: MIT/X license)

```

:lua bit.band(1,1)

```
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: atte
mpt to index global 'bit' (a nil value)
```

printf 'abcde{}' | $HOME/.local/share/firenvim/firenvim

```
Error detected while processing function OnStdin[28]..WriteStdout:
line    5:
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:1: attempt to index global 'bit' (a nil value)
```

**Comment by glacambre** [comment]
Does `:lua print((require 'bit').band(1,1))` print `1`? If not, what if you replace `bit` with `bitop` or `luabitop`?

If one of these work, does adding
```lua
if bit == nil then
  bit = require 'require-that-worked'
end
```
at the top of [lua/websocket.lua](https://github.com/glacambre/firenvim/blob/master/lua/websocket.lua) and [lua/utils.lua](https://github.com/glacambre/firenvim/blob/master/lua/utils.lua) make the error disappear?

**Comment by oren** [comment]
yes. :lua print((require 'bit').band(1,1)) show me 1. where do i find those files?

**Comment by glacambre** [comment]
In the directory where vim-plug downloads your plugins (which is the directory you give to `plug#begin()` I belive). Try `find $HOME -name websocket.lua` if you can't find it.

**Comment by oren** [comment]
Yes! I am using vim to type this message! Thank you

**Comment by glacambre** [comment]
Thanks for helping dbug this :)

**Comment by AnakTeka** [comment]
I'm having a same problem 

`:lua print((require 'bit').band(1,1))` gives me 1

any ideas?

**Comment by glacambre** [comment]
@AnakTeka please open a new issue :)
