### ISSUE TITLE
hide command line message when triggering firenvim

### ISSUE THREAD

**Issue by pwntester** [glacambre/firenvim#328]
hi, 

Is there a way to hide the message in command line? I tried various `shortmess` options but no luck so far:

<img width="846" alt="imagen" src="https://user-images.githubusercontent.com/125701/71771534-eda86200-2f3c-11ea-81ad-9583bbf4ce00.png">

Thanks,
A

**Comment by glacambre** [comment]
Kind of a hack, but you could try `au BufWritePost * call nvim_input("<C-l>")`. You could also try the external command line by setting the [localSetting](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object) named [cmdline](https://github.com/glacambre/firenvim#using-the-external-command-line) to 'firenvim'.

**Comment by pwntester** [comment]
Thanks!
