### ISSUE TITLE
Internal command line widget makes completion plugin(s) unusable

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#329]
I'm trying to use the `'cmdline': 'firenvim'` option which makes the overall UI a lot nicer, but I'm having trouble making it usable. In particular it seems to cause the whole UI to choke on autocompletion (which works with the normal Neovim command line option). I'm using deoplete, and whenever it activates I get some flicker and then a garbage character in the buffer.

Demo:

Insert.

![image](https://user-images.githubusercontent.com/173595/71776601-5aefdd80-2fa5-11ea-9601-ca528ed35a85.png)

^^^ The above came from trying to type "Insert." in the Firenvim mode on this post with completion enabled. You can't see the garbage in Github's rendered version but if you view the source to this post it is there.

**Comment by glacambre** [comment]
I can't reproduce this either with Neovim's default completion or with deoplete. Could you provide a minimal init.vim+steps to reproduce this issue?

(I don't think this is a firenvim bug btw - since the characters are inserted in the buffer rather than being just "visual glitches" I'd blame deoplete rather than firenvim).

**Comment by alerque** [comment]
Sure I'll work on a minimal reproduction. Since it did it on a couple machines at once when I changed that setting I assumed it was pretty universal, but it could be some other bad interaction. Feel free to assign this issue to me so I don't forget.

**Comment by glacambre** [comment]
@alerque Can you still reproduce this? I haven't done anything to specifically fix this issue but I've solved other bugs that might have been related.

**Comment by alerque** [comment]
No, in fact I am unable to reproduce it. I had completion disabled in Firenvim because I couldn't come up with a sane MWE and it was too broken to leave on. I just enabled in and it seems to work fine (aside from <kbd>Ctrl</kbd>+<kbd>N</kbd> being by default completion shortcut!). This must have been affected by other fixes as you suggest.
