### ISSUE TITLE
Make Firenvim based command line the default mode

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#330]
Given stability issues (for example #329) in might be early for this, but as soon as it's considered stable I think the default mode should be to use the Firnvim provided web command line overlay by default. This would alleviate requests like #328 as well. As it is I don't think the feature is even discoverable enough for those that would want it to take advantage of it. Clearly those that weren't expecting it might want to force the other mode. I will probably tweak this on a per site basis (or preferably based on the available space), but it seems like a sensible default.

**Comment by glacambre** [comment]
I'll need to fix https://github.com/neovim/neovim/issues/11558 before I make the Firenvim commandline the default.

**Comment by glacambre** [comment]
I made the new renderer a bit more aggressive about clearing command prompts and so I made the firenvim commandline the default. This change will reach you in next release :)
