### ISSUE TITLE
Cmd key on MacOS

### ISSUE THREAD

**Issue by pwntester** [glacambre/firenvim#332]
Hi,

When I paste text on MacOS (Cmd-V), I only get `<D-v>` printed in the firenvim frame. Is this a known limitation, Is there any workaround for this?

Thanks!

**Comment by glacambre** [comment]
I don't think `<D-v>` is a default neovim binding. Does `"+p` (neovim's default "paste from clipboard" binding) work? If yes, does `:nnoremap <D-v> "+p` work?

**Comment by pwntester** [comment]
No idea where the `<D-v>` binding comes from, neovim doesnt seem to understand it. Adding the mapping suggested above at least let me paste in normal mode using control key instead, thanks

**Comment by justinmk** [comment]
> No idea where the `<D-v>` binding comes from

That is the correct keycode for CMD+v. But yes, Nvim doesn't do anything with this mapping by default so you would need to map it.

**Comment by glacambre** [comment]
Great, I'm closing this issue then. Feel free to reopen it if you have more questions :)

**Comment by pwntester** [comment]
For future reference, I managed to use Cmd-v for pasting in insert mode adding `inoremap <D-v> <C-R>+`

Thanks!

**Comment by justinmk** [comment]
why use pastetoggle...?

**Comment by pwntester** [comment]
For whatever reason, not using it was resulting in an extra line break after the pasted text. Stackoverflow suggested the pastetoggle version that worked. For after re-testing it, Im not able to reproduce the extra linebreak and the simpler `inoremap <D-v> <C-r>+` version worked without a problem.

**Comment by bs** [comment]
Ran into this after first getting the plugin loaded today. I also am running into things like hitting <S-D-]> (the keyboard shortcut for switching tabs on macOS) both being intercepted by the browser and switching tabs AND being intercepted by neovim and pasted in this buffer. Is there a recommended way to handle this? Unbind that sequence in .vimrc on a conditional?

Also, happy to put some of these into a FAQ and submit a pull request for Mac users.

**Comment by glacambre** [comment]
This sounds like a bug in Firefox, keyboard shortcuts should either be 
intercepted by the page and not by the browser or the opposite. I'll 
double check to make sure that I'm not forgetting to cancel `<D-*>` 
events (this would really surprise me, all events are treated the same) 
and then open a bug on Firefox's issue tracker.

In the meantime, binding this to a no-op like `:map <S-D-]> <nop>` is 
indeed a good workaround. You can check if you're in Firenvim with the 
UIEnter event or the g:started_by_firenvim variable, see the readme for 
more info :).
