### ISSUE TITLE
firenvim does not work. Text field becomes unresponsive, $XDG_DATA_HOME not set?

### ISSUE THREAD

**Issue by AtomToast** [glacambre/firenvim#337]
- OS Version: linux x86-64
- Browser Version:  Firefox 68.0
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: Use firenvim
- What happened: The text field becomes unresponsive and I can't type anything. C-e doesn't do anything either

I went through the trouble shooting guide and when calling 
`echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim`
it just gives me `zsh: no such file or directory: /firenvim/firenvim`
However it does work correctly with the full path to the script:
```
> echo 'abcde{}' | .local/share/firenvim/firenvim                                                                                                                            
{"version": "0.1.17"}
```
When checking `echo $XDG_DATA_HOME` it returns nothing, so that might be the issue?  

Furthermore I actually managed to get it to run in the for testing recommended `http://txti.es` but I couldn't actually use it on any other website like github or reddit.  

There are also some errors in the web, browser and firenvim extension console but I don't quite know which ones are related.  
I could find just this one with a fitting name:  
![image](https://user-images.githubusercontent.com/27757087/71827251-c023fb80-3097-11ea-92d8-172c6048f18d.png)

**Comment by glacambre** [comment]
>when calling `echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim` it just gives me `zsh: no such file or directory: /firenvim/firenvim`

I would recommend setting `$XDG_DATA_HOME` to something in your .zshenv. Lots of software expect this variable to exist. Note that, as you found out, this isn't required to get Firenvim to work - Firenvim will use neovim's `stdpath('data')`, which seems to default to `.local/share/`.

>I actually managed to get it to run in the for testing recommended http://txti.es but I couldn't actually use it on any other website like github or reddit.

Could you try with a fresh firefox profile? (Running `firefox -P` will open Firefox's profile manager.)

**Comment by AtomToast** [comment]
> I would recommend setting $XDG_DATA_HOME to something in your .zshenv. Lots of
> software expect this variable to exist. Note that, as you found out, this
> isn't required to get Firenvim to work - Firenvim will use neovim's
> stdpath('data'), which seems to default to .local/share/.

That's good to know, I now set XDG_DATA_HOME XDG_CONFIG_HOME and XDG_CACHE_HOME

> Could you try with a fresh firefox profile? (Running firefox -P will open
> Firefox's profile manager.)

This actually worked! I am now writing this from within firenvim. Now the
question is, what is causing the problem?

**Comment by glacambre** [comment]
I believe you probably have either a setting or an extension that tries to force-upgrade plaintext connections made to localhost to TLS ones. You could try to go through `about:config` and see if there's anything suspicious. I'm going to close this issue because I believe there's nothing I can do to solve your problem but if you have more questions/find out what is wrong, please do not hesitate to reply to this issue :)

**Comment by glacambre** [comment]
Could you list the addons you have installed and the settings you have in `~/.mozilla/firefox/[your profile directory]/user.js` and `~/.mozilla/firefox/[your profile directory]/prefs.js`?

**Comment by AtomToast** [comment]
My list of addons is pretty extensive:  
- Bitwarden
- Cookie AutoDelete
- cookiex.txt
- Dark Reader
- Decentraleyes
- Disconnect
- Don't touch my tabs! (rel=noopener)
- DuckDuckGo Privacy Essentials
- ff2mpv
- Firefox Color
- Firefox Multi-Account Containers
- Google search link fix
- HTTPS Everywhere
- I don't care about cookies
- Joplin Web Clipper
- LessPass
- Link Cleaner
- minerBlock
- OneTab
- Privacy Badger
- React Developer Tools
- Reddit Enhancement Suite
- Saka Key
- Skip Redirect
- Smart Amazon Smile
- Tab Center Reborn
- Terms of Service; Didn't Read
- uBlock Origin
- uMatrix
- Web Developer
- Wikiwand: Wikipedia Modernized
- YouTube Auto Like
- YouTube Channel Whitelist for uBlock Origin

I don't seem to have a user.js
This is my prefs.js: https://hastebin.com/ilenezicos.cpp

**Comment by glacambre** [comment]
I can't reproduce this bug, even when installing your addons and using your prefs.js. I'd recommend moving to a new firefox profile (i.e. creating a new profile, copying cookies.sqlite, formhistory.sqlite and places.sqlite from the previous profile to the new one, installing firenvim and then re-configuring your browser one step at a time making sure that Firenvim keeps working after changing each setting/installing each addon).

**Comment by AtomToast** [comment]
Oof, okay.  
Guess I'll give that a shot maybe on the weekend

**Comment by AtomToast** [comment]
I have now set up a new Firefox profile from scratch with all my previous addons
and configurations and it now seems to work fine!

I don't know what caused it but maybe it just has to do with the profile being a
few years old now and me constantly playing around with my stuff.

**Comment by glacambre** [comment]
Great, thanks for letting me know! :)
