### ISSUE TITLE
Rewrite the renderer

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#347]
The current renderer is pretty slow and is partially responsible for Firenvim's latency problem. This is because it uses the DOM, which isn't intended for this kind of use. Using the DOM made a lot of sense at the beginning of Firenvim because it reduced the amount of things to learn, however, now that I know most of what you need to know in order to write a Neovim GUI, it would make sense to rewrite it with performance in mind.

The new renderer should:
1) Support all current Neovim UI extensions
2) Be easy to maintain
3) Be fast

Supporting all current Neovim UI extensions from the start is important because it helps [avoid bugs](https://github.com/neovim/neovim/issues/11646#issuecomment-570074095) and will create part of the groundwork necessary for new, yet-to-come ui extensions. Easy maintenance is important because I have less and less motivation to work on Firenvim, I should thus reduce the maintenance burden for myself and make it easy for new contributors to hack on Firenvim. Being fast is the whole point of the rewrite and the only reason it would be ok to sacrifice speed is that an UI extension can't be implemented in an efficient way or that it would increase the maintenance burden. 

There are multiple technologies that could satisfy our needs:
- The Canvas2D API
- WebGL
- WebGPU

The canvas API is probably the easiest API to work with but also the slowest but it might be enough to reach 60fps (you can't go higher in a browser). An important point is that it has text-rendering functions (e.g. [fillText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText)), this would help a lot during development.
The WebGL approach would be more complex but provide more control. It doesn't provide text-rendering functions and thus would probably require to hack something by rendering text with Canvas2D first and then caching the glyphs and reusing the pixels in a WebGL context.
WebGPU isn't out yet but seems to be "WebGL but modeled on Vulkan rather than OpenGL". It would probably suffer from the same issues we have with WebGL.

[Neovim-e](https://github.com/coolwanglu/neovim-e) uses Canvas2D.
[Nyaovim](https://github.com/rhysd/NyaoVim) says it uses a canvas but I couldn't find the code.
[OniVim 1](https://github.com/onivim/oni) uses WebGL.
[Veonim](https://github.com/veonim/veonim) uses WebGL.
[Vv](https://github.com/vv-vim/vv) uses Canvas2D.

Overall, it seems that even though the Canvas approach seems simpler, the more polished UIs chose to use WebGL. This might indicate that Canvas2D isn't good enough.

One last thing to keep in mind is that some users probably use canvas-disabling extensions. Since Firenvim renders things in its own iframe it might not be affected, we need to figure out how these extension work and whether we'll need to implement a fallback to the DOM renderer or not.

I can probably use Pavel Fatin's excellent [typometer](https://pavelfatin.com/typometer/) to measure how fast the new renderer is compared to the old one.

**Comment by NilsIrl** [comment]
> This is because it uses the DOM, which isn't intended for this kind of use.

The "modern" web: Surprised Pikachu

**Comment by NilsIrl** [comment]
> to reach 60fps (you can't go higher in a browser

I think you can go higher in the browser.

source: this monitor refresh rate website: https://www.testufo.com/

**Comment by glacambre** [comment]
Mh, looks like you're right. I think I remember reading about a 60fps limitaiton for the [requestAnimationFrame API](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) when it first came out in 2012-2013 but it looks like it doesn't anymore :).

**Comment by NilsIrl** [comment]
> The WebGL approach would be more complex but provide more control. It doesn't provide text-rendering functions and thus would probably require to hack something by rendering text with Canvas2D first and then caching the glyphs and reusing the pixels in a WebGL context.

Is this really necessary? Games and stuff (which use openGL) do draw text on screen, so it is probably better to follow the "normal" approach of drawing stuff on screen than using Canvas2D for that.

**Comment by glacambre** [comment]
>Games and stuff (which use openGL) do draw text on screen, so it is probably better to follow the "normal" (i.e. the one used by games/GPU accelerated terminals) approach of drawing stuff on screen than using Canvas2D for that.

There are two reasons I can't/don't want to use this approach:
1) Drawing fonts requires knowing what they should look like (i.e. knowing about their bezier curves). As far as I know, there are no APIs that let you "open" fonts and read data. One solution would be to bake-in a font but `:set guifont` wouldn't work anymore.
2) Even if it was possible to access the font's data, I would need a text-rendering engine. I can't implement one myself ([text rendering is insanely difficult](https://gankra.github.io/blah/text-hates-you/)) and it would be absurd to ship a JS one when the browser's is already there and available under the canvas API.

As far as I can tell, drawing to a Canvas2D to know what glyphs should look like is what [Oni](https://github.com/onivim/oni/blob/aecf5c6de086d63d3cdd816215ae93d3ef440d8e/browser/src/Renderer/WebGLRenderer/TextRenderer/GlyphAtlas/GlyphAtlas.ts#L152) and [Veonim](https://github.com/veonim/veonim/blob/78b76fc61278b85a91fb32d2e02d6a71fc5b6772/src/render/font-texture-atlas.ts#L74) do, even though they use WebGL and can access font data.

**Comment by glacambre** [comment]
I'm encountering this weird issue where the letter spacing (for a monospace font!) is wrong (left is current, right is a canvas):

![2020-03-22-155521_1920x1080_scrot](https://user-images.githubusercontent.com/11534587/77253087-8905c500-6c58-11ea-822e-9e75f33ba815.png)

Veonim has the same issue, I couldn't test Oni (can't start Oni1, can't build Oni2) and I'm not seeing anything in Neovim-e/Vv's source code that would handle such an issue so I'm not sure what's happening/how to fix it.

**Comment by glacambre** [comment]
I'm happy to report that I've made a nice amount of progress on this issue this weekend and that I'm now "stuck" (this isn't really blocking but it prevents me from profiling Firenvim properly) on a neovim bug (not really a bug, more of a missed optimization): https://github.com/neovim/neovim/issues/12424

**Comment by glacambre** [comment]
I found a workaround to neovim/neovim#12424, so I've been able to profile Firenvim as needed. I think the core of the renderer is ready - I have ~300fps on a 20x80 canvas and a consistent ~60fps on a 50x200 canvas when continuously performing full screen updates (a scenario that probably will never happen in practice).

These stats aren't great in the absolute considering the small amount of work Firenvim does comparing to, say, videogames. But they are good enough when considering the low amount of code required and the fact that maintainability is more important than performance to me. Most of the "slowness" is caused by garbage collection - I could probably make Firenvim smarter in its allocation patterns but I don't find this worth the complexity.

Now I have to re-implement support for persistent mode, external commandline and probably a few other features that I can't think of right now. Once this is done, I'll publish a new release with the new renderer as default and a setting to switch to the old renderer. I'll wait a month for bug reports to trickle in and if none arrive or if I manage to fix them all in that timeframe I'll publish a new release that removes the old renderer.

**Comment by alerque** [comment]
> I'm encountering this weird issue where the letter spacing (for a monospace font!) is wrong

The canvas rendering is missing any shaping. It is not a letter space issue *per se*, it's just blindly drawing glyphs into boxes without listening to the font's description of where those glyphs should be relative to the bounding box. This is information the shaper should be supplying, but it manifestly isn't being used. Even in a monospace font where the overall output width of every glyph should be the same, some characters will have an advance value that should be used before the actual vector content starts. An `l` will have more advance than an `m`. In the sample above everything is starting slammed left inside the glyph width box, but that's not how the coordinate space in many fonts works.

**Comment by glacambre** [comment]
Yeah, the renderer was actually using the non-monospaced version of the 
font I told it to use. It turns out that if you change the dimensions of 
the canvas, any setting that you might have applied to the canvas (such 
as the fontface to use) will be reset to the default value. Not very 
user-friendly for a supposedly user-friendly API ¯\_(ツ)_/¯.

**Comment by glacambre** [comment]
Hi all, it took a while but I think the new renderer is ready. If you have time, I'd really appreciate your help with testing it. I gave instructions to do that in https://github.com/glacambre/firenvim/pull/730#issuecomment-711033641 . I think I'll probably merge it in a few weeks :).

**Comment by maxigaz** [comment]
Hi @glacambre! In the linked comment you mentioned removing the stable version as one of the steps. I took a different approach and disabled the stable one, opened `about:debugging#/runtime/this-firefox` and opened `manifest.json` found in the extracted archive. Is this also an appropriate way of installing it temporarily, or are there any downsides?

So, I’ve just tried it on Firefox 81.0 under Manjaro Linux. It feels *much* snappier than it used to be, I can say that by using it for editing this very message. (It loads faster and responds to key presses similarly to Neovim run in a terminal emulator.)

On the other hand, there are black artifacts on the status bar and Airline. See the screenshot below:

![firenvim-2020-10-17_21-02](https://user-images.githubusercontent.com/10419911/96351801-31301f00-10be-11eb-93d1-d07ab09dafe8.png)

In comparison, here’s how it looks if I go back to the stable version:

![firenvim-2020-10-17_21-03](https://user-images.githubusercontent.com/10419911/96351805-38efc380-10be-11eb-86f9-b9de389034ca.png)

**Comment by glacambre** [comment]
@maxigaz
>Is this also an appropriate way of installing it temporarily, or are there any downsides?

It's appropriate, the only downside is that the addon will be unloaded when Firefox shuts down, but I guess this could be seen as an advantage too :).

Thanks a lot for testing this! I'll try to reproduce and fix the rendering issues you're seeing.

**Comment by glacambre** [comment]
This is now implemented (in less that a year! ;D) on master. For now, you can go back to the HTML renderer with the following settings:
```
let g:firenvim_config = {
  \ 'localSettings': {
    \ '.*': {
      \ 'renderer': 'html',
    \ }
  \ }
\ }
```
Please report any bug you may find as I plan on removing the HTML renderer in a month or two. I'll publish a new release very soon.

**Comment by NilsIrl** [comment]
I'm two years too late, but maybe xterm.js could do it: https://xtermjs.org/, it has a webgl addon as well.
