### ISSUE TITLE
Detect brave when chrome isn't installed

### ISSUE THREAD

**Issue by habamax** [glacambre/firenvim#355]
Found comment stating firenvim works for brave: https://github.com/glacambre/firenvim/issues/144#issuecomment-540520767

> Oh, cool to see that firenvim works as is in Brave :)

But It doesn't work for brave though. At least when no chrome/chromium is installed.

When you `call firenvim#install()` it echoes there are no chrome or chromium and doesn't install anything.

![image](https://user-images.githubusercontent.com/234774/72426363-9d31cf80-379a-11ea-939f-22a859a8d42d.png)

**Comment by glacambre** [comment]
Hi, thanks for reporting this issue. Could you try to run `call firenvim#install(1)` in neovim and see if that fixes your issue?

**Comment by habamax** [comment]
Yes it helped. Thank you!

I have another issue, not sure if it belongs here though.

I turned off automatic loading in config:

```
if exists('g:started_by_firenvim')
	packadd firenvim
	set gfn=Iosevka\ Slab\ Extended:h12
	au BufEnter github.com_*.txt set filetype=markdown
	au BufEnter www.linux.org.ru_*.txt set filetype=markdown
	let g:firenvim_config = {
				\	'localSettings': {
				\		'.*': {
				\			'selector': '',
				\			'priority': 0,
				\		}
				\	}
				\ }
endif
```

And it works really well in firefox as I set up a shortcut `C-A-v`.

But for brave (and actually for chrome too) I was unable to find a setting to
set up a shortcut. Suggested `Ctrl-e` does select browser address bar instead.

**Comment by habamax** [comment]
What I have in extension settings:
![image](https://user-images.githubusercontent.com/234774/72428797-7aee8080-379f-11ea-94e0-f8d0abc39987.png)

**Comment by habamax** [comment]
Initial issue is resolved!

**Comment by habamax** [comment]
Found in the docs: chrome://extensions/shortcuts

**Comment by glacambre** [comment]
Reopening because your problem can be fixed "automatically" - I just have to detect brave's configuration files and run the chrome installation steps.

Does configuring the keyboard shortcut in `chrome://extensions/shortcuts` work?

**Comment by habamax** [comment]
> Does configuring the keyboard shortcut in `chrome://extensions/shortcuts` work?

Yes indeed!
