### ISSUE TITLE
Can't paste in emojis 😅

### ISSUE THREAD

**Issue by Stvad** [glacambre/firenvim#366]
- OS Version: mac x86-64
- Browser Version:  Firefox 73.0
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: To paste in emoji from system clipboard
- What happened: I see ?? instead of emoji.

```
nnoremap <D-v> "+p
inoremap <D-v> <C-r>+
```

Are the mappins I have for interacting with system clipboard.  
I focus on pasting, becaues if emoji is already in the text field - firenvim deals with it just fine.

Also I can paste them into nvim opened in iTerm2, and that works just fine as well.

>

**Comment by glacambre** [comment]
Pasting emojis works fine for me - are you sure it also works in neovim in a terminal? (Make sure to explicitly use `"+p` rather than `<D-v>` - some terminals have special handling of pasting shortcuts and do not use the same mechanism neovim uses when using `"+p`).

**Comment by Stvad** [comment]
Just tested using `"+p` explicitly in neovim in the iterm - still works

**Comment by Stvad** [comment]
A workaround suggested in #11432 (let $LANG='en_US.UTF-8') works. After doing that pasting works properly

**Comment by glacambre** [comment]
Great, thanks for taking the time to debug this :). One last question: what's the value of `$LANG` in firenvim?

**Comment by Stvad** [comment]
The output of `language` command:  
Current language: "en_US/en_US/en_US/C/en_US/en_US"

`echo $LANG` (when not overriden by the above configuration)
en_US

**Comment by glacambre** [comment]
Great, this means that this isn't a problem with the env var not being set or being modified by the browser, so this issue should fix itself once https://github.com/neovim/neovim/issues/11432. I'm going to close this issue, if https://github.com/neovim/neovim/issues/11432 is fixed and the problem doesn't disappear in Firenvim, please let me know and I'll reopen and investigate :)
