### ISSUE TITLE
Distinguish Shift + arrow-key

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#369]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 79.0.3945.79
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: `c-v shift-left`
- What happened in firenvim: `<left>`
- What happened in gvim: `<s-left>`

I have a map that uses shift for changing gui size. Would be great to have it work on firenvim

**Comment by justinmk** [comment]
should work as long as s-left or left is sent to Nvim. Test case:

```
nn <s-left> :echo 'sl'<cr>
nn <left> :echo 'left'<cr>
call nvim_input('<s-left>')
call nvim_input('<left>')
```

**Comment by BlueDrink9** [comment]
Yeah, it works in terminal nvim with kitty, which is why I opened the issue here.

**Comment by glacambre** [comment]
Thanks for reporting this bug :)
