### ISSUE TITLE
Manual trigger shortcut doesn't work on empty fields when `takeover=nonempty`

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#371]
Settings:

```
'.*': {
    \ 'selector': 'textarea, div[role="textbox"]',
        \ 'cmdline': 'firenvim',
        \ 'takeover': 'nonempty',
```

- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 79.0.3945.79
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: Click an empty textbox, use the chrome shortcut I've set up to manually trigger firenvim.
- What happened: No firenvim. Entering a single character and trying again: Firenvim.

**Comment by glacambre** [comment]
Please stop finding bugs in Firenvim :<

Just kidding, thanks for the report, I'll look into it :)

**Comment by BlueDrink9** [comment]
If I didn't think firenvim was worth making perfect...
