### ISSUE TITLE
When minimising or exiting, sync up cursor location within textbox

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#380]
And another one

Related to the discussion around minimising firenvim in order to check eg github user or issue expansion, it would be marvellous for the cursor position within nvim to be synced to the cursor position within the box. This would allow a simple minimise > type and check > re-open.

I think it would also be pleasant on startup, because I often initiate editng a box by clicking (roughly) where I want to start editing, when text already exists.

**Comment by glacambre** [comment]
Good idea!

>I think it would also be pleasant on startup, because I often initiate editng a box by clicking (roughly) where I want to start editing, when text already exists.

This is already implemented. Is it not working for you?

**Comment by BlueDrink9** [comment]
It is now, but didn't seem to when I checked it writing this issue.

**Comment by glacambre** [comment]
It doesn't make sense to try to synchronize the cursor when the textarea and buffer's content differ, so the action of minimizing or exiting the firenvim frame shouldn't result in synchronizing the cursor.
It does make sense to synchronize the cursor when the buffer and textarea's content are synchronized. This is already already implemented for `:w`.
So I think what's really missing is a way to detect changes in the underlying textarea's content and update the file accordingly (letting either `autochdir` or `:e`) do the work.

**Comment by BlueDrink9** [comment]
Makes sense. Could you check, when minimising, whether the text is synced, and if so then sync cursor?
Say I quickly want to add a user tag at the start of my comment. `gg0<c-z>@user`, except the cursor in the underlying box didn't sync up so I end up typing the tag at the end of my comment

Good to know it syncs on write.

**Comment by glacambre** [comment]
Can't you just `:nnoremap <C-z> :w<CR>:call firenvim#hide_frame()<CR>`?

**Comment by BlueDrink9** [comment]
Good idea. Feel free to close
