### ISSUE TITLE
Windows: has('clipboard') returns 0, despite the fact that the clipboard is accessible.

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#381]
- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 79.0.3945.130
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: `has('clipboard')`
- What happened: `0`
- What I expected: `1`

This check is often used for behavior handling in plugins and config scripts.

In my case, it's the difference between trying to use `paste.exe` or `"+` when I push `<c-v>`.

**Comment by glacambre** [comment]
>has('clipboard') returns 0, despite the fact that the clipboard is accessible

Do you mean that despite `has('clipboard')` reporting 0, Neovim manages to paste your clipboard's content when using `"+p`? This sounds like a Neovim bug rather than a firenvim one.

If instead the problem is that `"+p` doesn't work despite win32yank being installed, I think this might be a path issue. I'm not sure how you're sure to check what's in your path on Windows though, does running `:!where win32yank` in Firenvim report the same things as in Neovim?

**Comment by BlueDrink9** [comment]
The first option. May be a neovim issue then, but it works fine from a command line nvim and nvim-qt

**Comment by glacambre** [comment]
@justinmk Do you have an idea of what might be happening here?

**Comment by BlueDrink9** [comment]
I take it back, for some reason the clipboard is no longer working.
This is what I get after `checkhealth`:

E5009: Invalid $VIMRUNTIME: C:\Program Files (x86)\vim\vim80

**Comment by glacambre** [comment]
Could you take a look at your environment variables and see if you have one named `VIMRUNTIME`?

**Comment by BlueDrink9** [comment]
The error is in the neovim FAQ, so I'll try some debugging. And I'll see if I can repro with no vimrc

**Comment by BlueDrink9** [comment]
Normal nvim runtime is fine, no environment variables astray. But even with no RC, within firenvim $VIMRUNTIME is using vim's, not nvim's...

**Comment by BlueDrink9** [comment]
The `&rtp` is fine when running via console, but in browser it's off. I'll check firefox.

**Comment by BlueDrink9** [comment]
Firefox was fine (although required update). I'll restart chrome...

**Comment by BlueDrink9** [comment]
Restarting chrome and re-installing firenvim seems to have fixed it. Problem at my end, sorry for the hassle.
