### ISSUE TITLE
Figure out what went wrong with the Chrome release

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#394]
Received this email:

>Chrome Web Store
>
>
>Dear Developer,
>
>Your Google Chrome item "Firenvim" with ID: egpjdkipkomnmjhjmdamaniclmdlobbo
>did not comply with our policies and was removed from the Chrome Web Store.
>
>
>
>Your item did not comply with the following section of our Program Policies:
>
>
>"Spam and Placement in the Store"
>
>
>Items should work and provide some functionality upon installation.
>Items should provide the promised functionality that aligns with the
>description of the item.
>
>Please review your item and make necessary changes so that it provides the
>function/service included in the item's description.
>
>
>
>Once your item complies with Chrome Web Store policies, you may request
>re-publication in the Chrome Web Store Developer Dashboard. Your item will be
>reviewed for policy compliance prior to re-publication.
>
>
>If you have any questions about this email, please respond and the Chrome Web
>Store Developer Support team will follow up with you.
>
>
>
>Important Note:
>Repeated or egregious policy violations in the Chrome Web Store may result in
>your developer account being suspended or could lead to a ban from using the
>Chrome Web Store platform.
>
>This may also result in the suspension of related Google services associated
>with your Google account.
>
>
>
>Sincerely,
>
>Chrome Web Store Developer Support

**Comment by glacambre** [comment]
There were probably issues with static resources not being present and the contents of the archive I submitted having the wrong directory structure. This happened because I finally started automating the release-creation process. I fixed it and submitted a new release to both the Firefox addon store and the Chrome web store.

**Comment by marcopullo** [comment]
@glacambre seems like this may have broke the Chrome extension, I'm unable to install Firenvim.

1. Go to Chrome Web store: https://chrome.google.com/webstore/detail/firenvim/egpjdkipkomnmjhjmdamaniclmdlobbo?hl=en
2. Click `Add to Chrome`. Confirm permissions and click `Add Extension`.
3. Installation fails with error message:
```
An error has occurred
Could not decode image: 'firenvim16.png'
```

Googling around says this happens if manifest image is too big or an invalid format.

**Comment by glacambre** [comment]
Yup, there was a problem with my automated release process. I fixed it yesterday and submitted a new Firenvim release to the chrome store, it should become available on wednesday or thursday (that is, if the Google review process goes fine…).

Thanks for reporting this and sorry for the inconvenience.

**Comment by marcopullo** [comment]
I've been patiently waiting for someone to create this since I first learned of neovim, so what's a few more days :). Awesome project btw!
