### ISSUE TITLE
firenvim editor frame sometimes starts unfocused

### ISSUE THREAD

**Issue by infokiller** [glacambre/firenvim#419]
- OS Version: linux x86-64 (Arch 5.4.19.a-1-hardened)
- Browser Version: Google Inc. Chrome 80.0.3987.100
- Browser Addon Version: 0.1.20
- Neovim Plugin Version: 0.1.20
- What I tried to do: click on a textarea to start editing using firenvim
- What happened: the firenvim iframe appeared correctly but gets out of focus, which requires me to click on it again in order to interact with it

I verified this is not related to my vimrc by following [the troubleshooting](https://github.com/glacambre/firenvim/blob/afca3bdd9003a74c73a54873fac248d8ad4a9c32/TROUBLESHOOTING.md#make-sure-its-not-your-initvim).
This issue is inconsistent- sometimes the firenvim frame is focused and sometimes not. It seems to happen more often (or only) with relatively small text areas.
To reproduce this, I'm using [this webpage](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea). I click on the right textarea, reload a few times, and repeat until this issue happens. Here's a screencast of what happens:

![test](https://user-images.githubusercontent.com/10516814/74546800-d012e300-4f53-11ea-8108-7a243ce412c7.gif)

Note that the second time I click on the textarea the frame is slightly dimmed.

**Comment by infokiller** [comment]
Just a quick update that I can't reproduce this on my laptop which runs almost exactly the same software as my desktop (where I was able to reproduce this bug).

**Comment by glacambre** [comment]
Thanks for the update :).
This is probably caused by a race condition that will most probably disappear in the next Firenvim release :).

**Comment by infokiller** [comment]
Another issue that seems related (please let me know if you want me to open a separate issue for it):
Sometimes when I type in the firenvim frame it seems some keys are "swallowed" (firenvim behaves as if they weren't typed). I think there's usually also a mini flash of the iframe when that happens.
BTW, it case it wasn't clear: both issues only started in a recent version of firenvim (between 1 to 2-3 months ago).

**Comment by glacambre** [comment]
Hi @infokiller, I released a new version that I believe should fix most of your problems, could you upgrade to Firenvim 0.1.23 and see if you can still reproduce the bugs you mentionned?

**Comment by infokiller** [comment]
Sure thing, just upgraded, though given this is a non-deterministic issue, it may take 3-4 weeks till I can be reasonably confident that this issue is fixed (depending on how much I'll happen to do in-browser text editing during this time).

**Comment by infokiller** [comment]
I haven't ran into this issue during this time, so I'll go ahead and close it.

**Comment by glacambre** [comment]
Great - thanks for letting me know and closing this issue! :)
