### ISSUE TITLE
Tridactyl hints show below firenvim

### ISSUE THREAD

**Issue by NilsIrl** [glacambre/firenvim#423]
- OS Version: linux x86-64
- Browser Version:  Firefox 72.0.2
- Browser Addon Version: 0.1.20
- Neovim Plugin Version: master (2020-02-16)

- What I tried to do:

Press "f" with tridactyl for hints to show up.

- What happened:

Hint for the textarea doesn't show up. The most likely cause being it is below the firenvim window.

**Comment by glacambre** [comment]
Fixed in #425 - thanks for the report :)
