### ISSUE TITLE
External commandline doesn't always disappear after display

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#448]
- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 80.0.3987.116
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.21
- What I tried to do: Correct a spelling mistake with `z=`
- What happened: The spelling suggestions menu persisted after my selection, when I would have expected it to disappear (it covers the screen)

**Comment by glacambre** [comment]
This happens because of https://github.com/neovim/neovim/issues/11558 . One workaround is to change your `cmdline` setting back to `neovim`. Another one is to press `:` to make it disappear :).

**Comment by BlueDrink9** [comment]
Sounds like it's time for a workaround mapping. Thank you!

**Comment by glacambre** [comment]
The new renderer fixes this issue :)

**Comment by BlueDrink9** [comment]
Does this require nightly nvim? I'm still getting this with firenvim 0.2.0 on nvim 0.4.3

**Comment by glacambre** [comment]
Woops, sorry, looks like I closed this a bit too fast. The new renderer is more aggressive about killing messages but still not enough apparently :)

**Comment by glacambre** [comment]
I've opened https://github.com/neovim/neovim/pull/13903 , I'll close this issue once it's merged :).

**Comment by glacambre** [comment]
Closing this as my patch is now merged in neovim's master branch. Thanks for the report :)

**Comment by BlueDrink9** [comment]
I just tried neovim nightly, and I still seem to be having this issue. The spelling suggestions box, and the box saying the file name on startup, all stay hanging around until I open the command line.

**Comment by glacambre** [comment]
@BlueDrink9 Thanks for the report. Could you describe the steps you take to reproduce this issue? Because `z=` doesn't reproduce this bug anymore for me.

**Comment by BlueDrink9** [comment]
My apologies, seems to be working now. I didn't double-check that the nvim I was running in firenvim was nightly, so maybe it was still on 0.43.
