### ISSUE TITLE
Try to guess filetype from fancy editor settings

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#456]
CodeMirror and Ace probably have a way to retrieve the current language. This could be used to choose a better filename extension.

**Comment by NilsIrl** [comment]
We should find a standard way to indicate the language of a `textarea`. (For websites and extensions)

**Comment by benhormann** [comment]
I was just about to raise a suggestion for this. The following methods might not be documented, but are slightly more convenient than the documented counterparts.

CodeMirror:
editor.getOption('mode') // e.g. "application/json" or "text/javascript"

Ace:
editor.getOption('mode') // e.g. "ace/mode/json" or "ace/mode/javascript"

Monaco:
model.getModeId() // e.g. "json" or "javascript"

I was hoping to find the actual file name, but the editor doesn't really need to know so not getting my hopes up.
Or you could add a config item to allow a selector/lambda that returns the filename, per site? (site's like JSFiddle/CodePen don't have a file names, at least not visibly).

Random note: Over at Glitch.com, .js files are always in "text/jsx" mode...
