### ISSUE TITLE
Interesting repo

### ISSUE THREAD

**Issue by pvinis** [glacambre/firenvim#462]
Check out https://github.com/GhostText/GhostText, maybe this can work together with that? Not exactly the same way to do the same thing, but pretty close from the user's perspective.

**Comment by alerque** [comment]
@pvinis As a former user of GhostText before switching to Firenvim, I have no idea what you are trying to suggest here. GhostText was nice as long as it was the best option for using a real editor, but Firenvim's approach is much newer technology and light-years beyond what GhostText was accomplishing. The end result is _not close_ from (this) users perspective, one uses an external editor window and one embedes a full editor in the browser window.

Having used both extensively I would suggest that there is nothing that could "work together", they are different approaches to the same problem and the user is free to choose which approach suits their workflow, but it's kind of a one-or-the-other situation.

If you have a more concrete suggestion please elaborate...

**Comment by glacambre** [comment]
I know about GhostText (in fact, I even wanted to [steal code](https://github.com/GhostText/GhostText/issues/140#issuecomment-553733169) from them). One thing that I have thought about was that we could share the code that interacts with the page's editors ([here's firenvim's](https://github.com/glacambre/firenvim/tree/master/src/editors) and [here's GhostText's](https://github.com/GhostText/GhostText/tree/master/browser/scripts/InputArea)). There are two reasons I chose not to do this:

- I don't want to maintain an npm package
- I don't want to add a dependency I don't control to Firenvim for something this trivial

**Comment by pvinis** [comment]
I found it today and it seems like an easier-to-install way to do editing on an actual editor. I know that firenvim is better, but I remember having trouble installing it and making it work, but I did enjoy using it.

We can close the issue I guess now that you both have feedback on this.

Keep the great work up!
