### ISSUE TITLE
Firejail / apparmor / flatpack & friends support

### ISSUE THREAD

**Issue by cjsthompson** [glacambre/firenvim#469]
Firenvim does not work with firejail, apparmor and probably other such security tools because these prevent browsers from executing programs in the home directory for good reason. The Firenvim browser plug-in should be using D-Bus on UNIX for starting neovim.

**Comment by glacambre** [comment]
Firenvim does work with apparmor, you just need to change your ruleset to allow firefox to execute `~/.local/share/firenvim/firenvim` and neovim. The same is true of firejail.

This is a configuration issue on your machine :)

**Comment by cjsthompson** [comment]
Allowing programs to execute things in $HOME is a security hole.

**Comment by glacambre** [comment]
Can you explain in detail how allowing firefox to execute `~/.local/share/firenvim/firenvim` is less secure than allowing it to execute `/usr/bin/firenvim`?

**Comment by cjsthompson** [comment]
Sure. With D-Bus it wouldn't be executing /usr/bin/firenvim but /usr/bin/nvim directly which would itself be started in a sandbox. ~/.local/share/firenvim/firenvim is not in a sandbox.

**Comment by glacambre** [comment]
WebExtension APIs do not let you start anything with d-bus, you have to have your own binary that will be executed by firefox. This binary can be anywhere on the machine and can either exec nvim directly or ask D-Bus to do it, but it has to exist.

**Comment by cjsthompson** [comment]
I see. I assumed firefox supported D-Bus since it has a hard dependency on dbus-glib. You can't do much about it until Firefox fixes that problem indeed.
