### ISSUE TITLE
Chrome rejected new Firenvim version (again)

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#475]
The chrome web store rejected v0.1.22. Gotta fight the G-men again.

**Comment by alerque** [comment]
What's their beef (in brief)?

**Comment by glacambre** [comment]
They sent me the "Firenvim doesn't work" email that can be found here: https://github.com/glacambre/firenvim/issues/410#issuecomment-587109142

**Comment by glacambre** [comment]
Submitted a new version on the chrome web store which should become available in 3-4 days if it isn't rejected again.

**Comment by fogine** [comment]
well, without changelog or realease notes, I can not really care even though I'd like to :)
Stumbled upon this plugin today... great work!

**Comment by glacambre** [comment]
>Stumbled upon this plugin today... great work!
Thanks :)

There's a changelog [here](https://addons.mozilla.org/en-US/firefox/addon/firenvim/versions/). The Chrome web store doesn't have a changelog section as far as I know.

**Comment by fogine** [comment]
@glacambre thanks for the link. I my  humble opinion  I wouldn't bother putting changelog on chrome/firefox store  as nobody will find it there. It would be helpful to have it in the repo, at root as `README.md`...

**Comment by glacambre** [comment]
@fogine I'll add changelogs to the commits that are tagged, thanks for the suggestion :).

Firenvim 0.1.23 has been accepted by the chrome web store, so I'll close this issue.
