### ISSUE TITLE
Save on focus lost

### ISSUE THREAD

**Issue by Shatur95** [glacambre/firenvim#491]
Thank for your plugin! Is it possible to save firenvim buffer on focus lost?
I tried the following:

```vim
autocmd FocusLost,InsertLeave,BufLeave * ++nested write
```

But it not works for me.

**Comment by glacambre** [comment]
InsertLeave/BufLeave are triggered by neovim when you leave insert mode/move the cursor to another buffer, so there's nothing I can do for you if these do not work.

Neovim lacks a proper way to inform it that a UI has lost focus, I worked around this in #492 by manually triggering the FocusLost/FocusGained events. This means that in Firenvim 0.1.24, `autocmd FocusLost * ++nested write` will start working.

Thanks for opening this issue :)

**Comment by NilsIrl** [comment]
Could this be a regression? https://github.com/glacambre/firenvim/issues/117#issuecomment-549342723

**Comment by glacambre** [comment]
I don't think so - there's really no way for neovim to know if/when the UI loses focus. These two comments probably are more about InsertLeave than FocusLost.

**Comment by Shatur95** [comment]
@glacambre, thank you a lot!
