### ISSUE TITLE
Error detected while processing TextChanged Autocommands for "*":

### ISSUE THREAD

**Issue by yaohunzhanyue** [glacambre/firenvim#496]
vimrc
```
"auto save changes to page
autocmd TextChanged * ++nested write
autocmd TextChangedI * ++nested write
```
:message
```
Error detected while processing TextChanged Autocommands for "*":
```

**Comment by glacambre** [comment]
I don't have any error messages. Could you disable all your other neovim plugins and see if you can still reproduce this?

**Comment by yaohunzhanyue** [comment]
@glacambre Can't be reproduced, hard to find which plugin caused this error, I have too much plugin installed = =!
