### ISSUE TITLE
Rejected from the chrome web store again

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#518]
# Previous installments:
- https://github.com/glacambre/firenvim/issues/410
- https://github.com/glacambre/firenvim/issues/475

# Rejection email:

>Dear Developer,
>
>Your recent publish request for Google Chrome item "Firenvim" with ID: egpjdkipkomnmjhjmdamaniclmdlobbo was rejected because it did not comply with our policies.
>
>If you already have a published version of this item on the Chrome Web Store, it has not been affected and is still available.
>
>Your item did not comply with the following section of our Program Policies:
>
>"User Data Privacy"
>
>Your product violates the "Use of Permissions" section of the policy, which requires that you:
>
>    Request access to the narrowest permissions necessary to implement your product’s features or services.
>    If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
>    Don't attempt to "future proof" your product by requesting a permission that might benefit services or features that have not yet been implemented.
>
>
>Once your item complies with Chrome Web Store policies, you may request re-publication in the Chrome Web Store Developer Dashboard. Your item will be reviewed for policy compliance prior to re-publication.
>
>If you have any questions about this email, please respond and the Chrome Web Store Developer Support team will follow up with you.
>
>
>Important Note:
>
>Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform.
>
>This may also result in the suspension of related Google services associated with your Google account.
>
>
>Sincerely,
>
>Chrome Web Store Developer Support

# My Reply:

Dear Chrome Web Store team,

On 2020-04-21 08:36, Chrome Web Store Developer Support wrote:
> Your item did not comply with the following section of our Program 
> Policies <https://developer.chrome.com/webstore/program_policies>:
> 
> 
> "User Data Privacy"
> 
> Your product violates the "Use of Permissions" section of the policy, 
> which requires that you:
> 
>   * Request access to the narrowest permissions necessary to implement
>     your product’s features or services.
>   * If more than one permission could be used to implement a feature,
>     you must request those with the least access to data or functionality.
>   * Don't attempt to "future proof" your product by requesting a
>     permission that might benefit services or features that have not yet
>     been implemented.

Firenvim, whose goal is to let users communicate with the Neovim software they installed on their computer, only asks for three permissions:
- nativeMessaging: Required in order to start Neovim.
- storage: Required in order to save settings.
- tabs: Required in order to redispatch commands received by the background to the current tab, to store tab-specific values and to update the browserAction depending on the active tab.

On top of that, Firenvim requires the <all_urls> permission in order to be able to add event listeners to the page as soon as it loads in order to detect when the elements Firenvim users want to use Firenvim with are focused, but also to react to commands sent from the background script or the browserAction. There is no other way to do this.

I will also point out that Firenvim has used these permissions for multiple months/releases and that you used to deem them acceptable.

Please tell me what permissions you think Firenvim doesn't need and why.

**Comment by alerque** [comment]
Again? Great review process they have over there. At least they are consistent.

**Comment by glacambre** [comment]
# New email

Dear Developer, 
 

Upon review of your Product, we find that it does not comply with the Chrome Web Store’s User Data Policy, and it has been removed from the store.
 

Your Product violates the “Use of Permissions” section of the policy, which requires that you:
 

Request access to the narrowest permissions necessary to implement your Product’s features or services. If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
 

Don't attempt to "future proof" your Product by requesting a permission that might benefit services or features that have not yet been implemented.
 

To reinstate your Product, please ensure that your Product requests and uses only those permissions that are necessary to deliver the currently stated product’s features. 
 

If you’d like to re-submit your Product, please modify your Product so that it complies with the Chrome Web Store’s Developer Program Policies, then re-publish it in your Developer Dashboard. 
 

Please reply to this email for questions / clarifications regarding this Product removal.
 

Thank you for your cooperation,

Google Chrome Web Store team
 

---------------------------
 

Resubmission

If you resubmit your Product, it will not be immediately published live in the store. All re-submitted Products undergo a strict compliance review and will be re-published only if the Product passes that review.
 

Important Note

Repeated or egregious violations of the policies may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted Products will continue to be subject to the Chrome Web Store Program Policies and Terms of Service. 
 

Program Policies:

https://developers.google.com/chrome/web-store/program_policies
 

Developer Terms of Service: 

https://developers.google.com/chrome/web-store/terms
 

User Data Policy Chromium Blog Post:

http://blog.chromium.org/2016/04/ensuring-transparency-and-choice-in.html
 

Branding Guidelines: 

https://developers.google.com/chrome/web-store/branding
 

User Data Policy FAQ: 

https://developer.chrome.com/webstore/user_data

Chrome Web Store Developer Dashboard 

https://chrome.google.com/webstore/developer/dashboard

# My Reply

Not replying to this one. Logging into the Chrome Web Store, it looks like the Firenvim version I uploaded for review two days ago is still pending review.

**Comment by alerque** [comment]
What about repeated or egregious negligence during the review process?

**Comment by glacambre** [comment]
> What about repeated or egregious negligence during the review process?

I doubt there are actual humans reading Firenvim's source code/my 
replies, it's probably all automated. I'm wondering if there's something 
special in Firenvim's source code that sets of automated alarms. There 
are places where I have to basically `eval()` strings to get them to 
execute in the page's context rather than in the webextension's, this is 
something that would destroy the precision of any static analyzer.

I can't work around this unfortunately. Hopefully one day Firenvim will 
be perfect and never need to be uploaded to the Chrome Web Store again :).

**Comment by glacambre** [comment]
# New Email

Dear Developer,

Your recent publish request for Google Chrome item "Firenvim" with ID: egpjdkipkomnmjhjmdamaniclmdlobbo was rejected because it did not comply with our policies.

If you already have a published version of this item on the Chrome Web Store, it has not been affected and is still available.

Your item did not comply with the following section of our Program Policies:

"User Data Privacy"

Your product violates the "Use of Permissions" section of the policy, which requires that you:

    Request access to the narrowest permissions necessary to implement your product’s features or services.
    If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
    Don't attempt to "future proof" your product by requesting a permission that might benefit services or features that have not yet been implemented.


Once your item complies with Chrome Web Store policies, you may request re-publication in the Chrome Web Store Developer Dashboard. Your item will be reviewed for policy compliance prior to re-publication.

If you have any questions about this email, please respond and the Chrome Web Store Developer Support team will follow up with you.


Important Note:

Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform.

This may also result in the suspension of related Google services associated with your Google account.


Sincerely,

Chrome Web Store Developer Support

# My reply

On 2020-04-27 08:10, Chrome Web Store Developer Support wrote:
> Dear Developer,
>
> Your recent publish request for Google Chrome item "Firenvim" with ID: egpjdkipkomnmjhjmdamaniclmdlobbo was rejected because it did not comply with our policies.
>
> If you already have a published version of this item on the Chrome Web Store, it has not been affected and is still available.
>
>
> Your item did not comply with the following section of our Program Policies <https://developer.chrome.com/webstore/program_policies>:
>
>
> "User Data Privacy"
>
> Your product violates the "Use of Permissions" section of the policy, which requires that you:
>
>   * Request access to the narrowest permissions necessary to implement
>     your product’s features or services.
>   * If more than one permission could be used to implement a feature,
>     you must request those with the least access to data or functionality.
>   * Don't attempt to "future proof" your product by requesting a
>     permission that might benefit services or features that have not yet
>     been implemented.

Firenvim, whose goal is to let users communicate with the Neovim software they installed on their computer, only asks for three permissions:

- nativeMessaging: Required in order to start Neovim.
- storage: Required in order to save settings.
- tabs: Required in order to redispatch commands received by the background to the current tab, to store tab-specific values and to update the browserAction depending on the active tab.

On top of that, Firenvim requires the <all_urls> permission in order to be able to add event listeners to the page as soon as it loads in order to detect when the elements Firenvim users want to use Firenvim with are focused, but also to react to commands sent from the background script or the browserAction. There is no other way to do this.

I will also point out that Firenvim has used these permissions for multiple months/releases and that you used to deem them acceptable.

Please tell me what permissions you think Firenvim doesn't need and why.

**Comment by glacambre** [comment]
# Received on April 27

Dear Developer,

To have your item reinstated, please re-publish it in your developer dashboard. 

Thank you for your cooperation,

Google Chrome Web Store team

Please take a minute and click on the link to answer a quick survey below about your experience with us so we can improve our service- https://goo.gl/forms/oO6SYi3ToUq2rBnU2

# My reply

I didn't reply. I had already re-uploaded Firenvim on the chrome web store.

# Today

Dear Developer,

Your recent publish request for Google Chrome item "Firenvim" with ID: egpjdkipkomnmjhjmdamaniclmdlobbo was rejected because it did not comply with our policies.

If you already have a published version of this item on the Chrome Web Store, it has not been affected and is still available.

Your item did not comply with the following section of our Program Policies:

"User Data Privacy"

Your product violates the "Use of Permissions" section of the policy, which requires that you:

    Request access to the narrowest permissions necessary to implement your product’s features or services.
    If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
    Don't attempt to "future proof" your product by requesting a permission that might benefit services or features that have not yet been implemented.


Once your item complies with Chrome Web Store policies, you may request re-publication in the Chrome Web Store Developer Dashboard. Your item will be reviewed for policy compliance prior to re-publication.

If you have any questions about this email, please respond and the Chrome Web Store Developer Support team will follow up with you.

# My Reply

Dear Chrome Web Store team,

On 2020-04-30 11:01, Chrome Web Store Developer Support wrote:
> Dear Developer,
> 
> Your recent publish request for Google Chrome item "Firenvim" with ID: 
> egpjdkipkomnmjhjmdamaniclmdlobbo was rejected because it did not comply 
> with our policies.
> 
> If you already have a published version of this item on the Chrome Web 
> Store, it has not been affected and is still available.
> 
> 
> Your item did not comply with the following section of our Program 
> Policies <https://developer.chrome.com/webstore/program_policies>:
> 
> 
> "User Data Privacy"
> 
> Your product violates the "Use of Permissions" section of the policy, 
> which requires that you:
> 
>   * Request access to the narrowest permissions necessary to implement
>     your product’s features or services.
>   * If more than one permission could be used to implement a feature,
>     you must request those with the least access to data or functionality.
>   * Don't attempt to "future proof" your product by requesting a
>     permission that might benefit services or features that have not yet
>     been implemented.
> 
> 
> Once your item complies with Chrome Web Store policies, you may request 
> re-publication in the Chrome Web Store Developer Dashboard 
> <https://chrome.google.com/webstore/developer/dashboard>. Your item will 
> be reviewed for policy compliance prior to re-publication.
> 
> 
> If you have any questions about this email, please respond and the 
> Chrome Web Store Developer Support team will follow up with you.

Please tell me what permissions you believe Firenvim doesn't need and why.

**Comment by glacambre** [comment]
# New email

Dear Developer, 
 

Upon review of your Product, [Firenvim], with ID: [egpjdkipkomnmjhjmdamaniclmdlobbo], we find that it does not comply with the Chrome Web Store’s User Data Policy, and it has been removed from the store.
 

Your Product violates the “Use of Permissions” section of the policy, which requires that you:
 

Request access to the narrowest permissions necessary to implement your Product’s features or services. If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
 

**Don't attempt to "future proof" your Product by requesting a permission that might benefit services or features that have not yet been implemented.**
 

To reinstate your Product, please ensure that your Product requests and uses only those permissions that are necessary to deliver the currently stated product’s features. 
 

If you’d like to re-submit your Product, please modify your Product so that it complies with the Chrome Web Store’s Developer Program Policies, then re-publish it in your Developer Dashboard. 
 

Please reply to this email for questions / clarifications regarding this Product removal.
 

Thank you for your cooperation,

Google Chrome Web Store team

# My Reply:

Dear Chrome Web Store team,

On 2020-05-01 14:07, chromewebstore-dev-support@google.com wrote:
> Dear Developer,
> 
> Upon review of your Product, [Firenvim], with ID: 
> [egpjdkipkomnmjhjmdamaniclmdlobbo], we find that it does not comply with 
> the Chrome Web Store’s User Data Policy, and it has been removed from 
> the store.
> 
> Your Product violates the “Use of Permissions” section of the policy, 
> which requires that you:
> 
> Request access to the narrowest permissions necessary to implement your 
> Product’s features or services. If more than one permission could be 
> used to implement a feature, you must request those with the least 
> access to data or functionality.
> 
> *Don't attempt to "future proof" your Product by requesting a permission 
> that might benefit services or features that have not yet been implemented.*
> 
> To reinstate your Product, please ensure that your Product requests and 
> uses only those permissions that are necessary to deliver the currently 
> stated product’s features.
> 
> If you’d like to re-submit your Product, please modify your Product so 
> that it complies with the Chrome Web Store’s Developer Program Policies, 
> then re-publish it in your Developer Dashboard.
> 
> Please reply to this email for questions / clarifications regarding this 
> Product removal.

Firenvim uses all permissions mentioned in its manifest. Please describe what permissions you believe Firenvim doesn't need and why.

**Comment by glacambre** [comment]
# New email

Dear Developer,

Thank you for your item resubmission. Your item has been reviewed and will be available in the Chrome Web Store within 30 minutes.

Thank you for your cooperation.

Google Chrome Web Store team

Your feedback is always welcome. If you’d like, follow the link below to a quick survey about your experience with us so we can improve our service:

# My reply

No reply, Firenvim 0.1.27 has indeed been released on the Chrome Web Store.

**Comment by BlueDrink9** [comment]
What a nightmare. Thanks for sharing the emails here, and for continuing to support chrome despite all this
