### ISSUE TITLE
Firenvim sometimes fails to load buffer when plugin colourscheme is used

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#521]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 80.0.3987.163
- Browser Addon Version: 0.1.23
- Neovim Plugin Version: 0.1.24

# Description

Here's a funky one. I was having an issue where anywhere between 10-70% of the time, (using a key shortcut to re-trigger firenvim) firenvim was loading a blank nvim window with no buffer. I eventually narrowed it down to loading a colourschemefrom a plugin. Also tested with iCyMind/NeoSolarized and reedes/vim-colors-pencil. Same result with NeoSolarized, pencil didn't seem to have the issue. No issue with colourscheme 'default' or 'morning'.

By 'blank with no buffer' I mean it looked like a new nvim/vim instance. New file, no filename, none of the contents of the textbox.

Minimal reproduction (put in `firenvim` launch script.)

```
test=$(cat <<-END
call plug#begin('~/.vim/plugins') |
Plug 'https://github.com/glacambre/firenvim' |
Plug 'cormacrelf/vim-colors-github' |
call plug#end() |
colo github
END
)

exec '/path/to/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()' -u NORC --cmd 'set rtp+=$HOME/.vim/plugins/firenvim' -c "$test" 2>> ~/.logs/firenvim.err
```

**Comment by glacambre** [comment]
Thanks for reporting this issue. I believe this has been fixed in Firenvim v0.1.24, so I'll wait for #518 to be closed before investigating this one. If you're using Neovim nightly, I believe you can work around this bug by switching to a version built from this commit or earlier: https://github.com/neovim/neovim/commit/4139678f97ee556ab142031a1ed5c7580278b64f .

**Comment by BlueDrink9** [comment]
Thank you.

**Comment by glacambre** [comment]
@BlueDrink9 Firenvim 0.1.27 has been released on the chrome web store. Could you upgrade to that and let me know if you can still reproduce this issue?

**Comment by BlueDrink9** [comment]
It's gone, thank you!
