### ISSUE TITLE
Cursor doesn't change colour with colourscheme/background

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#525]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 80.0.3987.163
- Browser Addon Version: 0.1.23
- Neovim Plugin Version: 0.1.24
- What I tried to do: Used NORC option, then opened firenvim and tried to see the cursor with a light theme like vim-colors-github
- What happened: The cursor is invisible. Changing to any other theme shows that regardless of `colorscheme` or `background`, the cursor remains pure white.
- Expected behavior: At the very least the cursor should be black if background=light. I think terminal neovim just takes the cursor colour from the terminal by default, but `guicursor` can be used to specify its colour if needed.

I thought this might have been #309 at first, but my `guicursor` was set so I looked further.

**Comment by BlueDrink9** [comment]
https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-color-in-the-terminal

**Comment by glacambre** [comment]
Yep, looks like I'm using default fg/bg colors instead of the colors provided by `:guicursor`. Shouldn't be too hard to fix.

**Comment by BlueDrink9** [comment]
Oddly this doesn't occur with the following setup:

- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 80.0.3987.163
- Browser Addon Version: 0.1.23
- Neovim Plugin Version: 0.1.23

**Comment by glacambre** [comment]
I think you're just lucky enough to get a default cursor color that is 
visible :).

**Comment by BlueDrink9** [comment]
Correct. When I try with a dark colourscheme it becomes hard to see again.

But it does help explain why it took so long for me to report this, because before I noticed the pattern here it seemed random.

**Comment by glacambre** [comment]
Fixed in 756a54d - if you're using the addon from the chrome web store, you'll have to wait for #518 to be fixed before getting the fix :)
