### ISSUE TITLE
Input cursor virtually invisible

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#531]
- OS Version: linux x86-64
- Browser Version:  Firefox 75.0
- Browser Addon Version: 0.1.25
- Neovim Plugin Version: 0.1.25

After also getting bitten by #530 I did get both sides updated to 0.1.25 and Firefox restarted once cleanly on top of that. Everything functions _mostly_ as it should, but since the update the input cursor is nearly invisible. In fact in my favorite colorscheme (molokai) it is completely invisible, but I think that's because the background is not jet-black, only very dark grey. Switching to the default colorscheme I do actually see the cursor, but it is itself very dark grey, now against black.

I suppose it might work fine with a light color scheme, but the cursor color should not be hard coded, it should adapt to the colorscheme.

Sample using default colorscheme: 

![image](https://user-images.githubusercontent.com/173595/80346272-274a0380-8873-11ea-899a-d17c042cc7a6.png)

Yes there is a cursor there after `colorscheme: |`, but you can barely see it.

**Comment by alerque** [comment]
Likely related to #525.

**Comment by alerque** [comment]
Workaround from duplicate issue:

> ```viml
> hi Cursor ctermfg=black ctermbg=red guifg=black guibg=red
> set guicursor=n-v-c-i-ci-ve-r-cr:block-Cursor
> ```

**Comment by glacambre** [comment]
I'm happy to report that this is Not My Fault™: https://github.com/neovim/neovim/issues/12198 .

**Comment by glacambre** [comment]
Closed in 9da9110577e0b5699541cc307d74297d5ae496ac .

**Comment by glacambre** [comment]
I've published an update containing 9da9110 for firefox, and now I see that the cursor is only visible after entering insert mode once. Progress but not fixed yet.

**Comment by glacambre** [comment]
Fixed.

**Comment by BlueDrink9** [comment]
To clarify, is this fixed in 0.1.27 but only if using a neovim with neovim/neovim#12211 included? I'm still getting it on stable neovim with 0.1.27. Or has this firenvim fix just not been released yet?

**Comment by glacambre** [comment]
This is fixed and available in Firenvim v0.1.27. If you're still 
encountering issues, this means that the problem lies with your 
colorscheme. To confirm the problem doesn't come from Firenvim, you 
should be able to reproduce this issue in a terminal with 24-bit colors 
by setting the `termguicolors` setting.
