### ISSUE TITLE
Cursor is invisible

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#532]
- OS Version: linux x86-64
- Browser Version:  Firefox 75.0
- Browser Addon Version: 0.1.25
- Neovim Plugin Version: 0.1.24

Workaround:
```vim
hi Cursor ctermfg=black ctermbg=red guifg=black guibg=red
set guicursor=n-v-c-i-ci-ve-r-cr:block-Cursor
```

**Comment by alerque** [comment]
Duplicate of #531.

**Comment by glacambre** [comment]
Thanks for reporting #531 :)
