### ISSUE TITLE
Breaks when using HTTPS Everywhere encryption

### ISSUE THREAD

**Issue by AtomToast** [glacambre/firenvim#533]
- OS Version: linux x86-64
- Browser Version: Firefox 75.0
- Browser Addon Version: 0.1.26
- Neovim Plugin Version: 0.1.26
- What I tried to do: use the HTTPS Everywhere option "Encrypt All Sites
  Eligible"
- What happened: The Browser automatically upgraded the websocket connection to
  wss and then couldn't establish the connection to the local firenvim socket
  anymore.

**Comment by alerque** [comment]
Curious. I'm using *HTTPS Everywhere* too and haven't had this problem.

**Comment by AtomToast** [comment]
It only occured when turning on the second checkbox. It's disabled by default.

Then I could see inside of the browser console that first it upgrades from ws to wss and then firenvim throws an error because it can't connect

**Comment by glacambre** [comment]
Hi, thanks for reporting this issue. Unfortunately this is the same issue as #145: HTTPS everywhere adds a `upgrade-insecure-requests` field to the website's CSP and Firefox thus tries to upgrade the websocket. Websites' CSP shouldn't apply to webextensions and changing this requires changes in Firefox itself.

I'll close this issue in favor of #145.
