### ISSUE TITLE
Focus issue with CodeWars

### ISSUE THREAD

**Issue by Shatur95** [glacambre/firenvim#539]
- OS Version: linux x86-64
- Browser Version:  Firefox 75.0
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do:
1. Open any karta on CodeWars, for example [this](https://www.codewars.com/kata/55983863da40caa2c900004e/train/c).
2. Focus code field.
3. Focus test filed.
- What happened:
Focus becomes broken, it switches from one buffer to another automatically.

**Comment by glacambre** [comment]
Works fine for me. Can you still reproduce if you replace your init.vim with one that only loads Firenvim?

**Comment by Shatur95** [comment]
I'm sorry, for unknown reason my message wan not updated :(
The problem in `autocmd vimrc FocusLost * ++nested write`. Without this setting everything works.
BTW, here is Vimrc only for Firenvim (I tested without any plugins):
```vim
" Custom group for all autocmd's in configuration
augroup vimrc
    autocmd!
augroup END

if exists('g:started_by_firenvim')
  set laststatus=0

  autocmd vimrc FocusLost * ++nested write

  nnoremap <silent> <Esc><Esc> :call firenvim#focus_page()<CR>
  nnoremap <silent> <C-z> :write<CR>:call firenvim#hide_frame()<CR>
endif
```

**Comment by glacambre** [comment]
When you unfocus the Firenvim frame, you trigger the FocusLost 
autocommand you created. The FocusLost autocommand triggers a BufWrite 
autocommand. When the BufWrite autocommand is triggered, Firenvim writes 
the buffer's content to the page. When the element's content changes, 
the page attempts to focus the element. When the page tries to focus the 
element, Firenvim redirects focus to the Firenvim frame. Add extra 
Firenvim instances for extra zaniness.

So everything is working as expected. I'm not sure what should change in 
order to make this bug disappear. I could make Firenvim give up on 
refocusing itself when three attempts occur in less than a second, but 
I'm not a fan of this solution.

**Comment by Shatur95** [comment]
Bad to hear :(
Looks like this issue is not fixable. The solution could be just disable automatic writing.

**Comment by Shatur95** [comment]
I found another solution:

```vim
autocmd vimrc FocusLost * ++nested write | call firenvim#hide_frame() | call firenvim#focus_page()
```

This will just hide frame on focus lost.

**Comment by glacambre** [comment]
Thanks for reporting. I am surprised to learn that this works though. 
I'll try to understand why it does and see if I can copy the bits that 
make it work in the logic triggered on `:write`.

**Comment by Shatur95** [comment]
Please, let me know if you figure it out :)
As for me, hiding Neovim is even more convenient.
