### ISSUE TITLE
Inserting link issue with GMail

### ISSUE THREAD

**Issue by Shatur95** [glacambre/firenvim#540]
- OS Version: linux x86-64
- Browser Version:  Firefox 75.0
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do:
1. Open GMail.
2. Open any message and click to answer.
3. Type any word.
4. Hide Firenvim buffer, select word and press Ctrl + K to insert link.
- What happened:
Finenvim buffer appears and link is not inserted. I can hide Firenvim, press Ctrl+z to cancel previous action and the link will be available. But If I activate Firenvim again - the link will disappear.

**Comment by glacambre** [comment]
I'm not sure I understand what the issue is (or are there multiple issues?).

If your problem is that Firenvim appears when you select a word/press Ctrl + k, this is something I can't do anything about, as Firenvim can't tell what it should do - the only thing it sees is a focus event on an element that you want to use Firenvim on (see the `selector` setting described in the README). One workaround for this could be to change your `takeover` setting for gmail (see the README).

If the problem is that Firenvim removes rich text information from the buffer when reading it, that's normal - neovim is a text editor, not a rich text editor. The best Firenvim could do here is to offer you to edit the HTML of Gmail's email directly, but in general the HTML produced by contenteditable elements is not easy to read/edit.

**Comment by Shatur95** [comment]
Yes, it just removes HTML. Is it possible to avoid it?

**Comment by glacambre** [comment]
> Yes, it just removes HTML. Is it possible to avoid it?

I'll add a setting that lets you edit HTML directly, but it probably 
won't have satisfying results.

**Comment by Shatur95** [comment]
I think you are right. If it will display the whole HTML it will be not very convenient. It would be better to just disable it for Gmail for me. Is there a way to disable it for specific website?

**Comment by glacambre** [comment]
> Is there a way to disable it for specific website?

Yes, read how to configure `localSettings` and `takeover` in the Readme. 
If things are unclear/you can't get it to work, please let me know :).

**Comment by Shatur95** [comment]
I tried to just insert the following settings from the readme:
```vim
let fc = g:firenvim_config['localSettings']
let fc['https?://[^/]+\.co\.uk/'] = { 'takeover': 'never', 'priority': 1 }
```
But Firenvim stopped working at all.

**Comment by glacambre** [comment]
You need to define a `g:firenvim_config` object that has a 
`localSettings` key - see the readme:

 >From now on, localSettings examples will use the let fc[...] = ... 
shorthand, assuming that you have defined a g:firenvim_config object and 
that you have a line like let fc = g:firenvim_config['localSettings'] in 
your config.

https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object

Did you find this part of the readme? If not, how would you make it 
easier to find?
If yes, how would you make it clearer?

**Comment by Shatur95** [comment]
Sorry, I just missed that I need to create `g:firenvim_config` object first :(
Now I tried only the following:
```vim
let g:firenvim_config = { 
  \ 'globalSettings': {
    \ 'alt': 'all',
  \ },
  \ 'localSettings': {
    \ '.*': {
      \ 'cmdline': 'neovim',
      \ 'priority': 0,
      \ 'selector': 'textarea',
      \ 'takeover': 'always',
      \ }
  \ }
\ }
```
And it somehow disabled GMail automatically. Is this because `selector` is `textarea`?

**Comment by glacambre** [comment]
On 2020-05-01 11:14, Hennadii Chernyshchyk wrote:
> Sorry, I just missed that I need to create |g:firenvim_config| object 
> first :(

No problem :)

> Now I tried only the following:
> 
> let  g:firenvim_config  =  {
>    \ 'globalSettings': {
>      \ 'alt':'all',
>    \ },
>    \ 'localSettings': {
>      \ '.*': {
>        \ 'cmdline':'neovim',
>        \ 'priority':0,
>        \ 'selector':'textarea',
>        \ 'takeover':'always',
>        \ }
>    \ }
> \ }
> 
> And it somehow disabled GMail automatically. Is this because |selector| 
> is |textarea|?

Exactly. If you take a look at Gmail's source code, you'll notice that 
Gmail doesn't use a `<textarea>` element - instead it uses a `<div>` 
element the `role` attribute of which is set to `textbox`.

**Comment by Shatur95** [comment]
Thank you a lot for explanations.
I think that the Readme is clear. But I suggest to provide example with default `g:firenvim_config`. As for me such example would be better.
