### ISSUE TITLE
Suggestion: Add api function to send javascript

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#542]
I was thinking about #322, and thinking about how slack won't recognise artificially sent input, and about how it would be neat to have a shortcut to submit git comments.

A lot of these might be solved by letting users run or map custom JS functions for different websites.

You might choose not to do this for security or technical reasons, but it seems like a useful API element to add.

**Comment by glacambre** [comment]
On 2020-05-03 06:28, BlueDrink9 wrote:
> I was thinking about #322 
> <https://github.com/glacambre/firenvim/issues/322>, and thinking about 
> how slack won't recognise artificially sent input, and about how it 
> would be neat to have a shortcut to submit git comments.

I don't understand what you mean by "having a shortcut to submit git 
comments", could you describe that?

> A lot of these might be solved by letting users run or map custom JS 
> functions for different websites.
> 
> You might choose not to do this for security or technical reasons, but 
> it seems like a useful API element to add.

I don't think this would add any security issues, but the one thing I'm 
concerned about is that when you add `eval` to your API, your whole 
program becomes an API: you can't change the architecture of anything 
anymore without risking breaking something for someone.

**Comment by BlueDrink9** [comment]
I was meaning mapping something to run js to click the comment button, or to click it on :wq

**Comment by BlueDrink9** [comment]
I don't understand what you mean in your second point but like I said, if you think this functionality would cause issues then ignore me.

Maybe an alternative would be to only allow calling js funcs rather than arbitrary code eval, and make people define hose funcs with greasemonkey?

**Comment by glacambre** [comment]
You'll be able to use `:call firenvim#eval_js('alert("Hello World!")')` in the next release - or right now, if you build from master :)

**Comment by BlueDrink9** [comment]
Praise the dev, I'm so impressed how quickly you implement feature requests

**Comment by BlueDrink9** [comment]
In case others stumble on this, this is the js I'm using for clicking the github comment button:

```javascript
document.getElementById("partial-new-comment-form-actions").getElementsByClassName("btn btn-primary")[0].click();
```

**Comment by BlueDrink9** [comment]
I have just started using this with Slack, and it works seamlessly.  Love being able to just chat like a normal chat app, but if I want to edit a message there is no dissonance when I go to use my vim bindings. Thank you!

Slack setup (you need to enable the 'send' button in the slack workspace settings, rather than using the enter key to send):

```vim

elseif l:bufname =~? 'slack.com'
    set ft=markdown
    " For chat apps. Enter sents the message and deletes the buffer.
    " Shift enter is normal return.
    imap <buffer> <s-CR> <CR>
    " Insert mode by default.
    normal! i
    " slack doesn't actually respond to press_keys (see firenvim readme).
    " Requires the send button to be enabled for this workspace.
    let l:clickSubmitButtonJS = "'document.getElementsByClassName(\"c-icon c-icon--paperplane-filled\")[0].click();'"
    exec 'inoremap <buffer> <CR> <Esc>:w<CR>:call firenvim#eval_js(' . l:clickSubmitButtonJS . ')<CR>ggdGa'
```
