### ISSUE TITLE
keybindings overridden in `chrome://extensions/shortcuts` (`Ctrl-W` etc) don't work in incognito

### ISSUE THREAD

**Issue by infokiller** [glacambre/firenvim#544]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 81.0.4044.129
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do: Define `Ctrl-W`/`Ctrl-N`/`Ctrl-T` in `chrome://extensions/shortcuts` and use them in incognito
- What happened: Nothing

They do work if I Firenvim is enabled in incognito:

![image](https://user-images.githubusercontent.com/10516814/80917579-8c689200-8d68-11ea-9127-9c4ee7ebc622.png)

**Comment by glacambre** [comment]
Mh, works for me. The only difference is that I'm using Chromium instead of Chrome. Are you sure the keybindings work in non-incognito mode? Could you try to reproduce this with a clean browser profile?

**Comment by glacambre** [comment]
Can reproduce. I can't do anything about this though, Chrome doesn't send events to Firenvim. I'd recommend opening an issue in Chrome's bug tracker. Please let me know if you do so :)

**Comment by infokiller** [comment]
Thanks for looking into this!
I'm using Chromium too. Indeed it seems that Chromium should have handled these keybindings if they're triggered in incognito and the extension is disabled there.
I probably won't open a bug in Chromium as I really doubt it will get prioritized...
Closing.
