### ISSUE TITLE
Vim window goes away in github after switching back from preview tab

### ISSUE THREAD

**Issue by rightaway** [glacambre/firenvim#548]
- OS Version: linux x86-64
- Browser Version:  Firefox 75.0
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do: Enter a new github issue then switch to the preview tab then switch back to write tab.
- What happened: The vim window appears when I first click the write tab. But then I switch to preview tab and back to write tab and it doesn't show the vim window anymore. `<C-e>` doesn't enable it either. It should turn into a vim window when I select the text box in the write tab again.

Could there be a way to have a right-click menu item "Open in neovim"?

**Comment by glacambre** [comment]
The fix will be available in Firenvim 0.1.28. If you want it now, you can build the browser addon from master.

Thanks for reporting this bug :) !
