### ISSUE TITLE
Doesn't handle cmd+v on osx

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#551]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 81.0.4044.138
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do: Paste with `cmd + v`
- What happened: It entered the literal character sequence `<D-v>`

MacVim handles cmd + v transparently. It will even paste if you first press <c-q> (in insert mode, to insert literal char).

I've been ignoring this for ages, but it's just habit (especially in browser, or if I'm not expecting firenvim to take over if I click a text box ready to paste). I tend to do it in macvim and terminal neovim too, which is why it's jarring for it to fail here.

`innoremap <D-v> <c-r>+` is a workaround.

**Comment by glacambre** [comment]
I think I want to keep the current behavior. I want Firenvim to be a 
dumb GUI that doesn't set any setting/map any mappings. As you said, 
people can just `innoremap <D-v> <C-r>+`, `nnoremap <D-v> "+p` and 
`vnoremap <D-v> "+p`.

**Comment by BlueDrink9** [comment]
That's reasonable. I'll let you close it, or see if others chime in

**Comment by benlieb** [comment]
For future reference I was able to cobble together comments online to get this, which seems to let cmd-v (<D-v) work. 

```
if exists('g:started_by_firenvim')
  tmap <D-v> <C-w>"+
  nnoremap <D-v> "+p
  vnoremap <D-v> "+p
  inoremap <D-v> <C-R><C-O>+
  cnoremap <D-v> <C-R><C-O>+
endif
```

For what it's worth I couldn't find how else to do it natively. I assume there is a way? Anyone want to share?

**Comment by glacambre** [comment]
>For what it's worth I couldn't find how else to do it natively.

What do you mean by "natively"? The mappings you provided are as native as can be as far as I can tell :)

**Comment by benlieb** [comment]
I mean native to Vim. I thought there might be a way to paste into vim that doesn't do the <D-v>. Is there?

**Comment by glacambre** [comment]
I'm still confused, `"+p` is native to Vim. `p` is just the paste command and `"+` just refers to the `+` register, which contains the clipboard's content. Why does it not fit your definition of native?

**Comment by benlieb** [comment]
Ok, I misunderstood that `+` referred to the clipboard.
