### ISSUE TITLE
Neovim is not responding in Firefox

### ISSUE THREAD

**Issue by bs** [glacambre/firenvim#553]
Thank you for your work on this! I'm getting the message '''Neovim is not responding in Firefox'''. Have gone through the troubleshooting guide. Lua and required packages are all there and running.

- OS Version: mac x86-64
- Browser Version:  Firefox 76.0
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: commit 48464e47f55ca982b77392b5358c390886a2f840
- What I tried to do:
Installed neovim plugin and made sure post hook script was run.
Installed luabittop
Installed firefox plugin
'''
❯ printf 'abcde{}' | $HOME/.local/share/firenvim/firenvim
{"version": "0.1.27"}%
'''
- What happened:
Extension reports Neovim is not responding.

<3

**Comment by glacambre** [comment]
Thanks for the thanks :)

What Neovim version are you using? How did you install it? Does this 
still happen if you empty your init.vim and only leave the part that 
loads Firenvim? Could you paste the content of 
`$HOME/.local/share/firenvim/firenvim` here?

**Comment by bs** [comment]
I’ll be back in front of my desktop tomorrow and will take a look! I saw vim throw an exception related to firenvim earlier today.

**Comment by glacambre** [comment]
@bs ping :)

**Comment by bs** [comment]
Hi! :)

Well, I've gotten a bit further. I reinstalled the plugin, and ensured that post install() method was run.

Now the plugin seems to recognize that nvim is available, but focusing a text area freezes and I see:

```
Content Security Policy: Upgrading insecure request ‘ws://127.0.0.1:61001/2166655364’ to use ‘wss’
Firefox can’t establish a connection to the server at wss://127.0.0.1:61001/2166655364.
```

My nvim stats:

_```_
❯ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

**Comment by glacambre** [comment]
That's a very useful error message - are you perhaps using HTTPS 
Everywhere? There are issues with this extension: 
https://github.com/glacambre/firenvim/issues/533.

In any case, there's nothing I can do since the root cause lies with 
firefox (see https://github.com/glacambre/firenvim/issues/145 for more 
information).

**Comment by bs** [comment]
Oh, that's interesting! I am using HTTPS Everywhere. Disabling it worked perfectly.

I was actually [debugging HTTPS everywhere](https://github.com/earthspecies/raven_change_path/issues/2) just before I checked in on this today. 🤪
