### ISSUE TITLE
Support request: Negative pattern for selector?

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#558]
I want to avoid triggering firenvim on a textarea of class=`crayon-plain print-no` on all pages.

Is there a way to do a negative pattern for the selector? Something like `!textarea[class="crayon-plain print-no"]` or `!div[class="crayon-plain-wrap"]`?
            

```vim
let g:firenvim_config = {
    \ 'globalSettings': {
        \ 'alt': 'alphanum',
    \  },
    \ 'localSettings': {
        \ '.*': {
            \ 'priority': 0,
            \ 'selector': 'textarea, div[role="textbox"], !textarea[class="crayon-plain print-no"]',
            \ 'cmdline': 'firenvim',
            \ 'takeover': 'nonempty',
        \ },
    \ }
\ }
```

**Comment by glacambre** [comment]
I think this should work:

let  g:firenvim_config  =  {
      \ 'globalSettings': {
          \ 'alt':'alphanum',
      \   },
      \ 'localSettings': {
          \ '.*': {
              \ 'priority':0,
              \ 'selector':'textarea:not([class=crayon-plain]), 
div[role="textbox"]',
              \ 'cmdline':'firenvim',
              \ 'takeover':'nonempty',
          \ },
      \ }
\ }

**Comment by BlueDrink9** [comment]
Yup, that worked with the full class name (`crayon-plain print-no`)

**Comment by BlueDrink9** [comment]
Actually unless you prefer otherwise, I'll leave this open until you update docs?

Also, how might we `and` multiple such conditions?

**Comment by glacambre** [comment]
On 2020-05-13 06:47, BlueDrink9 wrote:
> Actually unless you prefer otherwise, I'll leave this open until you 
> update docs?

Done.

> Also, how might we |and| multiple such conditions?

Just like you would in CSS: `x:not():not():not()`.

**Comment by BlueDrink9** [comment]
thanks. I don't know CSS and therefore didn't recognise it as such, so didn't look the rules up myself. Good to know.
