### ISSUE TITLE
[Feature Request] Microsoft edge for win10 support?

### ISSUE THREAD

**Issue by Username404-59** [glacambre/firenvim#560]
- OS Version: win x86-64
- Browser Version: Microsoft Edge 84.0.513.0 (Canary 64bits)
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do: :call firenvim#install()
- What happened: firenvim didn't create registry keys for microsoft edge
So is it possible to manually create a registry key?
I would really like to use neovim in my favorite browser!
Edit: I'm talking about the new chromium-based version of edge.

**Comment by glacambre** [comment]
On 2020-05-13 17:09, Username404-59 wrote:
>   * What happened: firenvim didn't create registry keys for microsoft edge
>     So is it possible to manually create a registry key?
>     I would really like to use neovim in my favorite browser!

The instructions detailing what the registry keys should look like are 
there:

https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging#registration-and-host-manifest

It looks like it's the same as Chrome's - so if you have Google Chrome 
installed on your computer, Firenvim should have already created the 
correct registry key. If you don't have Google Chrome installed, you can 
use `:call firenvim#install(1)` to force the installation of the native 
manifest for all browsers, even the ones that aren't currently installed 
on your computer.

But looking at Microsoft's documentation, it looks like the native 
messenger (the program that lets the browser start neovim) has to be a 
UWP app. The current native messenger is just a simple bat script, so 
this would probably need to be replaced with a real binary for Edge to 
be able to start Neovim.

I've never developed for windows before, so I'm not sure what creating a 
UWP app entails. I'll take a deeper look into that this weekend.

**Comment by glacambre** [comment]
Writing a UWP app is quite a complicated endeavor and I don't see supporting Edge as worth the time it would take me to implement. However, if someone else (you? ;)) wanted to open a PR adding edge support, I would be delighted to merge it.

All the information you need to port Firenvim to edge is available [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging). Basically, you don't need to change anything in the browser extension itself, instead you need to:

- Create a UWP app that:
        - When started, sets the current working directory to Firenvim's data directory and starts neovim just like [this batch script](https://github.com/glacambre/firenvim/blob/1e673e391b80992d067966d49e1fa7b6689aac91/autoload/firenvim.vim#L304-L308)
        - When it receives messages from Edge, forwards them to Neovim's stdin
        - When it receives messages from Neovim's stdout, forwards them to Edge
- If the UWP App is written in a compiled language, it needs to be built with Github Actions. I'll take care of making Github Actions push the compiled binaries to Firenvim's release page.
- Last, but not least, make [firenvim#install](https://github.com/glacambre/firenvim/blob/1e673e391b80992d067966d49e1fa7b6689aac91/autoload/firenvim.vim#L414) detect when Microsoft Edge is installed by checking if there is a configuration directory for Edge and if there is, install the UWP APP.

Feel free to ask any question that might come up while porting Firenvim to Edge, I'll answer them to the best of my ability :).

**Comment by alerque** [comment]
Maybe keep this open with a new tag indicating it will only be implemented if somebody else tackles it? The helpful pointers you gave are likely to get lost otherwise.

**Comment by glacambre** [comment]
Good idea :)

**Comment by BlueDrink9** [comment]
I'd also like to note that Edge is available on OSX too, and hints suggest linux support is incoming. I'd assume regular or forced firenvim install would work on those platforms though.

**Comment by Username404-59** [comment]
Hello, so i'm not using edge anymore; i switched to linux (and i use basilisk), but it seems that they will add support for it; are UWP apps needed on macOS and linux?
Firenvim might actually already work on theses 🤔

**Comment by glacambre** [comment]
Basilisk [does not support webextensions](https://forum.palemoon.org/viewtopic.php?f=61&t=21298), so Firenvim cannot work there.

Firenvim will work in most browsers that support webextensions (Firefox, Chrome, Brave…) on Linux, Mac and Windows without requiring any changes (so no need for a UWP!).

**Comment by Username404-59** [comment]
When i said "that they will add support for it" i was speaking of microsoft edge on linux, (when you go to https://www.microsoftedgeinsider.com/en-us/download/?platform=linux you can see "coming soon")

**Comment by BlueDrink9** [comment]
I decided to test quickly, and I can confirm that firenvim works on the new Edge

**Comment by Username404-59** [comment]
> I decided to test quickly, and I can confirm that firenvim works on the new Edge on OSX

So that's an issue for windows 10 only, if it works on osx it should work on linux when it'll be released...

**Comment by glacambre** [comment]
The requirement of making the native messenger a UWP app has been dropped. The following patch make firenvim work with edge on windows when ran from wsl. Still need to test native browser+native neovim combo. Putting the patch here because I can't push from windows.

```diff
diff --git a/autoload/firenvim.vim b/autoload/firenvim.vim
index 2e6408d..88850c6 100644
--- a/autoload/firenvim.vim
+++ b/autoload/firenvim.vim
@@ -295,6 +295,20 @@ function! s:chrome_config_exists() abort
         return isdirectory(s:build_path(l:p))
 endfunction
 
+function! s:edge_config_exists() abort
+        let l:p = [$HOME, '.config', 'microsoft-edge']
+        if has('mac')
+                let l:p = [$HOME, 'Library', 'Application Support', 'Microsoft', 'Edge']
+        elseif has('win32')
+                let l:p = [$HOME, 'AppData', 'Local', 'Microsoft', 'Edge']
+        elseif s:is_wsl
+                let l:p = [s:get_windows_env_path('%LOCALAPPDATA%'), 'Microsoft', 'Edge']
+        elseif !empty($XDG_CONFIG_HOME)
+                let l:p = [$XDG_CONFIG_HOME, 'microsoft-edge']
+        end
+        return isdirectory(s:build_path(l:p))
+endfunction
+
 function! s:chrome_dev_config_exists() abort
         let l:p = [$HOME, '.config', 'google-chrome-unstable']
         if !empty($XDG_CONFIG_HOME)
@@ -315,6 +329,18 @@ function! s:get_chrome_manifest_dir_path() abort
         return s:build_path([$HOME, '.config', 'google-chrome', 'NativeMessagingHosts'])
 endfunction
 
+function! s:get_edge_manifest_dir_path() abort
+        if has('mac')
+                return s:build_path([$HOME, 'Library', 'Application Support', 'Microsoft', 'Edge', 'NativeMessagingHosts'])
+        elseif has('win32') || s:is_wsl
+                return s:get_data_dir_path()
+        end
+        if !empty($XDG_CONFIG_HOME)
+                return s:build_path([$XDG_CONFIG_HOME, 'microsoft-edge', 'NativeMessagingHosts'])
+        end
+        return s:build_path([$HOME, '.config', 'microsoft-edge', 'NativeMessagingHosts'])
+endfunction
+
 function! s:get_chrome_dev_manifest_dir_path() abort
         if has('mac')
                 throw 'No chrome dev on mac.'
@@ -554,7 +580,14 @@ function! s:get_browser_configuration() abort
                 call remove(l:browsers, 'opera')
                 call remove(l:browsers, 'chrome-dev')
         endif
-        return l:browsers
+        return { 'edge': {
+                        \ 'has_config': s:edge_config_exists(),
+                        \ 'manifest_content': function('s:get_chrome_manifest'),
+                        \ 'manifest_dir_path': function('s:get_edge_manifest_dir_path'),
+                        \ 'registry_key': 'HKCU:\Software\Microsoft\Edge\NativeMessagingHosts\firenvim',
+                \}
+        \}
+
 endfunction
 
 " Installing firenvim requires several steps:
```

**Comment by glacambre** [comment]
Done. I won't upload firenvim to the microsoft edge extension store as they're asking for lots of personal information I don't want to give them, but you can download firenvim from the chrome web store and everything works fine.
