### ISSUE TITLE
Plugin whitelist rather than blacklist & domain config

### ISSUE THREAD

**Issue by xerus2000** [glacambre/firenvim#561]
1. I would like to be able to white-list rather than blacklist - in most cases it is total overkill when I just write some quick text.
2. The black-/white-listing should be per domain rather than per tab, similar to how [DarkReader](https://darkreader.org/) does it.

**Comment by glacambre** [comment]
This can be achieved like this:

let g:firenvim_config = {
     \ 'globalSettings': {
         \ 'alt': 'all',
     \  },
     \ 'localSettings': {
         \ '.*': { 'takeover': 'never' },
         \ 'that-one-domain-I-want-to-use-firenvim-on': { 'takeover': 
'always' },
     \ }
\ }

You can find more information about setting up Firenvim in the Readme :).

**Comment by xerus2000** [comment]
Oh, I'm sorry, didn't look so far ^^ thanks :)

Maybe you should shorten the readme a little and move some parts (e.g. how to install from source) down or into another file - it is quite overwhelming currently.
