### ISSUE TITLE
Wrong text editor selected on fluent playground

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#563]
- OS Version: linux x86-64
- Browser Version:  Firefox 76.0
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do: Visit https://projectfluent.org/play/ , enabled the "config" pane, tried to edit the config
- What happened: Opened frame was filled with "messages" pane content.

**Comment by alerque** [comment]
Oh that's cute. I've actually used Firenvim on the Fluent playground before, but either didn't notice this or just wasn't using the config pane at all.

I've bumped into something similar but only –as I recall– on Turkish e-commerce websites that have screwy form inputs anyways and I had no desire to debug.

**Comment by glacambre** [comment]
Are the inputs available without having to create an account ? If yes I 
can take a look at them too :)

**Comment by glacambre** [comment]
This happens because the various panes of the website have an identical id even though [ids must be unique in a document](https://developer.mozilla.org/en-US/docs/Web/API/Element/id).

**Comment by glacambre** [comment]
This has been fixed by https://github.com/glacambre/firenvim/commit/85d12f4999a36d89c1aec3682f91a6f38f477f04 .
