### ISSUE TITLE
Feature request: mapping custom combos in browser for passing to Firenvim

### ISSUE THREAD

**Issue by infokiller** [glacambre/firenvim#574]
Context: I'm trying to use the regular Chromium undo/redo combos (`Ctrl-Z` and `Ctrl-Shift-Z`) in insert and visual modes in Firenvim.
AFAIK, vim doesn't distinguish these combos because terminal don't. The general workaround for this is to do higher level remapping of `Ctrl-Shift-Z` to an unused combo that vim understands, and then bind that in vim.

Could Firenvim additional keybindings to pass to vim, which users would then be able to configure in the browser settings?
What I mean is that in addition to the these existing settings:

![image](https://user-images.githubusercontent.com/10516814/82338691-de124d00-99f5-11ea-8527-6fd88d29f8a0.png)

There would also be an option to remap `<Plug>(FirenvimCustom1)`, `<Plug>(FirenvimCustom2)`, etc.

Then users can use this in their vimrc:
```vim
map <Plug>(FirenvimCustom1) <some action>
```

Thanks!

**Comment by glacambre** [comment]
No, this is a hack and just plain wrong. The proper solution is for 
Neovim to be able to differentiate <C-z> from <C-Z> - I've opened 
https://github.com/neovim/neovim/issues/12037 for this almost a month 
ago :).

This problem really bothers me so I'm planning on fixing it myself when 
I have enough free time to properly delve into Neovim's code.

**Comment by glacambre** [comment]
@infokiller Next neovim nightly should be able to differentiate `<C-z>` from `<C-Z>` :)

**Comment by infokiller** [comment]
Thanks @glacambre that's cool!
What's your personal experience with neovim nightly? do you find it stable, buggy, etc?

**Comment by glacambre** [comment]
Just to be clear I'm not responsible for this fix, numirias and jamessan are :).

It's usually is pretty stable but I've read that it breaks often these days. I'm on an 2 months old nightly and haven't experienced a single issue though.
