### ISSUE TITLE
[Feature Request] Custom config file.

### ISSUE THREAD

**Issue by jeremyjjbrown** [glacambre/firenvim#588]
It would be great to be able to use a specific init.vim for firenvim. The if/esle logic is really messy when there are multiple clients (IE vscode) of nvim that require skipping subsets of the config.

Great job on this plugin. It's pretty awesome.

**Comment by glacambre** [comment]
This can already be achieved like this:

if g:started_by_firenvim == 1
	source /path/to/firenvim/vimrc
else
	source /path/to/regular/vimrc
endif

or like this:

autocmd UIEnter * if nvim_get_chan_info(v:event.chan).client.name == 
"Firenvim" | source /path/to/firenvim/vimrc | endif

And I think this is already too many options. I don't think adding a 
third, non-standard way of configuring firenvim would be a good idea.

**Comment by jeremyjjbrown** [comment]
OK, thanks.

Before I file another ticket is is possible to only have firenvim not start up on the text area unless I hit <C-e> ?

Thanks
