### ISSUE TITLE
Getting "Neovim died without answering" error on chrome.

### ISSUE THREAD

**Issue by isaif** [glacambre/firenvim#604]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 81.0.4044.129
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27

- What I tried to do: 
 Installed the firenvim using vim-plug and also installed chrome plugin. I also have vim installed and nvim is sourcing the vimrc in its init.vim. The firenvim installation is added to nvim's init.vim and not to .vimrc as I read that it doesn't work in vim. I think I should add the installation in .vimrc but I don't know if this will cause any other issues or if it is the recommended method.

  init.vim
  ```
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath
  source ~/.vimrc
  set guicursor=
  Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
  ```

- What happened:
 getting error "Neovim died without answering." and the plugin is disabled. I have checked the source code and it seems this happens when nvim doesn't respond and a timeout is reached. How I can check why this is happening?

Edit: I tried installing firenvim in vim but it gives an error.

```
Error detected while processing /home/saif/.vim/plugged/firenvim/plugin/firenvim.vim:
line    8:
E216: No such group or event: UIEnter * call firenvim#onUIEnter(deepcopy(v:event))
```

**Comment by glacambre** [comment]
>How I can check why this is happening?

There is a troubleshooting guide: https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md :).

What happens when you run `echo 'abcde{}' | ~/local/share/firenvim/firenvim` in a shell?

**Comment by isaif** [comment]
Thanks it's working now. 

I had to move the installation of firenvim to .vimrc from init.vim and use the conditional statement of loading the firenvim only if it is nvim. This was in the documentation of neovim in [Transitioning from vim](https://neovim.io/doc/user/nvim.html#nvim-from-vim) section.

I have added the following line to my vimrc:

```
if has('nvim')
	Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
endif
```
