### ISSUE TITLE
Nvim throwing error in firefox

### ISSUE THREAD

**Issue by hrai** [glacambre/firenvim#619]
- OS Version: Ubuntu 20.x
- Browser Version: Firefox 77.0.1 (64-bit)
- Browser Addon Version: 0.1.29
- Neovim Plugin Version: Latest
- What I tried to do: Tried to add a new comment in Github
- What happened: Unhandled rejection error was thrown. Also, this happens when I go to any tab with textboxes.
![Screenshot from 2020-06-29 10-49-36](https://user-images.githubusercontent.com/4055444/85962874-6a9d2b80-b9f6-11ea-90b1-1aaba0f9c6b1.png)

**Comment by glacambre** [comment]
Hi :)

As described by the error message the error is thrown by CoC, so I'm not 
sure that Firenvim is to blame here and I think CoC developers might be 
able to figure out what's wrong better than me since I have zero 
experience with CoC's internals.

**Comment by glacambre** [comment]
I filed https://github.com/neoclide/coc.nvim/issues/2128 for you :).

**Comment by hrai** [comment]
This could be a red herring but when I removed below setting, it started working again.

```
let g:firenvim_config = {
	\ "globalSettings": {
		\ "server": "persistent"
	\}
\}

```

**Comment by glacambre** [comment]
Ah, interesting. Persistent mode does something funny with neovim - all windows are floating windows and that where all the editing happens. I guess this is what confuses CoC.

Can you reproduce this error in your terminal if you create a new floating window, create a new buffer in it, set its filetype to something that CoC activates itself on and start editing?
