### ISSUE TITLE
Breaks Google Docs

### ISSUE THREAD

**Issue by xerus2000** [glacambre/firenvim#630]
- OS Version: linux x86-64
- Browser Version:  Firefox 78.0
- Browser Addon Version: 0.1.29
- Neovim Plugin Version: 0.1.27
- What I tried to do: Edit a document on docs.google.com
- What happened: Whenever I try to set my cursor in a document, it vanishes again, so I can't edit. Firenvim configuration is the default. Disabling it in the tab made editing work again.
But it also doesn't show a firenvim textbox either.

**Comment by glacambre** [comment]
Yes, Firenvim can't work on Google docs. I'd recommend disabling Firenvim on that domain. I won't do this by default as I don't want to add a gazillion rules to Firenvim - I actually want to do the opposite and have it disabled by default. As this is a pretty big change I'm waiting for the need to push another breaking change before doing that.

**Comment by xerus2000** [comment]
How about a separate repo or something for a reasonable default config? I do think this plugin could be a lot handier if it would be disabled on broken sites by default. Why not do it like DarkReader and simply maintain a config in the repo and ask everyone who would like to change something for a PR? Is that really a significant overhead?

With the current policy you are offloading that work to _every single user_, which is much less efficient. I now blocked Notion, Google Docs, OSM and a change for Jetbrains YouTrack is also due.

**Comment by glacambre** [comment]
>How about a separate repo or something for a reasonable default config?

I think that's what people had in mind when they asked me to make the wiki user-editable.

>Why not do it like DarkReader and simply maintain a config in the repo and ask everyone who would like to change something for a PR? Is that really a significant overhead?

I think defaults should be set to the least surprising thing and never change. Firenvim being disabled by default everywhere unless explicitly enabled sounds like the least surprising default to me.

**Comment by xerus2000** [comment]
Ah, I wasn't aware of the wiki, that is a very good idea! I created a new page for this, maybe you can link it in the README? :)
https://github.com/glacambre/firenvim/wiki/Broken-Websites

**Comment by glacambre** [comment]
Done. Thank you for your contributions to the wiki :)

I'll close this issue because I don't think I'll ever fix Firenvim on Google Docs and the issue of breaking websites by default is something more general than Google Docs :)
