### ISSUE TITLE
Double linebreaks on Slack and Front

### ISSUE THREAD

**Issue by luisherranz** [glacambre/firenvim#631]
- OS Version: macOS Catalina
- Browser Version: Google Inc. Chrome 83.0.4103.116
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30

## What I tried to do:

Use firenvim on [Slack](https://slack.com/intl/en-es/) and [Front](https://frontapp.com/) apps.

## What happened:

Everything works, but when I switch between Firenvim and Slack/Front two linebreaks are added for each one.

This text:

```
line 1
line 2
line 3
```

becomes:

```
line 1

line 2

line 3
```

- Is it a known problem?
- Is there a way to avoid that?

**Comment by glacambre** [comment]
Hi, thanks for the report.

>   * Is it a known problem?

I think I've noticed this issue, but did not formally log it here.

>   * Is there a way to avoid that?

Not without making changes to Firenvim itself I think. I don't even know 
what's going wrong exactly :/.

**Comment by luisherranz** [comment]
Thanks for your answer @glacambre.

Is there a way to hook into the moment when firenvim gets/returns the content to process it?

**Comment by glacambre** [comment]
If you want these hooks for debugging this bug, I would suggest putting breakpoints in [TextareaEditor.ts:getContent](https://github.com/glacambre/firenvim/blob/afa3ef17d1a5b2244260854a376f794851e7ae82/src/editors/TextareaEditor.ts#L17) and [TextareaEditor.ts:setContent](https://github.com/glacambre/firenvim/blob/afa3ef17d1a5b2244260854a376f794851e7ae82/src/editors/TextareaEditor.ts#L51-L58).

If you want these hooks to pre/post process the text before sending it to the page you can use autocommands to do this, e.g. `autocmd BufNew slack.com_* :DoSomePreProcessing` or `autocmd BufWritePre slack.com_* :DoSomePostProcessing`.

Slack uses a contenteditable element, I think that's what's causing issues here.

**Comment by luisherranz** [comment]
Thanks @glacambre! I was able to fix it with:

```
autocmd BufEnter app.frontapp.com_* :%s/\n\n\n/\r\r/g
autocmd BufEnter app.slack.com_* :%s/\n\n\n\n/\r/g
```

**Comment by MahdiNazemi** [comment]
I understand this issue is closed, but I face a similar issue and was curious if anyone knows how to solve it.

If I type something like

```
first line
second line
third line
```

in Firenvim and `:wq`, I get the following in Slack:

```
first line

second line

third line

```

If I understand correctly, the `autocmd`s shared above help remove the extra new line characters when going back to Firenvim, but not the issue I described. Am I right?

**Comment by MahdiNazemi** [comment]
Thanks very much. The `'content': 'html'` line works well for my use case.
