### ISSUE TITLE
Chrome canary support

### ISSUE THREAD

**Issue by smackesey** [glacambre/firenvim#641]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 86.0.4197.0
- Browser Addon Version: 0.1.29
- Neovim Plugin Version: 0.1.29

I use both Chrome and Chrome Canary on my machine, and I noticed that firenvim was not working for Chrome Canary. I followed the Troubleshooting Guide and found that no "firenvim native manifest" was created for Chrome Canary (file in /$HOME/Library/Application Support/Google/Chrome Canary/NativeMessagingHosts). I copied the one from the adjacent Chrome directory and now it works. It would be nice if firenvim could've done this automatically on install, or if there could at least be a note in the README etc about this necessary extra step to make it work with Chrome Canary.

**Comment by glacambre** [comment]
Thank you for troubleshooting this yourself and for reporting this issue :)

**Comment by glacambre** [comment]
Thanks for reporting this issue. I couldn't test if my fix actually worked (I only have a linux machine to test on) but the patch was fairly simple so hopefully it does. It'd be nice if you could try it, but if you don't want to that's no big deal, the next Chrome Canary user will let me know whether Firenvim is still broken or not :)
