### ISSUE TITLE
Using press_keys function to enter Github comments

### ISSUE THREAD

**Issue by ruoyul** [glacambre/firenvim#646]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 83.0.4103.116
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30
- What I tried to do: Some websites such as Github and Gmail has shortcut Ctrl+Enter to enter comment or send email. I tried to use this with the `press_keys` function but couldn't get it to work. Here is what I have in my configs: `au BufEnter github.*.txt noremap <C-CR> <Esc>:w<CR>:call firenvim#press_keys("<LT>C-CR>")<CR>`
- What happened: on Github comments do not get submited

**Comment by glacambre** [comment]
Master now has a fix for this, it'll reach you when I publish a new release. In the meantime, you can probably use `firenvim#eval_js` in order to click on the button.

Thanks for reporting this bug! :)

**Comment by ruoyul** [comment]
Thanks!
