### ISSUE TITLE
Feature request: Resize textboxes

### ISSUE THREAD

**Issue by matheusfillipe** [glacambre/firenvim#650]
Is it possible to resize a texbox with shortcuts within Neovim? Firefox has keybindings like ctrl+enter for this but wont work inside insert mode for obious reasons. Would me nice to have this sort of utility for some Normal mode keybinding.  

I know I could just resize before but my goal is using this in combination with vimium and browsing full cursorless!

- OS Version: linux x86-64
- Browser Version:  Firefox 78.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30
- What I tried to do: Resize a texbox without a mouse
- What happened: Is not so fast having to exit nvim then using browser shortcuts and starting the session again.

**Comment by glacambre** [comment]
>Is it possible to resize a texbox with shortcuts within Neovim?

Yes, see `:help lines` and `:help columns` :)

**Comment by matheusfillipe** [comment]
> > Is it possible to resize a texbox with shortcuts within Neovim?
> 
> Yes, see `:help lines` and `:help columns` :)

**Comment by glacambre** [comment]
No problem, feel free to ask any other question you may have :)

**Comment by matheusfillipe** [comment]
Any idea why this doesn't work:

```
if exists('g:started_by_firenvim')
  set lines=28 columns=110
endif
```

**Comment by glacambre** [comment]
This is because there is no screen when your init.vim is read. Try to set this setting from a [UIEnter](https://github.com/glacambre/firenvim#building-a-firenvim-specific-config) event instead :).

**Comment by matheusfillipe** [comment]
Thanks! Now it worked... Haha just had to read a bit more! Keep up the good work this plugin is really great.

Another question. On my nvim I don't have this behavior but why is this adding line breaks automatically? Sorry if this is just written on the README.md and I didn't read again :P

**Comment by glacambre** [comment]
>On my nvim I don't have this behavior but why is this adding line breaks automatically?

There is no code that adds linebreaks in Firenvim so I'm not sure I understand what you mean, could you describe what you're seeing in more detail?

**Comment by matheusfillipe** [comment]
While I am typing this the lines suddenly breaks when it reaches the limit of
the text box I think? I am just going to leave this message unedited. As I type
in insert mode it just adds line breaks.

**Comment by glacambre** [comment]
This is probably because of your settings for editing markdown. Does it still happen if you run `:set formatoptions=` before typing text?

**Comment by matheusfillipe** [comment]
Thanks! Yes you are right :P 

Now I end this! Thanks a lot for the plugin and such a fast support!

**Comment by woshichuanqilz** [comment]
> This is because there is no screen when your init.vim is read. Try to set this setting from a [UIEnter](https://github.com/glacambre/firenvim#building-a-firenvim-specific-config) event instead :).

Hi, I Add the code `UIEnter` into the nvim settings
```vim

function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction
function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    set guifont=Hack:h18
    set lines=20
    set columns=40
    set laststatus=0
  endif
endfunction

" Already add the line below to the end of the file
autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```

But Just font change worked in my case lines and columns change not work. 

How to fix this. If I manually type the `set lines=20` it worked. 

How to change my settings.

**Comment by glacambre** [comment]
Hi @woshichuanqilz,

The code snippet you posted works fine for me (although I don't have the Hack font). You seem to have chosen a very large font size, perhaps the browser window isn't big enough to accomodate the number of lines and columns you're requesting?

Another possibility is that the website you're using firenvim on resizes the underlying text area. Could you try to reproduce your bug on http://txti.es/ ? It's a very simple website that doesn't do any resizing.

You could also try to check if all instructions are executed. For example, adding `hi Normal guibg=red` after the `set laststatus=0` line should turn the background of your buffers red. Does that work?

You can also check if something in your configuration is changing the size of the window with `:verbose set lines`. This should be printing the line number of the `:set lines` line in the OnUIEnter function, does that work?

**Comment by woshichuanqilz** [comment]
> Hi @woshichuanqilz,
> 
> The code snippet you posted works fine for me (although I don't have the Hack font). You seem to have chosen a very large font size, perhaps the browser window isn't big enough to accomodate the number of lines and columns you're requesting?
> 
> Another possibility is that the website you're using firenvim on resizes the underlying text area. Could you try to reproduce your bug on http://txti.es/ ? It's a very simple website that doesn't do any resizing.
> 
> You could also try to check if all instructions are executed. For example, adding `hi Normal guibg=red` after the `set laststatus=0` line should turn the background of your buffers red. Does that work?
> 
> You can also check if something in your configuration is changing the size of the window with `:verbose set lines`. This should be printing the line number of the `:set lines` line in the OnUIEnter function, does that work?

* change the size to 18 not work
* same issue on http://txti.es/ 
* `hi Normal guibg=red` worked.
* `verbose set lines` info normal, set lines last set by `OnUIEnter`

![2020-09-15_16-02](https://user-images.githubusercontent.com/11295355/93183507-a5993a80-f76d-11ea-961e-58884b240ce4.png)
![2020-09-15_16-06](https://user-images.githubusercontent.com/11295355/93183514-a762fe00-f76d-11ea-89f5-95eb2cdf8378.png)

**Comment by glacambre** [comment]
@woshichuanqilz Could you try with a fresh browser profile?

**Comment by fx-kirin** [comment]
I'm also having the resizing problem. It can change the lines and colmns variables, but suddelnly reset the size
 to the textbox size.

When I execute `:set lines` manually while typing in nvim, it can keep its modified size.

Any idea to fix it?

I disabled all the firefox addons except firenvim, but nothing has changed.

``` vim
function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction

function! SetLinesForFirefox()
    set lines=28 columns=110 laststatus=0
endfunction

function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    call SetLinesForFirefox()
    nnoremap <silent> <Leader>f :call SetLinesForFirefox()<CR>
    set guifont=Cica:h14
  endif
endfunction

autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```

![Peek 2020-11-25 17-56](https://user-images.githubusercontent.com/2161266/100205360-5e3ae180-2f48-11eb-811d-3fa9fc571f1e.gif)

**Comment by glacambre** [comment]
I think the problem might be setting both `guifont` and `lines` at the same time. You can try delaying one of them (with e.g. timer_start) and see if it helps. I'll open a new issue for this bug.
