### ISSUE TITLE
Feature Request: Disable globally

### ISSUE THREAD

**Issue by matheusfillipe** [glacambre/firenvim#654]
First of all thanks for this great project! 

Would it be possible to implement a way to disable the vim editor globally instead of a single tab? Or have it only triggered when the ctrl+e shortcut is pressed?

- OS Version: linux x86-64
- Browser Version:  Firefox 78.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30

**Comment by glacambre** [comment]
Already possible: https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements :)

**Comment by matheusfillipe** [comment]
Thanks!
