### ISSUE TITLE
Escape key not working on ubuntu

### ISSUE THREAD

**Issue by matheusfillipe** [glacambre/firenvim#662]
I copied my arch nvim configs to my ubuntu machine and configured firefox with firevim the same way I did on my arch. I already tried rebooting.

Launching nvim on a shell is normal and I'm able to use the esc key. I can confirm that firevim is sourcing the right init.vim since some shortcuts I set specifically for firevim are working. Tried disabling some extentions like vimium but didnt help.

Also tried with an almost empty init.vim such as:

```
call plug#begin()
Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
call plug#end()

```

But still same problem. Esc key doesn't work for nothing.

- OS Version: Ubuntu 20.04
- Browser Version:  Firefox 77.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30
- What I tried to do: Hit escape
- What happened: Nothing happens and I'm unable to go back to normal mode.

**Comment by glacambre** [comment]
What happens if you go in insert mode in Firenvim and then press `<C-v><CR>`?

**Comment by matheusfillipe** [comment]
> What happens if you go in insert mode in Firenvim and then press <C-v><CR>?

ctrl+V is pasting text, which it doesn't do on my normal nvim.

> <C-c> and <C-\><C-n> should still work I think.

None of these doesn't work as well.

**Comment by glacambre** [comment]
>ctrl+V is pasting text, which it doesn't do on my normal nvim.

This is not Firenvim's default behavior, you have a mapping that does this. Run `:verbose map <C-v>` to know wherer this mapping is.

**Comment by matheusfillipe** [comment]
No mapping found

**Comment by glacambre** [comment]
What about entering insert mode in Firenvim, pressing `<C-r>` and then running `=execute("verbose map <C-v>")` (and same thing with `<CR>`)?

**Comment by matheusfillipe** [comment]
Control R is reloading the page! firevim is not stealing all the focus as it should it seems.

**Comment by glacambre** [comment]
Does this happen with a fresh firefox profile? (`firefox -P` to open the profile manager)

**Comment by glacambre** [comment]
Oh, I know what might be happening - have you set `privacy.resistFingerprinting` to true in `about:config`?

**Comment by matheusfillipe** [comment]
> Oh, I know what might be happening - have you set `privacy.resistFingerprinting` to true in `about:config`?

Just set it, it was false, but it did not help.

**Comment by glacambre** [comment]
Yeah, it should be false - setting it to true breaks webextensions :/. What happens when using a fresh profile?

**Comment by matheusfillipe** [comment]
I just found out that I don't have the issue on the empty profile. Also on my current profile I figured out that this issue is only happening on the github page. What could it be? Some extension interfering?

**Comment by matheusfillipe** [comment]
I have this browser synced with firefox on arch linux and they have the same extensions installed. There I don't have this problem.

**Comment by matheusfillipe** [comment]
Also my esc key is not working on the github page at all so this is not firevim's fault at all.
