### ISSUE TITLE
Write on FocusLost broken when underlying element focuses itself on write

### ISSUE THREAD

**Issue by xerus2000** [glacambre/firenvim#678]
- OS Version: linux x86-64
- Browser Version:  Firefox 79.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30
- What I tried to do: Enter a regex using firenvim
- What happened: It constantly reopens the firenvim instance because it reloads the expression

Unless it is an easy fix, I would probably just add it to my ignore list, since I don't really need nvim there. Now that I think about it though, shouldn't firenvim open at all in there by default?

**Comment by glacambre** [comment]
Firenvim works fine on this website for me: selecting an editable element correctly opens firenvim, loaded with the text of the element. I can then type things in Firenvim and write to the underlying element as expected. Quitting Firenvim and further editing the text also works, without re-opening firenvim.

If you're seeing something different from that, could you try to use a fresh firefox profile with no extra addon and no firenvim config?

>shouldn't firenvim open at all in there by default?

Firenvim does open on this website for me and that's expected IMO. There's an editable (CodeMirror) element and I'd expect Firenvim to take over all editable elements.

**Comment by xerus2000** [comment]
https://streamable.com/pp5696
Seems to be in some special cases, here a video of my issues.

**Comment by glacambre** [comment]
Can you reproduce this on a fresh firefox profile?

**Comment by xerus2000** [comment]
Yes, I can indeed. Do I also need to test a blank nvim config? ^^
One thing worth noting is that I have write on InsertLeave enabled.

**Comment by glacambre** [comment]
>One thing worth noting is that I have write on InsertLeave enabled.

This could indeed be part of the issue if you have another plugin that makes you leave insert mode when FocusLost events are triggered. You leave the firenvim frame -> this triggers a write -> the underlying element focuses itself on write -> this makes firenvim focus itself -> the underlying element tries to grab focus again -> focus is lost for the firenvim frame -> this triggers a write -> the underlying element tries to focus itself -> this makes firenvim focus itself and so on and so forth.

**Comment by glacambre** [comment]
@xerus2000 Are you still experiencing this issue? I'm trying to recreate the bug you've mentionned and I can't. If you still can, could you upload your config here and either a precise list of steps required to reproduce the bug or a video (the link you posted in august expired :( ).

**Comment by xerus2000** [comment]
I'm experiencing this regularly on many sites and have since disabled automatic takeover of firenvim. I'll see what I can find out.

**Comment by glacambre** [comment]
This issue has been awaiting a repro for a month and half now, so I'll close it. If you still encounter this issue, feel free to complain (and to submit a repro ;)) and I'll re-open :)
