### ISSUE TITLE
Swap files - recovering lost work

### ISSUE THREAD

**Issue by xeruf** [glacambre/firenvim#679]
Does firenvim disable writing of swap files? If my browser or computer crashes and I wrote something in firenvim, I found no way so far of recovering it, unless the website itself has such functionality :/

**Comment by glacambre** [comment]
Yes, swap files are disabled: https://github.com/glacambre/firenvim/blob/f0b6ebc105dfcef9a53687824714c0faed542e9b/src/NeovimFrame.ts#L86

They'll be re-enabled once the state of Firenvim is improved but right now they'd make using firenvim much worse (mainly because of issues around firenvim not shutting down properly).

**Comment by xerus2000** [comment]
Any alternative way to make sure nothing is lost?

**Comment by glacambre** [comment]
```vim
function! My_Backup(timer) abort
        write /tmp/my_backup
endfunction
call timer_start(1000, 'My_Backup', {'repeat': -1})
```

**Comment by xerus2000** [comment]
`/tmp` will be cleared on reboot, but the idea sounds good :) (maybe `/var/tmp` instead)
But, why is that not a performance issue while swap files are?

**Comment by glacambre** [comment]
Swap files do not cause performance issues, they just linger around because firenvim instances are not (correctly) shut down, you thus frequently get a "restore from swap" prompt when you want to use firenvim on a page you already used it on.

**Comment by madranet** [comment]
@xerus2000 --If you're using a Chrome based browser and until swap recovery is implemented in Firenvim, you could try the Typio Form Recovery add-on. It's saved my bacon on a few occasions:

https://chrome.google.com/webstore/detail/typio-form-recovery/djkbihbnjhkjahbhjaadbepppbpoedaa?hl=en

_"No affiliation. Just a happy customer"_ --as the saying goes. And I presume similar plugins are available for Firefox.

**Comment by xerus2000** [comment]
@madranet I used to use that actually, but it didn't help me a lot either ^^
