### ISSUE TITLE
Highlight for Chinese characters are corrupted 

### ISSUE THREAD

**Issue by sefeng211** [glacambre/firenvim#697]
Hi, thanks for making this great addon!

Here's the screenshot of the issue that I am reporting.
![firenvim_chinese_character](https://user-images.githubusercontent.com/8703745/92414609-0055e500-f123-11ea-9c86-ed4de54d6637.png)

When I type Chinese characters in firenvim, the highlight for the characters seems broken. It works well other characters.

- OS Version: linux x86-64
- Browser Version:  Firefox 82.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30

**Comment by glacambre** [comment]
Hi, thanks for reporting this bug. This is the same issue as https://github.com/glacambre/firenvim/issues/471 - so I'll close your issue because #471 has a bit more information :).
