### ISSUE TITLE
Cannot open firenvim when replying to someone on Duolingo Discussions

### ISSUE THREAD

**Issue by silmeth** [glacambre/firenvim#707]
- OS Version: linux x86-64
- Browser Version:  Firefox 80.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30
- What I tried to do:

  Use firenvim on Duolingo discussions (https://forum.duolingo.com), when replying to existing post.

- What happened:
  
  The input text area changes (a new iframe appears above it with firenvim highlight) but it is empty (no nvim gets loaded inside).

  When writing a top-level post in a discussion, firenvim works as expected.

Similar problem exists in Tridactyl with the same Duolingo input areas – there it is caused by the CSS selector generated to get the current content of the textarea. Some elements around lower-level textareas in Duolingo get ids starting with a number which does not work with `#id-here` type selectors and require `tag[id="id-here"]` selectors but Tridactyl generates selectors like `#40796595` which are not valid. See tridactyl/tridactyl#2676

Maybe something similar happens here?

**Comment by glacambre** [comment]
You have correctly identified the problem, thanks for doing this, I had completely forgotten about the Tridactyl issue. I've pushed a fix in https://github.com/glacambre/firenvim/commit/1eb063ba854c61bfc62c1723f036aa226bd6b3d6, I'm just waiting for it to get a green checkmark and I'll publish a new release on firefox and chrome's web store :).

**Comment by glacambre** [comment]
I've submitted a new version for both browsers and Firefox's is already available so I'll close this issue. Let me know if you can still somehow reproduce the bug (I can't anymore so I'd be surprised if you could :) ).

**Comment by silmeth** [comment]
Yup. Works now! Thanks for so quick fix. :)
