### ISSUE TITLE
firenvim#install() won't work with nvim's appimages

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#71]
This happens because we use [`v:progpath`](https://github.com/glacambre/firenvim/blob/670b3dec0bc728930d2c70004fa1765891b69f38/autoload/firenvim.vim#L107) in order to get an absolute path to the neovim binary (this is needed because on OSX $PATH doesn't contain neovim).
Solving this requires detecting we're running in an appimage (checking if progpath points to somewhere in /tmp is probably enough) and finding the "real path" of that appimage.
Until this issue is fixed, a simple workaround is to just manually edit `~/.local/share/firenvim/firenvim` to make it point to the right path.

**Comment by justinmk** [comment]
AppImage defines `APPIMAGE` env var. [Documentation](https://github.com/AppImage/docs.appimage.org/blob/bc0b1a62ca76edb987feb904e962335f225ff37d/source/packaging-guide/environment-variables.rst#type-2-appimage-runtime)

**Comment by glacambre** [comment]
Thanks! :)
