### ISSUE TITLE
Implement key passthrough

### ISSUE THREAD

**Issue by infokiller** [glacambre/firenvim#717]
By default, Chromium binds `<C-1>` to go to the first tab, `<C-2>` to go to the second tab, etc.
However, that doesn't work in Firenvim frames.
Is there a way for me to make Firenvim ignore these mappings and pass them normally to the browser?
My understanding is that `firenvim#press_keys()` is not suitable for this.
Also, it looks like terminals can't actually distinguish these key combos.

Thanks

**Comment by glacambre** [comment]
Hi. I implement this feature in #739. Let me know if the documentation is clear enough on how to use it (writing documentation has never been my strong suit).

**Comment by infokiller** [comment]
Thanks @glacambre that's great, thanks for resolving this so quickly!
Documentation seems very clear to me. FWIW, I never felt Firenvim has bad documentation, and if anything wasn't clear to me you responded very quickly, and I'm grateful for all your efforts.

**Comment by infokiller** [comment]
Now that I'm trying to apply the new configuration, I do have two questions (and it may be useful to add them to the docs as well):

- How can I also disable Ctrl-minus and Ctrl-plus (which by default are used to zoom in/out)? Is it just `<C-->/<C-+>`?
- If I want to ignore these keys in all modes, should I add them to all modes defined here: https://github.com/neovim/neovim/blob/38efa1730f205bc2cd0da40b1fac8936eec1a835/src/nvim/cursor_shape.c#L25-L41

**Comment by glacambre** [comment]
>How can I also disable Ctrl-minus and Ctrl-plus (which by default are used to zoom in/out)? Is it just <C-->/<C-+>?

Yep. Note that if your keyboard layout requires pressing shift in order to generate one of these symbols (e.g. you have to press shift to get a `+` on french azerty layouts), you'll have to add it to the key representation (e.g. `<C-+>` will actually be `<SC-+>`).

>If I want to ignore these keys in all modes, should I add them to all modes defined here: …

I pushed a change a minute ago which lets you use "all" as a key to ignore keypresses in all modes :).

**Comment by luisherranz** [comment]
@glacambre has this been released? I'm trying to ignore CMD+Number in macOS because they are used to move to the tabs, but they dont' seem to work:

```vim
let g:firenvim_config = {
  \ 'globalSettings': {
    \ 'ignoreKeys': {
      \ 'all': ['<D-1>', '<D-2>', '<D-3>', '<D-4>', '<D-5>', '<D-6>', '<D-7>'],
    \ }
  \ }
\ }
```

Am I doing something wrong?

I have used `<D-X>` to map other commands, like copy/paste/save with sucess:

```vim
" Paste
inoremap <D-v> <C-r>+
nnoremap <D-v> "+p
vnoremap <D-v> "+p

" Copy
vnoremap <D-c> "+y

" Save
inoremap <D-s> :w<CR>
nnoremap <D-s> :w<CR>
vnoremap <D-s> :w<CR>
```

**Comment by glacambre** [comment]
@luisherranz This hasn't been released yet, sorry. I'll publish a new release as soon as https://github.com/glacambre/firenvim/pull/769 is merged. Your settings look correct to me :).

**Comment by alerque** [comment]
Thanks, I was puzzling about this too. I was under the impression it was released and have this tab and my config sitting open from a week or so ago trying to sort out why it wasn't working.

**Comment by glacambre** [comment]
@alerque Sorry. I've been thinking about keeping issues open and adding a "fixed-next-release" label until I publish a new release. I guess I'll stop thinking and start actually doing it :).

**Comment by alerque** [comment]
I wouldn't suggest keeping issues open, I would just put them in milestones. Keep then in a "next" milestone until it is released, at which point rename it to the release number and open a new milestone called "next". That will make it clear what issues are fixed and when to expect them, as well as a way to confirm what version something came out it without the issue noise of retagging or open issues.

**Comment by luisherranz** [comment]
Thanks @glacambre! Absolutely no problem. Firenvim makes my life so much easier, so huge thanks by the way 🙂

**Comment by glacambre** [comment]
I published a new release, let me know if it works :).

**Comment by luisherranz** [comment]
Working perfectly now 🙂

**Comment by infokiller** [comment]
I can confirm it works for me as well, thanks!
