### ISSUE TITLE
[question] how to avoid firenvim cover vimium?

### ISSUE THREAD

**Issue by Freed-Wu** [glacambre/firenvim#732]
## Environment

- OS: linux v5.4.13
- browser: firefox v79.0
- vi: nvim v0.4.3

## Reproduce Procedures

```{.sh}
mv $XDG_CONFIG_HOME/nvim/init.vim $XDG_CONFIG_HOME/nvim/init.vim.bak
vi $XDG_CONFIG_HOME/nvim/init.vim
```

```{.vim}
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/glacambre/firenvim
```

```{.sh}
vi --headless -c 'call firenvim#install(0)|q'
```

```{.txt}
No config detected for chromium. Skipping.
No config detected for opera. Skipping.
No config detected for brave. Skipping.
No config detected for vivaldi. Skipping.
No config detected for chrome-canary. Skipping.
Installed native manifest for chrome.
Installed native manifest for firefox.
```

```{.sh}
firefox -p
```

New a profile. install the following extensions from 'Find more add-on':

- vimium-FF
- firenvim

Open <https://github.com/>.
Sign in.
Enter an issue.
Enter a comment region.
Enter the firenvim frame.

```{.vim}
call firenvim#focus_page()
```

Press <kbd>o</kbd>
Press <kbd>Tab</kbd>

The vimium will be covered by firenvim.
![Screenshot from 2020-10-14 14-05-44](https://user-images.githubusercontent.com/32936898/95953355-45f58400-0e2c-11eb-8efd-68e174719e86.png)

**Comment by glacambre** [comment]
I can't reproduce this bug. Could you try with a fresh Chrome profile and see if the bug still happens?

**Comment by Freed-Wu** [comment]
this is my environment:

OS: linux 5.4.13
browser: firefox 79.0
firenvim: latest
vimium: latest

**Comment by glacambre** [comment]
I can't reproduce this with firefox either, please try a fresh Firefox profile. You can open Firefox's profile manager with `firefox -P` :)

**Comment by Freed-Wu** [comment]
i try it in google-chrome 80.0.3987.162. firenvim also cover vimium:

![Screenshot from 2020-10-14 12-04-20](https://user-images.githubusercontent.com/32936898/95942318-7120a900-0e15-11eb-8e7d-fc8440d79aa2.png)
![Screenshot from 2020-10-14 12-04-27](https://user-images.githubusercontent.com/32936898/95942328-74b43000-0e15-11eb-92d4-6bf9fef64976.png)

**Comment by Freed-Wu** [comment]
![Screenshot from 2020-10-14 12-29-05](https://user-images.githubusercontent.com/32936898/95943606-e2159000-0e18-11eb-9231-251269f6ddbb.png)

i open a new firefox profile which only installed vimium and firenvim. the firenvim frame still covers vimium. is my firefox version not enough late?

**Comment by glacambre** [comment]
Thank you for trying with a fresh profile. It's weird that you can reproduce the bug and I can't.

>is my firefox version not enough late?

I'm using Firefox 80.0.1 but I don't think this should matter. I have a few other questions:
- Have you configured firenvim with the `g:firenvim_config` object? If yes, could you paste it here?
- What desktop environment are you using? KDE?
- What keyboard layout are you using? Are you using a special input method, like e.g. pinyin?

And just to make sure I'm not doing something wrong, here are the steps I took, let me know if I'm doing something different from you:

- Started firefox
- Installed vimium-ff from https://addons.mozilla.org/en-GB/firefox/addon/vimium-ff/
- Installed firenvim from https://addons.mozilla.org/en-GB/firefox/addon/firenvim/
- Navigated to https://github.com/glacambre/firenvim/issues/732
- Signed in
- Went to the bottom of the page by using the scrollbar
- Clicked on the input field
- Typed `:call firenvim#hide_frame()` and pressed <key>Enter</key>
- Pressed <key>Escape</key>
- Pressed <key>o</key>
- Pressed <key>Tab</key>

**Comment by Freed-Wu** [comment]
sorry:(, it is my input error, should be `firenvim#focus_page()`

in my humble opinion, it cannot be thought as a bug. i am just think when
firenvim loses the focus, it should not cover any other float windows, such as
vimium. so i add 'question' in the title of this issue.

i have updated the discription by 'firefox -p' of the issue.
Thanks for your forgiveness!

**Comment by glacambre** [comment]
>i am just think when firenvim loses the focus, it should not cover any other float windows, such as vimium

Unfortunately this is impossible to implement correctly for reasons described in https://github.com/glacambre/firenvim/issues/427 . What I can do however is hardcode a z-index slightly lower than Vimium's, which uses a z-index of [2139999997](https://github.com/philc/vimium/blob/master/content_scripts/vimium.css#L150). I'll do this soon.

**Comment by glacambre** [comment]
The change has been implemented. The fix will reach you once I publish a new version. Thanks for the bug report :).
