### ISSUE TITLE
SHIFT Key Intermittently Acting as CTRL Key

### ISSUE THREAD

**Issue by madranet** [glacambre/firenvim#752]
- OS Version: OSX 10,14,4
- Browser Version: Yandex 20.9.0.1697 (64-bit)
- Browser Addon Version: 0.1.31? [current]
- Neovim Plugin Version: 0.1.31? [current]
- What I tried to do: Type a capital letter
- What happened: Contextual menu

There seems to be an intermittent problem [ie. hard to pin down] whereby, sometimes, after I've been typing in Firenvim for a while, the `SHIFT` keys will start popping up a contextual menu, instead of behaving as expected.

It's not a hardware problem with my keyboard, as it continues to work perfectly if I switch to another app. But, obviously it makes it impossible to use Firenvim as [apart from not being able to tpye properly, I can't access various vim functions... such as trying to save what I've written up to then.

Anyone else seeing that?

![2020-10-28_11-38-52](https://user-images.githubusercontent.com/669658/97434178-88cc5700-1916-11eb-8819-e3a6455443c4.png)

**Comment by madranet** [comment]
Closing this for now as it's 

- [ ] not saving the text I enter!

**Comment by glacambre** [comment]
Can you reproduce this on either Chrome or Firefox with a fresh browser profile?

**Comment by madranet** [comment]
The reproduceability bit is the tough one, as it's been happening intermittently. I've just tried in Chrome and typed a long paragraph and the `SHIFT` key behaved itself. But then, it might have done that anyway in Yandex.

I haven't been able test with Firefox yet, as I've not been able to get Firenvim to work there. I get a black border appear round the textbox when I click in it, but no Nvim editor loads.

**Comment by glacambre** [comment]
>The reproduceability bit is the tough one, as it's been happening intermittently.

I see. If you have time, please keep trying with Chrome - the longer you do that the more certain we'll be that this is a yandex-specific issue (I believe it is one because this is the first I hear about this issue and the first time I see someone using Firenvim on Yandex).

I'm thinking that this might also be tied to input methods. Are you using a specific keyboard layout/input method?

>I haven't been able test with Firefox yet, as I've not been able to get Firenvim to work there. I get a black border appear round the textbox when I click in it, but no Nvim editor loads.

If you installed Firefox after having installed Firenvim, you will need to run `:call firenvim#install()` again :).

**Comment by madranet** [comment]
> I see. If you have time, please keep trying with Chrome - the longer you do that the more certain we'll be that this is a yandex-specific issue (I believe it is one because this is the first I hear about this issue and the first time I see someone using Firenvim on Yandex).

I don't tend to use Chrome. Yandex is my primary browser. But I'll fire it up every now and then to continue testing. I suspect it might be a Yandex specific issue. Although Chrome-based, it does occasionally exhibit slightly different behaviour from the norm.  For example, in Yandex, if I switch to the preview tab on this Github textbox and then switch back to the Write tab, the nvim edit window is minimised into the top corner of the edit window. the same happens momentarily in Chrome, but then the Nvim window scales up again. In Yandex, it just stays minimised in the corner.

![SS 2020-10-28 at 18 18 35](https://user-images.githubusercontent.com/669658/97578455-b84b9400-19e8-11eb-9db1-16c0b0e6e5e9.png)

![SS 2020-10-28 at 18 21 47](https://user-images.githubusercontent.com/669658/97578465-bd104800-19e8-11eb-9833-32cb0a7eec30.png)

 
> I'm thinking that this might also be tied to input methods. Are you using a specific keyboard layout/input method?

I'm using UK Layout.

> If you installed Firefox after having installed Firenvim, you will need to run `:call firenvim#install()` again :).

I've tried that. Still not working for me in Firefox. 

I'm wondering if there's a conflict with the triggering on Firefox. I note that on OSX, the default keyboard shortcut to summons Firenvim is CMD+E [as opposed to CTRL+E on Linux] . However, if I look at the extension keyboard shortcuts in Firefox and actually attempt to manually put in CMD+E as the shortcut for Firenvim, I get a warning that I can't override a Firefox default shortcut.  [I've done some menu diving and can't find anything in Firefox that uses CMD+E, so the message seems dubious, but that's what it's saying]. 

![SS 2020-10-29 at 13 51 51](https://user-images.githubusercontent.com/669658/97582736-01eaad80-19ee-11eb-8bcd-7a0c04fe95f1.png)

I tried changing the shortcut, but it still didn't work.

**Comment by glacambre** [comment]
>I don't tend to use Chrome. Yandex is my primary browser. But I'll fire it up every now and then to continue testing.

Thanks!

>For example, in Yandex, if I switch to the preview tab on this Github textbox [...]

Weird. I've opened #756 for this.

>Still not working for me in Firefox.

If you actually care about using Firenvim in Firefox (as opposed to just trying to install it there in order to help with reproducing this issue), could you go through the [troubleshooting guide](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md) and see if everything is in order?

**Comment by madranet** [comment]
OK. I think we're getting somewhere now.  I ran through the troubleshooting guide and everything was as it should be until I got to the following stage:

> Make sure the browser extension can communicate with neovim
>   In your browser, open the background console. This requires the following steps:
> 
>   On Firefox:
>   Go to about:debugging
>   Select This Firefox in the left column.
>   Find firenvim.
>   Click on the inspect button.

I'm getting this in Firefox's console. It repeats over and over again:

![SS 2020-10-29 at 19 08 47](https://user-images.githubusercontent.com/669658/97622965-e5b23500-1a1c-11eb-84af-71189d98c842.png)

Any ideas?

**Comment by glacambre** [comment]
Are you using FoxReplace? Firenvim doesn't hace a replaceCurrentTab function but it looks like [FoxReplace does](https://github.com/Woundorf/foxreplace/blob/939b860c6935eef0cda995c16178620acbc7b038/scripts/background.js#L30).

**Comment by madranet** [comment]
> Are you using FoxReplace?

Yes, I am.  I've never noticed the console filling up like this before with FoxReplace. Maybe there's a conflict there. Time for some more investigating.

**Comment by madranet** [comment]
After a bit more experimentation, I think I've now discerned a pattern in the seemingly random way this happens. I'm now thinking it seems to be related in some way to the time between hitting the SHIFT key and a following key. As I'm typing this normally, SHIFT is working as expected. But if I stop typing and just tap either SHIFT key on their own...

![SS 2020-11-10 at 14 53 36](https://user-images.githubusercontent.com/669658/98691834-5c78f780-2366-11eb-9495-d593a0b06882.png)


...well, that screengrab shows you what happens.  

Yes, I'm pretty confident this is 100% reproducible for me now. Somehow, not immediately following SHIFT by hitting another key, is triggering this weird CTRL-like behaviour.

This might also explain why it seemed so random before: if I'm typing a couple of sentences 'straight through' I'm not leaving any time between hitting the SHIFT key and the next letter. If, on the other hand, I pause at the end of a sentence for a second or two, to think what to write next then, some of those times, I'm probably prematurely hitting the SHIFT key to begin the new sentence, then slightly pausing, while I think of the next word --which is triggering this odd behaviour.

Sounds crazy, doesn't it? But I'm pretty much 100% able to reproduce this now, just by hitting the SHIFT key without immediately hitting a following key? Is anyone else able to confirm this, or have I got some very weird add-on conflict at play here?

**Comment by madranet** [comment]
Hmmm... not for the first time, I may have spoken too soon. My 100% reproducibility mentioned previously seems to hold only once this behaviour has started happening. As I'm typing this, I'm [so far] able to hold either SHIFT key with no untoward side-effects. 

So we have a mystery wrapped in an enigma: _\<something unknown\>_ triggers this behaviour in the first place. Then, once it's started happening, it can be retriggered by hitting SHIFT key without any immediately following key.

**Comment by glacambre** [comment]
@madranet Could you try to see if this is tied to inputting non-ascii (or even perhaps non-alphanumerical?) characters?

**Comment by madranet** [comment]
I think I've solved it!
`
And it turns out, Firenvim isn't the culprit!

While taking screenshots before, I noticed that, as well as the popup menu appearing wherever the cursor was in the Firenvim window...

![SS 2020-11-10 at 20 52 13](https://user-images.githubusercontent.com/669658/98736113-51d95500-239c-11eb-97df-b91949f4d22a.png)

It was also appearing when the mouse was outside the window.  Here, for example over `Preview` tab at the top...

![SS 2020-11-10 at 20 54 59](https://user-images.githubusercontent.com/669658/98736152-5dc51700-239c-11eb-9624-54ef3cf10e1f.png)

Notice the _Look up "Preview"_ text at the top of that menu. I belatedly realised  I was seeing a built-in feature of Yandex Browser. It is actually the following setting which, as you can see, I have enabled:

![2020-11-10_21-34-20](https://user-images.githubusercontent.com/669658/98736325-91a03c80-239c-11eb-922f-cb8da2d2ed6f.png)

So it now seems obvious that what i'm actually seeing here is an expected behaviour of a built-in feature of Yandex Browser, with the exception that it's being triggered any time I press SHIFT with the cursor inside the Firenvim window. 

Of course, the Yandex Translate popup should only trigger when the SHIFT key is pressed with the cursor over an actual word and should then offer to translate that word. What looks to be happening with Firenvim is that the translate popup is triggered any time the cursor is over the Firenvim window and SHIFT [on its own] is pressed. And, rather than offering to translate the word under the cursor the feature either offers to translate the single letter under the cursor...

![2020-11-10_21-39-15 (2)](https://user-images.githubusercontent.com/669658/98737306-ee502700-239d-11eb-9d51-e52ad92f233a.png)

 or... and this was what made it so difficult to spot... if the cursor is just over empty space in the edit window, the translate menu pops up but doesn't have the _Look up "---"_ item at the top, as there was no text under the cursor. So it looks just like a normal contextual menu. Which was why I didn't make the connection for a long time...

![2020-11-10_21-41-25](https://user-images.githubusercontent.com/669658/98737405-0c1d8c00-239e-11eb-82b9-ec03b4db10fd.png)

So, mystery solved. It seems there's just a [probably unfixable] conflict between Firenvim and Yandex's built in translate function whereby pressing SHIFT anywhere inside a Firenvim window will trigger that popup menu, even though the translate function is not then passed anything it can actually process.

It also explains why I was only seeing this happen after typing SHIFT on its own before and why I was subsequently unable to reproduce it every time.  There is obviously a timeout on the translate popup menu function whereby it only triggers when SHIFT is not followed by another key within a certain time. And the unpredictable nature of the popup sometimes appearing and sometimes not was dependent on whether or not the cursor was over the Firenvim edit window at the time. And, on top of that, for the _Look up "--"_ menu entry to appear in the popup [which was what led to me making the connection with Yandex translate]  the cursor needs to be actually over some text as well. 

So those three voodoo entrails all need to come into alignment for the cause of this glitch to reveal itself. No wonder it took so much tracking down!

**Comment by glacambre** [comment]
Thanks a lot for taking the time to investigate this and letting me know what the issue was, I really appreciate it :).
