### ISSUE TITLE
Frame content not resizing on Github write/preview tab

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#756]
>For example, in Yandex, if I switch to the preview tab on this Github textbox and then switch back to the Write tab, the nvim edit window is minimised into the top corner of the edit window. the same happens momentarily in Chrome, but then the Nvim window scales up again. In Yandex, it just stays minimised in the corner.

![SS 2020-10-28 at 18 18 35](https://user-images.githubusercontent.com/669658/97578455-b84b9400-19e8-11eb-9db1-16c0b0e6e5e9.png)

![SS 2020-10-28 at 18 21 47](https://user-images.githubusercontent.com/669658/97578465-bd104800-19e8-11eb-9833-32cb0a7eec30.png)

_Originally posted by @madranet in https://github.com/glacambre/firenvim/issues/752#issuecomment-718767936_

**Comment by glacambre** [comment]
@madranet I performed lots of changes in the way Firenvim reacts to changes in the page. Are you still experiencing this bug on Firenvim v0.2.4?

**Comment by madranet** [comment]
The resizing bug seems to have gone [albeit I've only given it a very quick test]. But I am still getting some visual glitching:

1: Write some drivel
![SS 2021-02-05 at 10 35 46](https://user-images.githubusercontent.com/669658/107023339-64e2a200-679e-11eb-8312-4c6af45b2a4e.png)

2: Preview 
![SS 2021-02-05 at 10 35 57](https://user-images.githubusercontent.com/669658/107023385-74fa8180-679e-11eb-8f5f-124a9bf6aaf7.png)

3: Return [all OK so far]
![SS 2021-02-05 at 10 36 11](https://user-images.githubusercontent.com/669658/107024238-ade72600-679f-11eb-8ead-7101b9fef681.png)


4: Edit existing text
![SS 2021-02-05 at 10 37 01](https://user-images.githubusercontent.com/669658/107023491-a2dfc600-679e-11eb-9acd-1d2fff0ce0a9.png)

5: Preview
![SS 2021-02-05 at 10 37 09](https://user-images.githubusercontent.com/669658/107023512-aa06d400-679e-11eb-941e-7d9b8e85a005.png)

6: Return
![SS 2021-02-05 at 10 37 20](https://user-images.githubusercontent.com/669658/107023534-b2f7a580-679e-11eb-83cd-9a595f9bb11b.png)

We've now got the text overlayed on a ghost of itself and also the NVim window is kind of greyed out and inactive. It doesn't respond to keyboard commands until I actually click in it to 'activate' it again. Although, as you can see, the browser has still got the textarea highlighted as if it was still active.

This may all be a bit of an edge case though, what with Github's  use of 'live preview' by switching tabs at the top of the textarea. Most text input boxes will require some kind of page reload for a preview. In fact, it's not very likely I'd even use FireNvim when composing Github replies as I'd also lose the ability to drag and drop images.  So it may not be worth your while spending any more time on this, if the extension is behaving properly elsewhere in more conventional textareas.

**Comment by glacambre** [comment]
>We've now got the text overlayed on a ghost of itself and also the NVim window is kind of greyed out and inactive. It doesn't respond to keyboard commands until I actually click in it to 'activate' it again. Although, as you can see, the browser has still got the textarea highlighted as if it was still active.

This is all "normal", the Firenvim frame turns semi-transparent when it gets unfocused. The reason it gets unfocused is that you're playing with the page, so Firenvim can't quite tell if it should focus itself or not :). In your opinion, is there a better way to convey that the frame currently isn't focused?

I'll close this issue, thanks a lot for replying!
