### ISSUE TITLE
Neovim died without answering on Chrome and on Firefox

### ISSUE THREAD

**Issue by mpinkert** [glacambre/firenvim#760]
This error is occurring for me on Chrome and on Firefox, so I think it's something to do with the plugin itself or the operating system.

- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 86.0.4240.183
- Browser Addon Version: 0.1.31
- Neovim Plugin Version: 0.1.31
- What I tried to do: Use Firenvim on any text box
- What happened: The icon remains red and the message is "Neovim died without answering"

I have followed the troubleshooting guide.

* Using call firenvim#install(0) prints the "Installed native manifest for chrome/firefox" message
* Doing `echo abcde...` results in the message `{"version": "0.1.31"}%`. 
* Both Firefox and Chrome have the native manifest pointed to the right path
* Using `exec '/usr/local/bin/nvim' --headless --cmd 'let g:started_by_firenvim = v:true' -c 'call firenvim#run()' -u NORC --cmd 'set rtp+=/tmp/firenvim'` does not fix the issue.
* print debugging the init.vim does not give any errors.

For error logging

## Chrome

Opening the background page:
* Unchecked runtime.lastError: Native host has exited.
* background.ts:102 Uncaught (in promise) Neovim died without answering.
* background.ts:104 Uncaught (in promise) TypeError: Cannot read property 'server' of undefined
    at background.ts:104 

Going to Developer Tools/Console on txti.es

Uncaught (in promise) Error: Error: your settings are undefined. Try reloading the page. If this error persists, try the troubleshooting guide: https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md
    at getConfForUrl (configuration.ts:58)
    at getConf (configuration.ts:46)
    at content.ts:251

Do you have any thoughts on what else I can try?

**Comment by glacambre** [comment]
Thank you for following the troubleshooting guide :).

Do you have multiple neovim versions installed? Type `where nvim` in a terminal to find out.

Could you check that `~/Library/Application Support/Google/Chrome/NativeMessagingHosts/firenvim.json` exists and upload its content here if it does?

How did you install neovim and chrome?

If you replace the `exec` line of ~/.local/share/firenvim/firenvim with:
```sh
exec '/usr/bin/nvim' --headless --cmd 'echoerr v:progpath' 2>>/tmp/firenvim_errors
```
And then try to start firenvim from the browser, does anything get printed in /tmp/firenvim_errors?

**Comment by mpinkert** [comment]
Thanks for responding so quickly.

I only have one version of nvim installed (`/usr/local/bin/nvim` pointing to `../Cellar/neovim/0.4.4/bin/nvim`)

I installed Neovim via Homewbrew; I have checked and the path is still correct.  If I replace the exec, no file gets created (whether I point to `/usr/bin/nvim` or `/usr/local/bin/nvim`)

Chrome and Firefox were both installed using my organization's custom installer.  I tried reinstalling Firefox manually, but that didn't seem to help.

firenvim.json:

```json
{ "name": "firenvim", "description": "Turn Firefox into a Neovim client.", "path": "/Users/map080/.local/share/firenvim/firenvim", "type": "stdio", "allowed_origins": [ "chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/" ]}
```

**Comment by glacambre** [comment]
>If I replace the exec, no file gets created (whether I point to /usr/bin/nvim or /usr/local/bin/nvim)

So /tmp/firenvim_errors is created but nothing gets printed inside of it? This is getting very confusing... Maybe it's an OSX notarization issue? Could you try to disable these checks for the neovim binary and see if it helps?

**Comment by mpinkert** [comment]
Actually, /tmp/firenvim_errors does not get created.  There is no file at all.  I tried pointing to just nvim, and commenting out `unset NVIM_LISTEN_ADDRESS`, but neither helped.  

I just used bash to run the script from the commandline (`bash ~/.local/share/firenvim/firenvim`) and it did make the error file with this error:
```
Error detected while processing pre-vimrc command line:
/usr/local/Cellar/neovim/0.4.4/bin/nvimPress ENTER or type command to continue
```
So either this is part of the error, or the script isn't being called by the browser at all.  It's like the browser is not even trying to access the `~/.local/share/firenvim/firenvim` script. 

This is indeed a really confusing error.  The most bizarre part of this is that it worked in the past, but at some point a few weeks ago it just stopped working and I don't know what changed.

**Comment by glacambre** [comment]
Ok, if the file isn't created at all then the browser probably isn't running the script indeed. We could verify this by adding `touch /tmp/firenvim_script_has_run` at the top of `/Users/map080/.local/share/firenvim/firenvim`.

I'm thinking that your browser might be sandboxed or patched to prevent running executable from your machine (or maybe an antivirus is doing this?). Is your organization's installer something I can learn about on the internet? Are you able to run other addons that require executing programs (e.g. https://github.com/mdn/webextensions-examples/tree/master/native-messaging )?

**Comment by mpinkert** [comment]
I just tried Opera and the addon worked there with no issues.  It did not work in Chrome-Canary.  

Adding `touch..` did not work.

I think you're right about the sandboxing.  I tried the native-messaging example you sent and I get a "[Errno 1] Operation not permitted" error despite verifying that the file has execute permission.

The installer is custom to our organization so I doubt you could find anything about it online.

Any thoughts on a way around this or something else to check, or is this just impossible due to the enterprise?

**Comment by glacambre** [comment]
>It did not work in Chrome-Canary.

You need to re-run `firenvim#install()` after having installed chrome canary because it doesn't use the same directories as Chrome.

>Any thoughts on a way around this or something else to check, or is this just impossible due to the enterprise?

I think the easiest solution is to run a browser that wasn't installed through your organization's installers, but you're probably not allowed to do that. The other solution is to learn what the installer does to the browsers and try to circumvent it, but since I don't have access to the installer or to an OSX machine this is something only you can do :).

**Comment by mpinkert** [comment]
Fair enough.  Thanks for the support!  I will try to troubleshoot this more on my own.
