### ISSUE TITLE
[Question] Different vim configurations for different sites

### ISSUE THREAD

**Issue by lolimay** [glacambre/firenvim#766]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 87.0.4280.47
- Browser Addon Version: 0.1.31
- Neovim Plugin Version: 0.1.31
- What I tried to do:
- What happened:

I'd like to apply different vim configurations for different site. Is there some variable that contains site url to help me determine it? Any suggestions?

What I expected is:

```vim
if current_url ~= "github\.com"
  set background=light
  colorscheme github
else
  set background=dark
  colorscheme onedark
endif
```

**Comment by glacambre** [comment]
The domain name of the website is in the file's name, so you can apply site-specific settings like this:
```vim
au BufEnter github.com_*.txt set filetype=markdown
```
This is described [here](https://github.com/glacambre/firenvim#using-different-settings-depending-on-the-pageelement-being-edited). Let me know if you have ideas for making this easier to find/understand :).

**Comment by lolimay** [comment]
Nice, thanks!
