### ISSUE TITLE
Making Brave Work

### ISSUE THREAD

**Issue by ThePrimeagen** [glacambre/firenvim#773]
- OS Version: linux x86-64 (ubuntu, 19.10)
- Browser Version: Brave-Browser: 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: 0.1.32
- What I tried to do: Add some serious coconut oil.
- What happened:  Oil was added and brave worked!!!

But Seriously, this is what happened.  I am trying to make brave work and was
unable to do so.  Kept saying that "Neovim died", Luckily I was failing on
twitch and a nice viewer, named Flame_Kasai, told me to check the configs.

Therefore I did the following things:
0. Ensured that i installed everything: `nvim --headless "+call firenvim#install(69) | q"`

```
Installed native manifest for chromium.
Installed native manifest for opera.
Installed native manifest for brave.
Installed native manifest for vivaldi.
Aborting installation for chrome-canary. Chrome Canary doesn't exist on Linux
Installed native manifest for chrome.
Installed native manifest for firefox.
```

1. $HOME/.config/chromium/NativeMessagingHosts and ensured its identical to
   google-chrome's configuration.  It was.

2. firenvim still didn't work

3. Then It was mentioned, (flame above), that there is a BraveSoftware folder.
   I went into it and found another NativeMessagingHosts folder and copied the
   config from chromium to it (located here:
   $HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts).

4. ...

5. After that firenvim worked like a charm!! (and profit)

-----
After looking at the autoload script it does look like it mostly gets brave
correct.  My assumption is that the install does not put it in the correct
brave location.

This looks mostly correct.  It just seems to be missing `Brave-Browser` folder.

[AutoLoad](https://github.com/glacambre/firenvim/blob/master/autoload/firenvim.vim#L188)

----
BTW, I am typing this issue up using firenvim and its straight fire.

**Comment by glacambre** [comment]
Thanks for opening this issue and for taking the time to figure out what was wrong :). This is a bit surprising as I know some Firenvim users managed to make Brave work with Firenvim before (#355, #144).

@habamax @Mananit0 did you have to fiddle with the NativeMessagingHosts folder to get Firenvim to work with Brave on your machines?

**Comment by glacambre** [comment]
The fix created by @bryall has now been merged, so running `firenvim#install()` should now put the manifest in the right place.

Thanks for reporting this bug (and for making a video about Firenvim, it was great!) :).

**Comment by ThePrimeagen** [comment]
Of course it was @bryall .  He has categorically provided so many fixes for me :) Thanks bud!!
