### ISSUE TITLE
Thunderbird "browser" keyboard shortcuts

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#776]
>The ctrl+e shortcut was ineffective to bring back the Neovim window after I closed it once. But I suppose this is kind of expected, given that Thunderbird lists no shortcut for the add-on.

Using the commands API threw exceptions in thunderbird so I just assumed in wasn't available and removed the code, but it looks like commands should work actually:
https://thunderbird-webextensions.readthedocs.io/en/68/commands.html#manifest-file-properties
I'll investigate. Thanks for the report @Qeole :)

**Comment by glacambre** [comment]
This is blocked by a thunderbird issue. `browser.tabs.query({ active: true, currentWindow: true })` never returns a compose window, even if its window is the current window and its tab is active. I'll report this on bugzilla tomorrow.

**Comment by varac** [comment]
Is there any upstream TB issue to solve this blocker ?

**Comment by glacambre** [comment]
@varac Not to my knowledge, but I haven't looked in a while. Please feel free to open a bugzilla ticket if you can't find one :).

**Comment by glacambre** [comment]
I'll probably have to rewrite Firenvim for thunderbird from scratch once https://github.com/glacambre/firenvim/issues/984 is fixed, which will probably make this bug problem disappear. So I'll close this issue for now :)
