### ISSUE TITLE
Neovim related issue

### ISSUE THREAD

**Issue by LoydAndrew** [glacambre/firenvim#781]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 86.0.4240.75
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: fb525da
- What I tried to do:
   I walked through troubleshooting guide and got error on this step

>  echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim

- What happened:

> --- Autocommands ---Press ENTER or type command to continuenvim: /build/neovim-bBMLK2/neovim-0.5.0+ubuntu2+git202011021721-bab5b2fbd-d569569c9/src/nvim/message.c:2239: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
> [1]    7507 done                 echo 'abcde{}' | 
>        7508 abort (core dumped)  $HOME/.local/share/firenvim/firenvim

**Comment by glacambre** [comment]
This is the same issue as https://github.com/neovim/neovim/issues/11362 . This probably means that there are errors in your vimrc. What happens if you run `nvim --headless "+call firenvim#install(0) | q"` in your shell?

**Comment by LoydAndrew** [comment]
Basically the same error 

> --- Autocommands ---No config detected for chromium. Skipping.
> No config detected for opera. Skipping.
> No config detected for brave. Skipping.
> No config detected for vivaldi. Skipping.
> No config detected for chrome-canary. Skipping.
> Installed native manifest for chrome.
> Installed native manifest for firefox.nvim: /build/neovim-bBMLK2/neovim-0.5.0+ubuntu2+git202011021721-bab5b2fbd-d569569c9/src/nvim/message.c:2239: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
> [1]    9815 abort (core dumped)  nvim --headless "+call firenvim#install(0) | q"
>

**Comment by glacambre** [comment]
Could you try `nvim --headless "+q"` then? I'd expect neovim to give us a proper error.

**Comment by LoydAndrew** [comment]
Yeah. 
It produces this

> --- Autocommands ---nvim: /build/neovim-bBMLK2/neovim-0.5.0+ubuntu2+git202011021721-bab5b2fbd-d569569c9/src/nvim/message.c:2239: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
> [1]    9988 abort (core dumped)  nvim --headless "+q"

**Comment by glacambre** [comment]
Huh. Do you get any errors when starting neovim normally from the command line?

**Comment by LoydAndrew** [comment]
No, everything works just fine.  I encounter errors only when starting with headless argument.

**Comment by glacambre** [comment]
Is your init.vim available somewhere? I'd need to reproduce this bug to better understand what's going on.

**Comment by LoydAndrew** [comment]
https://github.com/LoydAndrew/nvim/blob/main/init.vim

**Comment by glacambre** [comment]
This line is causing the crash:

https://github.com/LoydAndrew/nvim/blob/eb9e8a68233b1509d06c3d3865aba17091a23631/init.vim#L20

It's bogus - it causes an error message and neovim crashes. The crash can be reproduced with the following init.vim:
```vim
autocmd vimenter *
set cmdheight=2
```

This is indeed covered by https://github.com/neovim/neovim/issues/11362 and there's nothing I can do at the Firenvim level :)

**Comment by LoydAndrew** [comment]
Thank you for you help! I will close this issue then.
