### ISSUE TITLE
Make nvim start in restricted mode (-Z) by default

### ISSUE THREAD

**Issue by ChocolateOverflow** [glacambre/firenvim#783]
Given that one of Firenvim's biggest security concerns is code execution, and that we usually don't need to execute shell code from the browser, I think it'd be safer to have the background nvim process run with `-Z` by default to run with restricted mode which restricts running shell commands with `!some_cmd`. I do realize that this won't stop it from accessing files with commands like `:edit` but simple disabling external shell commands should be a great step to restrict command execution.

**Comment by alerque** [comment]
This would be fine as long as this comes an override I can put in my config somewhere, I use external commands all the time!

**Comment by glacambre** [comment]
This is impossible on a technical level as `-Z` disables the lua interface, which prevents Firenvim from starting the websocket server it uses to communicate with the browser.

Even if technically possible, I'm not convinced this would improve anything as an attacker able to run shell commands from Firenvim would also be able to write something to your bashrc/zshrc and execute arbitrary code that way. The only real solution is for you to properly setup a sandbox for your browser/firenvim (there's a bit of information about this here: https://github.com/glacambre/firenvim/issues/238 ).
