### ISSUE TITLE
Can not turn element into neovim iframe in Coursera Jupyter labs

### ISSUE THREAD

**Issue by nguyentritai2906** [glacambre/firenvim#786]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 86.0.4240.183
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: 0.1.32
- What I tried to do: Trigger Firenvim to turn Coursera Jupyter lab's code block into neovim frame with 'C-e'
- What happened: Nothing happened although it works on other sites

**Comment by glacambre** [comment]
Hi, thanks for the report. Is there a way to access one of these jupyterlab instances for free?

**Comment by nguyentritai2906** [comment]
Hi @glacambre, there are some courses that you can audit and view the labs environment. Try search for the Understanding and Visualizing Data with Python course - Enroll for free and choose 'Audit' at the bottom left of the pop up window. You should be able to access the lab materials for this course.

**Comment by glacambre** [comment]
@nguyentritai2906 I tried to use neovim on coursera's jupyter labs and everything works fine AFAICS. I might have accidentally fixed it in the past few months, could you tell me if you're still experiencing issues?

**Comment by nguyentritai2906** [comment]
@glacambre Everything works fine now.

**Comment by nguyentritai2906** [comment]
@glacambre Yeah, everything working now. Thank you. Have a good day.

**Comment by glacambre** [comment]
Great, thanks for replying! :)
