### ISSUE TITLE
Neovim is not responding [Firefox ]

### ISSUE THREAD

**Issue by pmilosev** [glacambre/firenvim#798]
- OS Version: macOS x86-64 | 10.15.7
- Browser Version:  Firefox 82.0.2
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: commit e57643b33f8b8d2a42b3d1d3c667c3146306a341
- Neovim Version: 0.4.4
- What I tried to do: Clean setup
- What happened: Addon shows an error 'Neovim is not responding.'

I did the troubleshooting and some debugging:
- Installation seems to be working fine:
```
$ printf 'abcde{}' | /Users/pmilosev/.local/share/firenvim/firenvim
?{"version": "0.1.32", "settings": {"localSettings": {".*": {"priority": 0, "cmdline": "neovim", "selector": "textarea", "takeover": "always"}}, "globalSettings": {"alt": "all"}}}%  
```
- `$PATH` also seems to be fine (manually checked the `$PATH` in the `firenvim` script) 
- There is an uncaught timeout exception when I disable and enable the plugin (from FF addons):
```
Uncaught (in promise) Neovim is not responding. background.ts:81:15
    timeout background.ts:81
    (Async: setTimeout handler)
    registerErrors background.ts:76
    createNewInstance background.ts:208
    createNewInstance background.ts:202
    ts background.ts:230
    Webpack 3
```
As far as I could tell (sorry I'm not a web dev :)) the connection on line 207 times out `const nvim = browser.runtime.connectNative("firenvim");`
- I edited the `firenvim` script to log input arguments as well as `stdin` input. It looks like the browser is calling the script as
``` 
/Users/pmilosev/.local/share/firenvim/firenvim /Users/pmilosev/Library/Application Support/Mozilla/NativeMessagingHosts/firenvim.json firenvim@lacamb.re
```
As for `stdin` I could see messages like `p`, `r`, `o`, `q` but I didn't trace under which condition which message was received (except for `q` which was received when disabling the plugin, so I interpeted it as short for `quit` :))
NOTE: `stdin` logging was done using a simple shell `while true` loop with a `read line; sleep 1` inside, so might not be accurate.

**Comment by glacambre** [comment]
Thanks a lot for going through the troubleshooting guide and providing a thorough bug report :)

I'm wondering, are you not getting any errors at all when [redirecting the shell script](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#print-debugging-your-initvim)'s output? Usually when the background script hangs it's because Neovim emits errors.

Could you try Neovim v0.5? Neovim v0.4.4 should work fine if I recall correctly but maybe I broke compatibility somewhere without realizing.

Also, is your init.vim available somewhere? Maybe there's something in there triggering errors when ran by Firenvim.

**Comment by pmilosev** [comment]
Somehow I have missed the last section of the troubleshooting guide :)))
The reason I went into intercepting `stdin` was to actually try and send the same input manually, but I got no errors when I did that.
Now that I have redirected `stderr` and invoked `firenvim` the regular way I can see this error:
```
Downloading junegunn/vim-plug to manage plugins...Error detected while processing command line:
E117: Unknown function: firenvim#run[vim-plug] Invalid plug directory: /nvim/plugged. Try to call plug#begin with a valid directory
Press ENTER or type command to continueVim: Caught deadly signal 'SIGTERM'

Vim: Finished.
Downloading junegunn/vim-plug to manage plugins...Error detected while processing command line:
E117: Unknown function: firenvim#run[vim-plug] Invalid plug directory: /nvim/plugged. Try to call plug#begin with a valid directory
Press ENTER or type command to continueVim: Caught deadly signal 'SIGTERM'

Vim: Finished.
```
For some reason  `/nvim/plugged` is used instead of `$HOME/.config/nvim/plugged` and then of curse everything breaks.
I will try to find out why '$HOME/.config' part is missing (env. variable missing ?), but if you have any ideas please let me know.
Thanks

**Comment by pmilosev** [comment]
Ah finally - writting this comment in nvim.

As susspected the issue was resolution of env. variable which is defined my ~/.profile:
`export XDG_CONFIG_HOME="$HOME/.config"`

Then in my `init.vim` I have:
`call plug#begin(expand("$XDG_CONFIG_HOME/nvim/plugged"))`

This was fine until now as I exclusively used nvim from within command line.
But env. variables defined in `.profile` are not available in GUI apps - so I need to find a solution for that.

Temporarely changing my config to an explicit path solves the issue:
`call plug#begin(expand("/Users/pmilosev/.config/nvim/plugged"))`

Thanks
