### ISSUE TITLE
Repeating error: "Error detected while processing function My_Write: E32: No file name

### ISSUE THREAD

**Issue by madranet** [glacambre/firenvim#804]
- OS Version: mac x86-64
- Browser Version: Yandex Browser
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: 0.1.32

I was editing a text file in VimR today and this error kept appearing over and over again, every few seconds. I've seen it popup the odd time before. But this time it was really persistent!

![SS 2020-11-26 at 19 44 53](https://user-images.githubusercontent.com/669658/100387990-4d11d380-3021-11eb-9661-9a5b7d6417d9.png)

I loaded up my `~/.vim/bundle` directory in TextMate and did a search for `My_Write` across all my plugins and the smoking gun was only found in the hands of FireNvim. Any idea what's causing this and how to stop it? I've had to disable FireNvim for now, as this constantly repeating error is making VimR unusable.

I started editing the file in question by opening VimR and beginning to write. So, obviously, at that stage, the document had never been saved and was what would in GUI terms be considered an "untitled document". The wording of the error message `"No file name"` would suggest FireNvim  is having a problem with this... although why FireNvim is throwing up an error when it's not actually being used is a mystery.

**Comment by glacambre** [comment]
Sounds like you added [this example](https://github.com/glacambre/firenvim#automatically-syncing-changes-to-the-page) to your init.vim. If you don't need it I suggest removing it. If you do need it, you could try adding a check making sure that the file has a filename before writing it :)

**Comment by madranet** [comment]
> Sounds like you added [this example](https://github.com/glacambre/firenvim#automatically-syncing-changes-to-the-page) to your init.vim...

Ah. Good call. I did indeed add that to my `~/.vimrc`.  That's also solved the mystery of why Nvim has seemed to pause momentarily every few seconds while editing other documents, as if it was autosaving.  It was!  Naively, I never made the connection with that config option as I somehow assumed it would only be running when FireNvim was active.  

Well, I can live without autosave. Especially now I know that, as well as the annoying error messages, it's also to blame for the performance hit I've been seeing when using Nvim recently.

Actually, I'll try putting the autosave function inside the example given in the docs for testing if FireNvim is calling Nvim.  That should work, shouldn't it?....

```
" Config for Firenvim plugin 

"this var set if nvim was called by firenvim

if exists('g:started_by_firenvim')
 
"autosync buffer [throttled] once a second?
" don't use this generally, or it causes:
" error detected while processing function my_write: E32: no file name
" error, over and over again, while working in untitled docs

let g:dont_write = v:false
function! My_Write(timer) abort
    let g:dont_write = v:false
    write
endfunction

function! Delay_My_Write() abort
    if g:dont_write
        return
    end
    let g:dont_write = v:true
    call timer_start(10000, 'My_Write')
endfunction

au TextChanged * ++nested call Delay_My_Write()
au TextChangedI * ++nested call Delay_My_Write()

else
  "do nada
endif
```  
If using this approach, would I need to set something like `g:don't write = true` in the `else` clause, to reset things after a FireNvim invoked edit window has been closed again?

**Comment by glacambre** [comment]
>autosync buffer [throttled] once a second?

I think that's 10 seconds.

>If using this approach, would I need to set something like g:don't write = true in the else clause, to reset things after a FireNvim invoked edit window has been closed again?

I don't think so - `g:started_by_firenvim` will only ever be set when neovim is launched by Firenvim. This means that the TextChanged autocommands will only be created when neovim is launched by Firenvim and the Delay_My_Write/My_Write functions will only run when neovim was launched by Firenvim.

Right now Firenvim creates its own neovim instances so it can't pollute your other neovim instances. I do plan on implementing a proper (optional) server mode one day and if you decide to use that then you will have to replace `if exists('g:started_by_firenvim')` with UIEnter/UILeave.

**Comment by madranet** [comment]
> > autosync buffer [throttled] once a second?
> 
> I think that's 10 seconds.

Whoops! --of course.

> I don't think so - `g:started_by_firenvim` will only ever be set when neovim is launched by Firenvim ... 
> Right now Firenvim creates its own neovim instances so it can't pollute your other neovim instances...

Cool. thanks for the clarification.
