### ISSUE TITLE
Always on by default

### ISSUE THREAD

**Issue by kaihendry** [glacambre/firenvim#810]
I wanted to toggle it only when I strike C-e.

https://s.natalian.org/2020-12-02/default.mp4

I'm using latest since I installed it yesterday and I use Arch btw.

**Comment by glacambre** [comment]
Have you tried changing the [takeover](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements) setting? (Make sure you read the [description of the configuration object](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements) to understand how configuring firenvim works :))

**Comment by kaihendry** [comment]
I don't quite follow. `let fc['.*'] = { 'takeover': 'always' }` is the default and I need to set that as **never** in my `~/.config/nvim/init.vim`?

**Comment by glacambre** [comment]
Yes. Please note that as described in the [description of the configuration object](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements), `let fc[...] = { ... }` is shorthand for `let g:firenvim_config = { localSettings: { '...': { ... } } }`.

**Comment by kaihendry** [comment]
Via https://github.com/search?q=%22takeover%22+filename%3Ainit.vim&ref=simplesearch I'm using 

    let g:firenvim_config = {'globalSettings': {},'localSettings': {'.*': {'takeover': 'never'},},}

It appears to work. I would prefer this to be the default, since it's sensible to me to opt in!

Thank you

**Comment by glacambre** [comment]
I agree that it'd be better to make this the default but it's too late for that now, changing the default would mean breaking current configuration for current users.
