### ISSUE TITLE
Remove debug log line

### ISSUE THREAD

**Issue by h43z** [glacambre/firenvim#816]
I think you forgot to remove one debug line from the code. It's kinda annoying to have it there.

https://github.com/glacambre/firenvim/blob/d45928f91002d079ac083b3426cf209a03aefd59/src/NeovimFrame.ts#L22

Whats strange is sometimes when I click on the console.log entry in the web console it even crashes the tab in firefox.

**Comment by glacambre** [comment]
Woops, sorry about that! Fixed in https://github.com/glacambre/firenvim/commit/11c7ac7b7f14da00e8176a6627028cb8acbb2b15 , the change will reach you once I publish a new release. Thanks for the report :)
