### ISSUE TITLE
How to disable firenvim on a specific website?

### ISSUE THREAD

**Issue by rohitkrishna094** [glacambre/firenvim#836]
- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 87.0.4280.88
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: 0.1.32

#### What I tried to do 
I tried looking at #269 and added this to my neovim config

```
if exists('g:started_by_firenvim')
	call firenvim#configure_site('*somesite.com', '')
endif
```

I also tried #267, and added this

```
call firenvim#add_site_config('somesite.com')
```

But this also hands entire firenvim extension for me.

#### What happened
The entire firenvim hangs for some reason and doesn't work on other sites as well.

**Comment by glacambre** [comment]
Please read about [how the firenvim configuration object works](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object) and then about [configuring firenvim to not take over elements](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements). Let me know if you still don't understand how to disable Firenvim on a specific website, we'll try to find better wording :)

**Comment by rohitkrishna094** [comment]
Thanks. For reference, leaving the answer here. This is what I added to init.vim file and now whenever I go to "somesite" website, firenvim is not triggered.


```vim
let g:firenvim_config = { 
    \ 'globalSettings': {
        \ 'alt': 'all',
    \  },
    \ 'localSettings': {
        \ '.*': {
            \ 'cmdline': 'neovim',
            \ 'content': 'text',
            \ 'priority': 0,
            \ 'selector': 'textarea',
            \ 'takeover': 'always',
        \ },
    \ }
\ }

let fc = g:firenvim_config['localSettings']
let fc['https?://[^/]*somesite.com/*'] = { 'takeover': 'never', 'priority': 1 }
```
