### ISSUE TITLE
New renderer: black bar at end of window when resized by page

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#860]
- OS Version: linux x86-64
- Browser Version:  Firefox 84.0
- Browser Addon Version: 0.2.0
- Neovim Plugin Version: 0.2.0
- What I tried to do: Use Firenvim on Element
- What happened: The Firenvim frame got resized and a black line appeared at the bottom of the screen.

**Comment by alerque** [comment]
There might be something more general resize problems, or this might be the same issue, but I'm having trouble with *all* resize events. For example in this GitHub Issue as soon as my text is long enough to make the textarea grow it's going to cause the Firenvim view to *shrink* to be both narrower and shorter than the textarea it covers.

![image](https://user-images.githubusercontent.com/173595/104050657-fe4a8280-51f7-11eb-8dbc-3e06d966f37a.png)

Note when I first started *and* if I close and restart Firenvim it will come back at the right size.

**Comment by glacambre** [comment]
@alerque I can't reproduce the behavior you're describing, even with an empty init.vim. Could you share a reproducer?

**Comment by glacambre** [comment]
@alerque This issue is closed because I fixed it in master - I'll publish a new release within the hour, please open a new issue with repro steps if you're still able to reproduce the bug :).
