### ISSUE TITLE
Will not open to a preset number of lines and columns.

### ISSUE THREAD

**Issue by jdevries3133** [glacambre/firenvim#865]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 87.0.4280.88
- Browser Addon Version: 0.2.0
- Neovim Plugin Version: 0.2.1

^^ Maybe my problem is this mismatch? I tried to make sure they are both
at the latest, and I am pretty sure they are??

- What I tried to do:

Set nvim to open at a predefined number of rows & cols by using the code
snippet from the documentation.

- What happened:

This was working for a long time but broke recently. I suspect it might have
something to do with the new rendering engine which I think you recently
implemented? That is working great by the way, firenvim is much snappier
and responsive – great work!

Of course, it could be a config error on my part, so here is the bit of
my `init.vim` file where I do my firenvim business:

```vim
function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction
function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    set wrap  " WEIRDEST THING is that this still works somehow?
    set lines=20
    set columns=90
    au BufEnter github.com_*.txt set filetype=markdown
    au BufEnter old.reddit.com_*.txt set filetype=markdown
  endif
endfunction
autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```

I also do some site-specific config below. I added this more recently,
but even if I comment it out my main problem perserveres.

```vim
" site-specific firenvim configurations
if exists('g:started_by_firenvim')
    let g:firenvim_config = {
    \   'globalSettings': {},
    \   'localSettings': {}
    \}
    " do not open in the reddit chat.
    let g:firenvim_config['localSettings']['old.reddit.com'] = {
    \   'selector': 'textarea:not(._24sbNUBZcOO5r5rr66_bs4):not(.TqpfKgK2FdKbljZzdRLIU)',
    \   'takeover': 'always'
    \}
    " do not do anything in google web apps
    let g:firenvim_config['localSettings']['\(docs\|sheets\|slides\|mail\)\.google\.com*'] = {
    \   'takeover': 'never',
    \   'priority': 1,
    \}
    let g:firenvim_config['localSettings']['flipgrid.com'] = {'takeover': 'never'}
endif
```

Very sorry if this is a repetitive issue; to the best of my understanding after
looking around, it is not. Thank you so much for all you do on this project,
it really is a joy to use!

**Comment by glacambre** [comment]
>^^ Maybe my problem is this mismatch? I tried to make sure they are both at the latest, and I am pretty sure they are??

There's a delay in Chrome's addon publication mechanism, v0.2.1 should reach you soon hopefully :).

I'm a bit surprised I managed to break this with the new renderer, I though I had implemented resizes in the same way. I'll investigate, thanks a lot for the bug report! In the meantime, you can revert to the old renderer like this if you so choose:
```vim
let g:firenvim_config = {
  \ 'localSettings': {
    \ '.*': {
      \ 'renderer': 'html',
    \ }
  \ }
\ }
```

**Comment by jdevries3133** [comment]
Thank you, that reversion did bring back the behavior I had before.

Actually, as I continue to look at this, there are a few things going on for me. I definitely have a scaling issue, for one thing. As you can see, the editor is rendering with very small text. Also, weirdly, it seems that there is some acknowledgement of the lines and cols configuration as the editor loads, but at some point it just decides to fill the whole textarea anyway. Watch this video to see what I mean:

https://user-images.githubusercontent.com/58614260/104126272-add34200-5329-11eb-832e-53569abfe779.mov

**Comment by glacambre** [comment]
I think the difference comes from here:
https://github.com/glacambre/firenvim/blob/176a146168dac1c634f7387325ad0e22bf0d18d9/src/render/Redraw.ts#L304-L308
https://github.com/glacambre/firenvim/blob/176a146168dac1c634f7387325ad0e22bf0d18d9/src/render/RedrawCanvas.ts#L608-L612
With the old renderer Firenvim didn't do anything if guifont wasn't set, so there wouldn't be a resize on neovim startup. The new one sets a default and unconditionally resizes.

Closesly related to https://github.com/glacambre/firenvim/issues/800 ...

**Comment by jdevries3133** [comment]
Ok, I see. Given that advice, I was able to get things working as before
with the new renderer. I really appreciate your help! This is the
configuration that is making it happen:

```vim

function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction

function! SetFont(timer) abort
    set guifont=Monospace:h16
endfunction

function! SetLines(timer) abort
    set columns=100
    set lines=20
    set wrap
endfunction

function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    call timer_start(100, function("SetFont"))
    call timer_start(800, function("SetLines"))
    au BufEnter github.com_*.txt set filetype=markdown
    au BufEnter old.reddit.com_*.txt set filetype=markdown
  endif
endfunction
autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```

I am very happy to be writing my message in firenvim this time! Thank you for
all you do :)

I think maybe setting the default font size to 16pt instead of 9pt here is
worth consideration. I found that at 9pt, it was impossibly small to read,
but that may just be my experience.

https://github.com/glacambre/firenvim/blob/176a146168dac1c634f7387325ad0e22bf0d18d9/src/render/RedrawCanvas.ts#L608-L612

**Comment by glacambre** [comment]
I fixed the renderer to not trigger resizes on empty guifont/linespace settings so the new renderer's behavior will match that of the old one now (so you'll be able to drop the changes you made to your init.vim).

>I think maybe setting the default font size to 16pt instead of 9pt here is worth consideration.

I made a attempt at having it default to whatever default size the browser uses for regular text, we'll see if it works.

I'll publish a new release once I've decided what I want to do with #800 :)

**Comment by glacambre** [comment]
I've submitted v0.2.2 on the chrome and firefox add-on stores, the fix will hopefully reach you soon :)
