### ISSUE TITLE
Black artifacts after lines and even characters

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#867]
Similar to #860, I'm seeing strange black artifacts, especially after resize events. Usually this takes the form of a black line at one place in the frame, but several times it's been lines between lines. Just now while replying to another issue and playing with the resize, I got block bars after every character after the first line:

![image](https://user-images.githubusercontent.com/173595/104155262-d9246280-53f7-11eb-9e72-a3487250cfd2.png)

Its possible my issues are again related to page zoom levels rather than whatever was behind #860.

**Comment by glacambre** [comment]
Ah, I think I know what's going on, thanks for reporting this bug :)

**Comment by glacambre** [comment]
I published v0.2.3 on the firefox add-on store, let me know if you still encounter issues :)
