### ISSUE TITLE
Cant sent gmail with extension enabled

### ISSUE THREAD

**Issue by boydkelly** [glacambre/firenvim#873]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 87.0.4280.88
- Browser Addon Version: 0.2.3
- Neovim Plugin Version: 0.2.3
- What I tried to do:
- What happened:

**Comment by alerque** [comment]
This is probably a duplicate of #784, but without more details describing what happened it's hard to tell.

**Comment by boydkelly** [comment]
haha.   Sorry yes its the same issue.  But for some weird reason i clicked on send or whatever and my comment disappeared.   Oh well.  Thanks for the response.  Hope the issue of #784 gets fixed.
