### ISSUE TITLE
Unable to configure takeover setting.

### ISSUE THREAD

**Issue by LiterallyJohnny** [glacambre/firenvim#887]
- OS Version: Arch Linux, rolling release
- Browser Version:  Firefox Nightly 86.0a1 (2021-01-20) (64-bit)
- Browser Addon Version: 0.2.3
- Neovim Plugin Version: 0.2.3
- What I tried to do: I tried to configure the takeover setting so that Firenvim won't open the editor when selecting a text box unless I run the command for it.
- What happened: [I received an error on Neovim startup](https://i.imgur.com/uf2ieY4.png) and it still seems to be taking over boxes. Below is line 76:

```
let fc['.*'] = { 'takeover': 'never' }
```

[You can find my entire Neovim config here.](https://github.com/LiterallyJohnny/Dotfiles/tree/main/configs/nvim)

**Comment by LiterallyJohnny** [comment]
Note: I am also on the Neovim Nightly build. My version is `NVIM v0.5.0-dev+1037-gd6d4e3d1a`.

**Comment by glacambre** [comment]
I can't find a [firenvim config object](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object) in your init.vim, did you forget to commit that? :)

**Comment by LiterallyJohnny** [comment]
Yeah, it does seem as if I forgot to commit it. [You can find it here.](https://github.com/LiterallyJohnny/Dotfiles/tree/main/configs/nvim) You can find Firenvim's settings by going to the plugins folder and going to plugins.vim

**Comment by glacambre** [comment]
Great. As explained in [the documentation](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object), `let fc[...] = ...` is a shorthand that assumes that you have defined a `g:firenvim_config` object and that you have a line like `let fc = g:firenvim_config['localSettings']` in your config. I think this is what's missing from your config :)

**Comment by LiterallyJohnny** [comment]
Yep, that looks to be the issue. Thanks for your help!
