### ISSUE TITLE
Disable plugins when using firenvim

### ISSUE THREAD

**Issue by medwatt** [glacambre/firenvim#892]
- OS Version: linux x86-64
- Browser Version:  Firefox 84.0
- Browser Addon Version: 0.2.3
- Neovim Plugin Version: 0.2.3
- What I tried to do:

Thanks for such a wonderful plugin. Everything seems to be working great! I am just wondering that since I am not using most of the plugins I have installed if it is possible to disable most of them as there's no point loading them and this will probably speed up the process of launching neovim in the browser. Or maybe there's a way to have a separate `init.vim` file that I can load that is specific for firenvim?

**Comment by glacambre** [comment]
There are [many ways](https://github.com/glacambre/firenvim#building-a-firenvim-specific-config) to do this. You can use `UIEnter` (recommended) or `g:started_by_firenvim` to selectively set settings, run commands or even `:source` vimscript files that will load or not load your plugins. Let me know if you need more examples :).

**Comment by medwatt** [comment]
> There are [many ways](https://github.com/glacambre/firenvim#building-a-firenvim-specific-config) to do this. You can use `UIEnter` (recommended) or `g:started_by_firenvim` to selectively set settings, run commands or even `:source` vimscript files that will load or not load your plugins. Let me know if you need more examples :).

Thanks for your swift reply. At the moment, I basically copy-pasted the example you linked. This is what I have:

```vim
function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction

function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    set showtabline=0
    set laststatus=0
    set guifont=Iosevka\ Term:h14:r
  endif
endfunction

autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
au BufEnter github.com_*.txt filetype=markdown
au BufEnter localhost_lab_*.txt set filetype=python
```

I use a plugin called startify, which provides a start page with shortcuts to recently opened files, and I can definitely tell it is loading when firenvim fires. Since I'm won't be need using this plugin, I figured there's no need to load it along with almost 90% of my other plugins. I know you mentioned it in your post, but I wouldn't mind if you could give an example on how to only enable a couple of plugins. Better still, it would be nice to have a separate init file for just firenvim. I am currently using [vim-plug](https://github.com/junegunn/vim-plug) to load my plugins, if that matters.

**Comment by glacambre** [comment]
>Better still, it would be nice to have a separate init file for just firenvim.

You can do either:
```vim
function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    source /path/to/firenviminit.vim
  else
    source /path/to/regularinit.vim
  endif
endfunction
```

or

```vim
if exists("g:started_by_firenvim")
  source /path/to/firenviminit.vim
else
  source /path/to/regularinit.vim
endif
```

:)

**Comment by medwatt** [comment]
@glacambre thank you very much !
