### ISSUE TITLE
Neovim plugin version (0.1.32) and browser addon version (0.2.3) do not match.

### ISSUE THREAD

**Issue by madranet** [glacambre/firenvim#894]
- OS Version: mac x86-64
- Browser Version: Yandex Browser 20.12.0.1065 (64-bit)
- Browser Addon Version: 0.2.3
- Neovim Plugin Version: 0.1.32

I'm seeing this when I popup the FireNvim icon in my browser menubar.  Is there anything I need to do about this? I can't see any options anywhere for updating.

![SS 2021-01-23 at 12 23 37](https://user-images.githubusercontent.com/669658/105578175-2f898d80-5d76-11eb-9a92-6afe53104c08.png)

I also notice the icon is yellow now , when I'm pretty sure it used to be white before. Is this just a cosmetic change, or is the yellow indicating a warning [as per above error message]?

**Comment by glacambre** [comment]
That's a warning, you need to update the Neovim plugin (git pull, `minpac#update()` or whatever your plugin manager needs you to do to update plugins) :).

**Comment by madranet** [comment]
Ah, yes. That was it
