### ISSUE TITLE
[feature request] able to zoom nvim window

### ISSUE THREAD

**Issue by mirsella** [glacambre/firenvim#897]
hey, thanks  for project :)

i'm probably dumb and this is probably already possible but i coudln't find a way to zoom, make bigger the nvim window, and apparently nvim doesn't have a feature to zoom by itself, as it's managed by terminal app usually ? 

i think it would be useful to be able to make the nvim window bigger like a terminal we would do ctrl+scroll wheel.

thanks, and sorry if it already exists or a issue is already open for it.

**Comment by glacambre** [comment]
Hi. You can control the size of the font with `guifont`, e.g. `set guifont=monospace:h10`. See `:help guifont` for more information :)

**Comment by mirsella** [comment]
thank you, i added "command! -nargs=+ Zoom :set guifont=monospace:h<args>" to my init.vim. sorry i didn't find any resource online mentioning guifont when searching for zoom / bigger vim

**Comment by glacambre** [comment]
>sorry i didn't find any resource online mentioning guifont when searching for zoom

No problem, I'm glad I could help :)
