### ISSUE TITLE
Special support for <Tab>/<Enter> in non-textarea elements

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#9]
It's rather annoying to have to `:q!` these elements before being able to `<Tab>`/`<Enter>`.

**Comment by norcalli** [comment]
You could just set a variable to indicate that this is an embedded frame, and then based on that we can optionally set a keybinding for those. I would leave it up to the user to decide how those keybindings should be set, as long as they have the ability to differentiate sessions.

**Comment by infokiller** [comment]
@glacambre can you please elaborate?
What do you mean by "non-textarea" elements? do you refer to other editable elements that invoke firenvim?

**Comment by glacambre** [comment]
This is an issue I opened back when Firenvim took over every element (including input fields) without the ability to configure anything. It doesn't make sense anymore.
