### ISSUE TITLE
Firenvim does not set cursor position on write to Textarea

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#904]

**Comment by snippins** [comment]
@glacambre I just want to ask that the cursor position doesn't seem to be set accordingly in jupyter notebook (code mirror) yet, right? It's always reset to the beginning of the cell, unlike normal text area, for me at least.

**Comment by glacambre** [comment]
I'm quite certain this used to work, but it does seem to be broken at the moment. Thanks for reporting this issue!
