### ISSUE TITLE
recent wsl post-installation hook does not work

### ISSUE THREAD

**Issue by moongi-simon-hong** [glacambre/firenvim#918]
window 10 pro insider preview fast ring : build 21301.rs_prerelease.210123-1645
neovim : NVIM v0.5.0-dev+1062-gcc1851c9f
wsl distribution : ubuntu-20.04
install firenvim by vimplug

<img width="505" alt="firenvim" src="https://user-images.githubusercontent.com/75198947/106425158-cbb64180-64a6-11eb-9dc6-1589869bc3f4.png">

posthook script show weired error.
why wsl path deals with ? /mnt

In my other laptop with exact same comfiguration except window 10 pro insider runs smoothly
- due to some change to wsl-2 brough by window 10 insider?

**Comment by glacambre** [comment]
>why wsl path deals with ? /mnt

Firenvim needs to put a file (the [native manifest](https://developer.mozilla.org/en-us/docs/Mozilla/Add-ons/WebExtensions/Native_manifests)) on your disk on the windows side in order to make your browser know how to start the neovim server.

>In my other laptop with exact same comfiguration except window 10 pro insider runs smoothly. due to some change to wsl-2 brough by window 10 insider?

That is surprising. Are you saying that Firenvim used to work on wsl2 before?


In order to fix this, could you edit `autoload/firenvim.vim` (you can find this file on your disk by running `find ~ -name firenvim.vim`) and add `echo a:path` on [line 76](https://github.com/glacambre/firenvim/blob/696b978c76605be6acb22be4a7da2fa72b679473/autoload/firenvim.vim#L76), then run `nvim --headless ":call firenvim#install(0) | q"` again and upload the output log here?

**Comment by moongi-simon-hong** [comment]
more confusing results here.
Because U mentioned firenvim normally need addtional step in wsl
I tested another laptop. so 3 window laptop. each with differenct result
* first latop
	* firenvim in neovim(window native) -> firenvim in chrome(window native)
	* firenvim in neovim(wsl2) -> firenvim in chrome(wsl2 -> X11)
* second latop
	* firenvim in neovim(window native) -> firenvim in chrome(window native)
	* firenvim in neovim(wsl2) -> error mentioned orginal post
* third latop
	* firenvim in neovim(window native) -> firenvim in chrome(window native)
	* firenvim in neovim(wsl2) -> firenvim in chrome(window native)

confirmed by looking and neovim version in browser(0.44 in window native, 0.50-dev in wsl2)
It might be due to some environmental variable in bash. 
I tweak a lot of variables while configuring X11 stuff.

For a log I will check it when i got that laptop

**Comment by glacambre** [comment]
Ah, I know what's going on, when I added support for `(Native browser) -> (WSL Neovim)`, I broke `(WSL browser) -> (WSL neovim)`. I must admit I didn't expect anybody to run their browser in WSL. I'll try to fix it soon, thanks a lot for the details! :)

**Comment by glacambre** [comment]
Here's the diff that should make things work. I'll commit it in a few minutes.
```diff

diff --git a/autoload/firenvim.vim b/autoload/firenvim.vim
index 7b6c494..2d87290 100644
--- a/autoload/firenvim.vim
+++ b/autoload/firenvim.vim
@@ -57,8 +57,6 @@ function! firenvim#press_keys(...) abort
         call rpcnotify(firenvim#get_chan(), 'firenvim_press_keys', l:keys)
 endfunction
 
-let s:is_wsl = !empty($WSLENV) || !empty($WSL_DISTRO_NAME) || !empty ($WSL_INTEROP)
-
 " Turns a wsl path (forward slashes) into a windows one (backslashes)
 function! s:to_windows_path(path) abort
         if a:path[0] !=# '/'
@@ -590,6 +588,12 @@ function! s:get_browser_configuration() abort
 
 endfunction
 
+" At first, is_wsl is set to false, even on WSL. This lets us install firenvim
+" on the wsl side, in case people want to use a wsl browser.
+" Then, we set is_wsl to true if we're on wsl and launch firenvim#install
+" again, installing things on the host side.
+let s:is_wsl = v:false
+
 " Installing firenvim requires several steps:
 " - Create a batch/shell script that takes care of starting neovim with the
 "   right arguments. This is needed because the webextension api doesn't let
@@ -685,6 +689,14 @@ function! firenvim#install(...) abort
                         echo 'Created registry key for ' . l:name . '.'
                 endif
         endfor
+
+        if !s:is_wsl
+                let s:is_wsl = !empty($WSLENV) || !empty($WSL_DISTRO_NAME) || !empty ($WSL_INTEROP)
+                if s:is_wsl 
+                        echo "Installation complete on the wsl side. Performing install on the windows side."
+                        call firenvim#install(l:force_install, l:script_prolog)
+                endif
+        endif
 endfunction
 
 " Removes files created by Firenvim during its installation process
```

**Comment by glacambre** [comment]
There, should be fixed in https://github.com/glacambre/firenvim/commit/53229b4dd2359278db81278dc833188e081ca785 . Please update the neovim plugin, run `firenvim#install` again and then try to use firenvim - things should start working again :)

**Comment by moongi-simon-hong** [comment]
confirmed wsl-neovim -> wsl-chrome support.

So it was not window-insider or bash variable issued, not at all

Thanks a lot for fast fix!

long live the neovim!
