### ISSUE TITLE
Firenvim unable to load when init.vim sets `set shada`

### ISSUE THREAD

**Issue by rmagatti** [glacambre/firenvim#922]
#### OS Version
mac x86-64
#### Browser Version: 
Firefox 85.0
#### Browser Addon Version:
0.2.3
#### Neovim Plugin Version:
0.2.3

#### What happened: 
<img width="194" alt="Screen Shot 2021-02-02 at 12 42 53 PM" src="https://user-images.githubusercontent.com/2881382/106653625-4be6b080-6554-11eb-8f7a-6c5df26809c6.png">

This error results in Firenvim not being loaded at all.

This only happens if `set shada` is set in my config.
Without the shada option everything works fine.

**Comment by glacambre** [comment]
`:set shada` doesn't do anything, it just prints the value of the `shada` option, so you can remove it from your init.vim. `:set shada=...` works fine.

You can't have Neovim print anything to stdout when embedded in your browser as the browser expects messages formatted in a very specific way.

I'm closing this but feel free to ask any other question you may have :)

**Comment by glacambre** [comment]
Actually this error message is confusing and could be made clearer.

**Comment by rmagatti** [comment]
Ah you're right 🤦‍♂️  -- yeah the message threw me off there for sure. Glad it's not a bigger issue and it's mostly just me being a dummy. 👍
