### ISSUE TITLE
Cannot map `<c-cr>`

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#933]
- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 88.0.4324.146
- Browser Addon Version: 0.2.3
- Neovim Plugin Version: 0.2.3
- What I tried to do: `inoremap <c-cr> :wq<cr>`, then press ctrl+enter
- What happened: A newline is produced. `<c-v> Enter` produces `
`  (`^M`), same as in terminal.

I'm assuming GUIs like firenvim *can* handle ctrl + enter, but currently aren't.

**Comment by glacambre** [comment]
`CR` should be in caps, e.g. `inoremap <C-CR> <Esc>:wq<CR>` or `inoremap <C-CR> <cmd>:wq<CR>`. This works fine on my machine :).
