### ISSUE TITLE
Fallback fonts not used after 0.2

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#946]
- OS Version: win x86-64
- Browser Version: Google Inc. Chrome 88.0.4324.150
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.3
- What I tried to do: Use SCP NF font if it exists, otherwise use regular SCP. `:set gfn=SauceCodePro\ NF:h14, Source\ Code\ Pro:h14`
- What happened: Some other default font is used, rather than falling back to regular SCP.
- Other symptoms/notes/reproduction: set `guifont` to a font you know exists. Then set it to `existingFont,otherExistingFont`, and it seems to pick up the first font fine. BUT set it to `existingtypofon,otherExistingFont` and a default font is used rather than `otherExistingFont`.

This problem has only been happening since 0.2 (the new renderer?)

Also, not specifying font height for one or both fonts seems to cause strange issues with the font that I don't get in gvim.

I haven't tried this in other nvim UIs

**Comment by glacambre** [comment]
Hi, thanks for the report. Does this also happen with the old renderer (`'localSettings': { '.*': { 'renderer': 'html' } }`)?

**Comment by BlueDrink9** [comment]
Replicated on linux with `set gfn=SauceCodePro\ Nerd\ Font` (works) and `set gfn=SauceCodePro\ Nerd\ Font,oauntournft` (doesn't work).

Using the old renderer, both of the above seem to work, and so does `set gfn=oauntournft,SauceCodePro\ Nerd\ Font`

**Comment by glacambre** [comment]
Should be fixed on master - the fix will reach you when I publish a new release :)
