### ISSUE TITLE
disable Nagle

### ISSUE THREAD

**Issue by justinmk** [glacambre/firenvim#95]
Just a suggestion: did you try [TCP_NODELAY](http://docs.libuv.org/en/v1.x/tcp.html#c.uv_tcp_nodelay)? This should probably be done on both ends.

**Comment by glacambre** [comment]
I'm not sure this will have a huge impact as both Firefox and Chromium already disable Nagle's algorithm and buffer network IO themselves ([see this bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=542401)) but it certainly couldn't hurt.
