### ISSUE TITLE
works firefox not in brave. not sure why!

### ISSUE THREAD

**Issue by molleweide** [glacambre/firenvim#951]
- OS Version: macos Mojave
- Browser Version: Brave Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4
- What I tried to do:
follow the troubleshooting guide as well as I could.
- What happened:
I got firenvim to work in firefox. somewhere in the process I saw a browser/nvim version mismatch error but after 
updating it is still not working in Brave for me which is the browser I use mostly.  Before updating plug it showed as disabled
in red but now nothing happens. 
When I enter a textfield there is a link that is flashing once very fast next to `background page` link under extension details.
There were no console messages when pressing background page.

I will get back if I solve!! It used to work before.

**Comment by glacambre** [comment]
Are you using brave shield? Because this breaks Firenvim (see https://github.com/glacambre/firenvim/issues/823 ).

**Comment by molleweide** [comment]
I am going to read through the last paragraphs of the trouble shoot page but those were pretty advanced for me so I have take a break and comeback later

**Comment by molleweide** [comment]
oh nvm I just saw your comment!!

**Comment by molleweide** [comment]
Thanks for replying to my issue!!

**Comment by glacambre** [comment]
@molleweide Do you confirm that this is a brave shield issue?

**Comment by molleweide** [comment]
No I am not entirely sure yet! I haven’t gotten it to work by disabling single sites. I have to test global shield off first.

**Comment by glacambre** [comment]
Disabling on single sites won't work as the connections are performed from an extension context that is independent from pages.

Please let me know once you've tried disabling brave shield globally.

**Comment by molleweide** [comment]
For sure!

**Comment by glacambre** [comment]
This issue has been awaiting feedback for a month now so I'll close it. If you still encounter this issue, please try disabling brave shield, let me know if the bug is still hapening and I'll re-open :)

**Comment by molleweide** [comment]
Cool yeah i haven’t had time to look into it yet. But ill get back if and when!

**Comment by molleweide** [comment]
i see now that it works again in brave. i am not sure what has happened because i haven't really followed your development that extensively but now i subscribe to the project.  anyways, i am super appreciative that it works now! exciting!!
