### ISSUE TITLE
Keep FireNVim disabled by default

### ISSUE THREAD

**Issue by devanshuDesai** [glacambre/firenvim#956]
I'd like to keep FireNVim disabled by default and only activate it when I need
it. Is there a way to do this? I couldn't find anything in the configuration
file to do this.

**Comment by glacambre** [comment]
This is described here: https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements

Let me know if you have ideas to make this easier to find :)

**Comment by devanshuDesai** [comment]
Thank you so much!
