### ISSUE TITLE
Not working on nixos discourse

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#959]
https://discourse.nixos.org/t/using-firenvim-neovim-embedded-in-firefox-in-nixos/11623/3

**Comment by alerque** [comment]
Just to clarify (because the title threw me off): Firenvim works fine on discourse, it doesn't work fine in Firefox on NixOS, and that problem was mentioned on their discourse.

**Comment by glacambre** [comment]
No, I actually mean that Firenvim doesn't work on discourse.nixos.org :). I'm getting a black bar:
![20210222_19h38m46s_grim](https://user-images.githubusercontent.com/11534587/108754125-d7e16c00-7545-11eb-93f3-da0e5f298288.png)

**Comment by alerque** [comment]
It works fine for me.

![image](https://user-images.githubusercontent.com/173595/108756946-3fa1b200-755a-11eb-99a9-cbb671e8f67c.png)

**Comment by glacambre** [comment]
Huh, weird, this must be caused by a race or something. Thanks for trying it out :)

**Comment by glacambre** [comment]
Can't reproduce anymore :/.
