### ISSUE TITLE
Font size upscaled

### ISSUE THREAD

**Issue by goncalves-diogo** [glacambre/firenvim#963]
Hi, Thanks for the plugin!

- OS Version: linux x86-64
- Browser Version:  Firefox 85.0
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4
- What I tried to do: Edit text
- What happened: The text size, more specifically, the font size is just way too big. As you can see in the image below.

Thanks in advance for your time! :)

Quick note: This might be related to this issue #869. However i'm unsure.

![image](https://user-images.githubusercontent.com/33640150/108845944-f1ca8f80-75d5-11eb-9c61-ec472cb21760.png)

**Comment by glacambre** [comment]
Hi, thanks for the report :). Unfortunately I'm not sure I'll be able to find a font size that will please everyone - some want it big and others want it small. Until I find a solution that pleases everyone, you can use `:set guifont=monospace:h9` to control the font that should be used and its size (see `:help guifont` for more information).

**Comment by goncalves-diogo** [comment]
That indeed improves my experience, thanks a lot. Following up on what you suggested, is there any way to include the setting `:set guifont=monospace:h9` on the plugins settings. I couldn't find relevant information about it anywhere. Thanks again :)

**Comment by glacambre** [comment]
`:set guifont` is a neovim setting, not a Firenvim-specific one, so I'm not sure it really belongs on Firenvim's page. `:set guifont` will work with almost all other Neovim guis :).

**Comment by goncalves-diogo** [comment]
Okay, i thought it could a plugin specific setting. I will close the issue now, thanks :)
