### ISSUE TITLE
Problem inserting with dead keys on ubuntu (bug or design?) and workaround

### ISSUE THREAD

**Issue by lpanebr** [glacambre/firenvim#967]
- OS Version: **Ubuntu 20.04**
- Browser Version: **88.0.4324.96 (Official Build) (64-bit)**
- Browser Addon Version: **0.2.4**
- Neovim Plugin Version: **latest as of today.**
- What I tried to do: **I tried to type \` ^ ~ characters**, which in my case (ABNT keyboard) is done by pressing the `KEY + SPACE` sequence.
- What happened: **a space was inserted.**

ALSO: I noticed that if instead I type using the `RightAltKey + Key` sequence then it works.

**Comment by glacambre** [comment]
Hi, thanks for the report.
Could you add a `console.log(evt)` [here](https://github.com/glacambre/firenvim/blob/79bc6673dffcfcbfa886d38fe23c7793188e35be/src/frame.ts#L120) and [here](https://github.com/glacambre/firenvim/blob/79bc6673dffcfcbfa886d38fe23c7793188e35be/src/frame.ts#L174), build firenvim, load it in your browser, reproduce the bug and then upload the console logs here? Instructions to build Firenvim are available [here](https://github.com/glacambre/firenvim/blob/master/CONTRIBUTING.md).

**Comment by glacambre** [comment]
This issue has been awaiting an answer from the author for more than a month so I'll close it. If you are still experiencing a problem, let me know (and provide the information I asked ;) ) and I'll re-open :).
