### ISSUE TITLE
Larger area or floating window.

### ISSUE THREAD

**Issue by smichaud** [glacambre/firenvim#968]
I read the README.md and the TROUBLESHOOTING.md files, but didn't find anything about setting a larger area or creating a floating window. 

The area to type text/code is sometime very small, which make it hard to work with.

The original textarea often expand as you write text, which does not reflect in the neovim area. It would be nice to be able to set a fixed size in the configuration.

**Comment by smichaud** [comment]
Finally found #426. `set lines=20` works perfectly. Added this to my init.vim:
```
function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction

function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    set lines=20
  endif
endfunction

autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```

**Comment by knpwrs** [comment]
For anyone coming across this later, I have the following in my lua configuration and it works well. The only difference from @smichaud's solution is that it first checks to see if the number of lines is less than 10, then it sets the lines to 10:

```lua
vim.cmd([[
  function! s:IsFirenvimActive(event) abort
    if !exists('*nvim_get_chan_info')
      return 0
    endif
    let l:ui = nvim_get_chan_info(a:event.chan)
    return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
        \ l:ui.client.name =~? 'Firenvim'
  endfunction

  function! OnUIEnter(event) abort
    if s:IsFirenvimActive(a:event) && &lines < 10
      set lines=10
    endif
  endfunction

  augroup FirenvimUser
    autocmd!
    autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
  augroup end
]])
```
