### ISSUE TITLE
WSL: install script sometimes goes wrong

### ISSUE THREAD

**Issue by Gelio** [glacambre/firenvim#969]
- OS Version: win x86-64 (running WSL Ubuntu 20.04.2 LTS)
- Browser Version: Google Inc. Chrome 88.0.4324.190
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4
- What I tried to do: save the textarea content (`:wq`)
- What happened: got a message "E32: No file name"

![image](https://user-images.githubusercontent.com/889383/109536547-23ec5d80-7abe-11eb-901c-4d32449c4376.png)

The result of running `!pwd` is `/`

`Ctrl+g` shows 
![image](https://user-images.githubusercontent.com/889383/109538683-ae35c100-7ac0-11eb-9254-a21a97cdf391.png)

I have tried going through [TROUBLESHOOTING.md](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md) but to no avail - all things seem to be present.

2 things that were different were:
1. In "Make sure the firenvim native manifest has been created", the path to `firenvim` was not `%APPDATA%/firenvim` (`.../AppData/Roaming/firenvim`), but in `.../AppData/Local/firenvim`)
2. There were no messages in the _background page_'s console when a textarea was being converted via firenvim

Not sure if that helps, but `$XDG_DATA_HOME` is not set in WSL, and my neovim is in `/home/voreny/.config/nvim.appimage` (not `/usr/bin/nvim`) (it was detected properly and the path in my `firenvim` script is correct)

---'

Some more debugging information:

Result of `:autocmd BufWrite`:
![image](https://user-images.githubusercontent.com/889383/109539678-e1c51b00-7ac1-11eb-9a26-61207f9dad79.png)

I was able to save a file (`:w /tmp/x`), but the textarea content was not set after `:q`:
![image](https://user-images.githubusercontent.com/889383/109539780-fe615300-7ac1-11eb-828e-d644caeecb28.png)

`!ls` prints
![image](https://user-images.githubusercontent.com/889383/109539848-0d480580-7ac2-11eb-8f08-39a6346fee4d.png)

**Comment by Gelio** [comment]
I just noticed that in "Make sure it's not your init.vim" I should be editing the firenvim script on Windows, and not in WSL. Having changed the part of the script to

```
wsl "/home/voreny/.config/nvim.appimage" --headless --cmd "let g:started_by_firenvim = v:true" -c "call firenvim#run()" -u NORC --cmd 'set rtp+=/tmp/firenvim'
```

I got the following message after reloading the settings:

> Neovim plugin version (0.1.32) and browser addon version (0.2.4) do not match.

and now looks like my vimrc does not apply, in fact. The problem still remains

**Comment by glacambre** [comment]
Hi, thank you for opening this issue, going through the troubleshooting guide and providing all this debug information, this is very useful.

It's very weird that `:pwd` is `/` and I think this might be the root cause of the problem. Indeed, neovim being started in `/` would prevent it from writing the content of the textarea to the disk (because only root can write in `/`) and thus prevent neovim from loading said file with a name.

There should be a file named `chrome.ps1` in `AppData/Local/firenvim`, could you upload its content here? It should be a very simple script that creates a registry key. This registry key should be pointing to a script - could you upload the content of that script too?

**Comment by Gelio** [comment]
Thanks for a quick reply!

The `:pwd` output being `/` was also my suspicion

Here are the contents of the files you asked for:

1. `chrome.ps1` from `AppData/Local/firenvim`:

```ps1
New-Item -Path "HKCU:\Software\Google"
New-Item -Path "HKCU:\Software\Google\Chrome"
New-Item -Path "HKCU:\Software\Google\Chrome\NativeMessagingHosts"
New-Item -Path "HKCU:\Software\Google\Chrome\NativeMessagingHosts\firenvim"
Set-Item -Path "HKCU:\Software\Google\Chrome\NativeMessagingHosts\firenvim\" -Value "C:\Users\voren\AppData\Local\firenvim\firenvim-chrome.json"
```

2. `firenvim-chrome.json`:

```json
{ "name": "firenvim", "description": "Turn Firefox into a Neovim client.", "path": "C:\\Users\\voren\\AppData\\Local\\firenvim\\firenvim.bat", "type": "stdio", "allowed_origins": [ "chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/" ]}
```

3. `firenvim.bat`:

```bat
@echo off
mkdir "USER:\1000\firenvim" 2>nul
cd "USER:\1000\firenvim"

wsl "/home/voreny/.config/nvim.appimage" --headless --cmd "let g:started_by_firenvim = v:true" -c "call firenvim#run()"
```

**Comment by glacambre** [comment]
Ah, great, `USER:\1000\firenvim` looks completely wrong. I'm almost certain you can make firenvim work by just replacing that with the repository in which you want Firenvim to start.

I'll have to figure out why Firenvim thought this would be an appropriate path to start in.

**Comment by Gelio** [comment]
I have changed the paths to `C:\Users\voren\AppData\Local\firenvim-cache`, so the file looks like so:

```
@echo off
mkdir "C:\Users\voren\AppData\Local\firenvim-cache" 2>nul
cd "C:\Users\voren\AppData\Local\firenvim-cache"

wsl "/home/voreny/.config/nvim.appimage" --headless --cmd "let g:started_by_firenvim = v:true" -c "call firenvim#run()"
```

Unfortunately, it still does not work :/ "No file name" again

**Comment by glacambre** [comment]
I'm not sure escaping the backslashes is necessary in batch scripts.

Do you have a script in `/home/voreny/.local/share/firenvim/firenvim`? If yes, dose replacing the `
wsl "/home/voreny/.config/nvim.appimage" --headless --cmd "let g:started_by_firenvim = v:true" -c "call firenvim#run()"` with `wsl /home/voreny/.local/share/firenvim/firenvim` help?
`

**Comment by Gelio** [comment]
Yes, that was the fix. Having changed it, the file name looks to be set correctly (it is `github.com_glacambre-firenvim-issues-969_TEXTAREA-id-new-comment-field.txt`) and the pwd is `/run/user/1000/firenvim`

Thanks for the assistance. Not sure if you want to follow up with some soft of a fix, so I'll leave the issue open and let you close it when you desire

Thanks again! And I'm loving the experience so far 🙂

**Comment by glacambre** [comment]
I couldn't reproduce this bug nor identify where it came from just from reading the code so I added a way to trace installation steps with a $DRY_RUN environment variable. Next time someone reproduces this bug, I'll be prepared :).
