### ISSUE TITLE
feature request disable firenvim for certain sites

### ISSUE THREAD

**Issue by infix** [glacambre/firenvim#975]
Add an option to disable firenvim for certain sites

use case: 
- sites like discord.com use textarea for message body and using firenvim is awkward for instant messaging
- disable for this tab doesn't work for 2 reasons. I have to disable the tab every time I open a certain site, and firenvim is still disabled for this tab when navigating to a different site like Github

suggestion: add an option to disable sites firenvim for certain sites using regex like Vimium

![image](https://user-images.githubusercontent.com/40860821/110109345-f3eed400-7db5-11eb-9e6b-9555504405d7.png)

I'd love to work on this, and I'll try to open a PR over the weekend

**Comment by glacambre** [comment]
This is already possible, see https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements . Let me know if you have questions :)

**Comment by infix** [comment]
My bad, I should've read the configuration. Thank you
