### ISSUE TITLE
Timing of loading text into buffer

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#987]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 89.0.4389.72
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4
- What I tried to do: Tried to get firenvim starting in insert mode for empty buffers with `autocmd BufWinEnter * if line('$') == 1 && getline(1) == '' | startinsert | endif`.
- What happened: Boxes with text in them, when starting with firenvim, still end up starting in insert mode.

I'm assuming this is due to the timing of the autocmd and when firenvim fills the buffer. Is there an event it waits on for that? Could you trigger a user autocmd when firenvim has finished loading things into the buffer? (I.e. `doautocmd User FirenvimSetupDone`)

**Comment by glacambre** [comment]
Hi, thanks for the report. Firenvim used to open a buffer and then put text in it but I changed it to write the content of the textarea to a file and then open this file with a regular `:edit` command some time ago, so autocommands should work just like for regular files.

What I think might be happening is that firenvim starts neovim, neovim creates an empty buffer which triggers the autocommand and then firenvim tries to `:edit` the file that contains the textarea's content. So you would already be in insert mode before firenvim even tries to load the textarea file. I think you could verify this theory by adding an `else | stopinsert |` to your if statement.

I currently do not have access to a computer so I'll let you do the verifying :)

**Comment by BlueDrink9** [comment]
Aha. I'll look into that, and possibly switch to a `read` autocmd. Thanks!

**Comment by glacambre** [comment]
Just tried it and I can confirm that the autocommand gets triggered multiple times, sometimes with an empty buffer thanks to the following code:

```
let g:count = 0
autocmd BufWinEnter * if line('$') == 1 && getline(1) == '' | let g:count = g:count + 1 | endif
```

This isn't something I can fix as Neovim needs to be preloaded for performance reasons, so I'm going to close this issue. Let me know if you have more questions :)

**Comment by BlueDrink9** [comment]
Thoughts on including some sort of `doautocmd User FirenvimSetupDone`  when firenvim finishes loading?

**Comment by glacambre** [comment]
I'm not sure that's necessary - `autocmd BufWinEnter * if line('$') == 1 && getline(1) == '' && bufname() != '' | startinsert | endif` should do the trick.

**Comment by BlueDrink9** [comment]
Ah, right. Thank you!
