### ISSUE TITLE
Lua config ask for help, as it seems all hotkeys are not working

### ISSUE THREAD

**Issue by wisonye** [glacambre/firenvim#991]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 89.0.4389.82
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4

- What I tried to do:

   I upgraded to the latest `neovim 0.5 pre-release`, and I'm porting my `init.vim` to `init.lua`. It works fine almost for all my plugins. But this one does not work correctly.

- What happened:

   `firenvim` can open in `chrome`, but seems to run without any customized keybindings, have no idea what's happening there. I just copied the `firenvim` config from my `init.vim` (which works fine before) and convert some of them into `Lua` way. Below is my `Lua` config for the `firenvim` settings. I'm a `Lua` beginner, I don't know how to `convert` the `Vimscript function` in `autocommand` call. Is anyone could help me with this, plz? Thanks a lot:)

```lua
--[[
-----------------------------------------------------------------------
glacambre/firenvim
-----------------------------------------------------------------------
After running `:PaqInstall`, you still need to run the shell command
outside neovim to finish the rest installation.

Otherwise, this plugin won't work correctly!!!!!!!!!!!!!!!!!!!!!!!!!

nvim --headless "+call firenvim#install(0) | q"
--]]
vim.cmd 'let g:firenvim_config = { "globalSettings": { "alt": "all", }, "localSettings": { ".*": { "cmdline": "neovim", "content": "text", "priority": 0, "selector": "textarea", "takeover": "always", }, } }'

-- Disable `firenvim` for the particular webiste
vim.cmd 'let fc = g:firenvim_config["localSettings"]'
vim.cmd 'let fc["https?://twitter.com/"] = { "takeover": "never", "priority": 1 }'
vim.cmd 'let fc["https?://twitter.tv/"] = { "takeover": "never", "priority": 1 }'


-- Change `firenvim` file type to enable syntax highlight, `coc` works perfectly
-- " after this settings!!!
vim.cmd 'autocmd BufEnter github.com_*.txt set filetype=markdown'
vim.cmd 'autocmd BufEnter txti.es_*.txt set filetype=typescript'


-- " Increase the font size to solve the `text too small` issue
-- function! s:IsFirenvimActive(event) abort
--     if !exists('*nvim_get_chan_info')
--         return 0
--     endif
--     let l:ui = nvim_get_chan_info(a:event.chan)
--     return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
--       \ l:ui.client.name =~? 'Firenvim'
-- endfunction
-- 
-- function! OnUIEnter(event) abort
--     if s:IsFirenvimActive(a:event)
--         " Disable the status bar
--         set laststatus=0
-- 
--         " Increase the font size
--         set guifont=SauceCodePro\ Nerd\ Font:h18
--     endif
-- endfunction
-- 
-- autocmd UIEnter * call OnUIEnter(deepcopy(v:event))

-- No need to set explicitly under Neovim: always uses UTF-8 as the default encoding.
-- set encoding=UTF-8
vim.cmd 'set guifont=SauceCodePro\\ Nerd\\ Font:h11'
```

**Comment by wisonye** [comment]
Actually, I figured out by myself and fixed it already. Here is my `Lua` config focus on that part:

```lua
--[[
-----------------------------------------------------------------------
glacambre/firenvim
-----------------------------------------------------------------------
--]]
vim.cmd 'let g:firenvim_config = { "globalSettings": { "alt": "all", }, "localSettings": { ".*": { "cmdline": "neovim", "content": "text", "priority": 0, "selector": "textarea", "takeover": "always", }, } }'

-- Disable `firenvim` for the particular webiste
vim.cmd 'let fc = g:firenvim_config["localSettings"]'
vim.cmd 'let fc["https?://twitter.com/"] = { "takeover": "never", "priority": 1 }'
vim.cmd 'let fc["https?://twitter.tv/"] = { "takeover": "never", "priority": 1 }'
vim.cmd 'let fc["https?://mail.google.com/"] = { "takeover": "never", "priority": 1 }'


-- Change `firenvim` file type to enable syntax highlight, `coc` works perfectly
-- " after this settings!!!
vim.cmd 'autocmd BufEnter github.com_*.txt set filetype=markdown'
vim.cmd 'autocmd BufEnter txti.es_*.txt set filetype=typescript'


-- Increase the font size to solve the `text too small` issue
function IsFirenvimActive(event)
    if vim.g.enable_vim_debug then print("IsFirenvimActive, event: ", vim.inspect(event)) end

    if vim.fn.exists('*nvim_get_chan_info') == 0 then return 0 end

    local ui = vim.api.nvim_get_chan_info(event.chan)
    if vim.g.enable_vim_debug then print("IsFirenvimActive, ui: ", vim.inspect(ui)) end

    --[[
    If this function is running in browser, the `ui` looks like below:
    {
        client = {
            attributes = {
                [true] = 6 -- The channel number
            },
            methods = {
                [true] = 6 -- The channel number
            },
            name = "Firenvim",
            type = "ui",
            version = {
                -- ignore more info here
            }
        },
        id = 5, -- 
        mode = "rpc",
        stream = "socket
    }

    Otherwise, it looks like this:
    {
        [true] = 6 -- The channel name
    }
    --]]
    local is_firenvim_active_in_browser = (ui['client'] ~= nil and ui['client']['name'] ~= nil)
    if vim.g.enable_vim_debug then print("is_firenvim_active_in_browser: ", is_firenvim_active_in_browser) end
    return is_firenvim_active_in_browser
end

function OnUIEnter(event)
    if IsFirenvimActive(event) then
        -- Disable the status bar
        vim.cmd 'set laststatus=0'

        -- Increase the font size
        vim.cmd 'set guifont=SauceCodePro\\ Nerd\\ Font:h18'
    end
end

vim.cmd([[autocmd UIEnter * :call luaeval('OnUIEnter(vim.fn.deepcopy(vim.v.event))')]])

-- No need to set explicitly under Neovim: always uses UTF-8 as the default encoding.
-- set encoding=UTF-8
vim.cmd 'set guifont=SauceCodePro\\ Nerd\\ Font:h11'
```

The `vim.g.enable_vim_debug` is a global var to control whether log the debug information or not, set to
`false` by default. If set to `true`, then you can run `:messages` to view all the printed out debug info
for debugging purpose.

I hope that this may help someone who porting `init.vim` to `init.lua` :)

**Comment by wisonye** [comment]
@glacambre I believe this should be shown in the `README.md` for everyone to know about that? As `init.lua` has slowly become popular and many vim users will use it:)

Otherwise, plz feel free to close it, thanks :)

**Comment by glacambre** [comment]
I think init.lua is very far from being usable compared to init.vim - the snippets you're showing here are very verbose and more than half of your config is actually VimScript - you're just executing it line by line from the Lua interpreter with `vim.cmd` instead of having it all run in the VimScript interpreter.

I'm very concerned about verbosity - this is why I'm using the `let g:fc = …` syntax in the [documentation](https://github.com/glacambre/firenvim#understanding-firenvims-configuration-object). Making the documentation more verbose would result in less users reading it and more questions being asked, which is something I do not want :).

So for now I'll close this issue, but when Lua becomes a real alternative to VimScript for configuration I'll be sure to switch the documentation to Lua :).

**Comment by KarlWithK** [comment]
Do you think we are at that point now? I would really like a Lua configuration, but I"m unable to fully convert the settings for this plugin into lua.

**Comment by glacambre** [comment]
Yes, I think Lua is now a suitable language for configuring Neovim, and am open to replacing vimscript with lua in the config. I've opened https://github.com/glacambre/firenvim/issues/1391 to track this request.

This is something I don't see a lot of personal value in though, so I probably won't do it myself anytime soon. If you really want to configure Firenvim from Lua, I recommend you learn more about using Lua from Neovim. Reading the configuration pasted in the first post of this issue, `:help lua-vim-variables` and `:help nvim_create_autocmd` are really all you need to convert a firenvim configuration written in VimScript to Lua.
