### ISSUE TITLE
Neovim is not responding.

### ISSUE THREAD

**Issue by jonathandion** [glacambre/firenvim#999]
Hi, I'm having an error "Neovim is not responding." from the Google Chrome extension.

- OS Version: Mac M1 arm64 Big Sur 11.2.1
- Browser Version: Google Inc. Chrome 89.0.4389.90
- Browser Addon Version: 0.2.4

`printf 'abcde{}' | $HOME/.local/share/firenvim/firenvim` gives me `{"version": "0.2.4"}%`

Can someone help me debug and fix the issue? 

Thank you.

**Comment by glacambre** [comment]
Hi, could you go through the other steps of the troubleshooting guide? I'm particularly interested in knowing about whether [error messages are logged](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-browser-extension-can-communicate-with-neovim).

**Comment by glacambre** [comment]
@jonathandion Have you managed to solve your problem? :)

**Comment by jonathandion** [comment]
@glacambre Yes using the `tmp` directory works. Sorry for that.
